from openpyxl.descriptors.base import _BoolSetter
from openpyxl.descriptors.serialisable import Serialisable

class Protection(Serialisable):
    tagname: str
    @property
    def locked(self) -> bool: ...
    @locked.setter
    def locked(self, __value: _BoolSetter) -> None: ...
    @property
    def hidden(self) -> bool: ...
    @hidden.setter
    def hidden(self, __value: _BoolSetter) -> None: ...
    def __init__(self, locked: _BoolSetter = True, hidden: _BoolSetter = False) -> None: ...
