from _typeshed import Incomplete

log: Incomplete

class OpenIDToken:
    def get_jwt_config(self, grant) -> None: ...
    def generate_user_info(self, user, scope) -> None: ...
    def get_audiences(self, request): ...
    def process_token(self, grant, token): ...
    def __call__(self, grant) -> None: ...

class OpenIDCode(OpenIDToken):
    require_nonce: Incomplete
    def __init__(self, require_nonce: bool = False) -> None: ...
    def exists_nonce(self, nonce, request) -> None: ...
    def validate_openid_authorization_request(self, grant) -> None: ...
    def __call__(self, grant) -> None: ...
