import abc
from abc import abstractmethod

from sagemaker.cli.compatibility.v2.modifiers.modifier import Modifier

class ParamRenamer(Modifier, metaclass=abc.ABCMeta):
    @property
    @abstractmethod
    def calls_to_modify(self): ...
    @property
    @abstractmethod
    def old_param_name(self): ...
    @property
    @abstractmethod
    def new_param_name(self): ...
    def node_should_be_modified(self, node): ...
    def modify_node(self, node): ...

class MethodParamRenamer(ParamRenamer, metaclass=abc.ABCMeta):
    def node_should_be_modified(self, node): ...

class DistributionParameterRenamer(ParamRenamer):
    @property
    def calls_to_modify(self): ...
    @property
    def old_param_name(self): ...
    @property
    def new_param_name(self): ...

class S3SessionRenamer(MethodParamRenamer):
    @property
    def calls_to_modify(self): ...
    @property
    def old_param_name(self): ...
    @property
    def new_param_name(self): ...

class EstimatorImageURIRenamer(ParamRenamer):
    @property
    def calls_to_modify(self): ...
    @property
    def old_param_name(self): ...
    @property
    def new_param_name(self): ...

class ModelImageURIRenamer(ParamRenamer):
    @property
    def calls_to_modify(self): ...
    @property
    def old_param_name(self): ...
    @property
    def new_param_name(self): ...

class EstimatorCreateModelImageURIRenamer(MethodParamRenamer):
    @property
    def calls_to_modify(self): ...
    @property
    def old_param_name(self): ...
    @property
    def new_param_name(self): ...

class SessionCreateModelImageURIRenamer(MethodParamRenamer):
    @property
    def calls_to_modify(self): ...
    @property
    def old_param_name(self): ...
    @property
    def new_param_name(self): ...

class SessionCreateEndpointImageURIRenamer(MethodParamRenamer):
    @property
    def calls_to_modify(self): ...
    @property
    def old_param_name(self): ...
    @property
    def new_param_name(self): ...
