import logging
from _typeshed import Incomplete
from collections.abc import Iterator, Sequence

from ..std import tqdm as std_tqdm

class _TqdmLoggingHandler(logging.StreamHandler):
    tqdm_class: Incomplete
    def __init__(self, tqdm_class: type[std_tqdm] = ...) -> None: ...
    def emit(self, record) -> None: ...

def logging_redirect_tqdm(loggers: Sequence[logging.Logger] | None = ..., tqdm_class: type[std_tqdm] = ...) -> Iterator[None]: ...
def tqdm_logging_redirect(*args, **kwargs) -> Iterator[None]: ...
