from _typeshed import Incomplete

from OpenGL.GL import *

from ..GLGraphicsItem import GLGraphicsItem

__all__ = ["GLGridItem"]

class GLGridItem(GLGraphicsItem):
    antialias: Incomplete
    def __init__(
        self, size=None, color=(255, 255, 255, 76.5), antialias: bool = True, glOptions: str = "translucent", parentItem=None
    ) -> None: ...
    def setSize(self, x=None, y=None, z=None, size=None) -> None: ...
    def size(self): ...
    def setSpacing(self, x=None, y=None, z=None, spacing=None) -> None: ...
    def spacing(self): ...
    def setColor(self, color) -> None: ...
    def color(self): ...
    def paint(self) -> None: ...
