from _typeshed import Incomplete

from OpenGL.GL import *

from ..GLGraphicsItem import GLGraphicsItem

__all__ = ["GLMeshItem"]

class GLMeshItem(GLGraphicsItem):
    opts: Incomplete
    vertexes: Incomplete
    normals: Incomplete
    colors: Incomplete
    faces: Incomplete
    def __init__(self, parentItem=None, **kwds) -> None: ...
    def setShader(self, shader) -> None: ...
    def shader(self): ...
    def setColor(self, c) -> None: ...
    def setMeshData(self, **kwds) -> None: ...
    edges: Incomplete
    edgeColors: Incomplete
    def meshDataChanged(self) -> None: ...
    edgeVerts: Incomplete
    def parseMeshData(self) -> None: ...
    def paint(self) -> None: ...
