from typing import List, Optional

import click

def single_quote(s: str) -> str: ...
def double_quote(s: str) -> str: ...
def resolve_ctx(
    cli: click.Command, prog_name: str, args: List[str], resilient_parsing: bool = True
) -> Optional[click.core.Context]: ...
def split_args(line: str) -> List[str]: ...
def get_auto_shell() -> str: ...
