from _typeshed import Incomplete
from typing import Any

from ..rest import RestClient as RestClient, RestClientOptions as RestClientOptions
from ..types import TimeoutType as TimeoutType

class Guardian:
    domain: Incomplete
    protocol: Incomplete
    client: Incomplete
    def __init__(
        self,
        domain: str,
        token: str,
        telemetry: bool = True,
        timeout: TimeoutType = 5.0,
        protocol: str = "https",
        rest_options: RestClientOptions | None = None,
    ) -> None: ...
    def all_factors(self) -> list[dict[str, Any]]: ...
    async def all_factors_async(self) -> list[dict[str, Any]]: ...
    def update_factor(self, name: str, body: dict[str, Any]) -> dict[str, Any]: ...
    async def update_factor_async(self, name: str, body: dict[str, Any]) -> dict[str, Any]: ...
    def update_templates(self, body: dict[str, Any]) -> dict[str, Any]: ...
    async def update_templates_async(self, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_templates(self) -> dict[str, Any]: ...
    async def get_templates_async(self) -> dict[str, Any]: ...
    def get_enrollment(self, id: str) -> dict[str, Any]: ...
    async def get_enrollment_async(self, id: str) -> dict[str, Any]: ...
    def delete_enrollment(self, id: str) -> Any: ...
    async def delete_enrollment_async(self, id: str) -> Any: ...
    def create_enrollment_ticket(self, body: dict[str, Any]) -> dict[str, Any]: ...
    async def create_enrollment_ticket_async(self, body: dict[str, Any]) -> dict[str, Any]: ...
    def get_factor_providers(self, factor_name: str, name: str) -> dict[str, Any]: ...
    async def get_factor_providers_async(self, factor_name: str, name: str) -> dict[str, Any]: ...
    def update_factor_providers(self, factor_name: str, name: str, body: dict[str, Any]) -> dict[str, Any]: ...
    async def update_factor_providers_async(self, factor_name: str, name: str, body: dict[str, Any]) -> dict[str, Any]: ...
