from logging import Logger
from typing import Any, Iterable, Pattern, TypeVar

_T = TypeVar("_T")
_App = Any  # flask is not part of typeshed
_Response = Any  # flask is not part of typeshed
_Options = dict[str, Any]
_MultiDict = Any  # werkzeug is not part of typeshed

LOG: Logger
ACL_ORIGIN: str
ACL_METHODS: str
ACL_ALLOW_HEADERS: str
ACL_EXPOSE_HEADERS: str
ACL_CREDENTIALS: str
ACL_MAX_AGE: str
ACL_REQUEST_METHOD: str
ACL_REQUEST_HEADERS: str
ALL_METHODS: list[str]
CONFIG_OPTIONS: list[str]
FLASK_CORS_EVALUATED: str
RegexObject = Pattern[str]
DEFAULT_OPTIONS: _Options

def parse_resources(resources: dict[str, _Options] | list[str] | str) -> list[tuple[str, _Options]]: ...
def get_regexp_pattern(regexp: str | Pattern[str]) -> str: ...
def get_cors_origins(options: _Options, request_origin: str | None) -> list[str] | None: ...
def get_allow_headers(options: _Options, acl_request_headers: str | None) -> str | None: ...
def get_cors_headers(options: _Options, request_headers: dict[str, Any], request_method: str) -> _MultiDict: ...
def set_cors_headers(resp: _Response, options: _Options) -> _Response: ...
def probably_regex(maybe_regex: str | Pattern[str]) -> bool: ...
def re_fix(reg: str) -> str: ...
def try_match_any(inst: str, patterns: Iterable[str]) -> bool: ...
def try_match(request_origin: str, maybe_regex: str) -> bool: ...
def get_cors_options(appInstance: _App | None, *dicts: _Options) -> _Options: ...
def get_app_kwarg_dict(appInstance: _App | None = ...) -> _Options: ...
def flexible_str(obj: Any) -> str: ...
def serialize_option(options_dict: _Options, key: str, upper: bool = ...) -> None: ...
def ensure_iterable(inst: Iterable[_T]) -> Iterable[_T]: ...
def sanitize_regex_param(param: str | list[str]) -> list[str]: ...
def serialize_options(opts: _Options) -> _Options: ...
