from _typeshed import ReadableBuffer
from typing import SupportsBytes
from typing_extensions import Literal

PY_3: bool

def to_bytes(integer: int, length: int, byteorder: Literal["big", "little"]) -> bytes: ...
def from_bytes(bytesarray: SupportsBytes | ReadableBuffer, byteorder: Literal["big", "little"]) -> int: ...

class Counter:
    byteorder: str
    def __init__(self, nonce: SupportsBytes | ReadableBuffer, byteorder: Literal["big", "little"] = "big") -> None: ...
    def __call__(self) -> bytes: ...
    def reset(self) -> None: ...
