"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2020 The TensorFlow Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================

Distributed XLA service protocol.

This is a minimal distributed protocol intended for a small set of purposes
* barriers to wait for all clients to start up or shut down
* health checking to detect when clients vanish
* for sharing GPU topology and NCCL communicator state between distributed
  hosts.

The intention is that a service is started during cluster initialization and
persists for the lifetime of the cluster.
"""
import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.message
import sys

if sys.version_info >= (3, 8):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing_extensions.final
class DeviceProto(google.protobuf.message.Message):
    """Describes a device local to a host."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    LOCAL_DEVICE_ORDINAL_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    VENDOR_FIELD_NUMBER: builtins.int
    GLOBAL_DEVICE_ID_FIELD_NUMBER: builtins.int
    local_device_ordinal: builtins.int
    name: builtins.str
    vendor: builtins.str
    global_device_id: builtins.int
    """The following fields are present in the GlobalTopologyProto message
    returned by EnumerateDevices() but not in the LocalTopologyProto messages
    passed to EnumerateDevices(). In other words, the coordinator node
    determines the global device IDs during EnumerateDevices().
    Globally unique ID number.
    """
    def __init__(
        self,
        *,
        local_device_ordinal: builtins.int | None = ...,
        name: builtins.str | None = ...,
        vendor: builtins.str | None = ...,
        global_device_id: builtins.int | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["global_device_id", b"global_device_id", "local_device_ordinal", b"local_device_ordinal", "name", b"name", "vendor", b"vendor"]) -> None: ...

global___DeviceProto = DeviceProto

@typing_extensions.final
class LocalTopologyProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODE_ID_FIELD_NUMBER: builtins.int
    DEVICES_FIELD_NUMBER: builtins.int
    node_id: builtins.int
    @property
    def devices(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___DeviceProto]: ...
    def __init__(
        self,
        *,
        node_id: builtins.int | None = ...,
        devices: collections.abc.Iterable[global___DeviceProto] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["devices", b"devices", "node_id", b"node_id"]) -> None: ...

global___LocalTopologyProto = LocalTopologyProto

@typing_extensions.final
class GlobalTopologyProto(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    NODES_FIELD_NUMBER: builtins.int
    @property
    def nodes(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___LocalTopologyProto]: ...
    def __init__(
        self,
        *,
        nodes: collections.abc.Iterable[global___LocalTopologyProto] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["nodes", b"nodes"]) -> None: ...

global___GlobalTopologyProto = GlobalTopologyProto

@typing_extensions.final
class ConnectRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROTOCOL_VERSION_FIELD_NUMBER: builtins.int
    TIMEOUT_MILLISECONDS_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    CLIENT_ID_FIELD_NUMBER: builtins.int
    protocol_version: builtins.int
    timeout_milliseconds: builtins.int
    node_id: builtins.int
    """We assume that each node knows its globally-unique node ID, provided by
    whatever mechanism launches the tasks. Node IDs should form a dense range
    of integers [0, num_nodes).
    """
    client_id: builtins.int
    """A unique ID number for the client."""
    def __init__(
        self,
        *,
        protocol_version: builtins.int | None = ...,
        timeout_milliseconds: builtins.int | None = ...,
        node_id: builtins.int | None = ...,
        client_id: builtins.int | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["client_id", b"client_id", "node_id", b"node_id", "protocol_version", b"protocol_version", "timeout_milliseconds", b"timeout_milliseconds"]) -> None: ...

global___ConnectRequest = ConnectRequest

@typing_extensions.final
class ConnectResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    session_id: builtins.int
    def __init__(
        self,
        *,
        session_id: builtins.int | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["session_id", b"session_id"]) -> None: ...

global___ConnectResponse = ConnectResponse

@typing_extensions.final
class EnumerateDevicesRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    LOCAL_TOPOLOGY_FIELD_NUMBER: builtins.int
    session_id: builtins.int
    @property
    def local_topology(self) -> global___LocalTopologyProto: ...
    def __init__(
        self,
        *,
        session_id: builtins.int | None = ...,
        local_topology: global___LocalTopologyProto | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["local_topology", b"local_topology"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["local_topology", b"local_topology", "session_id", b"session_id"]) -> None: ...

global___EnumerateDevicesRequest = EnumerateDevicesRequest

@typing_extensions.final
class EnumerateDevicesResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    GLOBAL_TOPOLOGY_FIELD_NUMBER: builtins.int
    @property
    def global_topology(self) -> global___GlobalTopologyProto: ...
    def __init__(
        self,
        *,
        global_topology: global___GlobalTopologyProto | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing_extensions.Literal["global_topology", b"global_topology"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing_extensions.Literal["global_topology", b"global_topology"]) -> None: ...

global___EnumerateDevicesResponse = EnumerateDevicesResponse

@typing_extensions.final
class KeyValueGetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    TIMEOUT_MILLISECONDS_FIELD_NUMBER: builtins.int
    session_id: builtins.int
    key: builtins.bytes
    timeout_milliseconds: builtins.int
    def __init__(
        self,
        *,
        session_id: builtins.int | None = ...,
        key: builtins.bytes | None = ...,
        timeout_milliseconds: builtins.int | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "session_id", b"session_id", "timeout_milliseconds", b"timeout_milliseconds"]) -> None: ...

global___KeyValueGetRequest = KeyValueGetRequest

@typing_extensions.final
class KeyValueGetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    FOUND_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    found: builtins.bool
    value: builtins.bytes
    def __init__(
        self,
        *,
        found: builtins.bool | None = ...,
        value: builtins.bytes | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["found", b"found", "value", b"value"]) -> None: ...

global___KeyValueGetResponse = KeyValueGetResponse

@typing_extensions.final
class KeyValueSetRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    KEY_FIELD_NUMBER: builtins.int
    VALUE_FIELD_NUMBER: builtins.int
    session_id: builtins.int
    key: builtins.bytes
    value: builtins.bytes
    def __init__(
        self,
        *,
        session_id: builtins.int | None = ...,
        key: builtins.bytes | None = ...,
        value: builtins.bytes | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["key", b"key", "session_id", b"session_id", "value", b"value"]) -> None: ...

global___KeyValueSetRequest = KeyValueSetRequest

@typing_extensions.final
class KeyValueSetResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___KeyValueSetResponse = KeyValueSetResponse

@typing_extensions.final
class WaitAtBarrierRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    BARRIER_ID_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    TIMEOUT_MILLISECONDS_FIELD_NUMBER: builtins.int
    session_id: builtins.int
    barrier_id: builtins.bytes
    node_id: builtins.int
    timeout_milliseconds: builtins.int
    def __init__(
        self,
        *,
        session_id: builtins.int | None = ...,
        barrier_id: builtins.bytes | None = ...,
        node_id: builtins.int | None = ...,
        timeout_milliseconds: builtins.int | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["barrier_id", b"barrier_id", "node_id", b"node_id", "session_id", b"session_id", "timeout_milliseconds", b"timeout_milliseconds"]) -> None: ...

global___WaitAtBarrierRequest = WaitAtBarrierRequest

@typing_extensions.final
class WaitAtBarrierResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___WaitAtBarrierResponse = WaitAtBarrierResponse

@typing_extensions.final
class HeartbeatRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    session_id: builtins.int
    node_id: builtins.int
    def __init__(
        self,
        *,
        session_id: builtins.int | None = ...,
        node_id: builtins.int | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["node_id", b"node_id", "session_id", b"session_id"]) -> None: ...

global___HeartbeatRequest = HeartbeatRequest

@typing_extensions.final
class HeartbeatResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___HeartbeatResponse = HeartbeatResponse

@typing_extensions.final
class ShutdownRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SESSION_ID_FIELD_NUMBER: builtins.int
    NODE_ID_FIELD_NUMBER: builtins.int
    session_id: builtins.int
    node_id: builtins.int
    def __init__(
        self,
        *,
        session_id: builtins.int | None = ...,
        node_id: builtins.int | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing_extensions.Literal["node_id", b"node_id", "session_id", b"session_id"]) -> None: ...

global___ShutdownRequest = ShutdownRequest

@typing_extensions.final
class ShutdownResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    def __init__(
        self,
    ) -> None: ...

global___ShutdownResponse = ShutdownResponse
