from collections.abc import Callable, Iterable, KeysView, Mapping, Sequence
from re import Match, Pattern
from types import SimpleNamespace as Struct
from typing import Any, ClassVar, Final, Literal, Protocol, TypeAlias, overload, type_check_only
from typing_extensions import Never

from docutils import ApplicationError, DataError, nodes
from docutils.frontend import Values
from docutils.nodes import Node, system_message
from docutils.parsers.rst import Directive, _DirectiveFn
from docutils.parsers.rst.languages import RSTLanguageModule
from docutils.parsers.rst.tableparser import TableParser
from docutils.statemachine import StateMachineWS, StateWS, StringList, _StateMachineKwargs
from docutils.utils import Reporter

__docformat__: Final = "reStructuredText"

# The context of reStructuredText states is a list of str lines.
_Context: TypeAlias = list[str]
# The tuple below represents (context, next state, results)
_TransitionResult: TypeAlias = tuple[_Context, str | None, list[str]]
# Title styles are either the underline character (`_`) or a tuple of (overline, underline).
_TitleStyle: TypeAlias = str | tuple[str, str]
# The tuple below represents (string before, new nodes, remaining string, system messages).
_InlineResult: TypeAlias = tuple[str, list[Node], str, list[system_message]]
# The tuple below represents (nodes, blank_finish).
_ConstructResult: TypeAlias = tuple[list[Node], bool]

# The "memo" object is shared between nested state machines.
# `memo`, a `types.SimpleNamespace` at runtime.
@type_check_only
class _Memo(Protocol):
    document: nodes.document
    language: RSTLanguageModule | None
    title_styles: list[_TitleStyle]
    inliner: Inliner
    # Deprecated, will be removed in Docutils 2.0.
    reporter: Reporter
    section_level: int
    section_bubble_up_kludge: bool

class MarkupError(DataError): ...
class UnknownInterpretedRoleError(DataError): ...
class InterpretedRoleNotImplementedError(DataError): ...
class ParserError(ApplicationError): ...
class MarkupMismatch(Exception): ...

class RSTStateMachine(StateMachineWS[_Context]):
    language: RSTLanguageModule | None
    match_titles: bool
    memo: _Memo | None
    document: nodes.document
    reporter: Reporter
    node: nodes.Element | None
    section_level_offset: int
    def run(  # type: ignore[override]
        self,
        input_lines: Sequence[str] | StringList,
        document: nodes.document,
        input_offset: int = 0,
        match_titles: bool = True,
        inliner: Inliner | None = None,
    ) -> None: ...

class NestedStateMachine(RSTStateMachine):
    parent_state_machine: RSTStateMachine | None
    memo: _Memo
    def __init__(
        self,
        state_classes: Iterable[type[RSTState]],
        initial_state: str,
        debug: bool = False,
        parent_state_machine: RSTStateMachine | None = None,
    ) -> None: ...
    def run(  # type: ignore[override]
        self,
        input_lines: Sequence[str] | StringList,
        input_offset: int,
        memo: _Memo,
        node: nodes.Element,
        match_titles: bool = True,
    ) -> list[str]: ...

class RSTState(StateWS[_Context]):
    nested_sm: type[NestedStateMachine]
    nested_sm_cache: ClassVar[list[NestedStateMachine]]
    state_machine: RSTStateMachine
    memo: _Memo
    reporter: Reporter
    inliner: Inliner
    document: nodes.document
    def __init__(self, state_machine: RSTStateMachine, debug: bool = False) -> None: ...
    def runtime_init(self) -> None: ...

    @property
    def parent(self) -> nodes.Element | None: ...
    @parent.setter
    def parent(self, value: nodes.Element) -> None: ...

    def goto_line(self, abs_line_offset: int) -> None: ...
    def no_match(self, context: _Context, transitions: object) -> _TransitionResult: ...
    def bof(self, context: _Context) -> tuple[list[str], list[str]]: ...
    def nested_parse(
        self,
        block: StringList,
        input_offset: int,
        node: nodes.Element | None = None,
        match_titles: bool = False,
        state_machine_class: type[StateMachineWS[_Context]] | None = None,
        state_machine_kwargs: _StateMachineKwargs[_Context] | None = None,
    ) -> int: ...
    def nested_list_parse(
        self,
        block: StringList,
        input_offset: int,
        node: nodes.Element,
        initial_state: str,
        blank_finish: bool,
        blank_finish_state: str | None = None,
        extra_settings: dict[str, Any] = ...,
        match_titles: bool = False,
        state_machine_class: type[StateMachineWS[_Context]] | None = None,
        state_machine_kwargs: _StateMachineKwargs[_Context] | None = None,
    ) -> tuple[int, bool]: ...
    def section(self, title: str, source: str, style: _TitleStyle, lineno: int, messages: list[system_message]) -> None: ...
    def check_subsection(self, source: str, style: _TitleStyle, lineno: int) -> bool: ...
    def title_inconsistent(self, sourcetext: str, lineno: int) -> system_message: ...
    def new_subsection(self, title: str, lineno: int, messages: list[system_message]) -> None: ...
    def paragraph(self, lines: Iterable[str], lineno: int) -> tuple[list[Node], Literal[0, 1]]: ...
    def inline_text(self, text: str, lineno: int) -> tuple[list[Node], list[system_message]]: ...
    def unindent_warning(self, node_name: str) -> system_message: ...

# This is a tuple representing (group name, prefix, suffix, parts), where `parts` may again be definitions.
_BasicDefinition: TypeAlias = tuple[str, str, str, list[str]]
_DefinitionParts: TypeAlias = tuple[str, str, str, list[str | _BasicDefinition]]
_DefinitionType: TypeAlias = tuple[str, str, str, list[str | _DefinitionParts]]

@overload
def build_regexp(definition: _DefinitionType, compile_patterns: Literal[True] = True) -> Pattern[str]: ...
@overload
def build_regexp(definition: _DefinitionType, compile_patterns: Literal[False]) -> str: ...
@overload
def build_regexp(definition: _DefinitionType, compile_patterns: bool) -> Pattern[str] | str: ...

# `Inliner.patterns`, a `types.SimpleNamespace` at runtime.
@type_check_only
class _InlinerPatterns(Protocol):
    initial: Pattern[str]
    emphasis: Pattern[str]
    strong: Pattern[str]
    interpreted_or_phrase_ref: Pattern[str]
    embedded_link: Pattern[str]
    literal: Pattern[str]
    target: Pattern[str]
    substitution_ref: Pattern[str]
    email: Pattern[str]
    uri: Pattern[str]
    pep: Pattern[str]
    rfc: Pattern[str]

class Inliner:
    implicit_dispatch: list[tuple[Pattern[str], Callable[[Match[str], int], list[Node]]]]
    def __init__(self) -> None: ...
    start_string_prefix: str
    end_string_suffix: str
    parts: _DefinitionType
    patterns: _InlinerPatterns
    def init_customizations(self, settings: Values) -> None: ...
    reporter: Reporter
    document: nodes.document
    language: RSTLanguageModule | None
    parent: nodes.Element
    def parse(self, text: str, lineno: int, memo: _Memo, parent: nodes.Element) -> tuple[list[Node], list[system_message]]: ...
    non_whitespace_before: ClassVar[str]
    non_whitespace_escape_before: ClassVar[str]
    non_unescaped_whitespace_escape_before: ClassVar[str]
    non_whitespace_after: ClassVar[str]
    simplename: ClassVar[str]
    uric: ClassVar[str]
    uri_end_delim: ClassVar[str]
    urilast: ClassVar[str]
    uri_end: ClassVar[str]
    emailc: ClassVar[str]
    email_pattern: ClassVar[str]
    def quoted_start(self, match: Match[str]) -> bool: ...
    def inline_obj(
        self,
        match: Match[str],
        lineno: int,
        end_pattern: Pattern[str],
        nodeclass: type[nodes.TextElement],
        restore_backslashes: bool = False,
    ) -> tuple[str, list[Node], str, list[system_message], str]: ...
    def problematic(self, text: str, rawsource: str, message: system_message) -> nodes.problematic: ...
    def emphasis(self, match: Match[str], lineno: int) -> _InlineResult: ...
    def strong(self, match: Match[str], lineno: int) -> _InlineResult: ...
    def interpreted_or_phrase_ref(self, match: Match[str], lineno: int) -> _InlineResult: ...
    def phrase_ref(
        self, before: str, after: str, rawsource: str, escaped: str, text: str | None = None
    ) -> tuple[str, list[Node], str, list[system_message]]: ...
    def adjust_uri(self, uri: str) -> str: ...
    def interpreted(self, rawsource: str, text: str, role: str, lineno: int) -> tuple[list[Node], list[system_message]]: ...
    def literal(self, match: Match[str], lineno: int) -> _InlineResult: ...
    def inline_internal_target(self, match: Match[str], lineno: int) -> _InlineResult: ...
    def substitution_reference(self, match: Match[str], lineno: int) -> _InlineResult: ...
    def footnote_reference(self, match: Match[str], lineno: int) -> _InlineResult: ...
    def reference(self, match: Match[str], lineno: int, anonymous: bool = False) -> _InlineResult: ...
    def anonymous_reference(self, match: Match[str], lineno: int) -> _InlineResult: ...
    def standalone_uri(self, match: Match[str], lineno: int) -> list[Node]: ...
    def pep_reference(self, match: Match[str], lineno: int) -> list[Node]: ...
    rfc_url: ClassVar[str]
    def rfc_reference(self, match: Match[str], lineno: int) -> list[Node]: ...
    def implicit_inline(self, text: str, lineno: int) -> list[Node]: ...
    # Mapping of start-strings to the (unbound) methods above.
    dispatch: ClassVar[dict[str, Callable[[Inliner, Match[str], int], _InlineResult]]]

# `Body.enum`, a `types.SimpleNamespace` at runtime.
@type_check_only
class _EnumeratorInfo(Protocol):
    formatinfo: dict[str, Struct]
    formats: KeysView[str]
    sequences: list[str]
    sequencepats: dict[str, str]
    converters: dict[str, Callable[[str], int]]
    sequenceregexps: dict[str, Pattern[str]]

# `Body.explicit.patterns`, a `types.SimpleNamespace` at runtime.
@type_check_only
class _ExplicitPatterns(Protocol):
    target: Pattern[str]
    reference: Pattern[str]
    substitution: Pattern[str]

# `Body.explicit`, a `types.SimpleNamespace` at runtime.
@type_check_only
class _ExplicitInfo(Protocol):
    patterns: _ExplicitPatterns
    # (unbound method, pattern)
    constructs: list[tuple[Callable[[Body, Match[str]], _ConstructResult], Pattern[str]]]

class Body(RSTState):
    double_width_pad_char: ClassVar[str]
    enum: ClassVar[_EnumeratorInfo]
    # Some of these are induction variables leaked from the class body.
    format: str
    sequence: str
    grid_table_top_pat: ClassVar[Pattern[str]]
    simple_table_top_pat: ClassVar[Pattern[str]]
    simple_table_border_pat: ClassVar[Pattern[str]]
    pats: ClassVar[dict[str, str]]
    patterns: ClassVar[dict[str, str | Pattern[str]]]
    initial_transitions: ClassVar[Sequence[str] | Sequence[tuple[str, str]]]
    def indent(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def block_quote(self, indented: StringList, line_offset: int) -> list[Node]: ...
    attribution_pattern: ClassVar[Pattern[str]]
    def split_attribution(
        self, indented: StringList, line_offset: int
    ) -> tuple[StringList, StringList | None, int | None, StringList | None, int | None]: ...
    def check_attribution(self, indented: StringList, attribution_start: int) -> tuple[int | None, int | None]: ...
    def parse_attribution(self, indented: StringList, line_offset: int) -> tuple[nodes.attribution, list[system_message]]: ...
    def bullet(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def list_item(self, indent: int) -> tuple[nodes.list_item, bool]: ...
    def enumerator(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    # The returned tuple represents (format, sequence, text, ordinal).
    def parse_enumerator(self, match: Match[str], expected_sequence: str | None = None) -> tuple[str, str, str, int | None]: ...
    def is_enumerated_list_item(self, ordinal: int | None, sequence: str, format: str) -> Literal[1] | None: ...
    def make_enumerator(self, ordinal: int, sequence: str, format: str) -> tuple[str, str] | None: ...
    def field_marker(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def field(self, match: Match[str]) -> tuple[nodes.field, bool]: ...
    def parse_field_marker(self, match: Match[str]) -> str: ...
    def parse_field_body(self, indented: StringList, offset: int, node: nodes.Element) -> None: ...
    def option_marker(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def option_list_item(self, match: Match[str]) -> tuple[nodes.option_list_item, bool]: ...
    def parse_option_marker(self, match: Match[str]) -> list[nodes.option]: ...
    def doctest(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def line_block(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def line_block_line(self, match: Match[str], lineno: int) -> tuple[nodes.line, list[system_message], bool]: ...
    def nest_line_block_lines(self, block: nodes.line_block) -> None: ...
    def nest_line_block_segment(self, block: nodes.line_block) -> None: ...
    def grid_table_top(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def simple_table_top(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def table_top(
        self,
        match: Match[str],
        context: _Context,
        next_state: str,
        isolate_function: Callable[[], tuple[StringList | list[str], list[system_message], bool]],
        parser_class: type[TableParser],
    ) -> _TransitionResult: ...
    def table(
        self,
        isolate_function: Callable[[], tuple[StringList | list[str], list[system_message], bool]],
        parser_class: type[TableParser],
    ) -> tuple[list[Node], bool]: ...
    def isolate_grid_table(self) -> tuple[StringList | list[str], list[system_message], bool]: ...
    def isolate_simple_table(self) -> tuple[StringList | list[str], list[system_message], bool]: ...
    def malformed_table(self, block: StringList, detail: str = "", offset: int = 0) -> list[system_message]: ...
    # `tabledata` is (column widths, header rows, body rows), as returned by the table parsers.
    def build_table(
        self,
        tabledata: tuple[list[int], list[list[Any]], list[list[Any]]],
        tableline: int,
        stub_columns: int = 0,
        widths: list[int] | Literal["auto", "grid", ""] | None = None,
    ) -> nodes.table: ...
    # A row is a list of cells; a cell is `None` (spanned) or (morerows, morecols, offset, content lines).
    def build_table_row(
        self, rowdata: Sequence[tuple[int, int, int, StringList | list[str]] | None], tableline: int
    ) -> nodes.row: ...
    explicit: ClassVar[_ExplicitInfo]
    def footnote(self, match: Match[str]) -> _ConstructResult: ...
    def citation(self, match: Match[str]) -> _ConstructResult: ...
    def hyperlink_target(self, match: Match[str]) -> _ConstructResult: ...
    def make_target(self, block: Sequence[str], block_text: str, lineno: int, target_name: str | None) -> nodes.target: ...
    def parse_target(self, block: Sequence[str], block_text: str, lineno: int) -> tuple[Literal["refname", "refuri"], str]: ...
    def is_reference(self, reference: str) -> str | None: ...
    def add_target(self, targetname: str | None, refuri: str, target: nodes.target, lineno: int) -> None: ...
    def substitution_def(self, match: Match[str]) -> _ConstructResult: ...
    def disallowed_inside_substitution_definitions(self, node: nodes.Node) -> str: ...
    def directive(self, match: Match[str], **option_presets: object) -> _ConstructResult: ...
    def run_directive(
        self, directive: type[Directive] | _DirectiveFn, match: Match[str], type_name: str, option_presets: dict[str, Any]
    ) -> _ConstructResult: ...
    # The returned tuple represents (arguments, options, content, content_offset).
    def parse_directive_block(
        self, indented: StringList, line_offset: int, directive: type[Directive], option_presets: dict[str, Any]
    ) -> tuple[list[str], dict[str, Any], StringList, int]: ...
    def parse_directive_options(
        self,
        option_presets: dict[str, Any],
        option_spec: Mapping[str, Callable[[str], object]],
        arg_block: StringList | list[str],
    ) -> tuple[dict[str, Any], StringList | list[str]]: ...
    def parse_directive_arguments(self, directive: type[Directive], arg_block: StringList | list[str]) -> list[str]: ...
    # Returns (1, options) on success, or (0, error message) on failure.
    def parse_extension_options(
        self, option_spec: Mapping[str, Callable[[str], object]], datalines: StringList
    ) -> tuple[Literal[1], dict[str, Any]] | tuple[Literal[0], str]: ...
    def unknown_directive(self, type_name: str) -> _ConstructResult: ...
    def comment(self, match: Match[str]) -> _ConstructResult: ...
    def explicit_markup(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def explicit_construct(self, match: Match[str]) -> _ConstructResult: ...
    def explicit_list(self, blank_finish: bool) -> None: ...
    def anonymous(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def anonymous_target(self, match: Match[str]) -> _ConstructResult: ...
    def line(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def text(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...

class RFC2822Body(Body):
    patterns: ClassVar[dict[str, str | Pattern[str]]]
    initial_transitions: ClassVar[list[tuple[str, str]]]
    def rfc2822(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def rfc2822_field(self, match: Match[str]) -> tuple[nodes.field, bool]: ...

class SpecializedBody(Body):
    # At runtime, all transition methods of this class are aliases of `invalid_input()`, which always raises.
    # Subclasses must override those they wish to use. The stub keeps the regular transition signatures so that subclasses have
    # the intended override signature.
    # They have additionally been redeclared with @type_check_only so that supporting type_checkers may identify these as
    # non-existing methods.
    def invalid_input(
        self, match: Match[str] | None = None, context: _Context | None = None, next_state: str | None = None
    ) -> Never: ...
    @type_check_only
    def indent(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    @type_check_only
    def bullet(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    @type_check_only
    def enumerator(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    @type_check_only
    def field_marker(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    @type_check_only
    def option_marker(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    @type_check_only
    def doctest(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    @type_check_only
    def line_block(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    @type_check_only
    def grid_table_top(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    @type_check_only
    def simple_table_top(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    @type_check_only
    def explicit_markup(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    @type_check_only
    def anonymous(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    @type_check_only
    def line(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    @type_check_only
    def text(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...

class BulletList(SpecializedBody):
    blank_finish: bool
    def bullet(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...

class DefinitionList(SpecializedBody):
    def text(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...

class EnumeratedList(SpecializedBody):
    auto: int
    blank_finish: bool
    format: str
    lastordinal: int
    sequence: str
    def enumerator(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...

class FieldList(SpecializedBody):
    blank_finish: bool
    def field_marker(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...

class OptionList(SpecializedBody):
    blank_finish: bool
    def option_marker(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...

class RFC2822List(SpecializedBody, RFC2822Body):
    patterns: ClassVar[dict[str, str | Pattern[str]]]
    initial_transitions: ClassVar[list[tuple[str, str]]]
    blank_finish: bool
    def rfc2822(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    blank = SpecializedBody.invalid_input

class ExtensionOptions(FieldList):
    def parse_field_body(self, indented: StringList, offset: int, node: nodes.Element) -> None: ...

class LineBlock(SpecializedBody):
    blank = SpecializedBody.invalid_input
    blank_finish: bool
    def line_block(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...

class Explicit(SpecializedBody):
    blank_finish: bool
    def explicit_markup(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def anonymous(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    blank = SpecializedBody.invalid_input

class SubstitutionDef(Body):
    patterns: ClassVar[dict[str, str | Pattern[str]]]
    initial_transitions: ClassVar[list[str]]
    blank_finish: bool
    def embedded_directive(self, match: Match[str], context: _Context, next_state: str) -> Never: ...
    def text(self, match: Match[str], context: _Context, next_state: str) -> Never: ...

class Text(RSTState):
    patterns: ClassVar[dict[str, str | Pattern[str]]]
    initial_transitions: ClassVar[list[tuple[str, str]]]
    def blank(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def eof(self, context: _Context) -> list[str]: ...
    def indent(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def underline(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def text(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def literal_block(self) -> list[Node]: ...
    def quoted_literal_block(self) -> list[Node]: ...
    def definition_list_item(self, termline: _Context) -> tuple[nodes.definition_list_item, bool]: ...
    classifier_delimiter: ClassVar[Pattern[str]]
    def term(self, lines: Sequence[str], lineno: int) -> tuple[list[Node], list[system_message]]: ...

class SpecializedText(Text):
    def eof(self, context: _Context) -> list[str]: ...
    # See the comment in SpecializedBody.
    def invalid_input(
        self, match: Match[str] | None = None, context: _Context | None = None, next_state: str | None = None
    ) -> Never: ...
    @type_check_only
    def blank(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    @type_check_only
    def indent(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    @type_check_only
    def underline(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    @type_check_only
    def text(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...

class Definition(SpecializedText):
    blank_finish: bool
    def eof(self, context: _Context) -> list[str]: ...
    def indent(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...

class Line(SpecializedText):
    eofcheck: int
    def eof(self, context: _Context) -> list[str]: ...
    def blank(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def text(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    indent = text
    def underline(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def short_overline(self, context: _Context, blocktext: str, lineno: int, lines: int = 1) -> None: ...
    def state_correction(self, context: _Context, lines: int = 1) -> Never: ...

class QuotedLiteralBlock(RSTState):
    patterns: ClassVar[dict[str, str | Pattern[str]]]
    initial_transitions: ClassVar[tuple[str, ...]]
    messages: list[system_message]
    initial_lineno: int | None
    def __init__(self, state_machine: RSTStateMachine, debug: bool = False) -> None: ...
    def blank(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def eof(self, context: _Context) -> list[str]: ...
    def indent(self, match: Match[str], context: _Context, next_state: str) -> Never: ...
    def initial_quoted(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def quoted(self, match: Match[str], context: _Context, next_state: str) -> _TransitionResult: ...
    def text(self, match: Match[str], context: _Context, next_state: str) -> Never: ...

state_classes: tuple[type[RSTState], ...]
