from collections.abc import Callable
from typing import Any, TypeAlias

from google.protobuf.descriptor import FieldDescriptor

_Sizer: TypeAlias = Callable[[Any], int]
_SizerFactory: TypeAlias = Callable[[int, bool, bool], _Sizer]

Int32Sizer: _SizerFactory
Int64Sizer: _SizerFactory
EnumSizer: _SizerFactory
UInt32Sizer: _SizerFactory
UInt64Sizer: _SizerFactory
SInt32Sizer: _SizerFactory
SInt64Sizer: _SizerFactory
Fixed32Sizer: _SizerFactory
SFixed32Sizer: _SizerFactory
FloatSizer: _SizerFactory
Fixed64Sizer: _SizerFactory
SFixed64Sizer: _SizerFactory
DoubleSizer: _SizerFactory
BoolSizer: _SizerFactory

def StringSizer(field_number: int, is_repeated: bool, is_packed: bool) -> _Sizer: ...
def BytesSizer(field_number: int, is_repeated: bool, is_packed: bool) -> _Sizer: ...
def GroupSizer(field_number: int, is_repeated: bool, is_packed: bool) -> _Sizer: ...
def MessageSizer(field_number: int, is_repeated: bool, is_packed: bool) -> _Sizer: ...
def MessageSetItemSizer(field_number: int) -> _Sizer: ...
def MapSizer(field_descriptor: FieldDescriptor, key_sizer: _Sizer, value_sizer: _Sizer) -> _Sizer: ...
def TagBytes(field_number: int, wire_type: int) -> bytes: ...

_Encoder: TypeAlias = Callable[[Callable[[bytes], object], Any, bool], None]

def Int32Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def Int64Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def EnumEncoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def UInt32Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def UInt64Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def SInt32Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def SInt64Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def Fixed32Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def Fixed64Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def SFixed32Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def SFixed64Encoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def FloatEncoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def DoubleEncoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def BoolEncoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def StringEncoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def BytesEncoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def GroupEncoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def MessageEncoder(field_number: int, is_repeated: bool, is_packed: bool) -> _Encoder: ...
def MessageSetItemEncoder(field_number: int) -> _Encoder: ...
def MapEncoder(
    field_descriptor: FieldDescriptor, key_encoder: _Encoder, value_encoder: _Encoder, key_sizer: _Sizer, value_sizer: _Sizer
) -> _Encoder: ...
