from typing import Any

from google.protobuf.descriptor import FieldDescriptor as FieldDescriptor

class FieldMask:
    def ToJsonString(self) -> str: ...
    def FromJsonString(self, value: Any) -> None: ...
    def IsValidForDescriptor(self, message_descriptor: Any) -> bool: ...
    def AllFieldsFromDescriptor(self, message_descriptor: Any) -> None: ...
    def CanonicalFormFromMask(self, mask: Any) -> None: ...
    def Union(self, mask1: Any, mask2: Any) -> None: ...
    def Intersect(self, mask1: Any, mask2: Any) -> None: ...
    def MergeMessage(
        self, source: Any, destination: Any, replace_message_field: bool = False, replace_repeated_field: bool = False
    ) -> None: ...
