from collections.abc import Callable
from typing import Any, TypeVar
from unittest import TestResult

_T = TypeVar("_T")

class LocalTestResult(TestResult):
    parent_result: TestResult
    def __init__(self, parent_result: TestResult) -> None: ...
    def addError(self, test: Any, error: Any) -> None: ...
    def addFailure(self, test: Any, error: Any) -> None: ...
    def addSkip(self, test: Any, reason: str) -> None: ...
    def addDuration(self, test: Any, duration: float) -> None: ...

class ReferenceLeakCheckerMixin:
    NB_RUNS: int
    def run(self, result: TestResult | None = None) -> TestResult: ...

def SkipReferenceLeakChecker(reason: str) -> Callable[[_T], _T]: ...
def TestCase(test_class: _T) -> _T: ...
