from ldap.pkginfo import __version__ as __version__

def escape_dn_chars(s): ...
def str2dn(dn, flags: int = 0): ...
def dn2str(dn): ...
def explode_dn(dn, notypes: bool = False, flags: int = 0): ...
def explode_rdn(rdn, notypes: bool = False, flags: int = 0): ...
def is_dn(s, flags: int = 0): ...
