from ldap.pkginfo import __version__ as __version__

def escape_dn_chars(s: str) -> str: ...
def str2dn(dn: str, flags: int = 0) -> list[list[tuple[str, str, int]]]: ...
def dn2str(dn: list[list[tuple[str, str, int]]], flags: int = 0) -> str: ...
def explode_dn(dn: str, notypes: bool = False, flags: int = 0) -> list[str]: ...
def explode_rdn(rdn: str, notypes: bool = False, flags: int = 0) -> list[str]: ...
def is_dn(s: str, flags: int = 0) -> bool: ...
def normalize(s: str, flags: int = 0) -> str: ...
