from typing import Any

__all__ = ["LDAPObject", "SimpleLDAPObject", "ReconnectLDAPObject", "LDAPBytesWarning"]

class LDAPBytesWarning(Warning): ...
class NO_UNIQUE_ENTRY(Exception): ...

class SimpleLDAPObject:
    CLASSATTR_OPTION_MAPPING: dict[str, Any]
    timeout: int
    protocol_version: Any
    def __init__(
        self,
        uri: str,
        trace_level: int = 0,
        trace_file: Any = ...,
        trace_stack_limit: int = 5,
        bytes_mode: Any = ...,
        bytes_strictness: Any = ...,
        fileno: Any = ...,
    ) -> None: ...
    # Property: bytes_mode
    def bytes_mode(self) -> Any: ...
    # Property: bytes_strictness
    def bytes_strictness(self) -> Any: ...
    def __setattr__(self, name: str, value: Any) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def fileno(self) -> Any: ...
    def abandon_ext(self, msgid: Any, serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def abandon(self, msgid: Any) -> Any: ...
    def cancel(self, cancelid: Any, serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def cancel_s(self, cancelid: Any, serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def add_ext(self, dn: str, modlist: Any, serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def add_ext_s(self, dn: str, modlist: Any, serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def add(self, dn: str, modlist: Any) -> Any: ...
    def add_s(self, dn: str, modlist: Any) -> Any: ...
    def simple_bind(self, who: Any = ..., cred: Any = ..., serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def simple_bind_s(self, who: Any = ..., cred: Any = ..., serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def bind(self, who: Any, cred: Any, method: Any = ...) -> Any: ...
    def bind_s(self, who: Any, cred: Any, method: Any = ...) -> Any: ...
    def sasl_interactive_bind_s(
        self, who: Any, auth: Any, serverctrls: Any = ..., clientctrls: Any = ..., sasl_flags: Any = ...
    ) -> Any: ...
    def sasl_non_interactive_bind_s(
        self, sasl_mech: Any, serverctrls: Any = ..., clientctrls: Any = ..., sasl_flags: Any = ..., authz_id: str = ""
    ) -> None: ...
    def sasl_external_bind_s(
        self, serverctrls: Any = ..., clientctrls: Any = ..., sasl_flags: Any = ..., authz_id: str = ""
    ) -> None: ...
    def sasl_gssapi_bind_s(
        self, serverctrls: Any = ..., clientctrls: Any = ..., sasl_flags: Any = ..., authz_id: str = ""
    ) -> None: ...
    def sasl_bind_s(self, dn: Any, mechanism: Any, cred: Any, serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def compare_ext(self, dn: str, attr: str, value: Any, serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def compare_ext_s(self, dn: str, attr: str, value: Any, serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def compare(self, dn: str, attr: str, value: Any) -> Any: ...
    def compare_s(self, dn: str, attr: str, value: Any) -> Any: ...
    def delete_ext(self, dn: str, serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def delete_ext_s(self, dn: str, serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def delete(self, dn: str) -> Any: ...
    def delete_s(self, dn: str) -> Any: ...
    def extop(self, extreq: Any, serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def extop_result(self, msgid: Any = ..., all: int = 1, timeout: Any = ...) -> Any: ...
    def extop_s(self, extreq: Any, serverctrls: Any = ..., clientctrls: Any = ..., extop_resp_class: Any = ...) -> Any: ...
    def modify_ext(self, dn: str, modlist: Any, serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def modify_ext_s(self, dn: str, modlist: Any, serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def modify(self, dn: str, modlist: Any) -> Any: ...
    def modify_s(self, dn: str, modlist: Any) -> Any: ...
    def modrdn(self, dn: str, newrdn: str, delold: int = 1) -> Any: ...
    def modrdn_s(self, dn: str, newrdn: str, delold: int = 1) -> Any: ...
    def passwd(self, user: Any, oldpw: Any, newpw: Any, serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def passwd_s(
        self, user: Any, oldpw: Any, newpw: Any, serverctrls: Any = ..., clientctrls: Any = ..., extract_newpw: bool = False
    ) -> Any: ...
    def rename(
        self, dn: str, newrdn: str, newsuperior: Any = ..., delold: int = 1, serverctrls: Any = ..., clientctrls: Any = ...
    ) -> Any: ...
    def rename_s(
        self, dn: str, newrdn: str, newsuperior: Any = ..., delold: int = 1, serverctrls: Any = ..., clientctrls: Any = ...
    ) -> Any: ...
    def result(self, msgid: Any = ..., all: int = 1, timeout: Any = ...) -> Any: ...
    def result2(self, msgid: Any = ..., all: int = 1, timeout: Any = ...) -> Any: ...
    def result3(self, msgid: Any = ..., all: int = 1, timeout: Any = ..., resp_ctrl_classes: Any = ...) -> Any: ...
    def result4(
        self,
        msgid: Any = ...,
        all: int = 1,
        timeout: Any = ...,
        add_ctrls: int = 0,
        add_intermediates: int = 0,
        add_extop: int = 0,
        resp_ctrl_classes: Any = ...,
    ) -> Any: ...
    def search_ext(
        self,
        base: str,
        scope: int,
        filterstr: Any = ...,
        attrlist: Any = ...,
        attrsonly: int = 0,
        serverctrls: Any = ...,
        clientctrls: Any = ...,
        timeout: int = -1,
        sizelimit: int = 0,
    ) -> Any: ...
    def search_ext_s(
        self,
        base: str,
        scope: int,
        filterstr: Any = ...,
        attrlist: Any = ...,
        attrsonly: int = 0,
        serverctrls: Any = ...,
        clientctrls: Any = ...,
        timeout: int = -1,
        sizelimit: int = 0,
    ) -> Any: ...
    def search(self, base: str, scope: int, filterstr: Any = ..., attrlist: Any = ..., attrsonly: int = 0) -> Any: ...
    def search_s(self, base: str, scope: int, filterstr: Any = ..., attrlist: Any = ..., attrsonly: int = 0) -> Any: ...
    def search_st(
        self, base: str, scope: int, filterstr: Any = ..., attrlist: Any = ..., attrsonly: int = 0, timeout: int = -1
    ) -> Any: ...
    def start_tls_s(self) -> Any: ...
    def unbind_ext(self, serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def unbind_ext_s(self, serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def unbind(self) -> Any: ...
    def unbind_s(self) -> Any: ...
    def whoami_s(self, serverctrls: Any = ..., clientctrls: Any = ...) -> Any: ...
    def get_option(self, option: Any) -> Any: ...
    def set_option(self, option: Any, invalue: Any) -> None: ...
    def search_subschemasubentry_s(self, dn: Any = ...) -> Any: ...
    def read_s(
        self,
        dn: str,
        filterstr: Any = ...,
        attrlist: Any = ...,
        serverctrls: Any = ...,
        clientctrls: Any = ...,
        timeout: int = -1,
    ) -> Any: ...
    def read_subschemasubentry_s(self, subschemasubentry_dn: Any, attrs: Any = ...) -> Any: ...
    def find_unique_entry(
        self,
        base: str,
        scope: Any = ...,
        filterstr: Any = ...,
        attrlist: Any = ...,
        attrsonly: int = 0,
        serverctrls: Any = ...,
        clientctrls: Any = ...,
        timeout: int = -1,
    ) -> Any: ...
    def read_rootdse_s(self, filterstr: Any = ..., attrlist: Any = ...) -> Any: ...
    def get_naming_contexts(self) -> Any: ...

class ReconnectLDAPObject(SimpleLDAPObject):
    __transient_attrs__: Any
    def __init__(
        self,
        uri: str,
        trace_level: int = 0,
        trace_file: Any = ...,
        trace_stack_limit: int = 5,
        bytes_mode: Any = ...,
        bytes_strictness: Any = ...,
        retry_max: int = 1,
        retry_delay: float = 60.0,
        fileno: Any = ...,
    ) -> None: ...
    def passwd_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def reconnect(self, uri: str, retry_max: int = 1, retry_delay: float = 60.0, force: bool = True) -> None: ...
    def set_option(self, option: Any, invalue: Any) -> None: ...
    def bind_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def simple_bind_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def start_tls_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def sasl_interactive_bind_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def sasl_bind_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def add_ext_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def cancel_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def compare_ext_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def delete_ext_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def extop_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def modify_ext_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def rename_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def search_ext_s(self, *args: Any, **kwargs: Any) -> Any: ...
    def whoami_s(self, *args: Any, **kwargs: Any) -> Any: ...

class LDAPObject(SimpleLDAPObject): ...
