from _typeshed import Incomplete

class logging_file_class:
    def __init__(self, logging_level: int) -> None: ...
    def write(self, msg: str) -> None: ...
    def flush(self) -> None: ...

logging_file_obj: Incomplete
