from _typeshed import Incomplete

from ..graphicsItems.ROI import ROI
from ..Qt import QtWidgets

__all__ = ["Canvas"]

class Canvas(QtWidgets.QWidget):
    sigSelectionChanged: Incomplete
    sigItemTransformChanged: Incomplete
    sigItemTransformChangeFinished: Incomplete
    ui: Incomplete
    view: Incomplete
    itemList: Incomplete
    allowTransforms: Incomplete
    multiSelectBox: Incomplete
    redirect: Incomplete
    items: Incomplete
    grid: Incomplete
    hideBtn: Incomplete
    ctrlSize: int
    sizeApplied: bool
    registeredName: Incomplete
    menu: Incomplete
    def __init__(self, parent=None, allowTransforms: bool = True, hideCtrl: bool = False, name=None) -> None: ...
    def splitterMoved(self) -> None: ...
    def hideBtnClicked(self) -> None: ...
    def autoRange(self) -> None: ...
    def resizeEvent(self, ev=None) -> None: ...
    def updateRedirect(self, *args) -> None: ...
    def redirectItems(self, canvas) -> None: ...
    def reclaimItems(self) -> None: ...
    def treeItemChanged(self, item, col) -> None: ...
    def treeItemSelected(self) -> None: ...
    def selectedItems(self): ...
    def selectItem(self, item) -> None: ...
    def showMultiSelectBox(self) -> None: ...
    def mirrorSelectionClicked(self) -> None: ...
    def reflectSelectionClicked(self) -> None: ...
    def resetTransformsClicked(self) -> None: ...
    def multiSelectBoxChanged(self) -> None: ...
    def multiSelectBoxChangeFinished(self) -> None: ...
    def multiSelectBoxMoved(self) -> None: ...
    def addGraphicsItem(self, item, **opts): ...
    def addGroup(self, name, **kargs): ...
    def addItem(self, citem): ...
    def treeItemMoved(self, item, parent, index) -> None: ...
    def itemVisibilityChanged(self, item) -> None: ...
    def removeItem(self, item) -> None: ...
    def clear(self) -> None: ...
    def addToScene(self, item) -> None: ...
    def removeFromScene(self, item) -> None: ...
    def listItems(self): ...
    def getListItem(self, name): ...
    def itemTransformChanged(self, item) -> None: ...
    def itemTransformChangeFinished(self, item) -> None: ...
    menuItem: Incomplete
    def itemListContextMenuEvent(self, ev) -> None: ...
    def removeClicked(self) -> None: ...

class SelectBox(ROI):
    def __init__(self, scalable: bool = False) -> None: ...
