from geojson.base import GeoJSON

class Feature(GeoJSON):
    def __init__(self, id=None, geometry=None, properties=None, **extra) -> None: ...
    def errors(self): ...

class FeatureCollection(GeoJSON):
    def __init__(self, features, **extra) -> None: ...
    def errors(self): ...
    def __getitem__(self, key): ...
