from collections.abc import Iterable
from typing import Any

from geojson.base import GeoJSON

from geojson import Feature

DEFAULT_PRECISION: int

class Geometry(GeoJSON):
    def __init__(
        self, coordinates: None | Feature | Iterable[Any] = None, validate: bool = False, precision: None | int = None, **extra
    ) -> None: ...
    @classmethod
    def clean_coordinates(
        cls, coords: Geometry | tuple[Any, ...] | list[tuple[Any, ...]], precision: None | int
    ) -> None | tuple[Any, ...] | list[tuple[Any, ...]]: ...

class GeometryCollection(GeoJSON):
    def __init__(self, geometries=..., **extra) -> None: ...
    def errors(self) -> list[str] | None: ...
    def __getitem__(self, key) -> Geometry | tuple[()] | None: ...

def check_point(coord) -> str | None: ...

class Point(Geometry):
    def errors(self) -> list[str] | None: ...

class MultiPoint(Geometry):
    def errors(self) -> list[str] | None: ...

def check_line_string(coord) -> str | None: ...

class LineString(MultiPoint):
    def errors(self) -> list[str] | None: ...

class MultiLineString(Geometry):
    def errors(self) -> list[str] | None: ...

def check_polygon(coord) -> str | None: ...

class Polygon(Geometry):
    def errors(self) -> list[str] | None: ...

class MultiPolygon(Geometry):
    def errors(self) -> list[str] | None: ...

class Default: ...
