from collections.abc import Generator
from typing import Any, Literal

from geojson.geometry import Geometry

from geojson import Feature, GeoJSON

def coords(obj: Feature | Geometry | dict[str, Any]) -> Generator[tuple[Any]]: ...
def map_coords(func, obj) -> dict[str, Any]: ...
def map_tuples(func, obj) -> list[tuple[float]]: ...
def map_geometries(func, obj) -> GeoJSON: ...
def generate_random(
    featureType: Literal["Point", "LineString", "Polygon"],
    numberVertices: int = 3,
    boundingBox: list[float] = [-180.0, -90.0, 180.0, 90.0],
) -> Feature: ...
