from _typeshed import Incomplete
from collections.abc import Generator

def coords(obj) -> Generator[Incomplete, Incomplete]: ...
def map_coords(func, obj): ...
def map_tuples(func, obj): ...
def map_geometries(func, obj): ...
def generate_random(featureType, numberVertices: int = 3, boundingBox=[-180.0, -90.0, 180.0, 90.0]): ...
