from _typeshed import Incomplete

class HaltServer(BaseException):
    reason: Incomplete
    exit_status: Incomplete
    def __init__(self, reason, exit_status: int = 1) -> None: ...

class ConfigError(Exception): ...
class AppImportError(Exception): ...
