from _typeshed import Incomplete

class Pidfile:
    fname: Incomplete
    pid: Incomplete
    def __init__(self, fname) -> None: ...
    def create(self, pid) -> None: ...
    def rename(self, path) -> None: ...
    def unlink(self) -> None: ...
    def validate(self): ...
