# AUTOGENERATED BY scripts/sync_auth0_python.py
from typing import type_check_only

from auth0.management.blacklists import Blacklists

@type_check_only
class _BlacklistsAsync(Blacklists):
    async def get_async(self, aud: str | None = None) -> list[dict[str, str]]: ...
    async def create_async(self, jti: str, aud: str | None = None) -> dict[str, str]: ...
