# AUTOGENERATED BY scripts/sync_auth0_python.py
from typing import Any, type_check_only

from auth0.management.connections import Connections

@type_check_only
class _ConnectionsAsync(Connections):
    async def all_async(
        self,
        strategy: str | None = None,
        fields: list[str] | None = None,
        include_fields: bool = True,
        page: int | None = None,
        per_page: int | None = None,
        extra_params: dict[str, Any] | None = None,
        name: str | None = None,
    ) -> list[dict[str, Any]]: ...
    async def get_async(self, id: str, fields: list[str] | None = None, include_fields: bool = True) -> dict[str, Any]: ...
    async def delete_async(self, id: str) -> Any: ...
    async def update_async(self, id: str, body: dict[str, Any]) -> dict[str, Any]: ...
    async def create_async(self, body: dict[str, Any]) -> dict[str, Any]: ...
    async def delete_user_by_email_async(self, id: str, email: str) -> Any: ...
