# AUTOGENERATED BY scripts/sync_auth0_python.py
from typing import Any, type_check_only

from auth0.management.email_templates import EmailTemplates

@type_check_only
class _EmailTemplatesAsync(EmailTemplates):
    async def create_async(self, body: dict[str, Any]) -> dict[str, Any]: ...
    async def get_async(self, template_name: str) -> dict[str, Any]: ...
    async def update_async(self, template_name: str, body: dict[str, Any]) -> dict[str, Any]: ...
