# AUTOGENERATED BY scripts/sync_auth0_python.py
from typing import Any, type_check_only

from auth0.management.grants import Grants

@type_check_only
class _GrantsAsync(Grants):
    async def all_async(
        self,
        page: int | None = None,
        per_page: int | None = None,
        include_totals: bool = False,
        extra_params: dict[str, Any] | None = None,
    ): ...
    async def delete_async(self, id: str) -> Any: ...
