# AUTOGENERATED BY scripts/sync_auth0_python.py
from typing import Any, type_check_only

from auth0.management.jobs import Jobs

@type_check_only
class _JobsAsync(Jobs):
    async def get_async(self, id: str) -> dict[str, Any]: ...
    async def get_failed_job_async(self, id: str) -> dict[str, Any]: ...
    async def export_users_async(self, body: dict[str, Any]): ...
    async def import_users_async(
        self,
        connection_id: str,
        file_obj: Any,
        upsert: bool = False,
        send_completion_email: bool = True,
        external_id: str | None = None,
    ) -> dict[str, Any]: ...
    async def send_verification_email_async(self, body: dict[str, Any]) -> dict[str, Any]: ...
