# AUTOGENERATED BY scripts/sync_auth0_python.py
from typing import Any, type_check_only

from auth0.management.tenants import Tenants

@type_check_only
class _TenantsAsync(Tenants):
    async def get_async(self, fields: list[str] | None = None, include_fields: bool = True) -> dict[str, Any]: ...
    async def update_async(self, body: dict[str, Any]) -> dict[str, Any]: ...
