import ast
from _typeshed import Incomplete

FUNCTION_CALL_MODIFIERS: Incomplete
IMPORT_MODIFIERS: Incomplete
NAME_MODIFIERS: Incomplete
MODULE_MODIFIERS: Incomplete
IMPORT_FROM_MODIFIERS: Incomplete

class ASTTransformer(ast.NodeTransformer):
    def visit_Call(self, node): ...
    def visit_Name(self, node): ...
    def visit_Import(self, node): ...
    def visit_Module(self, node): ...
    def visit_ImportFrom(self, node): ...
