from typing import Any, ClassVar
from _typeshed import Incomplete
from tree_sitter import Language

class Node:
    start_byte: int
    start_point: tuple[int,int]
    end_byte:int
    end_point:tuple[int,int]
    has_changes:bool
    has_error:bool
    is_missing:bool
    is_named:bool
    child_count:int
    named_child_count:bool
    children:list[Node]
    next_named_sibling: Node|None
    next_sibling: Node|None
    parent: Node|None
    prev_named_sibling: Node|None
    prev_sibling: Node|None
    text: bytes
    type: str
    __hash__: ClassVar[None]  # type: ignore[assignment]
    def child_by_field_id(self, __id: int) -> Node|None: ...
    def child_by_field_name(self,__name:str)->Node|None: ...
    def sexp(self)->str: ...
    def walk(self)->TreeCursor: ...
    def __eq__(self, other:object)->bool: ...
    def __ne__(self, other:object)->bool: ...
    # There are __ge__, __gt__, __le__, __lt__ methods but they seem to always return False
    #
    #    >>> n
    #    <Node kind=call, start_point=(0, 0), end_point=(0, 14)>
    #    >>> n >= "", n <= "", n >= 0, n <= 0, n >= (0,0), n <= (0,0)
    #    (False, False, False, False, False, False)
    def __ge__(self, other:object)->bool: ...
    def __gt__(self, other:object)->bool: ...
    def __le__(self, other:object)->bool: ...
    def __lt__(self, other:object)->bool: ...

class Parser:
    # At runtime, Parser(1, 2, 3) ignores the arguments, but that's most likely buggy code
    def __init__(self) -> None: ...
    def parse(self, source: bytes, old_tree: Tree | None = ..., keep_text: bool = ...) -> Tree: ...
    def set_language(self, __language: Language) -> None: ...

class Query:
    def captures(self, *args, **kwargs): ...
    def matches(self, *args, **kwargs): ...

class Tree:
    root_node: Node
    text: bytes
    def edit(self, start_byte: int, old_end_byte: int, new_end_byte: int, start_point: tuple[int, int], old_end_point: tuple[int, int], new_end_point: tuple[int, int])->None: ...
    def walk(self) -> TreeCursor: ...

class TreeCursor:
    node: Node
    def current_field_name(self) -> None | Incomplete: ...
    def goto_first_child(self) -> bool: ...
    def goto_next_sibling(self) -> bool: ...
    def goto_parent(self) -> bool: ...
