"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Protocol Buffers - Google's data interchange format
Copyright 2026 Google LLC.  All rights reserved.

Use of this source code is governed by a BSD-style
license that can be found in the LICENSE file or at
https://developers.google.com/open-source/licenses/bsd
"""

import builtins as _builtins
import sys
import typing as _typing

from google.protobuf import descriptor as _descriptor, descriptor_pb2 as _descriptor_pb2, message as _message
from google.protobuf.internal import extension_dict as _extension_dict

if sys.version_info >= (3, 11):
    from typing import Never as _Never, TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias
    from typing_extensions import Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class JsonEnumValueOptions(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    STRING_FIELD_NUMBER: _builtins.int
    string: _builtins.str
    """Allows user to specify a custom string to use when serializing an enum
    value to JSON.

    Sample usage:
    enum Foo {
      ...
      FOO_BAR = 42 [(pb.enumvalue.json).string = "my_custom_name"];
    }
    """
    def __init__(self, *, string: _builtins.str | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["string", b"string"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["string", b"string"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___JsonEnumValueOptions: _TypeAlias = JsonEnumValueOptions  # noqa: Y015

JSON_FIELD_NUMBER: _builtins.int
json: _extension_dict._ExtensionFieldDescriptor[_descriptor_pb2.EnumValueOptions, Global___JsonEnumValueOptions]
