"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Protocol Buffers - Google's data interchange format
Copyright 2008 Google Inc.  All rights reserved.
https://developers.google.com/protocol-buffers/

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are
met:

    * Redistributions of source code must retain the above copyright
notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above
copyright notice, this list of conditions and the following disclaimer
in the documentation and/or other materials provided with the
distribution.
    * Neither the name of Google Inc. nor the names of its
contributors may be used to endorse or promote products derived from
this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

import builtins as _builtins
import sys
import typing as _typing
from collections import abc as _abc

from google.protobuf import descriptor as _descriptor, message as _message
from google.protobuf.internal import (
    containers as _containers,
    enum_type_wrapper as _enum_type_wrapper,
    well_known_types as _well_known_types,
)

if sys.version_info >= (3, 11):
    from typing import Never as _Never, TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias
    from typing_extensions import Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

class _NullValue:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _NullValueEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_NullValue.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    NULL_VALUE: _NullValue.ValueType  # 0
    """Null value."""

class NullValue(_NullValue, metaclass=_NullValueEnumTypeWrapper):
    """Represents a JSON `null`.

    `NullValue` is a sentinel, using an enum with only one value to represent
    the null value for the `Value` type union.

    A field of type `NullValue` with any value other than `0` is considered
    invalid. Most ProtoJSON serializers will emit a `Value` with a `null_value`
    set as a JSON `null` regardless of the integer value, and so will round trip
    to a `0` value.
    """

NULL_VALUE: NullValue.ValueType  # 0
"""Null value."""
Global___NullValue: _TypeAlias = NullValue  # noqa: Y015

@_typing.final
class Struct(_message.Message, _well_known_types.Struct):
    """Represents a JSON object.

    An unordered key-value map, intending to perfectly capture the semantics of a
    JSON object. This enables parsing any arbitrary JSON payload as a message
    field in ProtoJSON format.

    This follows RFC 8259 guidelines for interoperable JSON: notably this type
    cannot represent large Int64 values or `NaN`/`Infinity` numbers,
    since the JSON format generally does not support those values in its number
    type.

    If you do not intend to parse arbitrary JSON into your message, a custom
    typed message should be preferred instead of using this type.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class FieldsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___Value: ...
        def __init__(self, *, key: _builtins.str | None = ..., value: Global___Value | None = ...) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    FIELDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def fields(self) -> _containers.MessageMap[_builtins.str, Global___Value]:
        """Unordered map of dynamically typed values."""

    def __init__(self, *, fields: _abc.Mapping[_builtins.str, Global___Value] | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["fields", b"fields"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___Struct: _TypeAlias = Struct  # noqa: Y015

@_typing.final
class Value(_message.Message):
    """Represents a JSON value.

    `Value` represents a dynamically typed value which can be either
    null, a number, a string, a boolean, a recursive struct value, or a
    list of values. A producer of value is expected to set one of these
    variants. Absence of any variant is an invalid state.
    """

    DESCRIPTOR: _descriptor.Descriptor

    NULL_VALUE_FIELD_NUMBER: _builtins.int
    NUMBER_VALUE_FIELD_NUMBER: _builtins.int
    STRING_VALUE_FIELD_NUMBER: _builtins.int
    BOOL_VALUE_FIELD_NUMBER: _builtins.int
    STRUCT_VALUE_FIELD_NUMBER: _builtins.int
    LIST_VALUE_FIELD_NUMBER: _builtins.int
    null_value: Global___NullValue.ValueType
    """Represents a JSON `null`."""
    number_value: _builtins.float
    """Represents a JSON number. Must not be `NaN`, `Infinity` or
    `-Infinity`, since those are not supported in JSON. This also cannot
    represent large Int64 values, since JSON format generally does not
    support them in its number type.
    """
    string_value: _builtins.str
    """Represents a JSON string."""
    bool_value: _builtins.bool
    """Represents a JSON boolean (`true` or `false` literal in JSON)."""
    @_builtins.property
    def struct_value(self) -> Global___Struct:
        """Represents a JSON object."""

    @_builtins.property
    def list_value(self) -> Global___ListValue:
        """Represents a JSON array."""

    def __init__(
        self,
        *,
        null_value: Global___NullValue.ValueType | None = ...,
        number_value: _builtins.float | None = ...,
        string_value: _builtins.str | None = ...,
        bool_value: _builtins.bool | None = ...,
        struct_value: Global___Struct | None = ...,
        list_value: Global___ListValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "bool_value",
        b"bool_value",
        "kind",
        b"kind",
        "list_value",
        b"list_value",
        "null_value",
        b"null_value",
        "number_value",
        b"number_value",
        "string_value",
        b"string_value",
        "struct_value",
        b"struct_value",
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "bool_value",
        b"bool_value",
        "kind",
        b"kind",
        "list_value",
        b"list_value",
        "null_value",
        b"null_value",
        "number_value",
        b"number_value",
        "string_value",
        b"string_value",
        "struct_value",
        b"struct_value",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_kind: _TypeAlias = _typing.Literal[
        "null_value", "number_value", "string_value", "bool_value", "struct_value", "list_value"
    ]  # noqa: Y015
    _WhichOneofArgType_kind: _TypeAlias = _typing.Literal["kind", b"kind"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_kind) -> _WhichOneofReturnType_kind | None: ...

Global___Value: _TypeAlias = Value  # noqa: Y015

@_typing.final
class ListValue(_message.Message, _well_known_types.ListValue):
    """Represents a JSON array."""

    DESCRIPTOR: _descriptor.Descriptor

    VALUES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def values(self) -> _containers.RepeatedCompositeFieldContainer[Global___Value]:
        """Repeated field of dynamically typed values."""

    def __init__(self, *, values: _abc.Iterable[Global___Value] | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListValue: _TypeAlias = ListValue  # noqa: Y015
