from typing import Any, TypeVar, Callable, Iterable, Optional, Iterator
from ._base import Executor, Future

_T = TypeVar('_T')

class ThreadPoolExecutor(Executor):
    def __init__(self, max_workers: Optional[int] = ...) -> None: ...
    def submit(self, fn: Callable[..., _T], *args: Any, **kwargs: Any) -> Future[_T]: ...
    def map(self, func: Callable[..., _T], *iterables: Iterable[Any], timeout: Optional[float] = ..., chunksize: int = ...) -> Iterator[_T]: ...
    def shutdown(self, wait: bool = ...) -> None: ...
