from _typeshed import StrPath
from collections.abc import MutableSequence

def spawn(cmd: MutableSequence[bytes | StrPath], **kwargs) -> None: ...
def find_executable(executable: str, path: str | None = None) -> str | None: ...
