from typing import Any

from .errors import DistutilsPlatformError as DistutilsPlatformError

IS_PYPY: Any
PREFIX: Any
EXEC_PREFIX: Any
BASE_PREFIX: Any
BASE_EXEC_PREFIX: Any
project_base: Any
python_build: Any
build_flags: str

def get_python_version(): ...
def get_python_inc(plat_specific: int = ..., prefix: Any | None = ...): ...
def get_python_lib(plat_specific: int = ..., standard_lib: int = ..., prefix: Any | None = ...): ...
def customize_compiler(compiler) -> None: ...
def get_config_h_filename(): ...
def get_makefile_filename(): ...
def parse_config_h(fp, g: Any | None = ...): ...
def parse_makefile(fn, g: Any | None = ...): ...
def expand_makefile_vars(s, vars): ...
def get_config_vars(*args): ...
def get_config_var(name): ...
