from typing import Any

def get_host_platform(): ...
def get_platform(): ...

MACOSX_VERSION_VAR: str

def get_macosx_target_ver_from_syscfg(): ...
def get_macosx_target_ver(): ...
def split_version(s): ...
def convert_path(pathname): ...
def change_root(new_root, pathname): ...
def check_environ() -> None: ...
def subst_vars(s, local_vars): ...
def grok_environment_error(exc, prefix: str = ...): ...
def split_quoted(s): ...
def execute(func, args, msg: Any | None = ..., verbose: int = ..., dry_run: int = ...) -> None: ...
def strtobool(val): ...
def byte_compile(
    py_files,
    optimize: int = ...,
    force: int = ...,
    prefix: Any | None = ...,
    base_dir: Any | None = ...,
    verbose: int = ...,
    dry_run: int = ...,
    direct: Any | None = ...,
) -> None: ...
def rfc822_escape(header): ...
def run_2to3(files, fixer_names: Any | None = ..., options: Any | None = ..., explicit: Any | None = ...) -> None: ...
def copydir_run_2to3(
    src, dest, template: Any | None = ..., fixer_names: Any | None = ..., options: Any | None = ..., explicit: Any | None = ...
): ...

class Mixin2to3:
    fixer_names: Any
    options: Any
    explicit: Any
    def run_2to3(self, files): ...
