from typing import Any

class Version:
    def __init__(self, vstring: Any | None = ...) -> None: ...
    def __eq__(self, other): ...
    def __lt__(self, other): ...
    def __le__(self, other): ...
    def __gt__(self, other): ...
    def __ge__(self, other): ...

class StrictVersion(Version):
    version_re: Any
    version: Any
    prerelease: Any
    def parse(self, vstring) -> None: ...

class LooseVersion(Version):
    component_re: Any
    def __init__(self, vstring: Any | None = ...) -> None: ...
    vstring: Any
    version: Any
    def parse(self, vstring) -> None: ...
