import sys
from typing import Any, Optional, TypeVar, Union, Pattern, Tuple

_T = TypeVar('_T', bound='Version')

class Version:
    def __init__(self, vstring: Optional[str] = None) -> None: ...
    def __repr__(self) -> str: ...

    if sys.version_info >= (3,):
        def __eq__(self, other: object) -> bool: ...
        def __lt__(self: _T, other: Union[_T, str]) -> bool: ...
        def __le__(self: _T, other: Union[_T, str]) -> bool: ...
        def __gt__(self: _T, other: Union[_T, str]) -> bool: ...
        def __ge__(self: _T, other: Union[_T, str]) -> bool: ...

    # Methods part of the 'Version' interface, but not implemented
    # within the class itself

    def parse(self: _T, vstring: str) -> _T: ...
    def __str__(self) -> str: ...
    if sys.version_info >= (3,):
        def _cmp(self: _T, other: Union[_T, str]) -> bool: ...
    else:
        def __cmp__(self: _T, other: Union[_T, str]) -> bool: ...

class StrictVersion(Version):
    version_re: Pattern[str]
    version: Tuple[int, int, int]
    prerelease: Optional[Tuple[str, int]]

class LooseVersion(Version):
    component_re: Pattern[str]
    vstring: str
    version: Tuple[Union[str, int], ...]
