from _typeshed import Incomplete

class Hyperparameter:
    validation: Incomplete
    validation_message: Incomplete
    name: Incomplete
    data_type: Incomplete
    def __init__(self, name, validate=..., validation_message: str = "", data_type=...) -> None: ...
    def validate(self, value) -> None: ...
    def __get__(self, obj, objtype): ...
    def __set__(self, obj, value) -> None: ...
    def __delete__(self, obj) -> None: ...
    @staticmethod
    def serialize_all(obj): ...
