from _typeshed import Incomplete

from ..construct import Adapter, Construct, Subconstruct

class RepeatUntilExcluding(Subconstruct):
    predicate: Incomplete
    def __init__(self, predicate, subcon) -> None: ...

class _ULEB128Adapter(Adapter): ...
class _SLEB128Adapter(Adapter): ...

def ULEB128(name): ...
def SLEB128(name): ...

class StreamOffset(Construct):
    def __init__(self, name) -> None: ...
