from io import FileIO
from typing import Any, overload

def lex(code, lexer): ...
@overload
def format(tokens, formatter, outfile: FileIO) -> None: ...
@overload
def format(tokens, formatter, outfile: None = ...) -> str: ...
@overload
def highlight(code, lexer, formatter, outfile: FileIO) -> None: ...
@overload
def highlight(code, lexer, formatter, outfile: None = ...) -> str: ...
