import re

class EndOfText(RuntimeError): ...

class Scanner:
    data: str
    data_length: int
    start_pos: int
    pos: int
    flags: int
    last: str
    match: str
    def __init__(self, text: str, flags: int = 0) -> None: ...
    @property
    def eos(self) -> bool: ...
    def check(self, pattern: str) -> re.Match[str] | None: ...
    def test(self, pattern: str) -> bool: ...
    def scan(self, pattern: str) -> bool: ...
    def get_char(self) -> None: ...
