from io import TextIOWrapper
from typing import Any, Optional

split_path_re: Any
doctype_lookup_re: Any
tag_re: Any
xml_decl_re: Any

class ClassNotFound(ValueError): ...
class OptionError(Exception): ...

def get_choice_opt(options: Any, optname: Any, allowed: Any, default: Optional[Any] = ..., normcase: bool = ...): ...
def get_bool_opt(options: Any, optname: Any, default: Optional[Any] = ...): ...
def get_int_opt(options: Any, optname: Any, default: Optional[Any] = ...): ...
def get_list_opt(options: Any, optname: Any, default: Optional[Any] = ...): ...
def docstring_headline(obj: Any): ...
def make_analysator(f: Any): ...
def shebang_matches(text: Any, regex: Any): ...
def doctype_matches(text: Any, regex: Any): ...
def html_doctype_matches(text: Any): ...
def looks_like_xml(text: Any): ...
def surrogatepair(c: Any): ...
def format_lines(var_name: Any, seq: Any, raw: bool = ..., indent_level: int = ...): ...
def duplicates_removed(it: Any, already_seen: Any = ...): ...

class Future:
    def get(self) -> None: ...

def guess_decode(text: Any): ...
def guess_decode_from_terminal(text: Any, term: Any): ...
def terminal_encoding(term: Any): ...

class UnclosingTextIOWrapper(TextIOWrapper):
    def close(self) -> None: ...
