from typing import Any, ClassVar, List

import psycopg2
import psycopg2.extensions
BINARY: type
BINARYARRAY: type
BOOLEAN: type
BOOLEANARRAY: type
BYTES: type
BYTESARRAY: type
CIDRARRAY: type
DATE: type
DATEARRAY: type
DATETIME: type
DATETIMEARRAY: type
DATETIMETZ: type
DATETIMETZARRAY: type
DECIMAL: type
DECIMALARRAY: type
FLOAT: type
FLOATARRAY: type
INETARRAY: type
INTEGER: type
INTEGERARRAY: type
INTERVAL: type
INTERVALARRAY: type
LONGINTEGER: type
LONGINTEGERARRAY: type
MACADDRARRAY: type
NUMBER: type
PYDATE: type
PYDATEARRAY: type
PYDATETIME: type
PYDATETIMEARRAY: type
PYDATETIMETZ: type
PYDATETIMETZARRAY: type
PYINTERVAL: type
PYINTERVALARRAY: type
PYTIME: type
PYTIMEARRAY: type
REPLICATION_LOGICAL: int
REPLICATION_PHYSICAL: int
ROWID: type
ROWIDARRAY: type
STRING: type
STRINGARRAY: type
TIME: type
TIMEARRAY: type
UNICODE: type
UNICODEARRAY: type
UNKNOWN: type
adapters: dict
apilevel: str
binary_types: dict
encodings: dict
paramstyle: str
sqlstate_errors: dict
string_types: dict
threadsafety: int

class AsIs:
    adapted: ClassVar[member_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getquoted(self, *args, **kwargs) -> Any: ...
    def __conform__(self, *args, **kwargs) -> Any: ...

class Binary:
    adapted: ClassVar[member_descriptor] = ...
    buffer: ClassVar[member_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getquoted(self, *args, **kwargs) -> Any: ...
    def prepare(conn) -> prepareforbinaryencodingusingconn: ...
    def __conform__(self, *args, **kwargs) -> Any: ...

class Boolean:
    adapted: ClassVar[member_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getquoted(self, *args, **kwargs) -> Any: ...
    def __conform__(self, *args, **kwargs) -> Any: ...

class Column:
    display_size: ClassVar[member_descriptor] = ...
    internal_size: ClassVar[member_descriptor] = ...
    name: ClassVar[member_descriptor] = ...
    null_ok: ClassVar[member_descriptor] = ...
    precision: ClassVar[member_descriptor] = ...
    scale: ClassVar[member_descriptor] = ...
    table_column: ClassVar[member_descriptor] = ...
    table_oid: ClassVar[member_descriptor] = ...
    type_code: ClassVar[member_descriptor] = ...
    __hash__: ClassVar[None] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __getitem__(self, index) -> Any: ...
    def __getstate__(self) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __len__(self) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class ConnectionInfo:
    backend_pid: ClassVar[getset_descriptor] = ...
    dbname: ClassVar[getset_descriptor] = ...
    dsn_parameters: ClassVar[getset_descriptor] = ...
    error_message: ClassVar[getset_descriptor] = ...
    host: ClassVar[getset_descriptor] = ...
    needs_password: ClassVar[getset_descriptor] = ...
    options: ClassVar[getset_descriptor] = ...
    password: ClassVar[getset_descriptor] = ...
    port: ClassVar[getset_descriptor] = ...
    protocol_version: ClassVar[getset_descriptor] = ...
    server_version: ClassVar[getset_descriptor] = ...
    socket: ClassVar[getset_descriptor] = ...
    ssl_attribute_names: ClassVar[getset_descriptor] = ...
    ssl_in_use: ClassVar[getset_descriptor] = ...
    status: ClassVar[getset_descriptor] = ...
    transaction_status: ClassVar[getset_descriptor] = ...
    used_password: ClassVar[getset_descriptor] = ...
    user: ClassVar[getset_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def parameter_status(self, *args, **kwargs) -> Any: ...
    def ssl_attribute(self, *args, **kwargs) -> Any: ...

class DataError(psycopg2.DatabaseError): ...

class DatabaseError(psycopg2.Error): ...

class Decimal:
    adapted: ClassVar[member_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getquoted(self, *args, **kwargs) -> Any: ...
    def __conform__(self, *args, **kwargs) -> Any: ...

class Diagnostics:
    column_name: ClassVar[getset_descriptor] = ...
    constraint_name: ClassVar[getset_descriptor] = ...
    context: ClassVar[getset_descriptor] = ...
    datatype_name: ClassVar[getset_descriptor] = ...
    internal_position: ClassVar[getset_descriptor] = ...
    internal_query: ClassVar[getset_descriptor] = ...
    message_detail: ClassVar[getset_descriptor] = ...
    message_hint: ClassVar[getset_descriptor] = ...
    message_primary: ClassVar[getset_descriptor] = ...
    schema_name: ClassVar[getset_descriptor] = ...
    severity: ClassVar[getset_descriptor] = ...
    severity_nonlocalized: ClassVar[getset_descriptor] = ...
    source_file: ClassVar[getset_descriptor] = ...
    source_function: ClassVar[getset_descriptor] = ...
    source_line: ClassVar[getset_descriptor] = ...
    sqlstate: ClassVar[getset_descriptor] = ...
    statement_position: ClassVar[getset_descriptor] = ...
    table_name: ClassVar[getset_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...

class Error(Exception):
    cursor: ClassVar[member_descriptor] = ...
    diag: ClassVar[getset_descriptor] = ...
    pgcode: ClassVar[member_descriptor] = ...
    pgerror: ClassVar[member_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self) -> Any: ...
    def __setstate__(self, state) -> Any: ...

class Float:
    adapted: ClassVar[member_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getquoted(self, *args, **kwargs) -> Any: ...
    def __conform__(self, *args, **kwargs) -> Any: ...

class ISQLQuote:
    _wrapped: ClassVar[member_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getbinary() -> Any: ...
    def getbuffer() -> Any: ...
    def getquoted() -> Any: ...

class Int:
    adapted: ClassVar[member_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getquoted(self, *args, **kwargs) -> Any: ...
    def __conform__(self, *args, **kwargs) -> Any: ...

class IntegrityError(psycopg2.DatabaseError): ...

class InterfaceError(psycopg2.Error): ...

class InternalError(psycopg2.DatabaseError): ...

class List:
    adapted: ClassVar[member_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getquoted(self, *args, **kwargs) -> Any: ...
    def prepare(self, *args, **kwargs) -> Any: ...
    def __conform__(self, *args, **kwargs) -> Any: ...

class NotSupportedError(psycopg2.DatabaseError): ...

class Notify:
    channel: ClassVar[member_descriptor] = ...
    payload: ClassVar[member_descriptor] = ...
    pid: ClassVar[member_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __eq__(self, other) -> Any: ...
    def __ge__(self, other) -> Any: ...
    def __getitem__(self, index) -> Any: ...
    def __gt__(self, other) -> Any: ...
    def __hash__(self) -> Any: ...
    def __le__(self, other) -> Any: ...
    def __len__(self) -> Any: ...
    def __lt__(self, other) -> Any: ...
    def __ne__(self, other) -> Any: ...

class OperationalError(psycopg2.DatabaseError): ...

class ProgrammingError(psycopg2.DatabaseError): ...

class QueryCanceledError(psycopg2.OperationalError): ...

class QuotedString:
    adapted: ClassVar[member_descriptor] = ...
    buffer: ClassVar[member_descriptor] = ...
    encoding: ClassVar[getset_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getquoted(self, *args, **kwargs) -> Any: ...
    def prepare(self, *args, **kwargs) -> Any: ...
    def __conform__(self, *args, **kwargs) -> Any: ...

class ReplicationConnection(psycopg2.extensions.connection):
    autocommit: ClassVar[getset_descriptor] = ...
    isolation_level: ClassVar[getset_descriptor] = ...
    replication_type: ClassVar[getset_descriptor] = ...
    reset: ClassVar[getset_descriptor] = ...
    set_isolation_level: ClassVar[getset_descriptor] = ...
    set_session: ClassVar[getset_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...

class ReplicationCursor(psycopg2.extensions.cursor):
    feedback_timestamp: ClassVar[getset_descriptor] = ...
    io_timestamp: ClassVar[getset_descriptor] = ...
    wal_end: ClassVar[member_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def consume_stream(consumer, keepalive_interval = ...) -> Any: ...
    def read_message() -> Any: ...
    def send_feedback(write_lsn = ..., flush_lsn = ..., apply_lsn = ..., reply = ..., force = ...) -> Any: ...
    def start_replication_expert(command, decode = ..., status_interval = ...) -> Any: ...

class ReplicationMessage:
    cursor: ClassVar[member_descriptor] = ...
    data_size: ClassVar[member_descriptor] = ...
    data_start: ClassVar[member_descriptor] = ...
    payload: ClassVar[member_descriptor] = ...
    send_time: ClassVar[getset_descriptor] = ...
    wal_end: ClassVar[member_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...

class TransactionRollbackError(psycopg2.OperationalError): ...

class Warning(Exception): ...

class Xid:
    bqual: ClassVar[member_descriptor] = ...
    database: ClassVar[member_descriptor] = ...
    format_id: ClassVar[member_descriptor] = ...
    gtrid: ClassVar[member_descriptor] = ...
    owner: ClassVar[member_descriptor] = ...
    prepared: ClassVar[member_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def from_string(self, *args, **kwargs) -> Any: ...
    def __getitem__(self, index) -> Any: ...
    def __len__(self) -> Any: ...

class connection:
    DataError: ClassVar[getset_descriptor] = ...
    DatabaseError: ClassVar[getset_descriptor] = ...
    Error: ClassVar[getset_descriptor] = ...
    IntegrityError: ClassVar[getset_descriptor] = ...
    InterfaceError: ClassVar[getset_descriptor] = ...
    InternalError: ClassVar[getset_descriptor] = ...
    NotSupportedError: ClassVar[getset_descriptor] = ...
    OperationalError: ClassVar[getset_descriptor] = ...
    ProgrammingError: ClassVar[getset_descriptor] = ...
    Warning: ClassVar[getset_descriptor] = ...
    async: ClassVar[member_descriptor] = ...
    async_: ClassVar[member_descriptor] = ...
    autocommit: ClassVar[getset_descriptor] = ...
    binary_types: ClassVar[member_descriptor] = ...
    closed: ClassVar[member_descriptor] = ...
    cursor_factory: ClassVar[member_descriptor] = ...
    deferrable: ClassVar[getset_descriptor] = ...
    dsn: ClassVar[member_descriptor] = ...
    encoding: ClassVar[member_descriptor] = ...
    info: ClassVar[getset_descriptor] = ...
    isolation_level: ClassVar[getset_descriptor] = ...
    notices: ClassVar[member_descriptor] = ...
    notifies: ClassVar[member_descriptor] = ...
    pgconn_ptr: ClassVar[getset_descriptor] = ...
    protocol_version: ClassVar[member_descriptor] = ...
    readonly: ClassVar[getset_descriptor] = ...
    server_version: ClassVar[member_descriptor] = ...
    status: ClassVar[member_descriptor] = ...
    string_types: ClassVar[member_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def cancel() -> Any: ...
    def close() -> Any: ...
    def commit() -> Any: ...
    def cursor(name = ..., cursor_factory = ..., withhold = ...) -> Any: ...
    def fileno(self, *args, **kwargs) -> Any: ...
    def get_backend_pid() -> Any: ...
    def get_dsn_parameters() -> Any: ...
    def get_native_connection() -> Any: ...
    def get_parameter_status(parameter) -> Any: ...
    def get_transaction_status() -> Any: ...
    def isexecuting(self, *args, **kwargs) -> Any: ...
    def lobject(oid = ..., mode = ..., new_oid = ..., new_file = ..., 
lobject_factory = ...) -> Any: ...
    def poll(self, *args, **kwargs) -> Any: ...
    def reset() -> Any: ...
    def rollback() -> Any: ...
    def set_client_encoding(encoding) -> Any: ...
    def set_isolation_level(level) -> Any: ...
    def set_session(self, *args, **kwargs) -> Any: ...
    def tpc_begin(xid) -> Any: ...
    def tpc_commit(self, *args, **kwargs) -> Any: ...
    def tpc_prepare() -> Any: ...
    def tpc_recover() -> Any: ...
    def tpc_rollback(self, *args, **kwargs) -> Any: ...
    def xid(format_id, gtrid, bqual) -> Any: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, type, value, traceback) -> Any: ...

class cursor:
    arraysize: ClassVar[member_descriptor] = ...
    binary_types: ClassVar[member_descriptor] = ...
    closed: ClassVar[getset_descriptor] = ...
    connection: ClassVar[member_descriptor] = ...
    description: ClassVar[member_descriptor] = ...
    itersize: ClassVar[member_descriptor] = ...
    lastrowid: ClassVar[member_descriptor] = ...
    name: ClassVar[member_descriptor] = ...
    pgresult_ptr: ClassVar[getset_descriptor] = ...
    query: ClassVar[member_descriptor] = ...
    row_factory: ClassVar[member_descriptor] = ...
    rowcount: ClassVar[member_descriptor] = ...
    rownumber: ClassVar[member_descriptor] = ...
    scrollable: ClassVar[getset_descriptor] = ...
    statusmessage: ClassVar[member_descriptor] = ...
    string_types: ClassVar[member_descriptor] = ...
    typecaster: ClassVar[member_descriptor] = ...
    tzinfo_factory: ClassVar[member_descriptor] = ...
    withhold: ClassVar[getset_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def callproc(procname, parameters = ...) -> Any: ...
    def cast(oid, s) -> value: ...
    def close() -> Any: ...
    def copy_expert(sql, file, size = ...) -> Any: ...
    def copy_from(file, table, sep = ..., null = ..., size = ..., columns = ...) -> Any: ...
    def copy_to(file, table, sep = ..., null = ..., columns = ...) -> Any: ...
    def execute(query, vars = ...) -> Any: ...
    def executemany(query, vars_list) -> Any: ...
    def fetchall() -> listoftuple: ...
    def fetchmany(size = ...) -> listoftuple: ...
    def fetchone() -> tupleorNone: ...
    def mogrify(self, *args, **kwargs) -> Any: ...
    def nextset() -> Any: ...
    def scroll(value, mode = ...) -> Any: ...
    def setinputsizes(sizes) -> Any: ...
    def setoutputsize(size, column = ...) -> Any: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, type, value, traceback) -> Any: ...
    def __iter__(self) -> Any: ...
    def __next__(self) -> Any: ...

class lobject:
    closed: ClassVar[getset_descriptor] = ...
    mode: ClassVar[member_descriptor] = ...
    oid: ClassVar[member_descriptor] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def close() -> Any: ...
    def export(filename) -> Any: ...
    def read(size = ...) -> Any: ...
    def seek(offset, whence = ...) -> Any: ...
    def tell() -> Any: ...
    def truncate(len = ...) -> Any: ...
    def unlink() -> Any: ...
    def write(str) -> Any: ...

def Date(year, month, day) -> newdate: ...
def DateFromPy(*args, **kwargs) -> Any: ...
def DateFromTicks(ticks) -> newdate: ...
def IntervalFromPy(*args, **kwargs) -> Any: ...
def Time(hour, minutes, seconds, tzinfo = ...) -> newtime: ...
def TimeFromPy(*args, **kwargs) -> Any: ...
def TimeFromTicks(ticks) -> newtime: ...
def Timestamp(year, month, day, hour, minutes, seconds, tzinfo = ...) -> newtimestamp: ...
def TimestampFromPy(*args, **kwargs) -> Any: ...
def TimestampFromTicks(ticks) -> newtimestamp: ...
def _connect(*args, **kwargs) -> Any: ...
def adapt(*args, **kwargs) -> Any: ...
def encrypt_password(*args, **kwargs) -> Any: ...
def get_wait_callback(*args, **kwargs) -> Any: ...
def libpq_version(*args, **kwargs) -> Any: ...
def new_array_type(oids, name, baseobj) -> newtypeobject: ...
def new_type(oids, name, castobj) -> newtypeobject: ...
def parse_dsn(*args, **kwargs) -> Any: ...
def quote_ident(*args, **kwargs) -> Any: ...
def register_type(*args, **kwargs) -> Any: ...
def set_wait_callback(_none) -> Any: ...
