from typing import Any, ClassVar

import psycopg2
import psycopg2.extensions

BINARY: Any
BINARYARRAY: Any
BOOLEAN: Any
BOOLEANARRAY: Any
BYTES: Any
BYTESARRAY: Any
CIDRARRAY: Any
DATE: Any
DATEARRAY: Any
DATETIME: Any
DATETIMEARRAY: Any
DATETIMETZ: Any
DATETIMETZARRAY: Any
DECIMAL: Any
DECIMALARRAY: Any
FLOAT: Any
FLOATARRAY: Any
INETARRAY: Any
INTEGER: Any
INTEGERARRAY: Any
INTERVAL: Any
INTERVALARRAY: Any
LONGINTEGER: Any
LONGINTEGERARRAY: Any
MACADDRARRAY: Any
NUMBER: Any
PYDATE: Any
PYDATEARRAY: Any
PYDATETIME: Any
PYDATETIMEARRAY: Any
PYDATETIMETZ: Any
PYDATETIMETZARRAY: Any
PYINTERVAL: Any
PYINTERVALARRAY: Any
PYTIME: Any
PYTIMEARRAY: Any
REPLICATION_LOGICAL: int
REPLICATION_PHYSICAL: int
ROWID: Any
ROWIDARRAY: Any
STRING: Any
STRINGARRAY: Any
TIME: Any
TIMEARRAY: Any
UNICODE: Any
UNICODEARRAY: Any
UNKNOWN: Any
adapters: dict[Any, Any]
apilevel: str
binary_types: dict[Any, Any]
encodings: dict[Any, Any]
paramstyle: str
sqlstate_errors: dict[Any, Any]
string_types: dict[Any, Any]
threadsafety: int

__libpq_version__: int

class AsIs:
    adapted: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getquoted(self, *args, **kwargs): ...
    def __conform__(self, *args, **kwargs): ...

class Binary:
    adapted: ClassVar[Any] = ...
    buffer: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getquoted(self, *args, **kwargs): ...
    def prepare(self, conn): ...
    def __conform__(self, *args, **kwargs): ...

class Boolean:
    adapted: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getquoted(self, *args, **kwargs): ...
    def __conform__(self, *args, **kwargs): ...

class Column:
    display_size: ClassVar[Any] = ...
    internal_size: ClassVar[Any] = ...
    name: ClassVar[Any] = ...
    null_ok: ClassVar[Any] = ...
    precision: ClassVar[Any] = ...
    scale: ClassVar[Any] = ...
    table_column: ClassVar[Any] = ...
    table_oid: ClassVar[Any] = ...
    type_code: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __eq__(self, other): ...
    def __ge__(self, other): ...
    def __getitem__(self, index): ...
    def __getstate__(self): ...
    def __gt__(self, other): ...
    def __le__(self, other): ...
    def __len__(self): ...
    def __lt__(self, other): ...
    def __ne__(self, other): ...
    def __setstate__(self, state): ...

class ConnectionInfo:
    backend_pid: ClassVar[Any] = ...
    dbname: ClassVar[Any] = ...
    dsn_parameters: ClassVar[Any] = ...
    error_message: ClassVar[Any] = ...
    host: ClassVar[Any] = ...
    needs_password: ClassVar[Any] = ...
    options: ClassVar[Any] = ...
    password: ClassVar[Any] = ...
    port: ClassVar[Any] = ...
    protocol_version: ClassVar[Any] = ...
    server_version: ClassVar[Any] = ...
    socket: ClassVar[Any] = ...
    ssl_attribute_names: ClassVar[Any] = ...
    ssl_in_use: ClassVar[Any] = ...
    status: ClassVar[Any] = ...
    transaction_status: ClassVar[Any] = ...
    used_password: ClassVar[Any] = ...
    user: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def parameter_status(self, *args, **kwargs): ...
    def ssl_attribute(self, *args, **kwargs): ...

class DataError(psycopg2.DatabaseError): ...
class DatabaseError(psycopg2.Error): ...

class Decimal:
    adapted: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getquoted(self, *args, **kwargs): ...
    def __conform__(self, *args, **kwargs): ...

class Diagnostics:
    column_name: ClassVar[Any] = ...
    constraint_name: ClassVar[Any] = ...
    context: ClassVar[Any] = ...
    datatype_name: ClassVar[Any] = ...
    internal_position: ClassVar[Any] = ...
    internal_query: ClassVar[Any] = ...
    message_detail: ClassVar[Any] = ...
    message_hint: ClassVar[Any] = ...
    message_primary: ClassVar[Any] = ...
    schema_name: ClassVar[Any] = ...
    severity: ClassVar[Any] = ...
    severity_nonlocalized: ClassVar[Any] = ...
    source_file: ClassVar[Any] = ...
    source_function: ClassVar[Any] = ...
    source_line: ClassVar[Any] = ...
    sqlstate: ClassVar[Any] = ...
    statement_position: ClassVar[Any] = ...
    table_name: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...

class Error(Exception):
    cursor: ClassVar[Any] = ...
    diag: ClassVar[Any] = ...
    pgcode: ClassVar[Any] = ...
    pgerror: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __reduce__(self): ...
    def __setstate__(self, state): ...

class Float:
    adapted: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getquoted(self, *args, **kwargs): ...
    def __conform__(self, *args, **kwargs): ...

class ISQLQuote:
    _wrapped: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getbinary(self, *args, **kwargs): ...
    def getbuffer(self, *args, **kwargs): ...
    def getquoted(self, *args, **kwargs): ...

class Int:
    adapted: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getquoted(self, *args, **kwargs): ...
    def __conform__(self, *args, **kwargs): ...

class IntegrityError(psycopg2.DatabaseError): ...
class InterfaceError(psycopg2.Error): ...
class InternalError(psycopg2.DatabaseError): ...

class List:
    adapted: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getquoted(self, *args, **kwargs): ...
    def prepare(self, *args, **kwargs): ...
    def __conform__(self, *args, **kwargs): ...

class NotSupportedError(psycopg2.DatabaseError): ...

class Notify:
    channel: ClassVar[Any] = ...
    payload: ClassVar[Any] = ...
    pid: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def __eq__(self, other): ...
    def __ge__(self, other): ...
    def __getitem__(self, index): ...
    def __gt__(self, other): ...
    def __hash__(self): ...
    def __le__(self, other): ...
    def __len__(self): ...
    def __lt__(self, other): ...
    def __ne__(self, other): ...

class OperationalError(psycopg2.DatabaseError): ...
class ProgrammingError(psycopg2.DatabaseError): ...
class QueryCanceledError(psycopg2.OperationalError): ...

class QuotedString:
    adapted: ClassVar[Any] = ...
    buffer: ClassVar[Any] = ...
    encoding: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def getquoted(self, *args, **kwargs): ...
    def prepare(self, *args, **kwargs): ...
    def __conform__(self, *args, **kwargs): ...

class ReplicationConnection(psycopg2.extensions.connection):
    autocommit: ClassVar[Any] = ...
    isolation_level: ClassVar[Any] = ...
    replication_type: ClassVar[Any] = ...
    reset: ClassVar[Any] = ...
    set_isolation_level: ClassVar[Any] = ...
    set_session: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...

class ReplicationCursor(psycopg2.extensions.cursor):
    feedback_timestamp: ClassVar[Any] = ...
    io_timestamp: ClassVar[Any] = ...
    wal_end: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def consume_stream(self, consumer, keepalive_interval=...): ...
    def read_message(self, *args, **kwargs): ...
    def send_feedback(self, write_lsn=..., flush_lsn=..., apply_lsn=..., reply=..., force=...): ...
    def start_replication_expert(self, command, decode=..., status_interval=...): ...

class ReplicationMessage:
    cursor: ClassVar[Any] = ...
    data_size: ClassVar[Any] = ...
    data_start: ClassVar[Any] = ...
    payload: ClassVar[Any] = ...
    send_time: ClassVar[Any] = ...
    wal_end: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...

class TransactionRollbackError(psycopg2.OperationalError): ...
class Warning(Exception): ...

class Xid:
    bqual: ClassVar[Any] = ...
    database: ClassVar[Any] = ...
    format_id: ClassVar[Any] = ...
    gtrid: ClassVar[Any] = ...
    owner: ClassVar[Any] = ...
    prepared: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def from_string(self, *args, **kwargs): ...
    def __getitem__(self, index): ...
    def __len__(self): ...

class connection:
    DataError: ClassVar[Any] = ...
    DatabaseError: ClassVar[Any] = ...
    Error: ClassVar[Any] = ...
    IntegrityError: ClassVar[Any] = ...
    InterfaceError: ClassVar[Any] = ...
    InternalError: ClassVar[Any] = ...
    NotSupportedError: ClassVar[Any] = ...
    OperationalError: ClassVar[Any] = ...
    ProgrammingError: ClassVar[Any] = ...
    Warning: ClassVar[Any] = ...
    async_: ClassVar[Any] = ...
    autocommit: ClassVar[Any] = ...
    binary_types: ClassVar[Any] = ...
    closed: ClassVar[Any] = ...
    cursor_factory: ClassVar[Any] = ...
    deferrable: ClassVar[Any] = ...
    dsn: ClassVar[Any] = ...
    encoding: ClassVar[Any] = ...
    info: ClassVar[Any] = ...
    isolation_level: ClassVar[Any] = ...
    notices: ClassVar[Any] = ...
    notifies: ClassVar[Any] = ...
    pgconn_ptr: ClassVar[Any] = ...
    protocol_version: ClassVar[Any] = ...
    readonly: ClassVar[Any] = ...
    server_version: ClassVar[Any] = ...
    status: ClassVar[Any] = ...
    string_types: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def cancel(self, *args, **kwargs): ...
    def close(self, *args, **kwargs): ...
    def commit(self, *args, **kwargs): ...
    def cursor(self, name=..., cursor_factory=..., withhold=...) -> cursor: ...
    def fileno(self, *args, **kwargs): ...
    def get_backend_pid(self, *args, **kwargs): ...
    def get_dsn_parameters(self, *args, **kwargs): ...
    def get_native_connection(self, *args, **kwargs): ...
    def get_parameter_status(self, parameter): ...
    def get_transaction_status(self): ...
    def isexecuting(self, *args, **kwargs): ...
    def lobject(self, oid=..., mode=..., new_oid=..., new_file=..., lobject_factory=...): ...
    def poll(self, *args, **kwargs): ...
    def reset(self): ...
    def rollback(self): ...
    def set_client_encoding(self, encoding): ...
    def set_isolation_level(self, level): ...
    def set_session(self, *args, **kwargs): ...
    def tpc_begin(self, xid): ...
    def tpc_commit(self, *args, **kwargs): ...
    def tpc_prepare(self): ...
    def tpc_recover(self): ...
    def tpc_rollback(self, *args, **kwargs): ...
    def xid(self, format_id, gtrid, bqual): ...
    def __enter__(self): ...
    def __exit__(self, type, value, traceback): ...

class cursor:
    arraysize: ClassVar[Any] = ...
    binary_types: ClassVar[Any] = ...
    closed: ClassVar[Any] = ...
    connection: ClassVar[Any] = ...
    description: ClassVar[Any] = ...
    itersize: ClassVar[Any] = ...
    lastrowid: ClassVar[Any] = ...
    name: ClassVar[Any] = ...
    pgresult_ptr: ClassVar[Any] = ...
    query: ClassVar[Any] = ...
    row_factory: ClassVar[Any] = ...
    rowcount: ClassVar[Any] = ...
    rownumber: ClassVar[Any] = ...
    scrollable: ClassVar[Any] = ...
    statusmessage: ClassVar[Any] = ...
    string_types: ClassVar[Any] = ...
    typecaster: ClassVar[Any] = ...
    tzinfo_factory: ClassVar[Any] = ...
    withhold: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def callproc(self, procname, parameters=...): ...
    def cast(self, oid, s): ...
    def close(self): ...
    def copy_expert(self, sql, file, size=...): ...
    def copy_from(self, file, table, sep=..., null=..., size=..., columns=...): ...
    def copy_to(self, file, table, sep=..., null=..., columns=...): ...
    def execute(self, query, vars=...): ...
    def executemany(self, query, vars_list): ...
    def fetchall(self) -> list[tuple[Any, ...]]: ...
    def fetchmany(self, size=...) -> list[tuple[Any, ...]]: ...
    def fetchone(self) -> tuple[Any, ...] | None: ...
    def mogrify(self, *args, **kwargs): ...
    def nextset(self): ...
    def scroll(self, value, mode=...): ...
    def setinputsizes(self, sizes): ...
    def setoutputsize(self, size, column=...): ...
    def __enter__(self): ...
    def __exit__(self, type, value, traceback): ...
    def __iter__(self): ...
    def __next__(self): ...

class lobject:
    closed: ClassVar[Any] = ...
    mode: ClassVar[Any] = ...
    oid: ClassVar[Any] = ...
    def __init__(self, *args, **kwargs) -> None: ...
    def close(self): ...
    def export(self, filename): ...
    def read(self, size=...): ...
    def seek(self, offset, whence=...): ...
    def tell(self): ...
    def truncate(self, len=...): ...
    def unlink(self): ...
    def write(self, str): ...

def Date(year, month, day): ...
def DateFromPy(*args, **kwargs): ...
def DateFromTicks(ticks): ...
def IntervalFromPy(*args, **kwargs): ...
def Time(hour, minutes, seconds, tzinfo=...): ...
def TimeFromPy(*args, **kwargs): ...
def TimeFromTicks(ticks): ...
def Timestamp(year, month, day, hour, minutes, seconds, tzinfo=...): ...
def TimestampFromPy(*args, **kwargs): ...
def TimestampFromTicks(ticks): ...
def _connect(*args, **kwargs): ...
def adapt(*args, **kwargs): ...
def encrypt_password(*args, **kwargs): ...
def get_wait_callback(*args, **kwargs): ...
def libpq_version(*args, **kwargs): ...
def new_array_type(oids, name, baseobj): ...
def new_type(oids, name, castobj): ...
def parse_dsn(*args, **kwargs): ...
def quote_ident(*args, **kwargs): ...
def register_type(*args, **kwargs): ...
def set_wait_callback(_none): ...
