from _typeshed import Incomplete
from collections.abc import Generator, Iterable

from networkx.utils.backends import _dispatchable

from ..classes.graph import Graph

__all__ = ["read_pajek", "parse_pajek", "generate_pajek", "write_pajek"]

def generate_pajek(G: Graph[Incomplete]) -> Generator[Incomplete, None, None]: ...
def write_pajek(G: Graph[Incomplete], path, encoding: str = "UTF-8") -> None: ...
@_dispatchable
def read_pajek(path, encoding: str = "UTF-8"): ...
@_dispatchable
def parse_pajek(lines: str | Iterable[str]): ...
def make_qstr(t): ...
