from typing import NamedTuple

class PhysicalDevice(NamedTuple):
    name: str
    device_type: str

def list_physical_devices(device_type: None | str = None) -> list[PhysicalDevice]: ...
def set_memory_growth(device: PhysicalDevice, enable: bool) -> None: ...
def set_visible_devices(devices: list[PhysicalDevice], device_type: None | str = None) -> None: ...
