version = "0.4.*"
upstream_repository = "https://github.com/rasbt/biopandas"
# requires a version of numpy with a `py.typed` file
# TODO: Lots of stubtest errors when using numpy 2
requires = ["numpy>=1.20,<2", "pandas-stubs"]
partial_stub = true

[tool.stubtest]
ignore_missing_stub = true
