from _typeshed import Self, Unused
from collections.abc import Callable
from typing import Any

def connection_memoize(key: str) -> Callable[..., Any]: ...

class TransactionalContext:
    def __enter__(self: Self) -> Self: ...
    def __exit__(self, type_: type[BaseException] | None, value: Unused, traceback: Unused) -> None: ...
