__license__: str
DIGIT: str
ALPHA: str
HEXDIG: str
DQUOTE: str
pct_encoded: str
unreserved: str
gen_delims: str
sub_delims: str
pchar: str
reserved: str
scheme: str
dec_octet: str
IPv4address: str
h16: str
ls32: str
IPv6address: str
IPvFuture: str
IP_literal: str
reg_name: str
userinfo: str
host: str
port: str
authority: str
segment: str
segment_nz: str
segment_nz_nc: str
path_abempty: str
path_absolute: str
path_noscheme: str
path_rootless: str
path_empty: str
path: str
query: str
fragment: str
hier_part: str
relative_part: str
relative_ref: str
URI: str
URI_reference: str
absolute_URI: str
http_URI: str
https_URI: str
ws_URI: str
wss_URI: str
some_delims: str
qchar: str
dtext_no_obs: str
rfc5322_atext: str
rfc5322_dot_atom_text: str
qcontent: str
rfc5322_FWS: str
rfc5322_CFWS: str
rfc5322_quoted_string: str
domain: str
local_part: str
addr_spec: str
hfvalue: str
hfname: str
hfield: str
to: str
hfields: str
mailto_URI: str
rfc2045_token: str
rfc2045_ietf_token: str
rfc2045_iana_tokens: str
rfc2045_x_token: str
rfc2045_extension_token: str
rfc2045_discrete_type: str
rfc2045_composite_type: str
rfc2045_type: str
rfc2045_subtype: str
rfc2045_quoted_string: str
rfc2045_attribute: str
rfc2045_value: str
rfc2045_parameter: str
mediatype: str
rfc2396_uric: str
data: str
data_URI: str
gopher_path: str
gopher_URI: str
file_f_scheme: str
file_f_auth: str
file_unc_path: str
file_drive_marker: str
file_drive_letter: str
file_windows_path: str
file_local_path: str
file_auth_path: str
file_f_hier_part: str
file_URI: str
