from ..constants import FileManagerType

WindowsFileManagerBehavior: dict[str, FileManagerType]

def windows_file_manager_type(file_manager: str) -> FileManagerType: ...
def parse_command_line_arguments(path_or_uri: list[str]) -> list[str]: ...
def launch_file_explorer(paths: list[str], verbose: bool | None = ...) -> None: ...
