from collections.abc import Container, Mapping
from typing import Any

from .backends.base import Key

def sign(
    payload: str | Mapping[str, Any], key: str | dict[str, Any] | Key, headers: Mapping[str, Any] | None = ..., algorithm: str = ...
) -> str: ...
def verify(token: str, key: str | Mapping[str, Any] | Key, algorithms: str | Container[str], verify: bool = ...) -> str: ...
def get_unverified_header(token: str) -> dict[str, Any]: ...
def get_unverified_headers(token: str) -> dict[str, Any]: ...
def get_unverified_claims(token: str) -> str: ...
