class E_FLAGS:
    EF_ARM_EABIMASK: int
    EF_ARM_EABI_VER1: int
    EF_ARM_EABI_VER2: int
    EF_ARM_EABI_VER3: int
    EF_ARM_EABI_VER4: int
    EF_ARM_EABI_VER5: int
    EF_ARM_GCCMASK: int
    EF_ARM_RELEXEC: int
    EF_ARM_HASENTRY: int
    EF_ARM_SYMSARESORTED: int
    EF_ARM_DYNSYMSUSESEGIDX: int
    EF_ARM_MAPSYMSFIRST: int
    EF_ARM_LE8: int
    EF_ARM_BE8: int
    EF_ARM_ABI_FLOAT_SOFT: int
    EF_ARM_ABI_FLOAT_HARD: int
    EF_PPC64_ABI_V0: int
    EF_PPC64_ABI_V1: int
    EF_PPC64_ABI_V2: int
    EF_MIPS_NOREORDER: int
    EF_MIPS_PIC: int
    EF_MIPS_CPIC: int
    EF_MIPS_XGOT: int
    EF_MIPS_64BIT_WHIRL: int
    EF_MIPS_ABI2: int
    EF_MIPS_ABI_ON32: int
    EF_MIPS_32BITMODE: int
    EF_MIPS_NAN2008: int
    EF_MIPS_ARCH: int
    EF_MIPS_ARCH_1: int
    EF_MIPS_ARCH_2: int
    EF_MIPS_ARCH_3: int
    EF_MIPS_ARCH_4: int
    EF_MIPS_ARCH_5: int
    EF_MIPS_ARCH_32: int
    EF_MIPS_ARCH_64: int
    EF_MIPS_ARCH_32R2: int
    EF_MIPS_ARCH_64R2: int
    EF_RISCV_RVC: int
    EF_RISCV_FLOAT_ABI: int
    EF_RISCV_FLOAT_ABI_SOFT: int
    EF_RISCV_FLOAT_ABI_SINGLE: int
    EF_RISCV_FLOAT_ABI_DOUBLE: int
    EF_RISCV_FLOAT_ABI_QUAD: int
    EF_RISCV_RVE: int
    EF_RISCV_TSO: int
    EF_LOONGARCH_OBJABI_MASK: int
    EF_LOONGARCH_OBJABI_V0: int
    EF_LOONGARCH_OBJABI_V1: int
    EF_LOONGARCH_ABI_MODIFIER_MASK: int
    EF_LOONGARCH_ABI_SOFT_FLOAT: int
    EF_LOONGARCH_ABI_SINGLE_FLOAT: int
    EF_LOONGARCH_ABI_DOUBLE_FLOAT: int
    EF_LARCH_OBJABI_MASK = EF_LOONGARCH_OBJABI_MASK
    EF_LARCH_OBJABI_V0 = EF_LOONGARCH_OBJABI_V0
    EF_LARCH_OBJABI_V1 = EF_LOONGARCH_OBJABI_V1
    EF_LARCH_ABI_MODIFIER_MASK = EF_LOONGARCH_ABI_MODIFIER_MASK
    EF_LARCH_ABI_SOFT_FLOAT = EF_LOONGARCH_ABI_SOFT_FLOAT
    EF_LARCH_ABI_SINGLE_FLOAT = EF_LOONGARCH_ABI_SINGLE_FLOAT
    EF_LARCH_ABI_DOUBLE_FLOAT = EF_LOONGARCH_ABI_DOUBLE_FLOAT

class E_FLAGS_MASKS:
    EFM_MIPS_ABI: int
    EFM_MIPS_ABI_O32: int
    EFM_MIPS_ABI_O64: int
    EFM_MIPS_ABI_EABI32: int
    EFM_MIPS_ABI_EABI64: int

class SHN_INDICES:
    SHN_UNDEF: int
    SHN_LORESERVE: int
    SHN_LOPROC: int
    SHN_HIPROC: int
    SHN_ABS: int
    SHN_COMMON: int
    SHN_HIRESERVE: int
    SHN_XINDEX: int

class SH_FLAGS:
    SHF_WRITE: int
    SHF_ALLOC: int
    SHF_EXECINSTR: int
    SHF_MERGE: int
    SHF_STRINGS: int
    SHF_INFO_LINK: int
    SHF_LINK_ORDER: int
    SHF_OS_NONCONFORMING: int
    SHF_GROUP: int
    SHF_TLS: int
    SHF_COMPRESSED: int
    SHF_MASKOS: int
    SHF_EXCLUDE: int
    SHF_MASKPROC: int

class RH_FLAGS:
    RHF_NONE: int
    RHF_QUICKSTART: int
    RHF_NOTPOT: int
    RHF_NO_LIBRARY_REPLACEMENT: int
    RHF_NO_MOVE: int
    RHF_SGI_ONLY: int
    RHF_GUARANTEE_INIT: int
    RHF_DELTA_C_PLUS_PLUS: int
    RHF_GUARANTEE_START_INIT: int
    RHF_PIXIE: int
    RHF_DEFAULT_DELAY_LOAD: int
    RHF_REQUICKSTART: int
    RHF_REQUICKSTARTED: int
    RHF_CORD: int
    RHF_NO_UNRES_UNDEF: int
    RHF_RLD_ORDER_SAFE: int

class P_FLAGS:
    PF_X: int
    PF_W: int
    PF_R: int
    PF_MASKOS: int
    PF_MASKPROC: int

class SUNW_SYMINFO_FLAGS:
    SYMINFO_FLG_DIRECT: int
    SYMINFO_FLG_FILTER: int
    SYMINFO_FLG_COPY: int
    SYMINFO_FLG_LAZYLOAD: int
    SYMINFO_FLG_DIRECTBIND: int
    SYMINFO_FLG_NOEXTDIRECT: int
    SYMINFO_FLG_AUXILIARY: int
    SYMINFO_FLG_INTERPOSE: int
    SYMINFO_FLG_CAP: int
    SYMINFO_FLG_DEFERRED: int

class VER_FLAGS:
    VER_FLG_BASE: int
    VER_FLG_WEAK: int
    VER_FLG_INFO: int
