from _typeshed import Incomplete

class Collection:
    sagemaker_session: Incomplete
    def __init__(self, sagemaker_session) -> None: ...
    def create(self, collection_name: str, parent_collection_name: str | None = None): ...
    def delete(self, collections: list[str]): ...
    def add_model_groups(self, collection_name: str, model_groups: list[str]): ...
    def remove_model_groups(self, collection_name: str, model_groups: list[str]): ...
    def move_model_group(self, source_collection_name: str, model_group: str, destination_collection_name: str): ...
    def list_collection(self, collection_name: str | None = None): ...
