from opentracing import Scope
from opentracing.scope_managers import ThreadLocalScopeManager

class AsyncioScopeManager(ThreadLocalScopeManager):
    def activate(self, span, finish_on_close): ...
    @property
    def active(self): ...

class _AsyncioScope(Scope):
    def __init__(self, manager, span, finish_on_close) -> None: ...
    def close(self) -> None: ...
