from opentracing import Scope, ScopeManager

class GeventScopeManager(ScopeManager):
    def activate(self, span, finish_on_close): ...
    @property
    def active(self): ...

class _GeventScope(Scope):
    def __init__(self, manager, span, finish_on_close) -> None: ...
    def close(self) -> None: ...
