from _typeshed import Incomplete

callbacks: Incomplete
old_callbacks: Incomplete
clear_tracebacks: bool

def registerCallback(fn) -> None: ...
def unregisterCallback(fn) -> None: ...
def register(fn) -> None: ...
def unregister(fn) -> None: ...
def setTracebackClearing(clear: bool = True) -> None: ...

class ExceptionHandler:
    orig_sys_excepthook: Incomplete
    orig_threading_excepthook: Incomplete
    def __init__(self) -> None: ...
    def remove(self) -> None: ...
    def sys_excepthook(self, *args): ...
    def threading_excepthook(self, args): ...
    def implements(self, interface=None): ...

handler: Incomplete
original_excepthook: Incomplete
original_threading_excepthook: Incomplete
