from .Transform3D import Transform3D

class SRTTransform3D(Transform3D):
    def __init__(self, init=None) -> None: ...
    def getScale(self): ...
    def getRotation(self): ...
    def getTranslation(self): ...
    def reset(self) -> None: ...
    def translate(self, *args) -> None: ...
    def setTranslate(self, *args) -> None: ...
    def scale(self, *args) -> None: ...
    def setScale(self, *args) -> None: ...
    def rotate(self, angle, axis=(0, 0, 1)) -> None: ...
    def setRotate(self, angle, axis=(0, 0, 1)) -> None: ...
    def setFromMatrix(self, m) -> None: ...
    def as2D(self): ...
    def saveState(self): ...
    def restoreState(self, state) -> None: ...
    def update(self) -> None: ...
    def matrix(self, nd: int = 3): ...
    def __reduce__(self): ...
