from typing import Any

from .collector import Collector as Collector

class GeckoCollector(Collector):
    def __init__(self, sample_interval_usec: int, *, skip_idle: bool = False, opcodes: bool = False) -> None: ...
    def collect(self, stack_frames: Any, timestamps_us: list[int] | None = None) -> None: ...
    def export(self, filename: str) -> None: ...
