from typing import Any

class CircularDependencyError(ValueError):
    data: Any
    def __init__(self, data) -> None: ...

def toposort(data) -> None: ...
def toposort_flatten(data, sort: bool = ...): ...
