version = "23.7.*"
upstream_repository = "https://github.com/gevent/gevent"
requires = ["types-greenlet", "types-psutil"]

[tool.stubtest]
# Run stubtest on all platforms, since there is some platform specific stuff
# especially in the stdlib module replacement
platforms = ["linux", "darwin", "win32"]
apt_dependencies = ["libev4", "libev-dev", "libuv1", "libuv1-dev"]
brew_dependencies = ["libev", "libuv"]
