import typing as t
from _typeshed import Incomplete

_Group = Incomplete  # must be replaced by click.Group after implementing of https://github.com/python/typeshed/issues/5768
_Command = Incomplete  # must be replaced by click.Command after implementing of GH-5768
_Context = Incomplete  # must be replaced by click.Context after implementing of GH-5768
_HelpFormatter = Incomplete  # must be replaced by click.HelpFormatter after implementing of GH-5768

__version__: str

class DefaultGroup(_Group):
    ignore_unknown_options: bool
    default_cmd_name: str
    default_if_no_args: bool
    def __init__(self, *args, **kwargs) -> None: ...
    def set_default_command(self, command: str) -> None: ...
    def parse_args(self, ctx: _Context, args: list[str]) -> list[str]: ...
    def get_command(self, ctx: _Context, cmd_name: str) -> _Command | None: ...
    def resolve_command(self, ctx: _Context, args: list[str]) -> tuple[str | None, _Command | None, list[str]]: ...
    def format_commands(self, ctx: _Context, formatter: _HelpFormatter) -> None: ...
    def command(self, *args, **kwargs) -> _Command: ...  # incomplete

class DefaultCommandFormatter:
    group: _Group
    formatter: _HelpFormatter
    mark: str
    def __init__(self, group: _Group, formatter: _HelpFormatter, mark: str = ...) -> None: ...
    def write_dl(self, rows: t.Sequence[tuple[str, str]], col_max: int = ..., col_spacing: int = ...) -> None: ...
    def __getattr__(self, attr: str) -> Incomplete: ...
    # __getattr__ used to ala-derive from click.HelpFormatter:
    # indent_increment: int
    # width: int | None
    # current_indent: int
    # buffer: t.List[str]
    # def write(self, string: str) -> None: ...
    # def indent(self) -> None: ...
    # def dedent(self) -> None: ...
    # def write_usage(self, prog: str, args: str = ..., prefix: str | None = ...) -> None: ...
    # def write_heading(self, heading: str) -> None: ...
    # def write_paragraph(self) -> None: ...
    # def write_text(self, text: str) -> None: ...
    # def section(self, name: str) -> t.Iterator[None]: ...
    # def indentation(self) -> t.Iterator[None]: ...
    # def getvalue(self) -> str: ...
