from .segment import Segment

MUTATION_UNSUPPORTED_MESSAGE: str

class FacadeSegment(Segment):
    initializing: bool
    def __init__(self, name: str, entityid: str, traceid: str, sampled: bool) -> None: ...
    def close(self, end_time: float | None = None) -> None: ...
    def put_http_meta(self, key: str, value) -> None: ...
    def put_annotation(self, key: str, value) -> None: ...
    def put_metadata(self, key: str, value, namespace: str = "default") -> None: ...
    def set_aws(self, aws_meta) -> None: ...
    def set_user(self, user) -> None: ...
    def add_throttle_flag(self) -> None: ...
    def add_fault_flag(self) -> None: ...
    def add_error_flag(self) -> None: ...
    def add_exception(self, exception, stack, remote: bool = False) -> None: ...
    def apply_status_code(self, status_code: int) -> None: ...
    def serialize(self) -> None: ...
    def ready_to_send(self) -> bool: ...
    def increment(self) -> None: ...
    def decrement_ref_counter(self) -> None: ...
    def _is_initializing(self, entityid: str, traceid: str, sampled: bool) -> bool: ...
