from _typeshed import Incomplete

from ..Qt import QtWidgets
from ..widgets.VerticalLabel import VerticalLabel

class Dock(QtWidgets.QWidget):
    sigStretchChanged: Incomplete
    sigClosed: Incomplete
    dockdrop: Incomplete
    area: Incomplete
    label: Incomplete
    labelHidden: bool
    moveLabel: bool
    autoOrient: Incomplete
    orientation: str
    topLayout: Incomplete
    widgetArea: Incomplete
    layout: Incomplete
    widgets: Incomplete
    currentRow: int
    hStyle: str
    vStyle: str
    nStyle: str
    dragStyle: str
    def __init__(
        self,
        name,
        area=None,
        size=(10, 10),
        widget=None,
        hideTitle: bool = False,
        autoOrientation: bool = True,
        label=None,
        **kargs,
    ) -> None: ...
    def implements(self, name=None): ...
    def setStretch(self, x=None, y=None) -> None: ...
    def stretch(self): ...
    def hideTitleBar(self) -> None: ...
    def showTitleBar(self) -> None: ...
    def title(self): ...
    def setTitle(self, text) -> None: ...
    def setOrientation(self, o: str = "auto", force: bool = False) -> None: ...
    def updateStyle(self) -> None: ...
    def resizeEvent(self, ev) -> None: ...
    def name(self): ...
    def addWidget(self, widget, row=None, col: int = 0, rowspan: int = 1, colspan: int = 1) -> None: ...
    drag: Incomplete
    def startDrag(self) -> None: ...
    def float(self) -> None: ...
    def container(self): ...
    def containerChanged(self, c) -> None: ...
    def raiseDock(self) -> None: ...
    def close(self) -> None: ...
    def dragEnterEvent(self, *args) -> None: ...
    def dragMoveEvent(self, *args) -> None: ...
    def dragLeaveEvent(self, *args) -> None: ...
    def dropEvent(self, *args) -> None: ...

class DockLabel(VerticalLabel):
    sigClicked: Incomplete
    sigCloseClicked: Incomplete
    dim: bool
    fixedWidth: bool
    fontSize: Incomplete
    dock: Incomplete
    mouseMoved: bool
    closeButton: Incomplete
    def __init__(self, text, closable: bool = False, fontSize: str = "12px") -> None: ...
    vStyle: Incomplete
    hStyle: Incomplete
    def updateStyle(self) -> None: ...
    def setDim(self, d) -> None: ...
    def setOrientation(self, o) -> None: ...
    def isClosable(self): ...
    pressPos: Incomplete
    def mousePressEvent(self, ev) -> None: ...
    def mouseMoveEvent(self, ev) -> None: ...
    def mouseReleaseEvent(self, ev) -> None: ...
    def mouseDoubleClickEvent(self, ev) -> None: ...
    def resizeEvent(self, ev) -> None: ...
