from _typeshed import Incomplete
from typing import TextIO

from antlr4.atn.ATNDeserializationOptions import ATNDeserializationOptions as ATNDeserializationOptions
from antlr4.atn.ATNDeserializer import ATNDeserializer as ATNDeserializer
from antlr4.BufferedTokenStream import TokenStream as TokenStream
from antlr4.CommonTokenFactory import TokenFactory as TokenFactory
from antlr4.error.Errors import (
    RecognitionException as RecognitionException,
    UnsupportedOperationException as UnsupportedOperationException,
)
from antlr4.error.ErrorStrategy import DefaultErrorStrategy as DefaultErrorStrategy
from antlr4.InputStream import InputStream as InputStream
from antlr4.Lexer import Lexer as Lexer
from antlr4.ParserRuleContext import ParserRuleContext as ParserRuleContext
from antlr4.Recognizer import Recognizer as Recognizer
from antlr4.RuleContext import RuleContext as RuleContext
from antlr4.Token import Token as Token
from antlr4.tree.ParseTreePatternMatcher import ParseTreePatternMatcher as ParseTreePatternMatcher
from antlr4.tree.Tree import ErrorNode as ErrorNode, ParseTreeListener as ParseTreeListener, TerminalNode as TerminalNode

class TraceListener(ParseTreeListener):
    def __init__(self, parser: Incomplete) -> None: ...
    def enterEveryRule(self, ctx: Incomplete) -> None: ...
    def visitTerminal(self, node: Incomplete) -> None: ...
    def visitErrorNode(self, node: Incomplete) -> None: ...
    def exitEveryRule(self, ctx: Incomplete) -> None: ...

class Parser(Recognizer):
    bypassAltsAtnCache: Incomplete
    buildParseTrees: bool
    def __init__(self, input: TokenStream, output: TextIO = ...) -> None: ...
    def reset(self) -> None: ...
    def match(self, ttype: int) -> Incomplete: ...
    def matchWildcard(self) -> Incomplete: ...
    def getParseListeners(self) -> Incomplete: ...
    def addParseListener(self, listener: ParseTreeListener) -> Incomplete: ...
    def removeParseListener(self, listener: ParseTreeListener) -> Incomplete: ...
    def removeParseListeners(self) -> None: ...
    def triggerEnterRuleEvent(self) -> None: ...
    def triggerExitRuleEvent(self) -> None: ...
    def getNumberOfSyntaxErrors(self) -> Incomplete: ...
    def getTokenFactory(self) -> Incomplete: ...
    def setTokenFactory(self, factory: TokenFactory) -> Incomplete: ...
    def getATNWithBypassAlts(self) -> Incomplete: ...
    def compileParseTreePattern(self, pattern: str, patternRuleIndex: int, lexer: Lexer | None = None) -> Incomplete: ...
    def getInputStream(self) -> Incomplete: ...
    def setInputStream(self, input: InputStream) -> Incomplete: ...
    def getTokenStream(self) -> Incomplete: ...
    def setTokenStream(self, input: TokenStream) -> Incomplete: ...
    def getCurrentToken(self) -> Incomplete: ...
    def notifyErrorListeners(self, msg: str, offendingToken: Token | None = None, e: RecognitionException | None = None) -> Incomplete: ...
    def consume(self) -> Incomplete: ...
    def addContextToParseTree(self) -> None: ...
    state: Incomplete
    def enterRule(self, localctx: ParserRuleContext, state: int, ruleIndex: int) -> Incomplete: ...
    def exitRule(self) -> None: ...
    def enterOuterAlt(self, localctx: ParserRuleContext, altNum: int) -> Incomplete: ...
    def getPrecedence(self) -> Incomplete: ...
    def enterRecursionRule(self, localctx: ParserRuleContext, state: int, ruleIndex: int, precedence: int) -> Incomplete: ...
    def pushNewRecursionContext(self, localctx: ParserRuleContext, state: int, ruleIndex: int) -> Incomplete: ...
    def unrollRecursionContexts(self, parentCtx: ParserRuleContext) -> Incomplete: ...
    def getInvokingContext(self, ruleIndex: int) -> Incomplete: ...
    def precpred(self, localctx: RuleContext, precedence: int) -> Incomplete: ...
    def inContext(self, context: str) -> Incomplete: ...
    def isExpectedToken(self, symbol: int) -> Incomplete: ...
    def getExpectedTokens(self) -> Incomplete: ...
    def getExpectedTokensWithinCurrentRule(self) -> Incomplete: ...
    def getRuleIndex(self, ruleName: str) -> Incomplete: ...
    def getRuleInvocationStack(self, p: RuleContext | None = None) -> Incomplete: ...
    def getDFAStrings(self) -> Incomplete: ...
    def dumpDFA(self) -> None: ...
    def getSourceName(self) -> Incomplete: ...
    def setTrace(self, trace: bool) -> Incomplete: ...
