from _typeshed import Incomplete

from antlr4.atn.ATN import ATN as ATN
from antlr4.error.Errors import IllegalStateException as IllegalStateException
from antlr4.RuleContext import RuleContext as RuleContext

class PredictionContext:
    EMPTY: Incomplete
    EMPTY_RETURN_STATE: int
    globalNodeCount: int
    id = globalNodeCount
    cachedHashCode: Incomplete
    def __init__(self, cachedHashCode: int) -> None: ...
    def __len__(self) -> int: ...
    def isEmpty(self) -> Incomplete: ...
    def hasEmptyPath(self) -> Incomplete: ...
    def getReturnState(self, index: int) -> Incomplete: ...
    def __hash__(self) -> Incomplete: ...

def calculateHashCode(parent: PredictionContext, returnState: int) -> Incomplete: ...
def calculateListsHashCode(parents: list[PredictionContext], returnStates: list[int]) -> Incomplete: ...

class PredictionContextCache:
    cache: Incomplete
    def __init__(self) -> None: ...
    def add(self, ctx: PredictionContext) -> Incomplete: ...
    def get(self, ctx: PredictionContext) -> Incomplete: ...
    def __len__(self) -> int: ...

class SingletonPredictionContext(PredictionContext):
    @staticmethod
    def create(parent: PredictionContext, returnState: int) -> Incomplete: ...
    parentCtx: Incomplete
    returnState: Incomplete
    def __init__(self, parent: PredictionContext, returnState: int) -> None: ...
    def __len__(self) -> int: ...
    def getParent(self, index: int) -> Incomplete: ...
    def getReturnState(self, index: int) -> Incomplete: ...
    def __eq__(self, other: Incomplete) -> Incomplete: ...
    def __hash__(self) -> Incomplete: ...

class EmptyPredictionContext(SingletonPredictionContext):
    def __init__(self) -> None: ...
    def isEmpty(self) -> Incomplete: ...
    def __eq__(self, other: Incomplete) -> Incomplete: ...
    def __hash__(self) -> Incomplete: ...

class ArrayPredictionContext(PredictionContext):
    parents: Incomplete
    returnStates: Incomplete
    def __init__(self, parents: list[PredictionContext], returnStates: list[int]) -> None: ...
    def isEmpty(self) -> Incomplete: ...
    def __len__(self) -> int: ...
    def getParent(self, index: int) -> Incomplete: ...
    def getReturnState(self, index: int) -> Incomplete: ...
    def __eq__(self, other: Incomplete) -> Incomplete: ...
    def __hash__(self) -> Incomplete: ...

def PredictionContextFromRuleContext(atn: ATN, outerContext: RuleContext = ...) -> Incomplete: ...
def merge(
    a: PredictionContext,
    b: PredictionContext,
    rootIsWildcard: bool,
    mergeCache: dict[tuple[Incomplete], SingletonPredictionContext],
) -> Incomplete: ...
def mergeSingletons(
    a: SingletonPredictionContext,
    b: SingletonPredictionContext,
    rootIsWildcard: bool,
    mergeCache: dict[tuple[Incomplete], SingletonPredictionContext],
) -> Incomplete: ...
def mergeRoot(a: SingletonPredictionContext, b: SingletonPredictionContext, rootIsWildcard: bool) -> Incomplete: ...
def mergeArrays(
    a: ArrayPredictionContext,
    b: ArrayPredictionContext,
    rootIsWildcard: bool,
    mergeCache: dict[tuple[Incomplete], SingletonPredictionContext],
) -> Incomplete: ...
def combineCommonParents(parents: list[PredictionContext]) -> Incomplete: ...
def getCachedPredictionContext(
    context: PredictionContext, contextCache: PredictionContextCache, visited: dict[PredictionContext, PredictionContext]
) -> Incomplete: ...
def getAllContextNodes(
    context: PredictionContext, nodes: list[Incomplete] = ..., visited: dict[PredictionContext, PredictionContext] = ...
) -> Incomplete: ...
