from _typeshed import Incomplete

from rich.progress import ProgressColumn # type: ignore

from .std import tqdm as std_tqdm

class FractionColumn(ProgressColumn):
    unit_scale: Incomplete
    unit_divisor: Incomplete
    def __init__(self, unit_scale: bool = ..., unit_divisor: int = ...) -> None: ...
    def render(self, task): ...

class RateColumn(ProgressColumn):
    unit: Incomplete
    unit_scale: Incomplete
    unit_divisor: Incomplete
    def __init__(self, unit: str = ..., unit_scale: bool = ..., unit_divisor: int = ...) -> None: ...
    def render(self, task): ...

class tqdm_rich(std_tqdm):
    def __init__(self, *args, **kwargs) -> None: ...
    def close(self) -> None: ...
    def clear(self, *_, **__) -> None: ...
    def display(self, *_, **__) -> None: ...
    def reset(self, total: Incomplete | None = ...) -> None: ...

def trrange(*args, **kwargs): ...

tqdm = tqdm_rich
trange = trrange
