from bs4.builder import HTMLParserTreeBuilder as HTMLParserTreeBuilder
from bs4.builder._htmlparser import BeautifulSoupHTMLParser as BeautifulSoupHTMLParser
from bs4.testing import HTMLTreeBuilderSmokeTest as HTMLTreeBuilderSmokeTest, SoupTest as SoupTest
from pdb import set_trace as set_trace
from typing import Any

class HTMLParserTreeBuilderSmokeTest(SoupTest, HTMLTreeBuilderSmokeTest):
    default_builder: Any
    def test_namespaced_system_doctype(self) -> None: ...
    def test_namespaced_public_doctype(self) -> None: ...
    def test_builder_is_pickled(self) -> None: ...
    def test_redundant_empty_element_closing_tags(self) -> None: ...
    def test_empty_element(self) -> None: ...
    def test_tracking_line_numbers(self) -> None: ...
    def test_on_duplicate_attribute(self) -> None: ...

class TestHTMLParserSubclass(SoupTest):
    def test_error(self) -> None: ...
