from collections.abc import Iterable
from typing import Any

import networkx as nx
from networkx.classes.graph import Graph, _Node

class NetworkXTreewidthBoundExceeded(nx.NetworkXException): ...

def is_chordal(G: Graph[Any]) -> bool: ...
def find_induced_nodes(G: Graph[_Node], s: _Node, t: _Node, treewidth_bound: int = ...) -> set[_Node]: ...
def chordal_graph_cliques(G: Graph[_Node]) -> Iterable[frozenset[_Node]]: ...
def chordal_graph_treewidth(G: Graph[Any]) -> int: ...
