from _typeshed import Incomplete

__all__ = ["ClientAuthentication"]

class ClientAuthentication:
    query_client: Incomplete
    def __init__(self, query_client) -> None: ...
    def register(self, method, func) -> None: ...
    def authenticate(self, request, methods, endpoint): ...
    def __call__(self, request, methods, endpoint: str = "token"): ...
