from _typeshed import Incomplete

from hvac.api.system_backend.system_backend_mixin import SystemBackendMixin

class Key(SystemBackendMixin):
    def read_root_generation_progress(self): ...
    def start_root_token_generation(self, otp: Incomplete | None = ..., pgp_key: Incomplete | None = ...): ...
    def generate_root(self, key, nonce): ...
    def cancel_root_generation(self): ...
    def get_encryption_key_status(self): ...
    def rotate_encryption_key(self): ...
    def read_rekey_progress(self, recovery_key: bool = ...): ...
    def start_rekey(
        self,
        secret_shares: int = ...,
        secret_threshold: int = ...,
        pgp_keys: Incomplete | None = ...,
        backup: bool = ...,
        require_verification: bool = ...,
        recovery_key: bool = ...,
    ): ...
    def cancel_rekey(self, recovery_key: bool = ...): ...
    def rekey(self, key, nonce: Incomplete | None = ..., recovery_key: bool = ...): ...
    def rekey_multi(self, keys, nonce: Incomplete | None = ..., recovery_key: bool = ...): ...
    def read_backup_keys(self, recovery_key: bool = ...): ...
    def cancel_rekey_verify(self): ...
    def rekey_verify(self, key, nonce): ...
    def rekey_verify_multi(self, keys, nonce): ...
    def read_rekey_verify_progress(self): ...
