from _typeshed import Incomplete
from logging import FileHandler as FileHandler

from huey.constants import WORKER_THREAD as WORKER_THREAD, WORKER_TYPES as WORKER_TYPES

config_defaults: Incomplete
config_keys: Incomplete

def option(name, **options): ...

class OptionParserHandler:
    def get_worker_options(self): ...
    def get_scheduler_options(self): ...
    def get_logging_options(self): ...
    def get_option_parser(self): ...

class ConsumerConfig:
    def __new__(cls, **kwargs): ...
    def validate(self) -> None: ...
    @property
    def loglevel(self): ...
    def setup_logger(self, logger: Incomplete | None = ...) -> None: ...
    @property
    def values(self): ...
