from _typeshed import Incomplete

class AsyncSimpleClient:
    client_args: Incomplete
    client_kwargs: Incomplete
    client: Incomplete
    namespace: str
    connected_event: Incomplete
    connected: bool
    input_event: Incomplete
    input_buffer: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    async def connect(
        self,
        url,
        headers={},
        auth: Incomplete | None = None,
        transports: Incomplete | None = None,
        namespace: str = "/",
        socketio_path: str = "socket.io",
        wait_timeout: int = 5,
    ) -> None: ...
    @property
    def sid(self): ...
    @property
    def transport(self): ...
    async def emit(self, event, data: Incomplete | None = None): ...
    async def call(self, event, data: Incomplete | None = None, timeout: int = 60): ...
    async def receive(self, timeout: Incomplete | None = None): ...
    async def disconnect(self) -> None: ...
    async def __aenter__(self): ...
    async def __aexit__(self, exc_type, exc_val, exc_tb) -> None: ...
