from _typeshed import Incomplete
from collections.abc import Callable
from email.message import Message

class ContentManager:
    def get_content(self, msg: Message, *args: Incomplete, **kw: Incomplete) -> Incomplete: ...
    def set_content(self, msg: Message, obj: Incomplete, *args: Incomplete, **kw: Incomplete) -> Incomplete: ...
    def add_get_handler(self, key: str, handler: Callable[..., Incomplete]) -> None: ...
    def add_set_handler(self, typekey: type, handler: Callable[..., Incomplete]) -> None: ...

raw_data_manager: ContentManager
