import ctypes
from _typeshed import Incomplete

class I2CError(IOError): ...
class _CI2CMessage(ctypes.Structure): ...
class _CI2CIocTransfer(ctypes.Structure): ...

class I2C:
    def __init__(self, devpath) -> None: ...
    def __del__(self) -> None: ...
    def __enter__(self): ...
    def __exit__(self, t, value, traceback) -> None: ...
    def transfer(self, address, messages) -> None: ...
    def close(self) -> None: ...
    @property
    def fd(self): ...
    @property
    def devpath(self): ...

    class Message:
        data: Incomplete
        read: Incomplete
        flags: Incomplete
        def __init__(self, data, read: bool = ..., flags: int = ...) -> None: ...
