from _typeshed import Incomplete

def comma_list(list_str, item_func: Incomplete | None = None): ...
def comma_set(list_str, item_func: Incomplete | None = None): ...
def comma_list_or_empty(list_str): ...
def list_of_ints(int_csv): ...
def list_of_ints_and_strs(csv): ...
def set_of_ints(int_csv): ...

class DateParsingError(Exception): ...

def parse_date_as_epoch_timestamp(date_str): ...
def parse_date(date_str, to_epoch_ts: bool = False): ...
