from _typeshed import Incomplete
from configparser import ConfigParser as ConfigParser
from functools import wraps as wraps
from io import StringIO as StringIO
from logging import NullHandler as NullHandler
from urllib.parse import urljoin as urljoin, urlparse as urlparse

log: Incomplete
imap = map
get_input = input
text = str

def iteritems(d): ...
def iternext(iter): ...
def is_p3k(): ...
def is_higher_py32(): ...
def is_higher_py35(): ...
def is_pypy(): ...
def conditional_lru_cache(func): ...
