from _typeshed import Incomplete

TAG_INVALID_CHARS_RE: Incomplete
TAG_INVALID_CHARS_SUBS: str

def pretty_json(obj): ...
def construct_url(host, api_version, path): ...
def construct_path(api_version, path): ...
def force_to_epoch_seconds(epoch_sec_or_dt): ...
def normalize_tags(tag_list): ...
