"""Stub file for the '_functools' module."""
# This is an autogenerated file. It serves as a starting point
# for a more percise manual annotation of this module.
# Feel free to edit the source below, but remove this header when you do.

from typing import List, Tuple, Dict, Undefined, GenericType

def reduce(*args, **kwargs) -> object:
    raise TypeError()


class partial(object):
    def __reduce__() -> tuple: ...
    def __setstate__(a, b, c, d) -> None: ...
