"""Stub file for the '_random' module."""
# This is an autogenerated file. It serves as a starting point
# for a more percise manual annotation of this module.
# Feel free to edit the source below, but remove this header when you do.

from typing import List, Tuple, Dict, Undefined, GenericType

class Random(object):
    def getrandbits(a: int) -> object:
        raise MemoryError()
        raise ValueError()
    def getstate() -> tuple: ...
    def jumpahead(*args, **kwargs) -> None:
        raise TypeError()
    def random() -> float: ...
    def seed(*args, **kwargs) -> None:
        raise MemoryError()
    def setstate(*args, **kwargs) -> None:
        raise TypeError()
        raise ValueError()
