"""Stub file for the '_random' module."""
# This is an autogenerated file. It serves as a starting point
# for a more percise manual annotation of this module.
# Feel free to edit the source below, but remove this header when you do.

class Random(object):
    def getrandbits(a: int) -> object:
        raise ValueError()
        raise MemoryError()
    def getstate() -> tuple: pass
    def jumpahead(*args, **kwargs) -> NoneType:
        raise TypeError()
    def random() -> float: pass
    def seed(*args, **kwargs) -> NoneType:
        raise MemoryError()
    def setstate(*args, **kwargs) -> NoneType:
        raise TypeError()
        raise ValueError()
