# This is an autogenerated file. It serves as a starting point
# for a more percise manual annotation of this module.
# Feel free to edit the source below, but remove this header when you do.

class array(object):
    def append(*args, **kwargs) -> NoneType: pass
    def buffer_info() -> tuple: pass
    def byteswap() -> NoneType:
        raise RuntimeError()
    def __copy__() -> object: pass
    def count(*args, **kwargs) -> int: pass
    def __deepcopy__(*args, **kwargs) -> object: pass
    def extend(*args, **kwargs) -> NoneType: pass
    def fromfile(a, b: int) -> NoneType:
        raise IOError()
        raise MemoryError()
        raise TypeError()
        raise EOFError()
    def fromlist(*args, **kwargs) -> NoneType:
        raise MemoryError()
        raise TypeError()
    def fromstring(a: Nothing) -> NoneType:
        raise MemoryError()
        raise ValueError()
    def fromunicode(a: str) -> NoneType:
        raise MemoryError()
        raise ValueError()
    def index(*args, **kwargs) -> int:
        raise ValueError()
    def insert(a: int, b) -> NoneType: pass
    def pop(*args, **kwargs) -> object:
        raise IndexError()
    def read(*args, **kwargs) -> NoneType:
        raise DeprecationWarning()
    def __reduce__() -> tuple:
        raise AttributeError()
    def remove(*args, **kwargs) -> NoneType:
        raise ValueError()
    def reverse() -> NoneType: pass
    def tofile(*args, **kwargs) -> NoneType:
        raise IOError()
        raise TypeError()
    def tolist() -> list: pass
    def tostring() -> str:
        raise MemoryError()
    def tounicode() -> unicode:
        raise ValueError()
    def write(*args, **kwargs) -> NoneType:
        raise DeprecationWarning()
    def __sizeof__() -> long: pass

class arrayiterator(object):
    pass
