"""Stub file for the 'signal' module."""
# This is an autogenerated file. It serves as a starting point
# for a more percise manual annotation of this module.
# Feel free to edit the source below, but remove this header when you do.

from typing import List, Tuple, Dict, Undefined, GenericType

ITIMER_PROF = Undefined(long)
ITIMER_REAL = Undefined(long)
ITIMER_VIRTUAL = Undefined(long)
ItimerError = Undefined(object)
NSIG = Undefined(int)
SIGABRT = Undefined(int)
SIGALRM = Undefined(int)
SIGBUS = Undefined(int)
SIGCHLD = Undefined(int)
SIGCLD = Undefined(int)
SIGCONT = Undefined(int)
SIGFPE = Undefined(int)
SIGHUP = Undefined(int)
SIGILL = Undefined(int)
SIGINT = Undefined(int)
SIGIO = Undefined(int)
SIGIOT = Undefined(int)
SIGKILL = Undefined(int)
SIGPIPE = Undefined(int)
SIGPOLL = Undefined(int)
SIGPROF = Undefined(int)
SIGPWR = Undefined(int)
SIGQUIT = Undefined(int)
SIGRTMAX = Undefined(int)
SIGRTMIN = Undefined(int)
SIGSEGV = Undefined(int)
SIGSTOP = Undefined(int)
SIGSYS = Undefined(int)
SIGTERM = Undefined(int)
SIGTRAP = Undefined(int)
SIGTSTP = Undefined(int)
SIGTTIN = Undefined(int)
SIGTTOU = Undefined(int)
SIGURG = Undefined(int)
SIGUSR1 = Undefined(int)
SIGUSR2 = Undefined(int)
SIGVTALRM = Undefined(int)
SIGWINCH = Undefined(int)
SIGXCPU = Undefined(int)
SIGXFSZ = Undefined(int)
SIG_DFL = Undefined(long)
SIG_IGN = Undefined(long)

def alarm(a: int) -> int: pass

def default_int_handler(*args, **kwargs) -> object:
    raise KeyboardInterrupt()

def getitimer(a: int) -> tuple: pass

def getsignal(a: int) -> None:
    raise ValueError()

def pause() -> None: pass

def set_wakeup_fd(a: int) -> long:
    raise ValueError()

def setitimer(a: int, b: float, *args, **kwargs) -> tuple: pass

def siginterrupt(a: int, b: int) -> None:
    raise RuntimeError()
    raise ValueError()

def signal(a: int, b) -> None:
    raise RuntimeError()
    raise TypeError()
    raise ValueError()
