"""Stub file for the 'thread' module."""
# This is an autogenerated file. It serves as a starting point
# for a more percise manual annotation of this module.
# Feel free to edit the source below, but remove this header when you do.

LockType = Undefined(lock)
error = Undefined(object)

def _count() -> int: pass

def allocate() -> lock: pass

def allocate_lock() -> lock: pass

def exit() -> object:
    raise SystemExit()

def exit_thread() -> object:
    raise SystemExit()

def get_ident() -> int: pass

def interrupt_main() -> NoneType: pass

def stack_size(*args, **kwargs) -> int:
    raise ValueError()

def start_new(*args, **kwargs) -> int:
    raise TypeError()
    raise MemoryError()

def start_new_thread(*args, **kwargs) -> int:
    raise TypeError()
    raise MemoryError()


class _local(object):
    pass

class _localdummy(object):
    pass

class lock(object):
    def __enter__(*args, **kwargs) -> bool: pass
    def __exit__(*args, **kwargs) -> NoneType: pass
    def acquire(*args, **kwargs) -> bool: pass
    def acquire_lock(*args, **kwargs) -> bool: pass
    def locked() -> bool: pass
    def locked_lock() -> bool: pass
    def release() -> NoneType: pass
    def release_lock() -> NoneType: pass
