# This is an autogenerated file. It serves as a starting point
# for a more percise manual annotation of this module.
# Feel free to edit the source below, but remove this header when you do.

def ctime(*args, **kwargs) -> str:
    raise ValueError()

def strptime(*args, **kwargs) -> object: pass

def strftime(a: str, *args, **kwargs) -> str:
    raise MemoryError()
    raise ValueError()

def tzset() -> NoneType: pass

def time() -> float:
    raise IOError()

def mktime(*args, **kwargs) -> float:
    raise OverflowError()

def sleep(a: float) -> NoneType: pass

def gmtime(*args, **kwargs) -> tuple: pass

def asctime(*args, **kwargs) -> str:
    raise ValueError()

def clock() -> float: pass

def localtime(*args, **kwargs) -> tuple: pass
