from collections.abc import Iterable
from types import ModuleType
from typing import Any

from docutils import ApplicationError, Component, TransformSpec, nodes
from docutils.nodes import Node

class TransformError(ApplicationError): ...

class Transform:
    default_priority: int | None
    document: nodes.document
    startnode: Node | None
    language: ModuleType
    def __init__(self, document: nodes.document, startnode: Node | None = None) -> None: ...
    def apply(self, **kwargs: Any) -> None: ...

class Transformer(TransformSpec):
    transforms: list[tuple[str, type[Transform], nodes.pending | None]]
    document: nodes.document
    applied: list[tuple[int, type[Transform], nodes.pending, Any]]
    sorted: bool
    components: dict[ComponentType, Component]
    serialno: int
    def __init__(self, document: nodes.document) -> None: ...
    def add_transform(self, transform_class: type[Transform], priority: int | None = None, **kwargs: Any) -> None: ...
    def add_transforms(self, transform_list: Iterable[type[Transform]]) -> None: ...
    def add_pending(self, pending: nodes.pending, priority: int | None = None) -> None: ...
    def get_priority_string(self, priority: int) -> str: ...
    def populate_from_components(self, components: Iterable[Component]) -> None: ...
    def apply_transforms(self) -> None: ...
