from _typeshed import Incomplete

from docutils import nodes
from docutils.transforms import Transform

__docformat__: str

class PropagateTargets(Transform):
    default_priority: int
    def apply(self) -> None: ...

class AnonymousHyperlinks(Transform):
    default_priority: int
    def apply(self) -> None: ...

class IndirectHyperlinks(Transform):
    default_priority: int
    def apply(self) -> None: ...
    def resolve_indirect_target(self, target) -> None: ...
    def nonexistent_indirect_target(self, target) -> None: ...
    def circular_indirect_reference(self, target) -> None: ...
    def indirect_target_error(self, target, explanation) -> None: ...
    def resolve_indirect_references(self, target) -> None: ...

class ExternalTargets(Transform):
    default_priority: int
    def apply(self) -> None: ...

class InternalTargets(Transform):
    default_priority: int
    def apply(self) -> None: ...
    def resolve_reference_ids(self, target) -> None: ...

class Footnotes(Transform):
    default_priority: int
    autofootnote_labels: Incomplete
    symbols: Incomplete
    def apply(self) -> None: ...
    def number_footnotes(self, startnum): ...
    def number_footnote_references(self, startnum) -> None: ...
    def symbolize_footnotes(self) -> None: ...
    def resolve_footnotes_and_citations(self) -> None: ...
    def resolve_references(self, note, reflist) -> None: ...

class CircularSubstitutionDefinitionError(Exception): ...

class Substitutions(Transform):
    default_priority: int
    def apply(self) -> None: ...

class TargetNotes(Transform):
    default_priority: int
    classes: Incomplete
    def __init__(self, document, startnode) -> None: ...
    def apply(self) -> None: ...
    def make_target_footnote(self, refuri, refs, notes): ...

class DanglingReferences(Transform):
    default_priority: int
    def apply(self) -> None: ...

class DanglingReferencesVisitor(nodes.SparseNodeVisitor):
    document: Incomplete
    unknown_reference_resolvers: Incomplete
    def __init__(self, document, unknown_reference_resolvers) -> None: ...
    def unknown_visit(self, node) -> None: ...
    def visit_reference(self, node) -> None: ...
    visit_footnote_reference = visit_reference
    visit_citation_reference = visit_reference
