"""Stub file for the 'atexit' module."""
# This is an autogenerated file. It serves as a starting point
# for a more precise manual annotation of this module.
# Feel free to edit the source below, but remove this header when you do.

from typing import List, Tuple, Dict, GenericType

def _clear() -> None: ...

def _ncallbacks() -> long: ...

def _run_exitfuncs() -> None: ...

def register(*args, **kwargs) -> object:
    raise MemoryError()
    raise TypeError()

def unregister(*args, **kwargs) -> None: ...
