from collections.abc import Callable
from typing import Any

def pdb_on_signal(signalnum: int | None = ...) -> None: ...
def pdb_on_exception(limit: int = ...) -> None: ...
def wrap_trace(
    obj: object, hook: Callable[Any, Any] = ..., which: str | None = ..., events: str | None = ..., label: str | None = ...
) -> object: ...
