from typing import NoReturn

def pdb_on_signal(signalnum: int | None = ...) -> NoReturn: ...
def pdb_on_exception(limit: int = ...) -> NoReturn: ...
def wrap_trace(obj, hook=..., which: str | None = ..., events: str | None = ..., label: str | None = ...): ...
