from _typeshed import Incomplete, StrOrBytesPath
from collections.abc import Callable, Generator, Iterable
from types import TracebackType
from typing import IO, Any, NoReturn
from typing_extensions import TypeAlias

_PathReturn: TypeAlias = Any

def mkdir_p(path: StrOrBytesPath) -> NoReturn: ...

class FilePerms:
    # class _FilePermProperty:
    #     attribute: Incomplete
    #     offset: Incomplete
    #     def __init__(self, attribute, offset) -> None: ...
    #     def __get__(self, fp_obj, type_: Incomplete | None = ...): ...
    #     def __set__(self, fp_obj, value): ...
    user: str
    group: str
    other: str
    def __init__(self, user: str = ..., group: str = ..., other: str = ...) -> None: ...
    @classmethod
    def from_int(cls, i: int) -> FilePerms: ...
    @classmethod
    def from_path(cls, path: StrOrBytesPath) -> FilePerms: ...
    def __int__(self) -> int: ...

def atomic_save(dest_path: str, **kwargs) -> AtomicSaver: ...

class AtomicSaver:
    dest_path: str
    overwrite: bool
    file_perms: int
    overwrite_part: bool
    part_filename: str
    rm_part_on_exc: bool
    text_mode: bool
    buffering: int
    dest_dir: StrOrBytesPath
    part_path: StrOrBytesPath
    mode: str
    open_flags: int
    part_file: str
    def __init__(self, dest_path: str, **kwargs) -> NoReturn: ...
    def setup(self) -> NoReturn: ...
    def __enter__(self) -> IO[Any] | None: ...
    def __exit__(
        self, exc_type: type[BaseException] | None, exc_val: BaseException | None, exc_tb: TracebackType | None
    ) -> NoReturn: ...

def iter_find_files(
    directory: str, patterns: str | list[Any], ignored: str | list[Any] | None = ..., include_dirs: bool = ...
) -> Generator[str, None, None]: ...
def copy_tree(
    src: StrOrBytesPath,
    dst: StrOrBytesPath,
    symlinks: bool = ...,
    ignore: None | Callable[[str, list[str]], Iterable[str]] | Callable[[StrOrBytesPath, list[str]], Iterable[str]] = ...,
) -> _PathReturn: ...

copytree = copy_tree
file = object

class DummyFile(file):
    name: str
    mode: str
    closed: bool
    errors: list[str]
    isatty: bool
    encoding: str
    newlines: list[str]
    softspace: int
    def __init__(self, path, mode: str = ..., buffering: Incomplete | None = ...) -> None: ...
    def close(self) -> None: ...
    def fileno(self) -> int: ...
    def flush(self) -> None: ...
    def next(self) -> None: ...
    def read(self, size: int = ...): ...
    def readline(self, size: int = ...): ...
    def readlines(self, size: int = ...): ...
    def seek(self) -> None: ...
    def tell(self): ...
    def truncate(self) -> None: ...
    def write(self, string) -> None: ...
    def writelines(self, list_of_strings) -> None: ...
    def __next__(self) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...
