from _typeshed import Incomplete

def get_all(type_obj, include_subtypes: bool = ...): ...

class GCToggler:
    postcollect: Incomplete
    def __init__(self, postcollect: bool = ...) -> None: ...
    def __enter__(self) -> None: ...
    def __exit__(self, exc_type, exc_val, exc_tb) -> None: ...

toggle_gc: Incomplete
toggle_gc_postcollect: Incomplete
