# TODO: DONE!

from collections.abc import Iterator
from typing import IO, AnyStr

def reverse_iter_lines(
    file_obj: IO[AnyStr], blocksize: int = ..., preseek: bool = ..., encoding: AnyStr | None = ...
) -> Iterator[AnyStr]: ...

# def reverse_iter_lines(
#     file_obj: IO[AnyStr], blocksize: int =..., preseek: bool = ..., encoding: AnyStr | None = ...
# ) -> Generator[Incomplete, None, None]: ...

class JSONLIterator:
    ignore_errors: bool
    def __init__(
        self, file_obj: IO[AnyStr], ignore_errors: bool = ..., reverse: bool = ..., rel_seek: float | None = ...
    ) -> None: ...
    @property
    def cur_byte_pos(self) -> int: ...
    # def next(self): ...
    # __next__: Incomplete
