from collections.abc import Callable, Generator, Iterable
from html.parser import HTMLParser
from typing import Any, NoReturn, TypeVar

_KT = TypeVar("_KT")
_VT = TypeVar("_VT")

unichr = chr

def camel2under(camel_string: str) -> str: ...
def under2camel(under_string: str) -> str: ...
def slugify(text: str, delim: str = ..., lower: bool = ..., ascii: bool = ...) -> str: ...
def split_punct_ws(text: str) -> str: ...
def unit_len(sized_iterable: Iterable[Any], unit_noun: str = ...) -> str: ...
def ordinalize(number: int | str, ext_only: bool = ...) -> str: ...
def cardinalize(unit_noun: str, count: int) -> str: ...
def singularize(word: str) -> str: ...
def pluralize(word: str) -> str: ...
def find_hashtags(string: str) -> list[str]: ...
def a10n(string: str) -> str: ...
def strip_ansi(text: str) -> str: ...
def asciify(text: str, ignore: bool = ...): ...
def is_ascii(text: str) -> bool: ...

class DeaccenterDict(dict[_KT, _VT]):
    def __missing__(self, key: _KT) -> _VT: ...
    def __getitem__(self, key: _KT) -> _VT: ...

def bytes2human(nbytes: int, ndigits: int = ...) -> str: ...

class HTMLTextExtractor(HTMLParser):
    strict: bool
    convert_charrefs: bool
    result: list[str]
    def __init__(self) -> NoReturn: ...
    def handle_data(self, d: str) -> NoReturn: ...
    def handle_charref(self, number: str) -> NoReturn: ...
    def handle_entityref(self, name: str) -> NoReturn: ...
    def get_text(self) -> str: ...

def html2text(html: str) -> str: ...
def gunzip_bytes(bytestring: bytes) -> bytes: ...
def gzip_bytes(bytestring: bytes, level: int = ...) -> int: ...
def iter_splitlines(text: str) -> Generator[str, None, None]: ...
def indent(text: str, margin: str, newline: str = ..., key: Callable[..., bool] = ...) -> str: ...
def is_uuid(obj, version: int = ...) -> bool: ...
def escape_shell_args(args: list[str], sep: str = ..., style: str | None = ...) -> str: ...
def args2sh(args: list[str], sep: str = ...) -> str: ...
def args2cmd(args: list[str], sep: str = ...) -> str: ...
def parse_int_list(range_string: str, delim: str = ..., range_delim: str = ...) -> list[int]: ...
def format_int_list(int_list: list[int], delim: str = ..., range_delim: str = ..., delim_space: bool = ...) -> str: ...

class MultiReplace:
    group_map: dict[str, str]
    combined_pattern: str
    def __init__(self, sub_map: dict[str, str], **kwargs) -> NoReturn: ...
    def sub(self, text: str) -> str: ...

def multi_replace(text: str, sub_map: dict[str, str], **kwargs) -> str: ...
def unwrap_text(text: str, ending: str = ...) -> str: ...

# Names in __all__ with no definition:
#   int_list_complement
#   int_list_to_int_tuples
