from _typeshed import Incomplete

def make_sentinel(name: str = ..., var_name: Incomplete | None = ...): ...
def issubclass(subclass, baseclass): ...
def get_all_subclasses(cls): ...

class classproperty:
    fn: Incomplete
    def __init__(self, fn) -> None: ...
    def __get__(self, instance, cls): ...
