from typing import Any

class WhatThePatchException(Exception): ...

class HunkException(WhatThePatchException):
    hunk: Any
    def __init__(self, msg: str, hunk: int | None = ...) -> None: ...

class ApplyException(WhatThePatchException): ...

class SubprocessException(ApplyException):
    code: Any
    def __init__(self, msg: str, code: int) -> None: ...

class HunkApplyException(HunkException, ApplyException, ValueError): ...
class ParseException(HunkException, ValueError): ...
