import abc
from collections.abc import Mapping

REAUTH_ORIGIN: str
SAML_CHALLENGE_MESSAGE: str
WEBAUTHN_TIMEOUT_MS: int

def get_user_password(text: str) -> str: ...

class ReauthChallenge(metaclass=abc.ABCMeta):
    @property
    @abc.abstractmethod
    def name(self) -> str: ...
    @property
    @abc.abstractmethod
    def is_locally_eligible(self) -> bool: ...
    @abc.abstractmethod
    def obtain_challenge_input(self, metadata: Mapping[str, object]) -> dict[str, object] | None: ...

class PasswordChallenge(ReauthChallenge):
    @property
    def name(self) -> str: ...
    @property
    def is_locally_eligible(self) -> bool: ...
    def obtain_challenge_input(self, unused_metadata: Mapping[str, object]) -> dict[str, object] | None: ...

class SecurityKeyChallenge(ReauthChallenge):
    @property
    def name(self) -> str: ...
    @property
    def is_locally_eligible(self) -> bool: ...
    def obtain_challenge_input(self, metadata: Mapping[str, object]) -> dict[str, object] | None: ...

class SamlChallenge(ReauthChallenge):
    @property
    def name(self) -> str: ...
    @property
    def is_locally_eligible(self) -> bool: ...
    def obtain_challenge_input(self, metadata: Mapping[str, object]) -> dict[str, object] | None: ...

AVAILABLE_CHALLENGES: dict[str, ReauthChallenge]
