import datetime
from collections.abc import Coroutine, Mapping, Sequence
from typing import Any

import google
import google.auth
import google.auth.transport
from google.auth import credentials

class Credentials(credentials.ReadOnlyScoped, credentials.CredentialsWithQuotaProject):
    token: str | None
    expiry: datetime.datetime | None

    def __init__(
        self,
        token: str | None,
        refresh_token: str | None = None,
        id_token: str | None = None,
        token_uri: str | None = None,
        client_id: str | None = None,
        client_secret: str | None = None,
        scopes: Sequence[str] | None = None,
        default_scopes: Sequence[str] | None = None,
        quota_project_id: str | None = None,
        expiry: datetime.datetime | None = None,
        rapt_token: str | None = None,
        refresh_handler: Any | None = None,
        enable_reauth_refresh: bool = False,
        granted_scopes: Sequence[str] | None = None,
        trust_boundary: Mapping[str, str] | None = None,
        universe_domain: str | None = None,
        account: str | None = "",
    ) -> None: ...
    @property
    def refresh_token(self) -> str | None: ...
    @property
    def scopes(self) -> Sequence[str] | None: ...
    @property
    def granted_scopes(self) -> Sequence[str] | None: ...
    @property
    def token_uri(self) -> str | None: ...
    @property
    def id_token(self) -> str | None: ...
    @property
    def client_id(self) -> str | None: ...
    @property
    def client_secret(self) -> str | None: ...
    @property
    def requires_scopes(self) -> bool: ...
    @property
    def rapt_token(self) -> str | None: ...
    @property
    def refresh_handler(self) -> Any | None: ...
    @refresh_handler.setter
    def refresh_handler(self, value: Any | None) -> None: ...
    @property
    def account(self) -> str: ...
    def get_cred_info(self) -> Mapping[str, str] | None: ...
    def with_quota_project(self, quota_project_id: str | None) -> Credentials: ...
    def with_token_uri(self, token_uri: str) -> Credentials: ...
    def with_account(self, account: str) -> Credentials: ...
    def with_universe_domain(self, universe_domain: str) -> Credentials: ...
    def refresh(self, request: google.auth.transport.Request) -> None | Coroutine[Any, Any, None]: ...
    @classmethod
    def from_authorized_user_info(cls, info: Mapping[str, str], scopes: Sequence[str] | None = None) -> Credentials: ...
    @classmethod
    def from_authorized_user_file(cls, filename: str, scopes: Sequence[str] | None = None) -> Credentials: ...
    def to_json(self, strip: Sequence[str] | None = None) -> str: ...

class UserAccessTokenCredentials(credentials.CredentialsWithQuotaProject):
    def __init__(self, account: str | None = None, quota_project_id: str | None = None) -> None: ...
    def with_account(self, account: str) -> UserAccessTokenCredentials: ...
    def with_quota_project(self, quota_project_id: str | None) -> UserAccessTokenCredentials: ...
    token: str | None
    expiry: datetime.datetime | None

    def refresh(self, request: google.auth.transport.Request) -> None: ...
    def before_request(
        self, request: google.auth.transport.Request, method: str, url: str, headers: Mapping[str, str]
    ) -> None: ...
