from typing import Any
from idlelib import rpc as rpc

def remote_object_tree_item(item: object) -> int: ...

class WrappedObjectTreeItem:
    def __init__(self, item: object) -> None: ...
    def __getattr__(self, name: str) -> Any: ...

class StubObjectTreeItem:
    sockio: rpc.RPCClient
    oid: int
    def __init__(self, sockio: rpc.RPCClient, oid: int) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
