from typing import Any

class Delegator:
    delegate: object
    def __init__(self, delegate: object | None = ...) -> None: ...
    def __getattr__(self, name: str) -> Any: ...
    def resetcache(self) -> None: ...
    def setdelegate(self, delegate: object) -> None: ...
