from _typeshed import Incomplete
from idlelib.delegator import Delegator as Delegator
from idlelib.redirector import WidgetRedirector as WidgetRedirector

class Percolator:
    def __getattr__(self, name: str) -> Incomplete: ...  # Incomplete
    text: Incomplete
    redir: Incomplete
    top: Incomplete
    filters: Incomplete
    def __init__(self, text) -> None: ...
    bottom: Incomplete
    def close(self) -> None: ...
    def insert(self, index, chars, tags: Incomplete | None = ...) -> None: ...
    def delete(self, index1, index2: Incomplete | None = ...) -> None: ...
    def insertfilter(self, filter) -> None: ...
    def insertfilterafter(self, filter, after) -> None: ...
    def removefilter(self, filter) -> None: ...
