"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing
from collections import abc as _abc

from google.protobuf import any_pb2 as _any_pb2, descriptor as _descriptor, message as _message
from google.protobuf.internal import containers as _containers
from tensorflow.core.framework import (
    graph_pb2 as _graph_pb2,
    op_def_pb2 as _op_def_pb2,
    tensor_pb2 as _tensor_pb2,
    tensor_shape_pb2 as _tensor_shape_pb2,
    types_pb2 as _types_pb2,
)
from tensorflow.core.protobuf import (
    saved_object_graph_pb2 as _saved_object_graph_pb2,
    saver_pb2 as _saver_pb2,
    struct_pb2 as _struct_pb2,
)

if sys.version_info >= (3, 11):
    from typing import Never as _Never, TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias
    from typing_extensions import Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class MetaGraphDef(_message.Message):
    """Protocol buffer containing the following which are necessary to restart
    training, run inference. It can be used to serialize/de-serialize memory
    objects necessary for running computation in a graph when crossing the
    process boundary. It can be used for long term storage of graphs,
    cross-language execution of graphs, etc.
      MetaInfoDef
      GraphDef
      SaverDef
      CollectionDef
      TensorInfo
      SignatureDef
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class MetaInfoDef(_message.Message):
        """Meta information regarding the graph to be exported.  To be used by users
        of this protocol buffer to encode information regarding their meta graph.
        """

        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class FunctionAliasesEntry(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            KEY_FIELD_NUMBER: _builtins.int
            VALUE_FIELD_NUMBER: _builtins.int
            key: _builtins.str
            value: _builtins.str
            def __init__(self, *, key: _builtins.str | None = ..., value: _builtins.str | None = ...) -> None: ...
            _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        META_GRAPH_VERSION_FIELD_NUMBER: _builtins.int
        STRIPPED_OP_LIST_FIELD_NUMBER: _builtins.int
        ANY_INFO_FIELD_NUMBER: _builtins.int
        TAGS_FIELD_NUMBER: _builtins.int
        TENSORFLOW_VERSION_FIELD_NUMBER: _builtins.int
        TENSORFLOW_GIT_VERSION_FIELD_NUMBER: _builtins.int
        STRIPPED_DEFAULT_ATTRS_FIELD_NUMBER: _builtins.int
        FUNCTION_ALIASES_FIELD_NUMBER: _builtins.int
        meta_graph_version: _builtins.str
        """User specified Version string. Can be the name of the model and revision,
        steps this model has been trained to, etc.
        """
        tensorflow_version: _builtins.str
        """The __version__ string of the tensorflow build used to write this graph.
        This will be populated by the framework, which will overwrite any user
        supplied value.
        """
        tensorflow_git_version: _builtins.str
        """The __git_version__ string of the tensorflow build used to write this
        graph. This will be populated by the framework, which will overwrite any
        user supplied value.
        """
        stripped_default_attrs: _builtins.bool
        """A flag to denote whether default-valued attrs have been stripped from
        the nodes in this graph_def.
        """
        @_builtins.property
        def stripped_op_list(self) -> _op_def_pb2.OpList:
            """A copy of the OpDefs used by the producer of this graph_def.
            Descriptions and Ops not used in graph_def are stripped out.
            """

        @_builtins.property
        def any_info(self) -> _any_pb2.Any:
            """A serialized protobuf. Can be the time this meta graph is created, or
            modified, or name of the model.
            """

        @_builtins.property
        def tags(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
            """User supplied tag(s) on the meta_graph and included graph_def.

            MetaGraphDefs should be tagged with their capabilities or use-cases.
            Examples: "train", "serve", "gpu", "tpu", etc.
            These tags enable loaders to access the MetaGraph(s) appropriate for a
            specific use-case or runtime environment.
            """

        @_builtins.property
        def function_aliases(self) -> _containers.ScalarMap[_builtins.str, _builtins.str]:
            """FunctionDef name to aliases mapping."""

        def __init__(
            self,
            *,
            meta_graph_version: _builtins.str | None = ...,
            stripped_op_list: _op_def_pb2.OpList | None = ...,
            any_info: _any_pb2.Any | None = ...,
            tags: _abc.Iterable[_builtins.str] | None = ...,
            tensorflow_version: _builtins.str | None = ...,
            tensorflow_git_version: _builtins.str | None = ...,
            stripped_default_attrs: _builtins.bool | None = ...,
            function_aliases: _abc.Mapping[_builtins.str, _builtins.str] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal[
            "any_info", b"any_info", "stripped_op_list", b"stripped_op_list"
        ]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal[
            "any_info",
            b"any_info",
            "function_aliases",
            b"function_aliases",
            "meta_graph_version",
            b"meta_graph_version",
            "stripped_default_attrs",
            b"stripped_default_attrs",
            "stripped_op_list",
            b"stripped_op_list",
            "tags",
            b"tags",
            "tensorflow_git_version",
            b"tensorflow_git_version",
            "tensorflow_version",
            b"tensorflow_version",
        ]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CollectionDefEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___CollectionDef: ...
        def __init__(self, *, key: _builtins.str | None = ..., value: Global___CollectionDef | None = ...) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class SignatureDefEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___SignatureDef: ...
        def __init__(self, *, key: _builtins.str | None = ..., value: Global___SignatureDef | None = ...) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    META_INFO_DEF_FIELD_NUMBER: _builtins.int
    GRAPH_DEF_FIELD_NUMBER: _builtins.int
    SAVER_DEF_FIELD_NUMBER: _builtins.int
    COLLECTION_DEF_FIELD_NUMBER: _builtins.int
    SIGNATURE_DEF_FIELD_NUMBER: _builtins.int
    ASSET_FILE_DEF_FIELD_NUMBER: _builtins.int
    OBJECT_GRAPH_DEF_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def meta_info_def(self) -> Global___MetaGraphDef.MetaInfoDef: ...
    @_builtins.property
    def graph_def(self) -> _graph_pb2.GraphDef:
        """GraphDef."""

    @_builtins.property
    def saver_def(self) -> _saver_pb2.SaverDef:
        """SaverDef."""

    @_builtins.property
    def collection_def(self) -> _containers.MessageMap[_builtins.str, Global___CollectionDef]:
        """collection_def: Map from collection name to collections.
        See CollectionDef section for details.
        """

    @_builtins.property
    def signature_def(self) -> _containers.MessageMap[_builtins.str, Global___SignatureDef]:
        """signature_def: Map from user supplied key for a signature to a single
        SignatureDef.
        """

    @_builtins.property
    def asset_file_def(self) -> _containers.RepeatedCompositeFieldContainer[Global___AssetFileDef]:
        """Asset file def to be used with the defined graph."""

    @_builtins.property
    def object_graph_def(self) -> _saved_object_graph_pb2.SavedObjectGraph:
        """Extra information about the structure of functions and stateful objects."""

    def __init__(
        self,
        *,
        meta_info_def: Global___MetaGraphDef.MetaInfoDef | None = ...,
        graph_def: _graph_pb2.GraphDef | None = ...,
        saver_def: _saver_pb2.SaverDef | None = ...,
        collection_def: _abc.Mapping[_builtins.str, Global___CollectionDef] | None = ...,
        signature_def: _abc.Mapping[_builtins.str, Global___SignatureDef] | None = ...,
        asset_file_def: _abc.Iterable[Global___AssetFileDef] | None = ...,
        object_graph_def: _saved_object_graph_pb2.SavedObjectGraph | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "graph_def",
        b"graph_def",
        "meta_info_def",
        b"meta_info_def",
        "object_graph_def",
        b"object_graph_def",
        "saver_def",
        b"saver_def",
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "asset_file_def",
        b"asset_file_def",
        "collection_def",
        b"collection_def",
        "graph_def",
        b"graph_def",
        "meta_info_def",
        b"meta_info_def",
        "object_graph_def",
        b"object_graph_def",
        "saver_def",
        b"saver_def",
        "signature_def",
        b"signature_def",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MetaGraphDef: _TypeAlias = MetaGraphDef  # noqa: Y015

@_typing.final
class CollectionDef(_message.Message):
    """CollectionDef should cover most collections.
    To add a user-defined collection, do one of the following:
    1. For simple data types, such as string, int, float:
         tf.add_to_collection("your_collection_name", your_simple_value)
       strings will be stored as bytes_list.

    2. For Protobuf types, there are three ways to add them:
       1) tf.add_to_collection("your_collection_name",
            your_proto.SerializeToString())

          collection_def {
            key: "user_defined_bytes_collection"
            value {
              bytes_list {
                value: "queue_name: \\"test_queue\\"\\n"
              }
            }
          }

     or

       2) tf.add_to_collection("your_collection_name", str(your_proto))

          collection_def {
            key: "user_defined_string_collection"
            value {
             bytes_list {
                value: "\\n\\ntest_queue"
              }
            }
          }

     or

       3) any_buf = any_pb2.Any()
          tf.add_to_collection("your_collection_name",
            any_buf.Pack(your_proto))

          collection_def {
            key: "user_defined_any_collection"
            value {
              any_list {
                value {
                  type_url: "type.googleapis.com/tensorflow.QueueRunnerDef"
                  value: "\\n\\ntest_queue"
                }
              }
            }
          }

    3. For Python objects, implement to_proto() and from_proto(), and register
       them in the following manner:
       ops.register_proto_function("your_collection_name",
                                   proto_type,
                                   to_proto=YourPythonObject.to_proto,
                                   from_proto=YourPythonObject.from_proto)
       These functions will be invoked to serialize and de-serialize the
       collection. For example,
       ops.register_proto_function(ops.GraphKeys.GLOBAL_VARIABLES,
                                   proto_type=variable_pb2.VariableDef,
                                   to_proto=Variable.to_proto,
                                   from_proto=Variable.from_proto)
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class NodeList(_message.Message):
        """NodeList is used for collecting nodes in graph. For example
        collection_def {
          key: "summaries"
          value {
            node_list {
              value: "input_producer/ScalarSummary:0"
              value: "shuffle_batch/ScalarSummary:0"
              value: "ImageSummary:0"
            }
          }
        """

        DESCRIPTOR: _descriptor.Descriptor

        VALUE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def value(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
        def __init__(self, *, value: _abc.Iterable[_builtins.str] | None = ...) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class BytesList(_message.Message):
        """BytesList is used for collecting strings and serialized protobufs. For
        example:
        collection_def {
          key: "trainable_variables"
          value {
            bytes_list {
              value: "\\n\\017conv1/weights:0\\022\\024conv1/weights/Assign
                     \\032\\024conv1/weights/read:0"
              value: "\\n\\016conv1/biases:0\\022\\023conv1/biases/Assign\\032
                     \\023conv1/biases/read:0"
            }
          }
        }
        """

        DESCRIPTOR: _descriptor.Descriptor

        VALUE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def value(self) -> _containers.RepeatedScalarFieldContainer[_builtins.bytes]: ...
        def __init__(self, *, value: _abc.Iterable[_builtins.bytes] | None = ...) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class Int64List(_message.Message):
        """Int64List is used for collecting int, int64 and long values."""

        DESCRIPTOR: _descriptor.Descriptor

        VALUE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def value(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
        def __init__(self, *, value: _abc.Iterable[_builtins.int] | None = ...) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class FloatList(_message.Message):
        """FloatList is used for collecting float values."""

        DESCRIPTOR: _descriptor.Descriptor

        VALUE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def value(self) -> _containers.RepeatedScalarFieldContainer[_builtins.float]: ...
        def __init__(self, *, value: _abc.Iterable[_builtins.float] | None = ...) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class AnyList(_message.Message):
        """AnyList is used for collecting Any protos."""

        DESCRIPTOR: _descriptor.Descriptor

        VALUE_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def value(self) -> _containers.RepeatedCompositeFieldContainer[_any_pb2.Any]: ...
        def __init__(self, *, value: _abc.Iterable[_any_pb2.Any] | None = ...) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    NODE_LIST_FIELD_NUMBER: _builtins.int
    BYTES_LIST_FIELD_NUMBER: _builtins.int
    INT64_LIST_FIELD_NUMBER: _builtins.int
    FLOAT_LIST_FIELD_NUMBER: _builtins.int
    ANY_LIST_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def node_list(self) -> Global___CollectionDef.NodeList: ...
    @_builtins.property
    def bytes_list(self) -> Global___CollectionDef.BytesList: ...
    @_builtins.property
    def int64_list(self) -> Global___CollectionDef.Int64List: ...
    @_builtins.property
    def float_list(self) -> Global___CollectionDef.FloatList: ...
    @_builtins.property
    def any_list(self) -> Global___CollectionDef.AnyList: ...
    def __init__(
        self,
        *,
        node_list: Global___CollectionDef.NodeList | None = ...,
        bytes_list: Global___CollectionDef.BytesList | None = ...,
        int64_list: Global___CollectionDef.Int64List | None = ...,
        float_list: Global___CollectionDef.FloatList | None = ...,
        any_list: Global___CollectionDef.AnyList | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "any_list",
        b"any_list",
        "bytes_list",
        b"bytes_list",
        "float_list",
        b"float_list",
        "int64_list",
        b"int64_list",
        "kind",
        b"kind",
        "node_list",
        b"node_list",
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "any_list",
        b"any_list",
        "bytes_list",
        b"bytes_list",
        "float_list",
        b"float_list",
        "int64_list",
        b"int64_list",
        "kind",
        b"kind",
        "node_list",
        b"node_list",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_kind: _TypeAlias = _typing.Literal[
        "node_list", "bytes_list", "int64_list", "float_list", "any_list"
    ]  # noqa: Y015
    _WhichOneofArgType_kind: _TypeAlias = _typing.Literal["kind", b"kind"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_kind) -> _WhichOneofReturnType_kind | None: ...

Global___CollectionDef: _TypeAlias = CollectionDef  # noqa: Y015

@_typing.final
class TensorInfo(_message.Message):
    """Information about a Tensor necessary for feeding or retrieval."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class CooSparse(_message.Message):
        """For sparse tensors, The COO encoding stores a triple of values, indices,
        and shape.
        """

        DESCRIPTOR: _descriptor.Descriptor

        VALUES_TENSOR_NAME_FIELD_NUMBER: _builtins.int
        INDICES_TENSOR_NAME_FIELD_NUMBER: _builtins.int
        DENSE_SHAPE_TENSOR_NAME_FIELD_NUMBER: _builtins.int
        values_tensor_name: _builtins.str
        """The shape of the values Tensor is [?].  Its dtype must be the dtype of
        the SparseTensor as a whole, given in the enclosing TensorInfo.
        """
        indices_tensor_name: _builtins.str
        """The indices Tensor must have dtype int64 and shape [?, ?]."""
        dense_shape_tensor_name: _builtins.str
        """The dynamic logical shape represented by the SparseTensor is recorded in
        the Tensor referenced here.  It must have dtype int64 and shape [?].
        """
        def __init__(
            self,
            *,
            values_tensor_name: _builtins.str | None = ...,
            indices_tensor_name: _builtins.str | None = ...,
            dense_shape_tensor_name: _builtins.str | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal[
            "dense_shape_tensor_name",
            b"dense_shape_tensor_name",
            "indices_tensor_name",
            b"indices_tensor_name",
            "values_tensor_name",
            b"values_tensor_name",
        ]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class CompositeTensor(_message.Message):
        """Generic encoding for composite tensors."""

        DESCRIPTOR: _descriptor.Descriptor

        TYPE_SPEC_FIELD_NUMBER: _builtins.int
        COMPONENTS_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def type_spec(self) -> _struct_pb2.TypeSpecProto:
            """The serialized TypeSpec for the composite tensor."""

        @_builtins.property
        def components(self) -> _containers.RepeatedCompositeFieldContainer[Global___TensorInfo]:
            """A TensorInfo for each flattened component tensor."""

        def __init__(
            self,
            *,
            type_spec: _struct_pb2.TypeSpecProto | None = ...,
            components: _abc.Iterable[Global___TensorInfo] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["type_spec", b"type_spec"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["components", b"components", "type_spec", b"type_spec"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    NAME_FIELD_NUMBER: _builtins.int
    COO_SPARSE_FIELD_NUMBER: _builtins.int
    COMPOSITE_TENSOR_FIELD_NUMBER: _builtins.int
    DTYPE_FIELD_NUMBER: _builtins.int
    TENSOR_SHAPE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """For dense `Tensor`s, the name of the tensor in the graph."""
    dtype: _types_pb2.DataType.ValueType
    @_builtins.property
    def coo_sparse(self) -> Global___TensorInfo.CooSparse:
        """There are many possible encodings of sparse matrices
        (https://en.wikipedia.org/wiki/Sparse_matrix).  Currently, TensorFlow
        uses only the COO encoding.  This is supported and documented in the
        SparseTensor Python class.
        """

    @_builtins.property
    def composite_tensor(self) -> Global___TensorInfo.CompositeTensor:
        """Generic encoding for CompositeTensors."""

    @_builtins.property
    def tensor_shape(self) -> _tensor_shape_pb2.TensorShapeProto:
        """The static shape should be recorded here, to the extent that it can
        be known in advance.  In the case of a SparseTensor, this field describes
        the logical shape of the represented tensor (aka dense_shape).
        """

    def __init__(
        self,
        *,
        name: _builtins.str | None = ...,
        coo_sparse: Global___TensorInfo.CooSparse | None = ...,
        composite_tensor: Global___TensorInfo.CompositeTensor | None = ...,
        dtype: _types_pb2.DataType.ValueType | None = ...,
        tensor_shape: _tensor_shape_pb2.TensorShapeProto | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "composite_tensor",
        b"composite_tensor",
        "coo_sparse",
        b"coo_sparse",
        "encoding",
        b"encoding",
        "name",
        b"name",
        "tensor_shape",
        b"tensor_shape",
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "composite_tensor",
        b"composite_tensor",
        "coo_sparse",
        b"coo_sparse",
        "dtype",
        b"dtype",
        "encoding",
        b"encoding",
        "name",
        b"name",
        "tensor_shape",
        b"tensor_shape",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_encoding: _TypeAlias = _typing.Literal["name", "coo_sparse", "composite_tensor"]  # noqa: Y015
    _WhichOneofArgType_encoding: _TypeAlias = _typing.Literal["encoding", b"encoding"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_encoding) -> _WhichOneofReturnType_encoding | None: ...

Global___TensorInfo: _TypeAlias = TensorInfo  # noqa: Y015

@_typing.final
class SignatureDef(_message.Message):
    """SignatureDef defines the signature of a computation supported by a TensorFlow
    graph.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class InputsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___TensorInfo: ...
        def __init__(self, *, key: _builtins.str | None = ..., value: Global___TensorInfo | None = ...) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class OutputsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___TensorInfo: ...
        def __init__(self, *, key: _builtins.str | None = ..., value: Global___TensorInfo | None = ...) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class DefaultsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> _tensor_pb2.TensorProto: ...
        def __init__(self, *, key: _builtins.str | None = ..., value: _tensor_pb2.TensorProto | None = ...) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    INPUTS_FIELD_NUMBER: _builtins.int
    OUTPUTS_FIELD_NUMBER: _builtins.int
    METHOD_NAME_FIELD_NUMBER: _builtins.int
    DEFAULTS_FIELD_NUMBER: _builtins.int
    method_name: _builtins.str
    """Deprecated: TensorFlow 2 always sets this to a fixed value;
    open-source TF Serving stopped checking by default since release 2.4.

    In TensorFlow 1, the method_name enabled users to mark a SignatureDef as
    supporting a particular method. Multiple SignatureDefs in a single
    MetaGraphDef could have the same method_name (e.g., to support multi-headed
    computation).
    """
    @_builtins.property
    def inputs(self) -> _containers.MessageMap[_builtins.str, Global___TensorInfo]:
        """Named input parameters."""

    @_builtins.property
    def outputs(self) -> _containers.MessageMap[_builtins.str, Global___TensorInfo]:
        """Named output parameters."""

    @_builtins.property
    def defaults(self) -> _containers.MessageMap[_builtins.str, _tensor_pb2.TensorProto]:
        """Named input to corresponding default values if any."""

    def __init__(
        self,
        *,
        inputs: _abc.Mapping[_builtins.str, Global___TensorInfo] | None = ...,
        outputs: _abc.Mapping[_builtins.str, Global___TensorInfo] | None = ...,
        method_name: _builtins.str | None = ...,
        defaults: _abc.Mapping[_builtins.str, _tensor_pb2.TensorProto] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "defaults", b"defaults", "inputs", b"inputs", "method_name", b"method_name", "outputs", b"outputs"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SignatureDef: _TypeAlias = SignatureDef  # noqa: Y015

@_typing.final
class AssetFileDef(_message.Message):
    """An asset file def for a single file or a set of sharded files with the same
    name.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TENSOR_INFO_FIELD_NUMBER: _builtins.int
    FILENAME_FIELD_NUMBER: _builtins.int
    filename: _builtins.str
    """The filename within an assets directory. Note: does not include the path
    prefix, i.e. directories. For an asset at /tmp/path/vocab.txt, the filename
    would be "vocab.txt".
    """
    @_builtins.property
    def tensor_info(self) -> Global___TensorInfo:
        """The tensor to bind the asset filename to."""

    def __init__(self, *, tensor_info: Global___TensorInfo | None = ..., filename: _builtins.str | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["tensor_info", b"tensor_info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["filename", b"filename", "tensor_info", b"tensor_info"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AssetFileDef: _TypeAlias = AssetFileDef  # noqa: Y015
