"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from google.protobuf import descriptor as _descriptor
from tensorflow.compiler.xla.tsl.protobuf.rpc_options_pb2 import RPCOptions as RPCOptions

DESCRIPTOR: _descriptor.FileDescriptor
