"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing

from google.protobuf import descriptor as _descriptor, message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper

if sys.version_info >= (3, 11):
    from typing import Never as _Never, TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias
    from typing_extensions import Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SaverDef(_message.Message):
    """Protocol buffer representing the configuration of a Saver."""

    DESCRIPTOR: _descriptor.Descriptor

    class _CheckpointFormatVersion:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _CheckpointFormatVersionEnumTypeWrapper(
        _enum_type_wrapper._EnumTypeWrapper[SaverDef._CheckpointFormatVersion.ValueType], _builtins.type
    ):
        DESCRIPTOR: _descriptor.EnumDescriptor
        LEGACY: SaverDef._CheckpointFormatVersion.ValueType  # 0
        """Internal legacy format."""
        V1: SaverDef._CheckpointFormatVersion.ValueType  # 1
        """Deprecated format: tf.Saver() which works with tensorflow::table::Table."""
        V2: SaverDef._CheckpointFormatVersion.ValueType  # 2
        """Current format: more efficient."""

    class CheckpointFormatVersion(_CheckpointFormatVersion, metaclass=_CheckpointFormatVersionEnumTypeWrapper):
        """A version number that identifies a different on-disk checkpoint format.
        Usually, each subclass of BaseSaverBuilder works with a particular
        version/format.  However, it is possible that the same builder may be
        upgraded to support a newer checkpoint format in the future.
        """

    LEGACY: SaverDef.CheckpointFormatVersion.ValueType  # 0
    """Internal legacy format."""
    V1: SaverDef.CheckpointFormatVersion.ValueType  # 1
    """Deprecated format: tf.Saver() which works with tensorflow::table::Table."""
    V2: SaverDef.CheckpointFormatVersion.ValueType  # 2
    """Current format: more efficient."""

    FILENAME_TENSOR_NAME_FIELD_NUMBER: _builtins.int
    SAVE_TENSOR_NAME_FIELD_NUMBER: _builtins.int
    RESTORE_OP_NAME_FIELD_NUMBER: _builtins.int
    MAX_TO_KEEP_FIELD_NUMBER: _builtins.int
    SHARDED_FIELD_NUMBER: _builtins.int
    KEEP_CHECKPOINT_EVERY_N_HOURS_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    filename_tensor_name: _builtins.str
    """The name of the tensor in which to specify the filename when saving or
    restoring a model checkpoint.
    """
    save_tensor_name: _builtins.str
    """The operation to run when saving a model checkpoint."""
    restore_op_name: _builtins.str
    """The operation to run when restoring a model checkpoint."""
    max_to_keep: _builtins.int
    """Maximum number of checkpoints to keep.  If 0, no checkpoints are deleted."""
    sharded: _builtins.bool
    """Shard the save files, one per device that has Variable nodes."""
    keep_checkpoint_every_n_hours: _builtins.float
    """How often to keep an additional checkpoint. If not specified, only the last
    "max_to_keep" checkpoints are kept; if specified, in addition to keeping
    the last "max_to_keep" checkpoints, an additional checkpoint will be kept
    for every n hours of training.
    """
    version: Global___SaverDef.CheckpointFormatVersion.ValueType
    def __init__(
        self,
        *,
        filename_tensor_name: _builtins.str | None = ...,
        save_tensor_name: _builtins.str | None = ...,
        restore_op_name: _builtins.str | None = ...,
        max_to_keep: _builtins.int | None = ...,
        sharded: _builtins.bool | None = ...,
        keep_checkpoint_every_n_hours: _builtins.float | None = ...,
        version: Global___SaverDef.CheckpointFormatVersion.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "filename_tensor_name",
        b"filename_tensor_name",
        "keep_checkpoint_every_n_hours",
        b"keep_checkpoint_every_n_hours",
        "max_to_keep",
        b"max_to_keep",
        "restore_op_name",
        b"restore_op_name",
        "save_tensor_name",
        b"save_tensor_name",
        "sharded",
        b"sharded",
        "version",
        b"version",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SaverDef: _TypeAlias = SaverDef  # noqa: Y015
