"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing
from collections import abc as _abc

from google.protobuf import any_pb2 as _any_pb2, descriptor as _descriptor, message as _message
from google.protobuf.internal import containers as _containers, enum_type_wrapper as _enum_type_wrapper
from tensorflow.core.framework import (
    tensor_shape_pb2 as _tensor_shape_pb2,
    types_pb2 as _types_pb2,
    variable_pb2 as _variable_pb2,
    versions_pb2 as _versions_pb2,
)
from tensorflow.core.protobuf import struct_pb2 as _struct_pb2, trackable_object_graph_pb2 as _trackable_object_graph_pb2

if sys.version_info >= (3, 11):
    from typing import Never as _Never, TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias
    from typing_extensions import Never as _Never

if sys.version_info >= (3, 13):
    from warnings import deprecated as _deprecated
else:
    from typing_extensions import deprecated as _deprecated

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SavedObjectGraph(_message.Message):
    """SavedObjectGraph shares some structure with TrackableObjectGraph, but
    SavedObjectGraph belongs to the MetaGraph and contains pointers to functions
    and type information, while TrackableObjectGraph lives in the checkpoint
    and contains pointers only to variable values.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class ConcreteFunctionsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___SavedConcreteFunction: ...
        def __init__(self, *, key: _builtins.str | None = ..., value: Global___SavedConcreteFunction | None = ...) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    NODES_FIELD_NUMBER: _builtins.int
    CONCRETE_FUNCTIONS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def nodes(self) -> _containers.RepeatedCompositeFieldContainer[Global___SavedObject]:
        """Flattened list of objects in the object graph.

        The position of the object in this list indicates its id.
        Nodes[0] is considered the root node.
        """

    @_builtins.property
    def concrete_functions(self) -> _containers.MessageMap[_builtins.str, Global___SavedConcreteFunction]:
        """Information about captures and output structures in concrete functions.
        Referenced from SavedBareConcreteFunction and SavedFunction.
        """

    def __init__(
        self,
        *,
        nodes: _abc.Iterable[Global___SavedObject] | None = ...,
        concrete_functions: _abc.Mapping[_builtins.str, Global___SavedConcreteFunction] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["concrete_functions", b"concrete_functions", "nodes", b"nodes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SavedObjectGraph: _TypeAlias = SavedObjectGraph  # noqa: Y015

@_typing.final
class SavedObject(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class SaveableObjectsEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___SaveableObject: ...
        def __init__(self, *, key: _builtins.str | None = ..., value: Global___SaveableObject | None = ...) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    CHILDREN_FIELD_NUMBER: _builtins.int
    DEPENDENCIES_FIELD_NUMBER: _builtins.int
    SLOT_VARIABLES_FIELD_NUMBER: _builtins.int
    USER_OBJECT_FIELD_NUMBER: _builtins.int
    ASSET_FIELD_NUMBER: _builtins.int
    FUNCTION_FIELD_NUMBER: _builtins.int
    VARIABLE_FIELD_NUMBER: _builtins.int
    BARE_CONCRETE_FUNCTION_FIELD_NUMBER: _builtins.int
    CONSTANT_FIELD_NUMBER: _builtins.int
    RESOURCE_FIELD_NUMBER: _builtins.int
    CAPTURED_TENSOR_FIELD_NUMBER: _builtins.int
    SAVEABLE_OBJECTS_FIELD_NUMBER: _builtins.int
    REGISTERED_NAME_FIELD_NUMBER: _builtins.int
    SERIALIZED_USER_PROTO_FIELD_NUMBER: _builtins.int
    REGISTERED_SAVER_FIELD_NUMBER: _builtins.int
    registered_name: _builtins.str
    """The fields below are filled when the user serializes a registered Trackable
    class or an object with a registered saver function.

    Registered classes may save additional metadata and supersede the
    default loading process where nodes are recreated from the proto.
    If the registered class cannot be found, then the object will load as one
    one of the default trackable objects: Autotrackable (a class similar to
    tf.Module), tf.function, or tf.Variable.

    Unlike SaveableObjects, which store the functions for saving and restoring
    from tensors, registered savers allow Trackables to write checkpoint shards
    directly (e.g. for performance or coordination reasons).
    *All registered savers must be available when loading the SavedModel.*

    The name of the registered class of the form "{package}.{class_name}".
    This field is used to search for the registered class at loading time.
    """
    registered_saver: _builtins.str
    """String name of the registered saver. At most one of `saveable_objects` or
    `registered_saver` is defined for each SavedObject.
    """
    @_builtins.property
    def children(
        self,
    ) -> _containers.RepeatedCompositeFieldContainer[
        _trackable_object_graph_pb2.TrackableObjectGraph.TrackableObject.ObjectReference
    ]:
        """Objects which this object depends on: named edges in the dependency
        graph.

        Note: All kinds of SavedObject may have children, except
        "constant" and "captured_tensor".
        """

    @_builtins.property
    def dependencies(
        self,
    ) -> _containers.RepeatedCompositeFieldContainer[
        _trackable_object_graph_pb2.TrackableObjectGraph.TrackableObject.ObjectReference
    ]:
        """Ordered list of dependencies that must be loaded before this object.
        SavedModel loads with the bottom-up approach, by first creating all objects
        (in the order defined by the dependencies), then connecting the edges.
        """

    @_builtins.property
    def slot_variables(
        self,
    ) -> _containers.RepeatedCompositeFieldContainer[
        _trackable_object_graph_pb2.TrackableObjectGraph.TrackableObject.SlotVariableReference
    ]:
        """Slot variables owned by this object. This describes the three-way
        (optimizer, variable, slot variable) relationship; none of the three
        depend on the others directly.

        Note: currently only valid if kind == "user_object".
        """

    @_builtins.property
    def user_object(self) -> Global___SavedUserObject: ...
    @_builtins.property
    def asset(self) -> Global___SavedAsset: ...
    @_builtins.property
    def function(self) -> Global___SavedFunction: ...
    @_builtins.property
    def variable(self) -> Global___SavedVariable: ...
    @_builtins.property
    def bare_concrete_function(self) -> Global___SavedBareConcreteFunction: ...
    @_builtins.property
    def constant(self) -> Global___SavedConstant: ...
    @_builtins.property
    def resource(self) -> Global___SavedResource: ...
    @_builtins.property
    def captured_tensor(self) -> Global___CapturedTensor: ...
    @_builtins.property
    def saveable_objects(self) -> _containers.MessageMap[_builtins.str, Global___SaveableObject]:
        """Stores the functions used to save and restore this object. At most one of
        `saveable_objects` or `registered_saver` is defined for each SavedObject.
        See the comment below for the difference between SaveableObject and
        registered savers.
        """

    @_builtins.property
    def serialized_user_proto(self) -> _any_pb2.Any:
        """The user-generated proto storing metadata for this object, to be passed to
        the registered classes's _deserialize_from_proto method when this object is
        loaded from the SavedModel.
        """

    def __init__(
        self,
        *,
        children: _abc.Iterable[_trackable_object_graph_pb2.TrackableObjectGraph.TrackableObject.ObjectReference] | None = ...,
        dependencies: (
            _abc.Iterable[_trackable_object_graph_pb2.TrackableObjectGraph.TrackableObject.ObjectReference] | None
        ) = ...,
        slot_variables: (
            _abc.Iterable[_trackable_object_graph_pb2.TrackableObjectGraph.TrackableObject.SlotVariableReference] | None
        ) = ...,
        user_object: Global___SavedUserObject | None = ...,
        asset: Global___SavedAsset | None = ...,
        function: Global___SavedFunction | None = ...,
        variable: Global___SavedVariable | None = ...,
        bare_concrete_function: Global___SavedBareConcreteFunction | None = ...,
        constant: Global___SavedConstant | None = ...,
        resource: Global___SavedResource | None = ...,
        captured_tensor: Global___CapturedTensor | None = ...,
        saveable_objects: _abc.Mapping[_builtins.str, Global___SaveableObject] | None = ...,
        registered_name: _builtins.str | None = ...,
        serialized_user_proto: _any_pb2.Any | None = ...,
        registered_saver: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "asset",
        b"asset",
        "bare_concrete_function",
        b"bare_concrete_function",
        "captured_tensor",
        b"captured_tensor",
        "constant",
        b"constant",
        "function",
        b"function",
        "kind",
        b"kind",
        "resource",
        b"resource",
        "serialized_user_proto",
        b"serialized_user_proto",
        "user_object",
        b"user_object",
        "variable",
        b"variable",
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "asset",
        b"asset",
        "bare_concrete_function",
        b"bare_concrete_function",
        "captured_tensor",
        b"captured_tensor",
        "children",
        b"children",
        "constant",
        b"constant",
        "dependencies",
        b"dependencies",
        "function",
        b"function",
        "kind",
        b"kind",
        "registered_name",
        b"registered_name",
        "registered_saver",
        b"registered_saver",
        "resource",
        b"resource",
        "saveable_objects",
        b"saveable_objects",
        "serialized_user_proto",
        b"serialized_user_proto",
        "slot_variables",
        b"slot_variables",
        "user_object",
        b"user_object",
        "variable",
        b"variable",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_kind: _TypeAlias = _typing.Literal[
        "user_object", "asset", "function", "variable", "bare_concrete_function", "constant", "resource", "captured_tensor"
    ]  # noqa: Y015
    _WhichOneofArgType_kind: _TypeAlias = _typing.Literal["kind", b"kind"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_kind) -> _WhichOneofReturnType_kind | None: ...

Global___SavedObject: _TypeAlias = SavedObject  # noqa: Y015

@_typing.final
class SavedUserObject(_message.Message):
    """A SavedUserObject is an object (in the object-oriented language of the
    TensorFlow program) of some user- or framework-defined class other than
    those handled specifically by the other kinds of SavedObjects.

    This object cannot be evaluated as a tensor, and therefore cannot be bound
    to an input of a function.
    """

    DESCRIPTOR: _descriptor.Descriptor

    IDENTIFIER_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    METADATA_FIELD_NUMBER: _builtins.int
    identifier: _builtins.str
    """Corresponds to a registration of the type to use in the loading program."""

    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def metadata(self) -> _builtins.str:
        """Metadata for deserializing this object.

        Deprecated! At the time of deprecation, Keras was the only user of this
        field, and its saving and loading code will be updated shortly.
        Please save your application-specific metadata to a separate file.
        """
    @metadata.setter
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def metadata(self, value: _builtins.str) -> None:
        """Metadata for deserializing this object.

        Deprecated! At the time of deprecation, Keras was the only user of this
        field, and its saving and loading code will be updated shortly.
        Please save your application-specific metadata to a separate file.
        """

    @_builtins.property
    def version(self) -> _versions_pb2.VersionDef:
        """Version information from the producer of this SavedUserObject."""

    def __init__(
        self,
        *,
        identifier: _builtins.str | None = ...,
        version: _versions_pb2.VersionDef | None = ...,
        metadata: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["version", b"version"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "identifier", b"identifier", "metadata", b"metadata", "version", b"version"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SavedUserObject: _TypeAlias = SavedUserObject  # noqa: Y015

@_typing.final
class SavedAsset(_message.Message):
    """A SavedAsset points to an asset in the MetaGraph.

    When bound to a function this object evaluates to a tensor with the absolute
    filename. Users should not depend on a particular part of the filename to
    remain stable (e.g. basename could be changed).
    """

    DESCRIPTOR: _descriptor.Descriptor

    ASSET_FILE_DEF_INDEX_FIELD_NUMBER: _builtins.int
    asset_file_def_index: _builtins.int
    """Index into `MetaGraphDef.asset_file_def[]` that describes the Asset.

    Only the field `AssetFileDef.filename` is used. Other fields, such as
    `AssetFileDef.tensor_info`, MUST be ignored.
    """
    def __init__(self, *, asset_file_def_index: _builtins.int | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["asset_file_def_index", b"asset_file_def_index"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SavedAsset: _TypeAlias = SavedAsset  # noqa: Y015

@_typing.final
class SavedFunction(_message.Message):
    """A function with multiple signatures, possibly with non-Tensor arguments."""

    DESCRIPTOR: _descriptor.Descriptor

    CONCRETE_FUNCTIONS_FIELD_NUMBER: _builtins.int
    FUNCTION_SPEC_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def concrete_functions(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def function_spec(self) -> Global___FunctionSpec: ...
    def __init__(
        self, *, concrete_functions: _abc.Iterable[_builtins.str] | None = ..., function_spec: Global___FunctionSpec | None = ...
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["function_spec", b"function_spec"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "concrete_functions", b"concrete_functions", "function_spec", b"function_spec"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SavedFunction: _TypeAlias = SavedFunction  # noqa: Y015

@_typing.final
class CapturedTensor(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    CONCRETE_FUNCTION_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """Name of captured tensor"""
    concrete_function: _builtins.str
    """Name of concrete function which contains the computed graph tensor."""
    def __init__(self, *, name: _builtins.str | None = ..., concrete_function: _builtins.str | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["concrete_function", b"concrete_function", "name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CapturedTensor: _TypeAlias = CapturedTensor  # noqa: Y015

@_typing.final
class SavedConcreteFunction(_message.Message):
    """Stores low-level information about a concrete function. Referenced in either
    a SavedFunction or a SavedBareConcreteFunction.
    """

    DESCRIPTOR: _descriptor.Descriptor

    BOUND_INPUTS_FIELD_NUMBER: _builtins.int
    CANONICALIZED_INPUT_SIGNATURE_FIELD_NUMBER: _builtins.int
    OUTPUT_SIGNATURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def bound_inputs(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def canonicalized_input_signature(self) -> _struct_pb2.StructuredValue:
        """Input in canonicalized form that was received to create this concrete
        function.
        """

    @_builtins.property
    def output_signature(self) -> _struct_pb2.StructuredValue:
        """Output that was the return value of this function after replacing all
        Tensors with TensorSpecs. This can be an arbitrary nested function and will
        be used to reconstruct the full structure from pure tensors.
        """

    def __init__(
        self,
        *,
        bound_inputs: _abc.Iterable[_builtins.int] | None = ...,
        canonicalized_input_signature: _struct_pb2.StructuredValue | None = ...,
        output_signature: _struct_pb2.StructuredValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "canonicalized_input_signature", b"canonicalized_input_signature", "output_signature", b"output_signature"
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "bound_inputs",
        b"bound_inputs",
        "canonicalized_input_signature",
        b"canonicalized_input_signature",
        "output_signature",
        b"output_signature",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SavedConcreteFunction: _TypeAlias = SavedConcreteFunction  # noqa: Y015

@_typing.final
class SavedBareConcreteFunction(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    CONCRETE_FUNCTION_NAME_FIELD_NUMBER: _builtins.int
    ARGUMENT_KEYWORDS_FIELD_NUMBER: _builtins.int
    ALLOWED_POSITIONAL_ARGUMENTS_FIELD_NUMBER: _builtins.int
    FUNCTION_SPEC_FIELD_NUMBER: _builtins.int
    concrete_function_name: _builtins.str
    """Identifies a SavedConcreteFunction."""
    allowed_positional_arguments: _builtins.int
    """The prefix of `argument_keywords` which may be identified by position."""
    @_builtins.property
    def argument_keywords(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]:
        """A sequence of unique strings, one per Tensor argument."""

    @_builtins.property
    def function_spec(self) -> Global___FunctionSpec:
        """The spec of the function that this ConcreteFunction is traced from. This
        allows the ConcreteFunction to be called with nest structure inputs. This
        field may not be populated. If this field is absent, the concrete function
        can only be called with flat inputs.
        TODO(b/169361281): support calling saved ConcreteFunction with structured
        inputs in C++ SavedModel API.
        """

    def __init__(
        self,
        *,
        concrete_function_name: _builtins.str | None = ...,
        argument_keywords: _abc.Iterable[_builtins.str] | None = ...,
        allowed_positional_arguments: _builtins.int | None = ...,
        function_spec: Global___FunctionSpec | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["function_spec", b"function_spec"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "allowed_positional_arguments",
        b"allowed_positional_arguments",
        "argument_keywords",
        b"argument_keywords",
        "concrete_function_name",
        b"concrete_function_name",
        "function_spec",
        b"function_spec",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SavedBareConcreteFunction: _TypeAlias = SavedBareConcreteFunction  # noqa: Y015

@_typing.final
class SavedConstant(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    OPERATION_FIELD_NUMBER: _builtins.int
    operation: _builtins.str
    """An Operation name for a ConstantOp in this SavedObjectGraph's MetaGraph."""
    def __init__(self, *, operation: _builtins.str | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["operation", b"operation"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SavedConstant: _TypeAlias = SavedConstant  # noqa: Y015

@_typing.final
class SavedVariable(_message.Message):
    """Represents a Variable that is initialized by loading the contents from the
    checkpoint.
    """

    DESCRIPTOR: _descriptor.Descriptor

    DTYPE_FIELD_NUMBER: _builtins.int
    SHAPE_FIELD_NUMBER: _builtins.int
    TRAINABLE_FIELD_NUMBER: _builtins.int
    SYNCHRONIZATION_FIELD_NUMBER: _builtins.int
    AGGREGATION_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    DEVICE_FIELD_NUMBER: _builtins.int
    EXPERIMENTAL_DISTRIBUTED_VARIABLE_COMPONENTS_FIELD_NUMBER: _builtins.int
    dtype: _types_pb2.DataType.ValueType
    trainable: _builtins.bool
    synchronization: _variable_pb2.VariableSynchronization.ValueType
    aggregation: _variable_pb2.VariableAggregation.ValueType
    name: _builtins.str
    device: _builtins.str
    @_builtins.property
    def shape(self) -> _tensor_shape_pb2.TensorShapeProto: ...
    @_builtins.property
    def experimental_distributed_variable_components(self) -> _containers.RepeatedCompositeFieldContainer[Global___SavedVariable]:
        """List of component variables for a distributed variable.

        When this field is non-empty, the SavedVariable will be assumed
        to be a distributed variable defined by the components listed here.

        This is only supported by experimental loaders at the moment.
        """

    def __init__(
        self,
        *,
        dtype: _types_pb2.DataType.ValueType | None = ...,
        shape: _tensor_shape_pb2.TensorShapeProto | None = ...,
        trainable: _builtins.bool | None = ...,
        synchronization: _variable_pb2.VariableSynchronization.ValueType | None = ...,
        aggregation: _variable_pb2.VariableAggregation.ValueType | None = ...,
        name: _builtins.str | None = ...,
        device: _builtins.str | None = ...,
        experimental_distributed_variable_components: _abc.Iterable[Global___SavedVariable] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["shape", b"shape"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "aggregation",
        b"aggregation",
        "device",
        b"device",
        "dtype",
        b"dtype",
        "experimental_distributed_variable_components",
        b"experimental_distributed_variable_components",
        "name",
        b"name",
        "shape",
        b"shape",
        "synchronization",
        b"synchronization",
        "trainable",
        b"trainable",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SavedVariable: _TypeAlias = SavedVariable  # noqa: Y015

@_typing.final
class FunctionSpec(_message.Message):
    """Represents `FunctionSpec` used in `Function`. This represents a
    function that has been wrapped as a TensorFlow `Function`.
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _JitCompile:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _JitCompileEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[FunctionSpec._JitCompile.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        DEFAULT: FunctionSpec._JitCompile.ValueType  # 0
        ON: FunctionSpec._JitCompile.ValueType  # 1
        OFF: FunctionSpec._JitCompile.ValueType  # 2

    class JitCompile(_JitCompile, metaclass=_JitCompileEnumTypeWrapper):
        """Whether the function should be compiled by XLA.

        The public interface to `tf.function` uses an optional boolean to
        represent three distinct states for this field.  Unfortunately, proto3
        removes the ability to explicitly check for the presence or absence of a
        field, so we instead map to an enum.

        See `tf.function` for details.
        """

    DEFAULT: FunctionSpec.JitCompile.ValueType  # 0
    ON: FunctionSpec.JitCompile.ValueType  # 1
    OFF: FunctionSpec.JitCompile.ValueType  # 2

    FULLARGSPEC_FIELD_NUMBER: _builtins.int
    IS_METHOD_FIELD_NUMBER: _builtins.int
    INPUT_SIGNATURE_FIELD_NUMBER: _builtins.int
    JIT_COMPILE_FIELD_NUMBER: _builtins.int
    is_method: _builtins.bool
    """Whether this represents a class method."""
    jit_compile: Global___FunctionSpec.JitCompile.ValueType
    @_builtins.property
    def fullargspec(self) -> _struct_pb2.StructuredValue:
        """Full arg spec from inspect.getfullargspec()."""

    @_builtins.property
    def input_signature(self) -> _struct_pb2.StructuredValue:
        """The input signature, if specified."""

    def __init__(
        self,
        *,
        fullargspec: _struct_pb2.StructuredValue | None = ...,
        is_method: _builtins.bool | None = ...,
        input_signature: _struct_pb2.StructuredValue | None = ...,
        jit_compile: Global___FunctionSpec.JitCompile.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "fullargspec", b"fullargspec", "input_signature", b"input_signature"
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "fullargspec",
        b"fullargspec",
        "input_signature",
        b"input_signature",
        "is_method",
        b"is_method",
        "jit_compile",
        b"jit_compile",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FunctionSpec: _TypeAlias = FunctionSpec  # noqa: Y015

@_typing.final
class SavedResource(_message.Message):
    """A SavedResource represents a TF object that holds state during its lifetime.
    An object of this type can have a reference to a:
    create_resource() and an initialize() function.
    """

    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_FIELD_NUMBER: _builtins.int
    device: _builtins.str
    """A device specification indicating a required placement for the resource
    creation function, e.g. "CPU". An empty string allows the user to select a
    device.
    """
    def __init__(self, *, device: _builtins.str | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SavedResource: _TypeAlias = SavedResource  # noqa: Y015

@_typing.final
class SaveableObject(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SAVE_FUNCTION_FIELD_NUMBER: _builtins.int
    RESTORE_FUNCTION_FIELD_NUMBER: _builtins.int
    save_function: _builtins.int
    """Node ids of concrete functions for saving and loading from a checkpoint.
    These functions save and restore directly from tensors.
    """
    restore_function: _builtins.int
    def __init__(self, *, save_function: _builtins.int | None = ..., restore_function: _builtins.int | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "restore_function", b"restore_function", "save_function", b"save_function"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SaveableObject: _TypeAlias = SaveableObject  # noqa: Y015
