"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing
from collections import abc as _abc

from google.protobuf import descriptor as _descriptor, message as _message
from google.protobuf.internal import containers as _containers
from tensorflow.core.framework import tensor_pb2 as _tensor_pb2, tensor_shape_pb2 as _tensor_shape_pb2, types_pb2 as _types_pb2

if sys.version_info >= (3, 11):
    from typing import Never as _Never, TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias
    from typing_extensions import Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class SnapshotRecord(_message.Message):
    """Each SnapshotRecord represents one batch of pre-processed input data. A batch
    consists of a list of tensors that we encode as TensorProtos. This message
    doesn't store the structure of the batch.
    """

    DESCRIPTOR: _descriptor.Descriptor

    TENSOR_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def tensor(self) -> _containers.RepeatedCompositeFieldContainer[_tensor_pb2.TensorProto]: ...
    def __init__(self, *, tensor: _abc.Iterable[_tensor_pb2.TensorProto] | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tensor", b"tensor"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SnapshotRecord: _TypeAlias = SnapshotRecord  # noqa: Y015

@_typing.final
class SnapshotMetadataRecord(_message.Message):
    """This stores the metadata information present in each snapshot record."""

    DESCRIPTOR: _descriptor.Descriptor

    GRAPH_HASH_FIELD_NUMBER: _builtins.int
    RUN_ID_FIELD_NUMBER: _builtins.int
    CREATION_TIMESTAMP_FIELD_NUMBER: _builtins.int
    VERSION_FIELD_NUMBER: _builtins.int
    DTYPE_FIELD_NUMBER: _builtins.int
    NUM_ELEMENTS_FIELD_NUMBER: _builtins.int
    FINALIZED_FIELD_NUMBER: _builtins.int
    graph_hash: _builtins.str
    """Stores the fingerprint of the graph that describes the dataset that is
    snapshotted.
    """
    run_id: _builtins.str
    """Run ID that this snapshot corresponds to."""
    creation_timestamp: _builtins.int
    """Time when we started creating this snapshot."""
    version: _builtins.int
    """Version of the snapshot data file format."""
    num_elements: _builtins.int
    """The number of elements in the snapshot."""
    finalized: _builtins.bool
    @_builtins.property
    def dtype(self) -> _containers.RepeatedScalarFieldContainer[_types_pb2.DataType.ValueType]:
        """A list of tensor dtype corresponding to each element of the snapshot."""

    def __init__(
        self,
        *,
        graph_hash: _builtins.str | None = ...,
        run_id: _builtins.str | None = ...,
        creation_timestamp: _builtins.int | None = ...,
        version: _builtins.int | None = ...,
        dtype: _abc.Iterable[_types_pb2.DataType.ValueType] | None = ...,
        num_elements: _builtins.int | None = ...,
        finalized: _builtins.bool | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "creation_timestamp",
        b"creation_timestamp",
        "dtype",
        b"dtype",
        "finalized",
        b"finalized",
        "graph_hash",
        b"graph_hash",
        "num_elements",
        b"num_elements",
        "run_id",
        b"run_id",
        "version",
        b"version",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SnapshotMetadataRecord: _TypeAlias = SnapshotMetadataRecord  # noqa: Y015

@_typing.final
class TensorMetadata(_message.Message):
    """Metadata for a single tensor in the Snapshot Record."""

    DESCRIPTOR: _descriptor.Descriptor

    TENSOR_SHAPE_FIELD_NUMBER: _builtins.int
    TENSOR_SIZE_BYTES_FIELD_NUMBER: _builtins.int
    tensor_size_bytes: _builtins.int
    """Number of uncompressed bytes used to store the tensor representation."""
    @_builtins.property
    def tensor_shape(self) -> _tensor_shape_pb2.TensorShapeProto: ...
    def __init__(
        self, *, tensor_shape: _tensor_shape_pb2.TensorShapeProto | None = ..., tensor_size_bytes: _builtins.int | None = ...
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["tensor_shape", b"tensor_shape"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "tensor_shape", b"tensor_shape", "tensor_size_bytes", b"tensor_size_bytes"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TensorMetadata: _TypeAlias = TensorMetadata  # noqa: Y015

@_typing.final
class SnapshotTensorMetadata(_message.Message):
    """Metadata for all the tensors in a Snapshot Record."""

    DESCRIPTOR: _descriptor.Descriptor

    TENSOR_METADATA_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def tensor_metadata(self) -> _containers.RepeatedCompositeFieldContainer[Global___TensorMetadata]: ...
    def __init__(self, *, tensor_metadata: _abc.Iterable[Global___TensorMetadata] | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["tensor_metadata", b"tensor_metadata"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SnapshotTensorMetadata: _TypeAlias = SnapshotTensorMetadata  # noqa: Y015

@_typing.final
class DistributedSnapshotMetadata(_message.Message):
    """Metadata for a `tf.data.Dataset` distributed snapshot."""

    DESCRIPTOR: _descriptor.Descriptor

    ELEMENT_SPEC_FIELD_NUMBER: _builtins.int
    COMPRESSION_FIELD_NUMBER: _builtins.int
    element_spec: _builtins.bytes
    """The element spec of the snapshotted dataset."""
    compression: _builtins.str
    """Whether and how to compress the snapshot.  Supported values are defined in
    `tsl::io::compression`.  In particular, an empty string specifies not to
    compress.
    """
    def __init__(self, *, element_spec: _builtins.bytes | None = ..., compression: _builtins.str | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["compression", b"compression", "element_spec", b"element_spec"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DistributedSnapshotMetadata: _TypeAlias = DistributedSnapshotMetadata  # noqa: Y015
