"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Copyright 2016 The TensorFlow Authors. All Rights Reserved.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
==============================================================================
"""

import builtins as _builtins
import sys
import typing as _typing

from google.protobuf import descriptor as _descriptor, message as _message
from tensorflow.core.protobuf import (
    cluster_pb2 as _cluster_pb2,
    config_pb2 as _config_pb2,
    device_filters_pb2 as _device_filters_pb2,
)

if sys.version_info >= (3, 11):
    from typing import Never as _Never, TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias
    from typing_extensions import Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ServerDef(_message.Message):
    """Defines the configuration of a single TensorFlow server."""

    DESCRIPTOR: _descriptor.Descriptor

    CLUSTER_FIELD_NUMBER: _builtins.int
    JOB_NAME_FIELD_NUMBER: _builtins.int
    REPLICA_FIELD_NUMBER: _builtins.int
    TASK_INDEX_FIELD_NUMBER: _builtins.int
    DEFAULT_SESSION_CONFIG_FIELD_NUMBER: _builtins.int
    PROTOCOL_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    CLUSTER_DEVICE_FILTERS_FIELD_NUMBER: _builtins.int
    job_name: _builtins.str
    """The name of the job of which this server is a member.

    NOTE(mrry): The `cluster` field must contain a `JobDef` with a `name` field
    that matches this name.
    """
    replica: _builtins.int
    """Replica this server manages."""
    task_index: _builtins.int
    """The task index of this server in its job.

    NOTE: The `cluster` field must contain a `JobDef` with a matching `name`
    and a mapping in its `tasks` field for this index.
    """
    protocol: _builtins.str
    """The protocol to be used by this server.

    Acceptable values include: "grpc", "grpc+verbs".
    """
    port: _builtins.int
    """The server port. If not set, then we identify the port from the job_name."""
    @_builtins.property
    def cluster(self) -> _cluster_pb2.ClusterDef:
        """The cluster of which this server is a member."""

    @_builtins.property
    def default_session_config(self) -> _config_pb2.ConfigProto:
        """The default configuration for sessions that run on this server."""

    @_builtins.property
    def cluster_device_filters(self) -> _device_filters_pb2.ClusterDeviceFilters:
        """Device filters for remote tasks in the cluster.
        NOTE: This is an experimental feature and only effective in TensorFlow 2.x.
        """

    def __init__(
        self,
        *,
        cluster: _cluster_pb2.ClusterDef | None = ...,
        job_name: _builtins.str | None = ...,
        replica: _builtins.int | None = ...,
        task_index: _builtins.int | None = ...,
        default_session_config: _config_pb2.ConfigProto | None = ...,
        protocol: _builtins.str | None = ...,
        port: _builtins.int | None = ...,
        cluster_device_filters: _device_filters_pb2.ClusterDeviceFilters | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "cluster",
        b"cluster",
        "cluster_device_filters",
        b"cluster_device_filters",
        "default_session_config",
        b"default_session_config",
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "cluster",
        b"cluster",
        "cluster_device_filters",
        b"cluster_device_filters",
        "default_session_config",
        b"default_session_config",
        "job_name",
        b"job_name",
        "port",
        b"port",
        "protocol",
        b"protocol",
        "replica",
        b"replica",
        "task_index",
        b"task_index",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ServerDef: _TypeAlias = ServerDef  # noqa: Y015
