"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing
from collections import abc as _abc

from google.protobuf import descriptor as _descriptor, message as _message, wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers

if sys.version_info >= (3, 11):
    from typing import Never as _Never, TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias
    from typing_extensions import Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class TrackableObjectGraph(_message.Message):
    """A TensorBundle addition which saves extra information about the objects which
    own variables, allowing for more robust checkpoint loading into modified
    programs.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class TrackableObject(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        @_typing.final
        class ObjectReference(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            NODE_ID_FIELD_NUMBER: _builtins.int
            LOCAL_NAME_FIELD_NUMBER: _builtins.int
            node_id: _builtins.int
            """An index into `TrackableObjectGraph.nodes`, indicating the object
            being referenced.
            """
            local_name: _builtins.str
            """A user-provided name for the edge."""
            def __init__(self, *, node_id: _builtins.int | None = ..., local_name: _builtins.str | None = ...) -> None: ...
            _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal["local_name", b"local_name", "node_id", b"node_id"]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        @_typing.final
        class SerializedTensor(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            NAME_FIELD_NUMBER: _builtins.int
            FULL_NAME_FIELD_NUMBER: _builtins.int
            CHECKPOINT_KEY_FIELD_NUMBER: _builtins.int
            name: _builtins.str
            """A name for the Tensor. Simple variables have only one
            `SerializedTensor` named "VARIABLE_VALUE" by convention. This value may
            be restored on object creation as an optimization.
            """
            full_name: _builtins.str
            """The full name of the variable/tensor, if applicable. Used to allow
            name-based loading of checkpoints which were saved using an
            object-based API. Should match the checkpoint key which would have been
            assigned by tf.train.Saver.
            """
            checkpoint_key: _builtins.str
            """The generated name of the Tensor in the checkpoint."""
            def __init__(
                self,
                *,
                name: _builtins.str | None = ...,
                full_name: _builtins.str | None = ...,
                checkpoint_key: _builtins.str | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal[
                "checkpoint_key", b"checkpoint_key", "full_name", b"full_name", "name", b"name"
            ]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        @_typing.final
        class SlotVariableReference(_message.Message):
            DESCRIPTOR: _descriptor.Descriptor

            ORIGINAL_VARIABLE_NODE_ID_FIELD_NUMBER: _builtins.int
            SLOT_NAME_FIELD_NUMBER: _builtins.int
            SLOT_VARIABLE_NODE_ID_FIELD_NUMBER: _builtins.int
            original_variable_node_id: _builtins.int
            """An index into `TrackableObjectGraph.nodes`, indicating the
            variable object this slot was created for.
            """
            slot_name: _builtins.str
            """The name of the slot (e.g. "m"/"v")."""
            slot_variable_node_id: _builtins.int
            """An index into `TrackableObjectGraph.nodes`, indicating the
            `Object` with the value of the slot variable.
            """
            def __init__(
                self,
                *,
                original_variable_node_id: _builtins.int | None = ...,
                slot_name: _builtins.str | None = ...,
                slot_variable_node_id: _builtins.int | None = ...,
            ) -> None: ...
            _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
            def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
            _ClearFieldArgType: _TypeAlias = _typing.Literal[
                "original_variable_node_id",
                b"original_variable_node_id",
                "slot_name",
                b"slot_name",
                "slot_variable_node_id",
                b"slot_variable_node_id",
            ]  # noqa: Y015
            def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
            def WhichOneof(self, oneof_group: _Never) -> None: ...

        CHILDREN_FIELD_NUMBER: _builtins.int
        ATTRIBUTES_FIELD_NUMBER: _builtins.int
        SLOT_VARIABLES_FIELD_NUMBER: _builtins.int
        REGISTERED_SAVER_FIELD_NUMBER: _builtins.int
        HAS_CHECKPOINT_VALUES_FIELD_NUMBER: _builtins.int
        @_builtins.property
        def children(
            self,
        ) -> _containers.RepeatedCompositeFieldContainer[Global___TrackableObjectGraph.TrackableObject.ObjectReference]:
            """Objects which this object depends on."""

        @_builtins.property
        def attributes(
            self,
        ) -> _containers.RepeatedCompositeFieldContainer[Global___TrackableObjectGraph.TrackableObject.SerializedTensor]:
            """Serialized data specific to this object."""

        @_builtins.property
        def slot_variables(
            self,
        ) -> _containers.RepeatedCompositeFieldContainer[Global___TrackableObjectGraph.TrackableObject.SlotVariableReference]:
            """Slot variables owned by this object."""

        @_builtins.property
        def registered_saver(self) -> Global___RegisteredSaver:
            """The registered saver used to save this object. If this saver is not
            present when loading the checkpoint, then loading will fail.
            """

        @_builtins.property
        def has_checkpoint_values(self) -> _wrappers_pb2.BoolValue:
            """Whether this object has checkpoint values or descendants with checkpoint
            values. This is computed at save time to avoid traversing the entire
            object graph proto when restoring (which also has to traverse the live
            object graph).
            """

        def __init__(
            self,
            *,
            children: _abc.Iterable[Global___TrackableObjectGraph.TrackableObject.ObjectReference] | None = ...,
            attributes: _abc.Iterable[Global___TrackableObjectGraph.TrackableObject.SerializedTensor] | None = ...,
            slot_variables: _abc.Iterable[Global___TrackableObjectGraph.TrackableObject.SlotVariableReference] | None = ...,
            registered_saver: Global___RegisteredSaver | None = ...,
            has_checkpoint_values: _wrappers_pb2.BoolValue | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal[
            "has_checkpoint_values", b"has_checkpoint_values", "registered_saver", b"registered_saver"
        ]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal[
            "attributes",
            b"attributes",
            "children",
            b"children",
            "has_checkpoint_values",
            b"has_checkpoint_values",
            "registered_saver",
            b"registered_saver",
            "slot_variables",
            b"slot_variables",
        ]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    NODES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def nodes(self) -> _containers.RepeatedCompositeFieldContainer[Global___TrackableObjectGraph.TrackableObject]: ...
    def __init__(self, *, nodes: _abc.Iterable[Global___TrackableObjectGraph.TrackableObject] | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["nodes", b"nodes"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TrackableObjectGraph: _TypeAlias = TrackableObjectGraph  # noqa: Y015

@_typing.final
class RegisteredSaver(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    OBJECT_NAME_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    """The name of the registered saver/restore function."""
    object_name: _builtins.str
    """Unique auto-generated name of the object."""
    def __init__(self, *, name: _builtins.str | None = ..., object_name: _builtins.str | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "object_name", b"object_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RegisteredSaver: _TypeAlias = RegisteredSaver  # noqa: Y015
