"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing

from google.protobuf import descriptor as _descriptor, message as _message
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper

if sys.version_info >= (3, 11):
    from typing import Never as _Never, TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias
    from typing_extensions import Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class VerifierConfig(_message.Message):
    """The config for graph verifiers."""

    DESCRIPTOR: _descriptor.Descriptor

    class _Toggle:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ToggleEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[VerifierConfig._Toggle.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        DEFAULT: VerifierConfig._Toggle.ValueType  # 0
        ON: VerifierConfig._Toggle.ValueType  # 1
        OFF: VerifierConfig._Toggle.ValueType  # 2

    class Toggle(_Toggle, metaclass=_ToggleEnumTypeWrapper): ...
    DEFAULT: VerifierConfig.Toggle.ValueType  # 0
    ON: VerifierConfig.Toggle.ValueType  # 1
    OFF: VerifierConfig.Toggle.ValueType  # 2

    VERIFICATION_TIMEOUT_IN_MS_FIELD_NUMBER: _builtins.int
    STRUCTURE_VERIFIER_FIELD_NUMBER: _builtins.int
    verification_timeout_in_ms: _builtins.int
    """Deadline for completion of all verification i.e. all the Toggle ON
    verifiers must complete execution within this time.
    """
    structure_verifier: Global___VerifierConfig.Toggle.ValueType
    """Perform structural validation on a tensorflow graph. Default is OFF."""
    def __init__(
        self,
        *,
        verification_timeout_in_ms: _builtins.int | None = ...,
        structure_verifier: Global___VerifierConfig.Toggle.ValueType | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "structure_verifier", b"structure_verifier", "verification_timeout_in_ms", b"verification_timeout_in_ms"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VerifierConfig: _TypeAlias = VerifierConfig  # noqa: Y015
