from _typeshed import Incomplete

class Reporter:
    def flush(self, metrics) -> None: ...

class HttpReporter(Reporter):
    compress_payload: Incomplete
    def __init__(self, compress_payload: bool = False) -> None: ...
    def flush_distributions(self, distributions) -> None: ...
    def flush_metrics(self, metrics) -> None: ...
    def flush_events(self, events) -> None: ...

class GraphiteReporter(Reporter):
    def flush(self, metrics) -> None: ...
