from typing import Any

from dateparser.conf import apply_settings
from dateparser.search.detection import BaseLanguageDetector
from dateparser.utils import normalize_unicode

class FullTextLanguageDetector(BaseLanguageDetector):
    languages: Any = ...
    language_unique_chars: Any = ...
    language_chars: Any = ...
    def __init__(self, languages: Any) -> None: ...
    def get_unique_characters(self, settings: Any) -> None: ...
    def character_check(self, date_string: Any, settings: Any) -> None: ...
