from _typeshed import Incomplete

import jupyter_rfb

__all__ = ["GraphicsLayoutWidget", "PlotWidget"]

class GraphicsView(jupyter_rfb.RemoteFrameBuffer):
    gfxView: Incomplete
    logical_size: Incomplete
    pixel_ratio: float
    def __init__(self, **kwds) -> None: ...
    def get_frame(self): ...
    def handle_event(self, event) -> None: ...

class GraphicsLayoutWidget(GraphicsView):
    gfxLayout: Incomplete
    def __init__(self, **kwds) -> None: ...
    def addPlot(self, *args, **kwds): ...
    def addViewBox(self, *args, **kwds): ...

class PlotWidget(GraphicsView):
    plotItem: Incomplete
    def __init__(self, **kwds) -> None: ...
    def getPlotItem(self): ...
    def __getattr__(self, attr): ...
