from typing import Any

from google.cloud import environment_vars as environment_vars
from google.cloud.datastore import Key as Key, helpers as helpers
from google.cloud.datastore_v1.proto import datastore_pb2 as datastore_pb2, entity_pb2 as entity_pb2, query_pb2 as query_pb2

class QueryIterator:
    def __iter__(self): ...
    def has_next(self) -> None: ...
    def has_next_async(self) -> None: ...
    def probably_has_next(self) -> None: ...
    def next(self) -> None: ...
    def cursor_before(self) -> None: ...
    def cursor_after(self) -> None: ...
    def index_list(self) -> None: ...

class Cursor:
    @classmethod
    def from_websafe_string(cls, urlsafe): ...
    cursor: Any
    def __init__(self, cursor: Any | None = ..., urlsafe: Any | None = ...) -> None: ...
    def to_websafe_string(self): ...
    def urlsafe(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __hash__(self): ...
