from _typeshed import Incomplete

from ...Qt import QtWidgets

translate: Incomplete

class ViewBoxMenu(QtWidgets.QMenu):
    view: Incomplete
    valid: bool
    viewMap: Incomplete
    viewAll: Incomplete
    ctrl: Incomplete
    widgetGroups: Incomplete
    dv: Incomplete
    mouseModes: Incomplete
    def __init__(self, view) -> None: ...
    def viewStateChanged(self) -> None: ...
    def updateState(self) -> None: ...
    def popup(self, *args) -> None: ...
    def autoRange(self) -> None: ...
    def xMouseToggled(self, b) -> None: ...
    def xManualClicked(self) -> None: ...
    def xRangeTextChanged(self) -> None: ...
    def xAutoClicked(self) -> None: ...
    def xAutoSpinChanged(self, val) -> None: ...
    def xLinkComboChanged(self, ind) -> None: ...
    def xAutoPanToggled(self, b) -> None: ...
    def xVisibleOnlyToggled(self, b) -> None: ...
    def yMouseToggled(self, b) -> None: ...
    def yManualClicked(self) -> None: ...
    def yRangeTextChanged(self) -> None: ...
    def yAutoClicked(self) -> None: ...
    def yAutoSpinChanged(self, val) -> None: ...
    def yLinkComboChanged(self, ind) -> None: ...
    def yAutoPanToggled(self, b) -> None: ...
    def yVisibleOnlyToggled(self, b) -> None: ...
    def yInvertToggled(self, b) -> None: ...
    def xInvertToggled(self, b) -> None: ...
    def setMouseMode(self, action) -> None: ...
    def setViewList(self, views) -> None: ...
