from _typeshed import Incomplete

__version__: str
CANNOT_START_LINE: Incomplete
ALL_CANNOT_START: Incomplete
CANNOT_END_LINE: Incomplete
ALL_CANNOT_END: Incomplete

def is_multi_byte(ch): ...
def getCharWidths(word, fontName, fontSize): ...
def wordSplit(word, maxWidths, fontName, fontSize, encoding: str = "utf8"): ...
def dumbSplit(word, widths, maxWidths): ...
def kinsokuShoriSplit(word, widths, availWidth) -> None: ...

rx: Incomplete

def cjkwrap(text, width, encoding: str = "utf8"): ...
