version = "2.0.*"
extra_description = """\
  Type hints for uWSGI's \
  [Python API](https://uwsgi-docs.readthedocs.io/en/latest/PythonModule.html). \
  Note that this API is available only when running python code inside a uWSGI process \
  and some parts of the API are only present when corresponding configuration options \
  have been enabled.
"""
