from _typeshed import Incomplete

from .GraphicsObject import GraphicsObject

__all__ = ["IsocurveItem"]

class IsocurveItem(GraphicsObject):
    level: Incomplete
    data: Incomplete
    path: Incomplete
    axisOrder: Incomplete
    def __init__(self, data=None, level: int = 0, pen: str = "w", axisOrder=None) -> None: ...
    def setData(self, data, level=None) -> None: ...
    def setLevel(self, level) -> None: ...
    pen: Incomplete
    def setPen(self, *args, **kwargs) -> None: ...
    brush: Incomplete
    def setBrush(self, *args, **kwargs) -> None: ...
    def updateLines(self, data, level) -> None: ...
    def boundingRect(self): ...
    def generatePath(self) -> None: ...
    def paint(self, p, *args) -> None: ...
