from _typeshed import Incomplete

from .. import debug
from .GraphicsObject import GraphicsObject

__all__ = ["ScatterPlotItem", "SpotItem"]

class SymbolAtlas:
    def __init__(self) -> None: ...
    def __getitem__(self, styles): ...
    def __len__(self) -> int: ...
    def devicePixelRatio(self): ...
    def setDevicePixelRatio(self, dpr) -> None: ...
    @property
    def pixmap(self): ...
    @property
    def maxWidth(self): ...
    def rebuild(self, styles=None) -> None: ...
    def clear(self) -> None: ...
    def diagnostics(self): ...

class ScatterPlotItem(GraphicsObject):
    sigClicked: Incomplete
    sigHovered: Incomplete
    sigPlotChanged: Incomplete
    picture: Incomplete
    fragmentAtlas: Incomplete
    data: Incomplete
    bounds: Incomplete
    opts: Incomplete
    def __init__(self, *args, **kargs) -> None: ...
    def setData(self, *args, **kargs) -> None: ...
    def addPoints(self, *args, **kargs) -> None: ...
    def invalidate(self) -> None: ...
    def getData(self): ...
    def implements(self, interface=None): ...
    def name(self): ...
    def setPen(self, *args, **kargs) -> None: ...
    def setBrush(self, *args, **kargs) -> None: ...
    def setSymbol(self, symbol, update: bool = True, dataSet=None, mask=None) -> None: ...
    def setSize(self, size, update: bool = True, dataSet=None, mask=None) -> None: ...
    def setPointsVisible(self, visible, update: bool = True, dataSet=None, mask=None) -> None: ...
    def setPointData(self, data, dataSet=None, mask=None) -> None: ...
    def setPxMode(self, mode) -> None: ...
    def updateSpots(self, dataSet=None) -> None: ...
    def clear(self) -> None: ...
    def dataBounds(self, ax, frac: float = 1.0, orthoRange=None): ...
    def pixelPadding(self): ...
    def boundingRect(self): ...
    def viewTransformChanged(self) -> None: ...
    def setExportMode(self, *args, **kwds) -> None: ...
    @debug.warnOnException
    def paint(self, p, option, widget) -> None: ...
    def points(self): ...
    def pointsAt(self, pos): ...
    ptsClicked: Incomplete
    def mouseClickEvent(self, ev) -> None: ...
    def hoverEvent(self, ev) -> None: ...

class SpotItem:
    def __init__(self, data, plot, index) -> None: ...
    def data(self): ...
    def index(self): ...
    def size(self): ...
    def pos(self): ...
    def viewPos(self): ...
    def setSize(self, size) -> None: ...
    def symbol(self): ...
    def setSymbol(self, symbol) -> None: ...
    def pen(self): ...
    def setPen(self, *args, **kargs) -> None: ...
    def resetPen(self) -> None: ...
    def brush(self): ...
    def setBrush(self, *args, **kargs) -> None: ...
    def resetBrush(self) -> None: ...
    def isVisible(self): ...
    def setVisible(self, visible) -> None: ...
    def setData(self, data) -> None: ...
    def updateItem(self) -> None: ...
