from _typeshed import Incomplete

from .UIGraphicsItem import UIGraphicsItem

__all__ = ["VTickGroup"]

class VTickGroup(UIGraphicsItem):
    path: Incomplete
    ticks: Incomplete
    xvals: Incomplete
    yrange: Incomplete
    def __init__(self, xvals=None, yrange=None, pen=None) -> None: ...
    pen: Incomplete
    def setPen(self, *args, **kwargs) -> None: ...
    def setXVals(self, vals) -> None: ...
    def setYRange(self, vals) -> None: ...
    def dataBounds(self, *args, **kargs) -> None: ...
    def yRange(self): ...
    def rebuildTicks(self) -> None: ...
    def paint(self, p, *args) -> None: ...
