from _typeshed import StrOrBytesPath, structseq
from collections.abc import Callable, Sequence
from typing import Final, Self, TypeAlias, final

_Location: TypeAlias = int | LocationInfo | None
_Frame: TypeAlias = tuple[str, _Location, str, int | None] | FrameInfo
_StackFrames: TypeAlias = Sequence[InterpreterInfo]
_Stats: TypeAlias = dict[str, int | float]

PROCESS_VM_READV_SUPPORTED: Final[int]
THREAD_STATUS_GIL_REQUESTED: Final[int]
THREAD_STATUS_HAS_EXCEPTION: Final[int]
THREAD_STATUS_HAS_GIL: Final[int]
THREAD_STATUS_MAIN_THREAD: Final[int]
THREAD_STATUS_ON_CPU: Final[int]
THREAD_STATUS_UNKNOWN: Final[int]

@final
class LocationInfo(structseq[int], tuple[int, int, int, int]):
    @property
    def lineno(self) -> int: ...
    @property
    def end_lineno(self) -> int: ...
    @property
    def col_offset(self) -> int: ...
    @property
    def end_col_offset(self) -> int: ...

@final
class FrameInfo(structseq[object], tuple[str, _Location, str, int | None]):
    @property
    def filename(self) -> str: ...
    @property
    def location(self) -> _Location: ...
    @property
    def funcname(self) -> str: ...
    @property
    def opcode(self) -> int | None: ...

@final
class CoroInfo(structseq[object], tuple[list[_Frame], int | str]):
    @property
    def call_stack(self) -> list[_Frame]: ...
    @property
    def task_name(self) -> int | str: ...

@final
class TaskInfo(structseq[object], tuple[int, str, list[CoroInfo], list[CoroInfo]]):
    @property
    def task_id(self) -> int: ...
    @property
    def task_name(self) -> str: ...
    @property
    def coroutine_stack(self) -> list[CoroInfo]: ...
    @property
    def awaited_by(self) -> list[CoroInfo]: ...

@final
class ThreadInfo(structseq[object], tuple[int, int, list[_Frame]]):
    @property
    def thread_id(self) -> int: ...
    @property
    def status(self) -> int: ...
    @property
    def frame_info(self) -> list[_Frame]: ...

@final
class InterpreterInfo(structseq[object], tuple[int, list[ThreadInfo]]):
    @property
    def interpreter_id(self) -> int: ...
    @property
    def threads(self) -> list[ThreadInfo]: ...

@final
class AwaitedInfo(structseq[object], tuple[int, list[TaskInfo]]):
    @property
    def thread_id(self) -> int: ...
    @property
    def awaited_by(self) -> list[TaskInfo]: ...

@final
class GCStatsInfo(structseq[object], tuple[int, int, int, int, int, int, int, int, int, float]):
    @property
    def gen(self) -> int: ...
    @property
    def iid(self) -> int: ...
    @property
    def ts_start(self) -> int: ...
    @property
    def ts_stop(self) -> int: ...
    @property
    def collections(self) -> int: ...
    @property
    def collected(self) -> int: ...
    @property
    def uncollectable(self) -> int: ...
    @property
    def candidates(self) -> int: ...
    @property
    def heap_size(self) -> int: ...
    @property
    def duration(self) -> float: ...

class RemoteUnwinder:
    def __init__(
        self,
        pid: int,
        *,
        all_threads: bool = False,
        only_active_thread: bool = False,
        mode: int = 0,
        debug: bool = False,
        skip_non_matching_threads: bool = True,
        native: bool = False,
        gc: bool = False,
    ) -> None: ...
    def get_stack_trace(self) -> list[InterpreterInfo]: ...
    def get_all_awaited_by(self) -> list[AwaitedInfo]: ...
    def get_async_stack_trace(self) -> list[AwaitedInfo]: ...
    def get_stats(self) -> _Stats: ...
    def pause_threads(self) -> bool: ...
    def resume_threads(self) -> bool: ...

class GCMonitor:
    def __init__(self, pid: int, *, debug: bool = False) -> None: ...
    def get_gc_stats(self, all_interpreters: bool = False) -> list[GCStatsInfo]: ...

class BinaryWriter:
    total_samples: int
    def __init__(
        self, filename: StrOrBytesPath, sample_interval_us: int, start_time_us: int, *, compression: int = 0
    ) -> None: ...
    def write_sample(self, stack_frames: _StackFrames, timestamp_us: int) -> None: ...
    def finalize(self) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: object = None, exc_val: object = None, exc_tb: object = None) -> bool: ...
    def get_stats(self) -> _Stats: ...

class BinaryReader:
    sample_count: int
    sample_interval_us: int
    def __init__(self, filename: StrOrBytesPath) -> None: ...
    def replay(self, collector: object, progress_callback: Callable[[int, int], object] | None = None) -> int: ...
    def get_info(self) -> dict[str, object]: ...
    def get_stats(self) -> _Stats: ...
    def close(self) -> None: ...
    def __enter__(self) -> Self: ...
    def __exit__(self, exc_type: object = None, exc_val: object = None, exc_tb: object = None) -> bool: ...

def zstd_available() -> bool: ...
def get_child_pids(pid: int, *, recursive: bool = True) -> list[int]: ...
def is_python_process(pid: int) -> bool: ...
def get_gc_stats(pid: int, *, all_interpreters: bool = False) -> list[GCStatsInfo]: ...
