from typing import Any, Callable, TypeVar

_C = TypeVar("_C", bound=Callable[..., Any])

def _clear() -> None: ...
def _ncallbacks() -> int: ...
def _run_exitfuncs() -> None: ...
def register(func: Callable[_P, _T], *args: _P.args, **kwargs: _P.kwargs) -> Callable[_P, _T]: ...
def unregister(func: Callable[..., Any]) -> None: ...
