from typing import Any, Callable, TypeVar

_C = TypeVar("_C", bound=Callable[..., Any])

def _clear() -> None: ...
def _ncallbacks() -> int: ...
def _run_exitfuncs() -> None: ...
def register(func: _C, *args: Any, **kwargs: Any) -> _C: ...
def unregister(func: Callable[..., Any]) -> None: ...
