from collections.abc import Iterable
from pathlib import Path
from typing import AnyStr, Union

__all__ = ["filter", "fnmatch", "fnmatchcase", "translate"]

def fnmatch(name: Union[AnyStr, Path], pat: AnyStr) -> bool: ...
def fnmatchcase(name: Union[AnyStr, Path], pat: AnyStr) -> bool: ...
def filter(names: Iterable[Union[AnyStr, Path]], pat: AnyStr) -> list[AnyStr]: ...
def translate(pat: str) -> str: ...
