"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Protocol messages for describing the configuration of the ExampleParserOp."""

import builtins as _builtins
import sys
import typing as _typing
from collections import abc as _abc

from google.protobuf import descriptor as _descriptor, message as _message
from google.protobuf.internal import containers as _containers
from tensorflow.core.framework import tensor_pb2 as _tensor_pb2, tensor_shape_pb2 as _tensor_shape_pb2, types_pb2 as _types_pb2

if sys.version_info >= (3, 11):
    from typing import Never as _Never, TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias
    from typing_extensions import Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class VarLenFeatureProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DTYPE_FIELD_NUMBER: _builtins.int
    VALUES_OUTPUT_TENSOR_NAME_FIELD_NUMBER: _builtins.int
    INDICES_OUTPUT_TENSOR_NAME_FIELD_NUMBER: _builtins.int
    SHAPES_OUTPUT_TENSOR_NAME_FIELD_NUMBER: _builtins.int
    dtype: _types_pb2.DataType.ValueType
    values_output_tensor_name: _builtins.str
    indices_output_tensor_name: _builtins.str
    shapes_output_tensor_name: _builtins.str
    def __init__(
        self,
        *,
        dtype: _types_pb2.DataType.ValueType | None = ...,
        values_output_tensor_name: _builtins.str | None = ...,
        indices_output_tensor_name: _builtins.str | None = ...,
        shapes_output_tensor_name: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "dtype",
        b"dtype",
        "indices_output_tensor_name",
        b"indices_output_tensor_name",
        "shapes_output_tensor_name",
        b"shapes_output_tensor_name",
        "values_output_tensor_name",
        b"values_output_tensor_name",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VarLenFeatureProto: _TypeAlias = VarLenFeatureProto  # noqa: Y015

@_typing.final
class FixedLenFeatureProto(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DTYPE_FIELD_NUMBER: _builtins.int
    SHAPE_FIELD_NUMBER: _builtins.int
    DEFAULT_VALUE_FIELD_NUMBER: _builtins.int
    VALUES_OUTPUT_TENSOR_NAME_FIELD_NUMBER: _builtins.int
    dtype: _types_pb2.DataType.ValueType
    values_output_tensor_name: _builtins.str
    @_builtins.property
    def shape(self) -> _tensor_shape_pb2.TensorShapeProto: ...
    @_builtins.property
    def default_value(self) -> _tensor_pb2.TensorProto: ...
    def __init__(
        self,
        *,
        dtype: _types_pb2.DataType.ValueType | None = ...,
        shape: _tensor_shape_pb2.TensorShapeProto | None = ...,
        default_value: _tensor_pb2.TensorProto | None = ...,
        values_output_tensor_name: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["default_value", b"default_value", "shape", b"shape"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "default_value",
        b"default_value",
        "dtype",
        b"dtype",
        "shape",
        b"shape",
        "values_output_tensor_name",
        b"values_output_tensor_name",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___FixedLenFeatureProto: _TypeAlias = FixedLenFeatureProto  # noqa: Y015

@_typing.final
class FeatureConfiguration(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    FIXED_LEN_FEATURE_FIELD_NUMBER: _builtins.int
    VAR_LEN_FEATURE_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def fixed_len_feature(self) -> Global___FixedLenFeatureProto: ...
    @_builtins.property
    def var_len_feature(self) -> Global___VarLenFeatureProto: ...
    def __init__(
        self,
        *,
        fixed_len_feature: Global___FixedLenFeatureProto | None = ...,
        var_len_feature: Global___VarLenFeatureProto | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "config", b"config", "fixed_len_feature", b"fixed_len_feature", "var_len_feature", b"var_len_feature"
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "config", b"config", "fixed_len_feature", b"fixed_len_feature", "var_len_feature", b"var_len_feature"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_config: _TypeAlias = _typing.Literal["fixed_len_feature", "var_len_feature"]  # noqa: Y015
    _WhichOneofArgType_config: _TypeAlias = _typing.Literal["config", b"config"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_config) -> _WhichOneofReturnType_config | None: ...

Global___FeatureConfiguration: _TypeAlias = FeatureConfiguration  # noqa: Y015

@_typing.final
class ExampleParserConfiguration(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class FeatureMapEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        @_builtins.property
        def value(self) -> Global___FeatureConfiguration: ...
        def __init__(self, *, key: _builtins.str | None = ..., value: Global___FeatureConfiguration | None = ...) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    FEATURE_MAP_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def feature_map(self) -> _containers.MessageMap[_builtins.str, Global___FeatureConfiguration]: ...
    def __init__(self, *, feature_map: _abc.Mapping[_builtins.str, Global___FeatureConfiguration] | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["feature_map", b"feature_map"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ExampleParserConfiguration: _TypeAlias = ExampleParserConfiguration  # noqa: Y015
