"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing

from google.protobuf import descriptor as _descriptor, message as _message

if sys.version_info >= (3, 11):
    from typing import Never as _Never, TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias
    from typing_extensions import Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class AllocationDescription(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REQUESTED_BYTES_FIELD_NUMBER: _builtins.int
    ALLOCATED_BYTES_FIELD_NUMBER: _builtins.int
    ALLOCATOR_NAME_FIELD_NUMBER: _builtins.int
    ALLOCATION_ID_FIELD_NUMBER: _builtins.int
    HAS_SINGLE_REFERENCE_FIELD_NUMBER: _builtins.int
    PTR_FIELD_NUMBER: _builtins.int
    requested_bytes: _builtins.int
    """Total number of bytes requested"""
    allocated_bytes: _builtins.int
    """Total number of bytes allocated if known"""
    allocator_name: _builtins.str
    """Name of the allocator used"""
    allocation_id: _builtins.int
    """Identifier of the allocated buffer if known"""
    has_single_reference: _builtins.bool
    """Set if this tensor only has one remaining reference"""
    ptr: _builtins.int
    """Address of the allocation."""
    def __init__(
        self,
        *,
        requested_bytes: _builtins.int | None = ...,
        allocated_bytes: _builtins.int | None = ...,
        allocator_name: _builtins.str | None = ...,
        allocation_id: _builtins.int | None = ...,
        has_single_reference: _builtins.bool | None = ...,
        ptr: _builtins.int | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "allocated_bytes",
        b"allocated_bytes",
        "allocation_id",
        b"allocation_id",
        "allocator_name",
        b"allocator_name",
        "has_single_reference",
        b"has_single_reference",
        "ptr",
        b"ptr",
        "requested_bytes",
        b"requested_bytes",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AllocationDescription: _TypeAlias = AllocationDescription  # noqa: Y015
