"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing
from collections import abc as _abc

from google.protobuf import descriptor as _descriptor, message as _message
from google.protobuf.internal import containers as _containers
from tensorflow.core.framework import (
    full_type_pb2 as _full_type_pb2,
    tensor_shape_pb2 as _tensor_shape_pb2,
    types_pb2 as _types_pb2,
)

if sys.version_info >= (3, 11):
    from typing import Never as _Never, TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias
    from typing_extensions import Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CppShapeInferenceResult(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class HandleShapeAndType(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        SHAPE_FIELD_NUMBER: _builtins.int
        DTYPE_FIELD_NUMBER: _builtins.int
        TYPE_FIELD_NUMBER: _builtins.int
        dtype: _types_pb2.DataType.ValueType
        @_builtins.property
        def shape(self) -> _tensor_shape_pb2.TensorShapeProto: ...
        @_builtins.property
        def type(self) -> _full_type_pb2.FullTypeDef: ...
        def __init__(
            self,
            *,
            shape: _tensor_shape_pb2.TensorShapeProto | None = ...,
            dtype: _types_pb2.DataType.ValueType | None = ...,
            type: _full_type_pb2.FullTypeDef | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["shape", b"shape", "type", b"type"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["dtype", b"dtype", "shape", b"shape", "type", b"type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class HandleData(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        IS_SET_FIELD_NUMBER: _builtins.int
        SHAPE_AND_TYPE_FIELD_NUMBER: _builtins.int
        is_set: _builtins.bool
        @_builtins.property
        def shape_and_type(
            self,
        ) -> _containers.RepeatedCompositeFieldContainer[Global___CppShapeInferenceResult.HandleShapeAndType]:
            """Only valid if <is_set>."""

        def __init__(
            self,
            *,
            is_set: _builtins.bool | None = ...,
            shape_and_type: _abc.Iterable[Global___CppShapeInferenceResult.HandleShapeAndType] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["is_set", b"is_set", "shape_and_type", b"shape_and_type"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    SHAPE_FIELD_NUMBER: _builtins.int
    HANDLE_DATA_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def shape(self) -> _tensor_shape_pb2.TensorShapeProto: ...
    @_builtins.property
    def handle_data(self) -> Global___CppShapeInferenceResult.HandleData: ...
    def __init__(
        self,
        *,
        shape: _tensor_shape_pb2.TensorShapeProto | None = ...,
        handle_data: Global___CppShapeInferenceResult.HandleData | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["handle_data", b"handle_data", "shape", b"shape"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["handle_data", b"handle_data", "shape", b"shape"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CppShapeInferenceResult: _TypeAlias = CppShapeInferenceResult  # noqa: Y015

@_typing.final
class CppShapeInferenceInputsNeeded(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INPUT_TENSORS_NEEDED_FIELD_NUMBER: _builtins.int
    INPUT_TENSORS_AS_SHAPES_NEEDED_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def input_tensors_needed(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    @_builtins.property
    def input_tensors_as_shapes_needed(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]: ...
    def __init__(
        self,
        *,
        input_tensors_needed: _abc.Iterable[_builtins.int] | None = ...,
        input_tensors_as_shapes_needed: _abc.Iterable[_builtins.int] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "input_tensors_as_shapes_needed", b"input_tensors_as_shapes_needed", "input_tensors_needed", b"input_tensors_needed"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CppShapeInferenceInputsNeeded: _TypeAlias = CppShapeInferenceInputsNeeded  # noqa: Y015
