"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing

from google.protobuf import descriptor as _descriptor, message as _message

if sys.version_info >= (3, 11):
    from typing import Never as _Never, TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias
    from typing_extensions import Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ReaderBaseState(_message.Message):
    """For serializing and restoring the state of ReaderBase, see
    reader_base.h for details.
    """

    DESCRIPTOR: _descriptor.Descriptor

    WORK_STARTED_FIELD_NUMBER: _builtins.int
    WORK_FINISHED_FIELD_NUMBER: _builtins.int
    NUM_RECORDS_PRODUCED_FIELD_NUMBER: _builtins.int
    CURRENT_WORK_FIELD_NUMBER: _builtins.int
    work_started: _builtins.int
    work_finished: _builtins.int
    num_records_produced: _builtins.int
    current_work: _builtins.bytes
    def __init__(
        self,
        *,
        work_started: _builtins.int | None = ...,
        work_finished: _builtins.int | None = ...,
        num_records_produced: _builtins.int | None = ...,
        current_work: _builtins.bytes | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "current_work",
        b"current_work",
        "num_records_produced",
        b"num_records_produced",
        "work_finished",
        b"work_finished",
        "work_started",
        b"work_started",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReaderBaseState: _TypeAlias = ReaderBaseState  # noqa: Y015
