"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing
from collections import abc as _abc

from google.protobuf import descriptor as _descriptor, message as _message
from google.protobuf.internal import containers as _containers
from tensorflow.core.framework import tensor_shape_pb2 as _tensor_shape_pb2, types_pb2 as _types_pb2

if sys.version_info >= (3, 11):
    from typing import Never as _Never, TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias
    from typing_extensions import Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ResourceHandleProto(_message.Message):
    """Protocol buffer representing a handle to a tensorflow resource. Handles are
    not valid across executions, but can be serialized back and forth from within
    a single run.
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class DtypeAndShape(_message.Message):
        """Protocol buffer representing a pair of (data type, tensor shape)."""

        DESCRIPTOR: _descriptor.Descriptor

        DTYPE_FIELD_NUMBER: _builtins.int
        SHAPE_FIELD_NUMBER: _builtins.int
        dtype: _types_pb2.DataType.ValueType
        """Data type of the tensor."""
        @_builtins.property
        def shape(self) -> _tensor_shape_pb2.TensorShapeProto:
            """Shape of the tensor."""

        def __init__(
            self, *, dtype: _types_pb2.DataType.ValueType | None = ..., shape: _tensor_shape_pb2.TensorShapeProto | None = ...
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["shape", b"shape"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["dtype", b"dtype", "shape", b"shape"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    DEVICE_FIELD_NUMBER: _builtins.int
    CONTAINER_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    HASH_CODE_FIELD_NUMBER: _builtins.int
    MAYBE_TYPE_NAME_FIELD_NUMBER: _builtins.int
    DTYPES_AND_SHAPES_FIELD_NUMBER: _builtins.int
    device: _builtins.str
    """Unique name for the device containing the resource."""
    container: _builtins.str
    """Container in which this resource is placed."""
    name: _builtins.str
    """Unique name of this resource."""
    hash_code: _builtins.int
    """Hash code for the type of the resource. Is only valid in the same device
    and in the same execution.
    """
    maybe_type_name: _builtins.str
    """For debug-only, the name of the type pointed to by this handle, if
    available.
    """
    @_builtins.property
    def dtypes_and_shapes(self) -> _containers.RepeatedCompositeFieldContainer[Global___ResourceHandleProto.DtypeAndShape]:
        """Data types and shapes for the underlying resource."""

    def __init__(
        self,
        *,
        device: _builtins.str | None = ...,
        container: _builtins.str | None = ...,
        name: _builtins.str | None = ...,
        hash_code: _builtins.int | None = ...,
        maybe_type_name: _builtins.str | None = ...,
        dtypes_and_shapes: _abc.Iterable[Global___ResourceHandleProto.DtypeAndShape] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "container",
        b"container",
        "device",
        b"device",
        "dtypes_and_shapes",
        b"dtypes_and_shapes",
        "hash_code",
        b"hash_code",
        "maybe_type_name",
        b"maybe_type_name",
        "name",
        b"name",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ResourceHandleProto: _TypeAlias = ResourceHandleProto  # noqa: Y015
