"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
Protocol buffer representing the shape of tensors."""

import builtins as _builtins
import sys
import typing as _typing
from collections import abc as _abc

from google.protobuf import descriptor as _descriptor, message as _message
from google.protobuf.internal import containers as _containers

if sys.version_info >= (3, 11):
    from typing import Never as _Never, TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias
    from typing_extensions import Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class TensorShapeProto(_message.Message):
    """Dimensions of a tensor."""

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class Dim(_message.Message):
        """One dimension of the tensor."""

        DESCRIPTOR: _descriptor.Descriptor

        SIZE_FIELD_NUMBER: _builtins.int
        NAME_FIELD_NUMBER: _builtins.int
        size: _builtins.int
        """Size of the tensor in that dimension.
        This value must be >= -1, but values of -1 are reserved for "unknown"
        shapes (values of -1 mean "unknown" dimension).  Certain wrappers
        that work with TensorShapeProto may fail at runtime when deserializing
        a TensorShapeProto containing a dim value of -1.
        """
        name: _builtins.str
        """Optional name of the tensor dimension."""
        def __init__(self, *, size: _builtins.int | None = ..., name: _builtins.str | None = ...) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name", "size", b"size"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    DIM_FIELD_NUMBER: _builtins.int
    UNKNOWN_RANK_FIELD_NUMBER: _builtins.int
    unknown_rank: _builtins.bool
    """If true, the number of dimensions in the shape is unknown.

    If true, "dim.size()" must be 0.
    """
    @_builtins.property
    def dim(self) -> _containers.RepeatedCompositeFieldContainer[Global___TensorShapeProto.Dim]:
        """Dimensions of the tensor, such as {"input", 30}, {"output", 40}
        for a 30 x 40 2D tensor.  If an entry has size -1, this
        corresponds to a dimension of unknown size. The names are
        optional.

        The order of entries in "dim" matters: It indicates the layout of the
        values in the tensor in-memory representation.

        The first entry in "dim" is the outermost dimension used to layout the
        values, the last entry is the innermost dimension.  This matches the
        in-memory layout of RowMajor Eigen tensors.

        If "dim.size()" > 0, "unknown_rank" must be false.
        """

    def __init__(
        self, *, dim: _abc.Iterable[Global___TensorShapeProto.Dim] | None = ..., unknown_rank: _builtins.bool | None = ...
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["dim", b"dim", "unknown_rank", b"unknown_rank"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TensorShapeProto: _TypeAlias = TensorShapeProto  # noqa: Y015
