def draw_page(page, stream) -> None: ...
def draw_stacking_context(stream, stacking_context) -> None: ...
def draw_background(stream, bg, clip_box: bool = True, bleed=None, marks=()) -> None: ...
def draw_background_image(stream, layer, style) -> None: ...
def draw_table(stream, table): ...
def draw_collapsed_borders(stream, table): ...
def draw_replacedbox(stream, box) -> None: ...
def draw_inline_level(
    stream, page, box, offset_x: int = 0, text_overflow: str = "clip", block_ellipsis: str = "none"
) -> None: ...
def draw_block_level(page, stream, blocks_and_cells) -> None: ...
