from _typeshed import Incomplete

SIDES: Incomplete

def set_mask_border(stream, box) -> None: ...
def draw_column_rules(stream, box) -> None: ...
def draw_border(stream, box) -> None: ...
def draw_border_image(box, stream, image, border_slice, border_repeat, border_outset, border_width): ...
def clip_border_segment(stream, style, width, side, border_box, border_widths=None, radii=None): ...
def draw_rounded_border(stream, box, style, color) -> None: ...
def draw_rect_border(stream, box, widths, style, color) -> None: ...
def draw_line(stream, x1, y1, x2, y2, thickness, style, color, offset: int = 0) -> None: ...
def draw_outline(stream, box) -> None: ...
def rounded_box(stream, radii) -> None: ...
