def draw_text(stream, textbox, offset_x, text_overflow, block_ellipsis) -> None: ...
def draw_emojis(stream, style, x, y, emojis) -> None: ...
def draw_first_line(stream, textbox, text_overflow, block_ellipsis, matrix): ...
def draw_text_decoration(stream, textbox, offset_x, offset_y, thickness, color) -> None: ...
