from ..Qt import QtWidgets

__all__ = ["ComboBox"]

class ComboBox(QtWidgets.QComboBox):
    def __init__(self, parent=None, items=None, default=None) -> None: ...
    def setValue(self, value) -> None: ...
    def setText(self, text) -> None: ...
    def value(self): ...
    def ignoreIndexChange(func): ...
    def blockIfUnchanged(func): ...
    @ignoreIndexChange
    @blockIfUnchanged
    def setItems(self, items) -> None: ...
    def items(self): ...
    def updateList(self, items): ...
    def indexChanged(self, index) -> None: ...
    def setCurrentIndex(self, index) -> None: ...
    def itemsChanged(self) -> None: ...
    @ignoreIndexChange
    def insertItem(self, *args) -> None: ...
    @ignoreIndexChange
    def insertItems(self, *args) -> None: ...
    @ignoreIndexChange
    def addItem(self, *args, **kwds) -> None: ...
    def setItemValue(self, name, value) -> None: ...
    @ignoreIndexChange
    @blockIfUnchanged
    def addItems(self, items) -> None: ...
    @ignoreIndexChange
    def clear(self) -> None: ...
    def saveState(self): ...
    def restoreState(self, v) -> None: ...
    def widgetGroupInterface(self): ...
