from _typeshed import Incomplete

from .GraphicsView import GraphicsView

__all__ = ["GraphicsLayoutWidget"]

class GraphicsLayoutWidget(GraphicsView):
    ci: Incomplete
    def __init__(self, parent=None, show: bool = False, size=None, title=None, **kargs) -> None: ...
    # Inherited from GraphicsLayout:
    def nextRow(self) -> None: ...
    def nextColumn(self) -> None: ...
    def nextCol(self, *args, **kargs): ...
    def addPlot(self, row=None, col=None, rowspan: int = 1, colspan: int = 1, **kargs): ...
    def addViewBox(self, row=None, col=None, rowspan: int = 1, colspan: int = 1, **kargs): ...
    def addLabel(self, text: str = " ", row=None, col=None, rowspan: int = 1, colspan: int = 1, **kargs): ...
    def addLayout(self, row=None, col=None, rowspan: int = 1, colspan: int = 1, **kargs): ...
    def addItem(self, item, row=None, col=None, rowspan: int = 1, colspan: int = 1) -> None: ...
    def getItem(self, row, col): ...
    def itemIndex(self, item): ...
    def removeItem(self, item) -> None: ...
    def clear(self) -> None: ...
