from _typeshed import Incomplete

from .GraphicsView import GraphicsView

__all__ = ["PlotWidget"]

class PlotWidget(GraphicsView):
    sigRangeChanged: Incomplete
    sigTransformChanged: Incomplete
    plotItem: Incomplete
    def __init__(self, parent=None, background: str = "default", plotItem=None, **kargs) -> None: ...
    def close(self) -> None: ...
    def __getattr__(self, attr): ...
    def viewRangeChanged(self, view, range) -> None: ...
    def widgetGroupInterface(self): ...
    def saveState(self): ...
    def restoreState(self, state): ...
    def getPlotItem(self): ...
