"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing
from collections import abc as _abc

from google.protobuf import descriptor as _descriptor, message as _message
from google.protobuf.internal import containers as _containers, enum_type_wrapper as _enum_type_wrapper
from tensorflow.core.protobuf.tpu import optimization_parameters_pb2 as _optimization_parameters_pb2

if sys.version_info >= (3, 11):
    from typing import Never as _Never, TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias
    from typing_extensions import Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class TPUEmbeddingConfiguration(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    class _Mode:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[TPUEmbeddingConfiguration._Mode.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNSPECIFIED: TPUEmbeddingConfiguration._Mode.ValueType  # 0
        INFERENCE: TPUEmbeddingConfiguration._Mode.ValueType  # 1
        TRAINING: TPUEmbeddingConfiguration._Mode.ValueType  # 2
        BACKWARD_PASS_ONLY: TPUEmbeddingConfiguration._Mode.ValueType  # 3

    class Mode(_Mode, metaclass=_ModeEnumTypeWrapper):
        """Mode. Should the embedding layer program be run for inference (just forward
        pass), training (both forward and backward pass) or just the backward_pass.
        """

    UNSPECIFIED: TPUEmbeddingConfiguration.Mode.ValueType  # 0
    INFERENCE: TPUEmbeddingConfiguration.Mode.ValueType  # 1
    TRAINING: TPUEmbeddingConfiguration.Mode.ValueType  # 2
    BACKWARD_PASS_ONLY: TPUEmbeddingConfiguration.Mode.ValueType  # 3

    class _ShardingStrategy:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _ShardingStrategyEnumTypeWrapper(
        _enum_type_wrapper._EnumTypeWrapper[TPUEmbeddingConfiguration._ShardingStrategy.ValueType], _builtins.type
    ):
        DESCRIPTOR: _descriptor.EnumDescriptor
        DIV_DEFAULT: TPUEmbeddingConfiguration._ShardingStrategy.ValueType  # 0
        MOD: TPUEmbeddingConfiguration._ShardingStrategy.ValueType  # 1

    class ShardingStrategy(_ShardingStrategy, metaclass=_ShardingStrategyEnumTypeWrapper):
        """Sharding strategy of the embedding tables among the hosts.
        If the sharding_strategy is "mod", each id is assigned to host
        "id % num_hosts". For instance, 13 ids are split across 5 hosts as:
        [[0, 5, 10], [1, 6, 11], [2, 7, 12], [3, 8], [4, 9]].
        If the sharding_strategy is "div", ids are assigned to hosts in a
        contiguous manner. In this case, 13 ids are split across 5 hosts as:
        [[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10], [11, 12]].
        In both the strategies, if the id space does not evenly divide the number
        of hosts, each of the first "table_descriptor.vocabulary_size % num_hosts"
        hosts will be assigned one more id.
        This partitioning strategy exactly follows that in the embedding_lookup
        TensorFlow function at tensorflow/python/ops/embedding_ops.py.
        """

    DIV_DEFAULT: TPUEmbeddingConfiguration.ShardingStrategy.ValueType  # 0
    MOD: TPUEmbeddingConfiguration.ShardingStrategy.ValueType  # 1

    @_typing.final
    class TableDescriptor(_message.Message):
        """Description of the various embedding tables."""

        DESCRIPTOR: _descriptor.Descriptor

        NAME_FIELD_NUMBER: _builtins.int
        VOCABULARY_SIZE_FIELD_NUMBER: _builtins.int
        DIMENSION_FIELD_NUMBER: _builtins.int
        NUM_FEATURES_FIELD_NUMBER: _builtins.int
        OPTIMIZATION_PARAMETERS_FIELD_NUMBER: _builtins.int
        name: _builtins.str
        """Name of the table."""
        vocabulary_size: _builtins.int
        """Size of the vocabulary (i.e., number of rows) in the table."""
        dimension: _builtins.int
        """The embedding dimension (i.e., the width of the embedding table)."""
        num_features: _builtins.int
        """Number of features mapped to this table."""
        @_builtins.property
        def optimization_parameters(self) -> _optimization_parameters_pb2.OptimizationParameters:
            """Details of the learning algorithm used to update the embedding
            parameters.
            """

        def __init__(
            self,
            *,
            name: _builtins.str | None = ...,
            vocabulary_size: _builtins.int | None = ...,
            dimension: _builtins.int | None = ...,
            num_features: _builtins.int | None = ...,
            optimization_parameters: _optimization_parameters_pb2.OptimizationParameters | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _typing.Literal["optimization_parameters", b"optimization_parameters"]  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal[
            "dimension",
            b"dimension",
            "name",
            b"name",
            "num_features",
            b"num_features",
            "optimization_parameters",
            b"optimization_parameters",
            "vocabulary_size",
            b"vocabulary_size",
        ]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class FeatureDescriptor(_message.Message):
        """Description of different input features."""

        DESCRIPTOR: _descriptor.Descriptor

        NAME_FIELD_NUMBER: _builtins.int
        TABLE_ID_FIELD_NUMBER: _builtins.int
        INPUT_SHAPE_FIELD_NUMBER: _builtins.int
        name: _builtins.str
        """Name of the input feature."""
        table_id: _builtins.int
        """Index of the corresponding table in the TableDescriptor list."""
        @_builtins.property
        def input_shape(self) -> _containers.RepeatedScalarFieldContainer[_builtins.int]:
            """Static shape of the inputs (excluding the reduction axis). Note that
            the shape of the actual inputs provided using the infeed op must be
            strictly smaller than input_shape. The outputs received at the TensorCore
            will have rank = input_shape.size() + 1. The innermost axis corresponds
            to the embedding dimension. If the input has shape [m, n, k] (excluding
            the reduction axis) and the embedding dimension is d, the output received
            at the TensorCore will have shape [m, n, k, d].
            """

        def __init__(
            self,
            *,
            name: _builtins.str | None = ...,
            table_id: _builtins.int | None = ...,
            input_shape: _abc.Iterable[_builtins.int] | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal[
            "input_shape", b"input_shape", "name", b"name", "table_id", b"table_id"
        ]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    @_typing.final
    class SpmdSharding(_message.Message):
        """SPMD (Single Program Multiple Data) sharding configuration for
        TPUEmbedding. When model parallelism is used on the TensorCore, the number
        of cores per replica must be passed to TPUEmbedding so that the right
        shapes can be computed in the TF/XLA bridge.
        """

        DESCRIPTOR: _descriptor.Descriptor

        ENABLED_FIELD_NUMBER: _builtins.int
        NUM_CORES_PER_REPLICA_FIELD_NUMBER: _builtins.int
        USE_MANUAL_PARTITIONING_FIELD_NUMBER: _builtins.int
        USE_SHARDY_PARTITIONER_FIELD_NUMBER: _builtins.int
        enabled: _builtins.bool
        """Whether SPMD sharding is enabled."""
        num_cores_per_replica: _builtins.int
        """Number of cores per replica."""
        use_manual_partitioning: _builtins.bool
        """If true, the tensors are manually partitioned. Otherwise, use the
        automatic SPMD partitioning. This should be true when users use
        `shard_map`.
        """
        use_shardy_partitioner: _builtins.bool
        """If true, lowers to Shardy custom-call for manual partitioning.
        Default is false.
        """
        def __init__(
            self,
            *,
            enabled: _builtins.bool | None = ...,
            num_cores_per_replica: _builtins.int | None = ...,
            use_manual_partitioning: _builtins.bool | None = ...,
            use_shardy_partitioner: _builtins.bool | None = ...,
        ) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal[
            "enabled",
            b"enabled",
            "num_cores_per_replica",
            b"num_cores_per_replica",
            "use_manual_partitioning",
            b"use_manual_partitioning",
            "use_shardy_partitioner",
            b"use_shardy_partitioner",
        ]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    TABLE_DESCRIPTOR_FIELD_NUMBER: _builtins.int
    MODE_FIELD_NUMBER: _builtins.int
    BATCH_SIZE_PER_TENSOR_CORE_FIELD_NUMBER: _builtins.int
    NUM_HOSTS_FIELD_NUMBER: _builtins.int
    NUM_TENSOR_CORES_FIELD_NUMBER: _builtins.int
    SHARDING_STRATEGY_FIELD_NUMBER: _builtins.int
    PIPELINE_EXECUTION_WITH_TENSOR_CORE_FIELD_NUMBER: _builtins.int
    PROFILE_DATA_DIRECTORY_FIELD_NUMBER: _builtins.int
    FEATURE_DESCRIPTOR_FIELD_NUMBER: _builtins.int
    SPMD_SHARDING_FIELD_NUMBER: _builtins.int
    mode: Global___TPUEmbeddingConfiguration.Mode.ValueType
    batch_size_per_tensor_core: _builtins.int
    """Number of samples in each batch of embedding layer activations sent to
    the TensorCore.
    """
    num_hosts: _builtins.int
    """Number of TPU hosts used for inference/training."""
    num_tensor_cores: _builtins.int
    """Number of TensorCore used for inference/training."""
    sharding_strategy: Global___TPUEmbeddingConfiguration.ShardingStrategy.ValueType
    pipeline_execution_with_tensor_core: _builtins.bool
    """This parameter determines if the execution of the sparse core will be
    pipelined with that of the TensorCore. This parameter only affects results
    when mode=TRAINING. If mode=INFERENCE or BACKWARD_PASS_ONLY, this parameter
    does not affect execution and hence, is a don't care value.

    false: The execution of the sparse core is not pipelined with that of the
    TensorCore. The forward pass of every step on the sparse core is executed
    only after the backward pass of the previous step is complete. And the
    backward pass on the sparse core is executed only after the embedding
    gradients have been computed on the TensorCore on every step. This ensures
    that the activations on every step observe the gradient updates from the
    previous step on both the sparse core and the TensorCore.

    true: The execution of the sparse core is pipelined with that of the
    TensorCore. The forward pass of every step on the sparse core can be
    executed after the forward pass of the previous step is complete without
    waiting for the backward pass. This improves the utilization of the sparse
    core allowing it to process step N+1 while the embedding gradients for step
    N are computed on the TensorCore. The backward pass of every step on the
    sparse core is executed directly after the forward pass for the next step
    is complete. The drawback is that embedding activations for step N+1 do not
    observe the embedding gradient updates from step N. This could affect model
    quality if step N and N+1 involve the same set of embedding IDs. However,
    since the embedding updates are sparse, this is generally not considered a
    problem.
    """
    profile_data_directory: _builtins.str
    """Directory where embedding lookup statistics are stored. These statistics
    summarize information about the inputs to the embedding lookup
    operation, in particular, the average number of embedding IDs per example
    and how well the embedding IDs are load balanced across the system. The
    lookup statistics are used during TPU initialization for embedding table
    partitioning. Collection of lookup statistics is done at runtime by
    profiling the embedding inputs: only 3% of input samples are profiled to
    minimize host CPU overhead. Once a suitable number of samples are
    profiled, the lookup statistics are saved to table-specific files in the
    profile data directory generally at the end of a TPU training loop. The
    filename corresponding to each table is obtained by hashing table specific
    parameters (e.g., table name and number of features) and global
    configuration parameters (e.g., sharding strategy and TPU worker task
    count). The same profile data directory can be shared amongst several
    models to reuse embedding lookup statistics.
    """
    @_builtins.property
    def table_descriptor(
        self,
    ) -> _containers.RepeatedCompositeFieldContainer[Global___TPUEmbeddingConfiguration.TableDescriptor]: ...
    @_builtins.property
    def feature_descriptor(
        self,
    ) -> _containers.RepeatedCompositeFieldContainer[Global___TPUEmbeddingConfiguration.FeatureDescriptor]:
        """If the feature_descriptor field is populated, the model should NOT populate
        TableDescriptor.num_features and batch_size_per_tensor_core. These two
        fields will be auto-populated by the TPUEmbedding rewrite passes.
        """

    @_builtins.property
    def spmd_sharding(self) -> Global___TPUEmbeddingConfiguration.SpmdSharding: ...
    def __init__(
        self,
        *,
        table_descriptor: _abc.Iterable[Global___TPUEmbeddingConfiguration.TableDescriptor] | None = ...,
        mode: Global___TPUEmbeddingConfiguration.Mode.ValueType | None = ...,
        batch_size_per_tensor_core: _builtins.int | None = ...,
        num_hosts: _builtins.int | None = ...,
        num_tensor_cores: _builtins.int | None = ...,
        sharding_strategy: Global___TPUEmbeddingConfiguration.ShardingStrategy.ValueType | None = ...,
        pipeline_execution_with_tensor_core: _builtins.bool | None = ...,
        profile_data_directory: _builtins.str | None = ...,
        feature_descriptor: _abc.Iterable[Global___TPUEmbeddingConfiguration.FeatureDescriptor] | None = ...,
        spmd_sharding: Global___TPUEmbeddingConfiguration.SpmdSharding | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["spmd_sharding", b"spmd_sharding"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "batch_size_per_tensor_core",
        b"batch_size_per_tensor_core",
        "feature_descriptor",
        b"feature_descriptor",
        "mode",
        b"mode",
        "num_hosts",
        b"num_hosts",
        "num_tensor_cores",
        b"num_tensor_cores",
        "pipeline_execution_with_tensor_core",
        b"pipeline_execution_with_tensor_core",
        "profile_data_directory",
        b"profile_data_directory",
        "sharding_strategy",
        b"sharding_strategy",
        "spmd_sharding",
        b"spmd_sharding",
        "table_descriptor",
        b"table_descriptor",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TPUEmbeddingConfiguration: _TypeAlias = TPUEmbeddingConfiguration  # noqa: Y015

@_typing.final
class TPUEmbeddingError(_message.Message):
    """A placeholder message that is used to define a unique Status payload
    URL for TPU embedding errors.
    """

    DESCRIPTOR: _descriptor.Descriptor

    def __init__(self) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TPUEmbeddingError: _TypeAlias = TPUEmbeddingError  # noqa: Y015
