from _typeshed import Incomplete

from .basetypes import GroupParameter, GroupParameterItem

class ActionGroupParameterItem(GroupParameterItem):
    itemWidget: Incomplete
    button: Incomplete
    def __init__(self, param, depth) -> None: ...
    def treeWidgetChanged(self) -> None: ...
    def optsChanged(self, param, opts) -> None: ...

class ActionGroupParameter(GroupParameter):
    itemClass = ActionGroupParameterItem
    sigActivated: Incomplete
    def __init__(self, **opts) -> None: ...
    def activate(self) -> None: ...
    def setButtonOpts(self, **opts) -> None: ...

class ActionGroup(ActionGroupParameter):
    sigActivated: Incomplete
    def __init__(self, **opts) -> None: ...
    def activate(self) -> None: ...
