from ..Parameter import Parameter
from .str import StrParameterItem

def popupFilePicker(
    parent=None, windowTitle: str = "", nameFilter: str = "", directory=None, selectFile=None, relativeTo=None, **kwargs
): ...

class FileParameterItem(StrParameterItem):
    def __init__(self, param, depth) -> None: ...
    def makeWidget(self): ...
    def setValue(self, value) -> None: ...
    def value(self): ...
    def updateDefaultBtn(self) -> None: ...
    def updateDisplayLabel(self, value=None): ...

class FileParameter(Parameter):
    itemClass = FileParameterItem
    def __init__(self, **opts) -> None: ...
