from _typeshed import Incomplete

import numpy as np

from ...Qt import QtWidgets
from ..Parameter import Parameter
from .basetypes import WidgetParameterItem

class SliderParameterItem(WidgetParameterItem):
    slider: QtWidgets.QSlider
    span: np.ndarray
    charSpan: np.ndarray
    emitter: Incomplete
    sigChanging: Incomplete
    def __init__(self, param, depth) -> None: ...
    def updateDisplayLabel(self, value=None) -> None: ...
    def setSuffix(self, suffix) -> None: ...
    def makeWidget(self): ...
    def spanToSliderValue(self, v): ...
    def prettyTextValue(self, v): ...
    def optsChanged(self, param, opts) -> None: ...
    def limitsChanged(self, param, limits) -> None: ...

class SliderParameter(Parameter):
    itemClass = SliderParameterItem
