from logging import Logger

from .connector import ServiceConnector as ServiceConnector
from .rule_cache import RuleCache as RuleCache

log: Logger
DEFAULT_INTERVAL: int

class RulePoller:
    def __init__(self, cache: RuleCache, connector: ServiceConnector) -> None: ...
    def start(self) -> None: ...
    def _worker(self) -> None: ...
    def wake_up(self) -> None: ...
    def _refresh_cache(self) -> None: ...
    def _reset_time_to_wait(self) -> None: ...
