from collections.abc import Iterator, MutableMapping

class FileAwareMapping(MutableMapping[str, str]):
    env: dict[str, str]
    cache: bool
    files_cache: dict[str, str]
    def __init__(self, env: dict[str, str] | None = None, cache: bool = True) -> None: ...
    def __getitem__(self, key: str) -> str: ...
    def __iter__(self) -> Iterator[str]: ...
    def __len__(self) -> int: ...
    def __setitem__(self, key: str, value: str) -> None: ...
    def __delitem__(self, key: str) -> None: ...
