from _typeshed import Incomplete
from collections.abc import MutableMapping

class FileAwareMapping(MutableMapping):
    env: Incomplete
    cache: Incomplete
    files_cache: Incomplete
    def __init__(self, env: Incomplete | None = None, cache: bool = True) -> None: ...
    def __getitem__(self, key): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __setitem__(self, key, value) -> None: ...
    def __delitem__(self, key) -> None: ...
