# TODO incomplete
from types import TracebackType, FrameType, ModuleType
from typing import Any, Callable, List, Optional, Tuple, NamedTuple

# Types and members
ModuleInfo = NamedTuple('ModuleInfo', [('name', str),
                                       ('suffix', str),
                                       ('mode', str),
                                       ('module_type', int),
                                       ])
def getmembers(object: Any,
               predicate: Callable[[Any], bool] = ...
              ) -> List[Tuple[str, Any]]: ...
def getmoduleinfo(path: str) -> Optional[ModuleInfo]: ...
def getmodulename(path: str) -> Optional[str]: ...

def ismodule(object: Any) -> bool: ...
def isclass(object: Any) -> bool: ...
def ismethod(object: Any) -> bool: ...
def isfunction(object: Any) -> bool: ...
def isisgeneratorfunction(object: Any) -> bool: ...
def isgenerator(object: Any) -> bool: ...
def istraceback(object: Any) -> bool: ...
def isframe(object: Any) -> bool: ...
def iscode(object: Any) -> bool: ...
def isbuiltin(object: Any) -> bool: ...
def isroutine(object: Any) -> bool: ...
def isabstract(object: Any) -> bool: ...
def ismethoddescriptor(object: Any) -> bool: ...
def isdatadescriptor(object: Any) -> bool: ...
def isgetsetdescriptor(object: Any) -> bool: ...
def ismemberdescriptor(object: Any) -> bool: ...

# Retrieving source code
def getdoc(object: Any) -> str: ...
def getcomments(object: Any) -> str: ...
def getfile(object: Any) -> str: ...
def getmodule(object: Any) -> ModuleType: ...
def getsourcefile(object: Any) -> str: ...
# TODO restrict to "module, class, method, function, traceback, frame,
# or code object"
def getsourcelines(object: Any) -> Tuple[List[str], int]: ...
# TODO restrict to "a module, class, method, function, traceback, frame,
# or code object"
def getsource(object: Any) -> str: ...
def cleandoc(doc: str) -> str: ...

# Classes and functions
# TODO make the return type more specific
def getclasstree(classes: List[type], unique: bool = ...) -> Any: ...

ArgSpec = NamedTuple('ArgSpec', [('args', List[str]),
                                 ('varargs', str),
                                 ('keywords', str),
                                 ('defaults', tuple),
                                 ])

def getargspec(func: Any) -> ArgSpec: ...
# TODO make the return type more specific
def getargvalues(frame: FrameType) -> Any: ...
# TODO formatargspec
# TODO formatargvalues
def getmro(cls: type) -> Tuple[type, ...]: ...
# TODO getcallargs

# The interpreter stack
# TODO getframeinfo
# TODO getouterframes
def getinnerframes(traceback: TracebackType, context: int = ...) -> List[FrameType]:
    ...

_FrameRecord = Tuple[FrameType, str, int, str, List[str], int]

def currentframe() -> FrameType: ...
def stack(context: int = ...) -> List[_FrameRecord]: ...
def trace(context: int = ...) -> List[_FrameRecord]: ...
