from _typeshed import SupportsWrite
from builtins import str as _str
from contextlib import AbstractContextManager
from typing import Final
from typing_extensions import LiteralString

from .core import Colorful, ColorfulString, _ColorModeType, _PaletteType

__version__: Final[_str]

NO_COLORS: Final[int]
ANSI_8_COLORS: Final[int]
ANSI_16_COLORS: Final[int]
ANSI_256_COLORS: Final[int]
TRUE_COLORS: Final[int]
COLORNAMES_COLORS: Final[_str]

close_fg_color: Final[_str]
close_bg_color: Final[_str]
no_bold: Final[_str]
no_dimmed: Final[_str]
no_italic: Final[_str]
no_underlined: Final[_str]
no_blinkslow: Final[_str]
no_blinkrapid: Final[_str]
no_inversed: Final[_str]
no_concealed: Final[_str]
no_struckthrough: Final[_str]

colormode: _ColorModeType
colorpalette: _str | _PaletteType | None

def setup(
    colormode: _ColorModeType | None = None, colorpalette: _str | _PaletteType | None = None, extend_colors: bool = False
) -> None: ...
def disable() -> None: ...
def use_8_ansi_colors() -> None: ...
def use_16_ansi_colors() -> None: ...
def use_256_ansi_colors() -> None: ...
def use_true_colors() -> None: ...
def use_palette(colorpalette: _str | _PaletteType) -> None: ...
def update_palette(colorpalette: _str | _PaletteType) -> None: ...
def use_style(style_name: _str) -> None: ...
def format(string: _str, *args: LiteralString, **kwargs: LiteralString) -> _str: ...
def str(string: _str) -> ColorfulString: ...
def print(
    *objects: object, sep: _str = " ", end: _str = "\n", file: SupportsWrite[_str] | None = None, flush: bool = False
) -> None: ...
def with_setup(
    colormode: _ColorModeType | None = None, colorpalette: _str | _PaletteType | None = None, extend_colors: bool = False
) -> AbstractContextManager[Colorful]: ...
def with_8_ansi_colors() -> AbstractContextManager[Colorful]: ...
def with_16_ansi_colors() -> AbstractContextManager[Colorful]: ...
def with_256_ansi_colors() -> AbstractContextManager[Colorful]: ...
def with_true_colors() -> AbstractContextManager[Colorful]: ...
def with_palette(colorpalette: _str | _PaletteType) -> AbstractContextManager[Colorful]: ...
def with_updated_palette(colorpalette: _str | _PaletteType) -> AbstractContextManager[Colorful]: ...
def with_style(style_name: _str) -> AbstractContextManager[Colorful]: ...
def __getattr__(name: _str) -> Colorful.ColorfulStyle: ...
