version = "5.3.*"
requires = ["types-setuptools"]

[tool.stubtest]
# Most modules are not meant to be used, yet are not marked as private
# Otherwise results in 138 "failed to find stubs" and 8 "is not present in stub"
ignore_missing_stub = true
