from collections.abc import Sequence
from typing import Literal

import _win32typing

def LoadPerfCounterTextStrings(cmdLine: str, bQuiet: bool | Literal[0, 1] = True, /) -> None: ...
def UnloadPerfCounterTextStrings(cmdLine: str, bQuiet: bool | Literal[0, 1] = True, /) -> None: ...
def CounterDefinition(titleIndex: int, /) -> _win32typing.PyPERF_COUNTER_DEFINITION: ...
def ObjectType(obCounters, /) -> _win32typing.PyPERF_OBJECT_TYPE: ...
def PerfMonManager(
    serviceName: str,
    seqPerfObTypes: Sequence[_win32typing.PyPERF_OBJECT_TYPE],  # must have only 1 item
    mappingName: str | None = None,
    eventSourceName: str | None = None,
    /,
) -> _win32typing.PyPerfMonManager: ...
