from win32.lib.pywintypes import error as error

def GetExpandedName(Source: str, /) -> str: ...
def Close(handle: int, /) -> None: ...
def Copy(hSrc: int, hDest: int, /) -> int: ...
def Init(handle: int, /) -> int: ...
def OpenFile(fileName: str, action: int, /) -> tuple[int, tuple[int, int, int, int, str | None]]: ...
