from typing import Literal, overload

import _win32typing
from win32.lib.pywintypes import error as error

def NCBBuffer(size: int, /) -> memoryview: ...
def Netbios(ncb: _win32typing.PyNCB, /) -> int: ...

@overload
def WNetAddConnection2(
    Type: int,
    LocalName: str | None,
    RemoteName: str,
    bProviderName: str | None = None,
    UserName: str | None = None,
    Password: str | None = None,
    Flags: int = 0,
    /,
) -> None: ...
@overload
def WNetAddConnection2(
    NetResource: _win32typing.PyNETRESOURCE, Password: str | None = None, UserName: str | None = None, Flags: int = 0
) -> None: ...

def WNetAddConnection3(
    HwndOwner: int | _win32typing.PyHANDLE | None,
    NetResource: _win32typing.PyNETRESOURCE,
    Password: str | None = None,
    UserName: str | None = None,
    Flags: int = 0,
) -> None: ...
def WNetCancelConnection2(name: str, flags: int, force: int, /) -> None: ...
def WNetOpenEnum(scope: int, type: int, usage: int, resource: _win32typing.PyNETRESOURCE | None, /) -> _win32typing.PyHANDLE: ...
def WNetCloseEnum(handle: _win32typing.PyHANDLE, /) -> None: ...
def WNetEnumResource(handle: int | _win32typing.PyHANDLE | None, maxExtries: int = 64, /) -> list[_win32typing.PyNETRESOURCE]: ...
def WNetGetUser(connection: str | None = None, /) -> str: ...

@overload
def WNetGetUniversalName(localPath: str, infoLevel: Literal[1] = 1, /) -> str: ...
@overload
def WNetGetUniversalName(localPath: str, infoLevel: Literal[2], /) -> tuple[str, str, str]: ...

def WNetGetResourceInformation(NetResource: _win32typing.PyNETRESOURCE, /) -> tuple[_win32typing.PyNETRESOURCE, str]: ...
def WNetGetLastError() -> tuple[int, str, str]: ...
def WNetGetResourceParent(NetResource: _win32typing.PyNETRESOURCE, /) -> _win32typing.PyNETRESOURCE: ...
def WNetGetConnection(connection: str | None = None, /) -> str: ...

NETRESOURCE = _win32typing.PyNETRESOURCE
NCB = _win32typing.PyNCB
# old "deprecated" names, before types could create instances.
NETRESOURCEType = _win32typing.PyNETRESOURCE
NCBType = _win32typing.PyNCB
