from typing import Final, Literal

import _win32typing

def CreateEnvironmentBlock(Token: int | _win32typing.PyHANDLE | None, Inherit: bool | Literal[0, 1]) -> dict[str, str] | None: ...
def DeleteProfile(SidString: str, ProfilePath: str | None = None, ComputerName: str | None = None) -> None: ...
def ExpandEnvironmentStringsForUser(Token: int | _win32typing.PyHANDLE | None, Src: str) -> str: ...
def GetAllUsersProfileDirectory() -> str: ...
def GetDefaultUserProfileDirectory() -> str: ...
def GetEnvironmentStrings() -> dict[str, str] | None: ...
def GetProfilesDirectory() -> str: ...
def GetProfileType() -> int: ...
def GetUserProfileDirectory(Token: int | _win32typing.PyHANDLE | None) -> str: ...
def LoadUserProfile(hToken: int | _win32typing.PyHANDLE | None, ProfileInfo: _win32typing.ProfileInfo) -> _win32typing.PyHKEY: ...
def UnloadUserProfile(Token: int | _win32typing.PyHANDLE | None, Profile: int | _win32typing.PyHANDLE | None) -> None: ...

PI_NOUI: Final[int]
PI_APPLYPOLICY: Final[int]
PT_MANDATORY: Final[int]
PT_ROAMING: Final[int]
PT_TEMPORARY: Final[int]
