from _typeshed import Incomplete
from collections.abc import Mapping, Sequence
from typing import Any

import google
import google.auth
import google.auth.crypt
import google.auth.transport
from google.auth import credentials

_TRUST_BOUNDARY_LOOKUP_ENDPOINT = ...

class Credentials(
    credentials.Scoped,
    credentials.CredentialsWithQuotaProject,
    credentials.CredentialsWithUniverseDomain,
    credentials.CredentialsWithTrustBoundary,
):
    def __init__(
        self,
        service_account_email: str = "default",
        quota_project_id: str | None = None,
        scopes: Sequence[str] | None = None,
        default_scopes: Sequence[str] | None = None,
        universe_domain: str | None = None,
        trust_boundary: Mapping[str, str] | None = None,
    ) -> None: ...
    @property
    def service_account_email(self) -> str: ...
    @property
    def requires_scopes(self) -> bool: ...
    @property
    def universe_domain(self) -> str: ...
    def get_cred_info(self) -> Mapping[str, str] | None: ...
    def with_quota_project(self, quota_project_id: str | None) -> Credentials: ...
    def with_scopes(self, scopes: Sequence[str], default_scopes: Sequence[str] | None = None) -> Credentials: ...
    def with_universe_domain(self, universe_domain: str | None) -> Credentials: ...
    def with_trust_boundary(self, trust_boundary: Mapping[str, str]) -> Credentials: ...
    def _build_trust_boundary_lookup_url(self) -> str: ...
    def _perform_refresh_token(self, request: google.auth.transport.Request) -> None: ...

class IDTokenCredentials(credentials.CredentialsWithQuotaProject, credentials.Signing, credentials.CredentialsWithTokenUri):
    def __init__(
        self,
        request: google.auth.transport.Request,
        target_audience: str | None = None,
        token_uri: str | None = None,
        additional_claims: Mapping[str, str] | None = None,
        service_account_email: str | None = None,
        signer: google.auth.crypt.Signer | None = None,
        use_metadata_identity_endpoint: bool = False,
        quota_project_id: str | None = None,
    ) -> None: ...
    def with_target_audience(self, target_audience: str) -> IDTokenCredentials: ...
    def with_quota_project(self, quota_project_id: str | None) -> IDTokenCredentials: ...
    def with_token_uri(self, token_uri: str) -> IDTokenCredentials: ...
    token: Incomplete
    expiry: Incomplete

    def refresh(self, request: google.auth.transport.Request) -> None: ...
    @property
    def signer(self) -> Any: ...
    def sign_bytes(self, message: bytes) -> bytes: ...
    @property
    def service_account_email(self) -> str: ...
    @property
    def signer_email(self) -> str: ...
