from _typeshed import Incomplete

IMAGE_URI_CONFIG_DIR: Incomplete

def get_latest_values(existing_content, scope: Incomplete | None = None): ...
def add_dlc_framework_version(
    existing_content, short_version, full_version, scope, processors, py_versions, registries, repository
) -> None: ...
def add_algo_version(
    existing_content, processors, scopes, full_version, py_versions, registries, repository, tag_prefix
) -> None: ...
def add_region(existing_content, region, account) -> None: ...
def add_version(existing_content, short_version, full_version, scope, processors, py_versions, tag_prefix) -> None: ...
def main() -> None: ...
