class Error(Exception): ...

def ZSTD_compress(data: str | bytes, level: int | None, threads: int | None) -> str | bytes: ...
def ZSTD_external() -> int: ...
def ZSTD_uncompress(data: str | bytes) -> str | bytes: ...
def ZSTD_version() -> str | bytes: ...
def ZSTD_version_number() -> int: ...
def compress(data: str | bytes, level: int | None, threads: int | None) -> str | bytes: ...
def decompress(data: str | bytes) -> str | bytes: ...
def dumps(data: str | bytes, level: int | None, threads: int | None) -> str | bytes: ...
def loads(data: str | bytes) -> str | bytes: ...
def uncompress(data: str | bytes) -> str | bytes: ...
def version() -> str | bytes: ...
