version = "304.*"
[tool.stubtest]
# The library only works on Windows; we currently only run stubtest on Ubuntu for third-party stubs in CI.
# See #8660
# `ignore_missing_stub = false` crashes stubtest. This should be fixed in next mypy update
# https://github.com/python/mypy/issues/13822
skip = true
