from collections.abc import Callable
from typing import Any, ClassVar
from typing_extensions import Self

from ..config import PyPIRCCommand

class register(PyPIRCCommand):
    description: str
    sub_commands: ClassVar[list[tuple[str, Callable[[Self], bool] | None]]]
    list_classifiers: int
    strict: int
    def initialize_options(self) -> None: ...
    def finalize_options(self) -> None: ...
    def run(self) -> None: ...
    def check_metadata(self) -> None: ...
    def classifiers(self) -> None: ...
    def verify_metadata(self) -> None: ...
    def send_metadata(self) -> None: ...
    def build_post_data(self, action): ...
    def post_to_server(self, data, auth: Any | None = None): ...
