from _typeshed import Incomplete

LastExportDirectory: Incomplete

class Exporter:
    allowCopy: bool
    Exporters: Incomplete
    @classmethod
    def register(cls) -> None: ...
    item: Incomplete
    def __init__(self, item) -> None: ...
    def parameters(self) -> None: ...
    def export(self, fileName=None, toBytes: bool = False, copy: bool = False) -> None: ...
    fileDialog: Incomplete
    def fileSaveDialog(self, filter=None, opts=None) -> None: ...
    def fileSaveFinished(self, fileName) -> None: ...
    def getScene(self): ...
    def getSourceRect(self): ...
    def getTargetRect(self): ...
    def setExportMode(self, export, opts=None) -> None: ...
    def getPaintItems(self, root=None): ...
    def render(self, painter, targetRect, sourceRect, item=None) -> None: ...
