from _typeshed import Incomplete

from .Exporter import Exporter

__all__ = ["ImageExporter"]

class ImageExporter(Exporter):
    Name: str
    allowCopy: bool
    params: Incomplete
    def __init__(self, item) -> None: ...
    def widthChanged(self) -> None: ...
    def heightChanged(self) -> None: ...
    def parameters(self): ...
    @staticmethod
    def getSupportedImageFormats(): ...
    png: Incomplete
    def export(self, fileName=None, toBytes: bool = False, copy: bool = False): ...
