import types
from typing import Any, Optional

def find_lexer_class(name: Any): ...
def get_lexer_by_name(_alias: Any, **options: Any): ...
def load_lexer_from_file(filename: Any, lexername: str = ..., **options: Any): ...
def get_lexer_for_filename(_fn: Any, code: Optional[Any] = ..., **options: Any): ...
def guess_lexer(_text: Any, **options: Any): ...

# Having every lexer class here doesn't seem to be worth it
def __getattr__(name: str) -> Any: ...
