from pygments.lexer import RegexLexer
from typing import Any

class AmbientTalkLexer(RegexLexer):
    name: str = ...
    filenames: Any = ...
    aliases: Any = ...
    mimetypes: Any = ...
    flags: Any = ...
    builtin: Any = ...
    tokens: Any = ...
