from pygments.lexer import RegexLexer
from typing import Any

class AMDGPULexer(RegexLexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    flags: Any = ...
    tokens: Any = ...
