from pygments.lexer import RegexLexer
from typing import Any

class AutohotkeyLexer(RegexLexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    mimetypes: Any = ...
    tokens: Any = ...

class AutoItLexer(RegexLexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    mimetypes: Any = ...
    keywords: Any = ...
    functions: Any = ...
    macros: Any = ...
    tokens: Any = ...
