from pygments.lexer import RegexLexer
from typing import Any

class BoaLexer(RegexLexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    reserved: Any = ...
    keywords: Any = ...
    classes: Any = ...
    operators: Any = ...
    string_sep: Any = ...
    built_in_functions: Any = ...
    tokens: Any = ...
