from pygments.lexer import RegexLexer
from typing import Any

class CapnProtoLexer(RegexLexer):
    name: str = ...
    filenames: Any = ...
    aliases: Any = ...
    flags: Any = ...
    tokens: Any = ...
