from pygments.lexer import RegexLexer
from typing import Any

class ChapelLexer(RegexLexer):
    name: str = ...
    filenames: Any = ...
    aliases: Any = ...
    known_types: Any = ...
    type_modifiers_par: Any = ...
    type_modifiers_mem: Any = ...
    type_modifiers: Any = ...
    declarations: Any = ...
    constants: Any = ...
    other_keywords: Any = ...
    tokens: Any = ...
