from pygments.lexer import ExtendedRegexLexer
from typing import Any

class CrystalLexer(ExtendedRegexLexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    mimetypes: Any = ...
    flags: Any = ...
    def heredoc_callback(self, match: Any, ctx: Any) -> None: ...
    def gen_crystalstrings_rules(): ...
    tokens: Any = ...
