from pygments.lexer import RegexLexer
from typing import Any

class DiffLexer(RegexLexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    mimetypes: Any = ...
    tokens: Any = ...
    def analyse_text(text: Any): ...

class DarcsPatchLexer(RegexLexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    DPATCH_KEYWORDS: Any = ...
    tokens: Any = ...

class WDiffLexer(RegexLexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    mimetypes: Any = ...
    flags: Any = ...
    ins_op: str = ...
    ins_cl: str = ...
    del_op: str = ...
    del_cl: str = ...
    normal: str = ...
    tokens: Any = ...
