from pygments.lexer import RegexLexer
from typing import Any

class EzhilLexer(RegexLexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    mimetypes: Any = ...
    flags: Any = ...
    tokens: Any = ...
    def analyse_text(text: Any): ...
    encoding: Any = ...
    def __init__(self, **options: Any) -> None: ...
