from pygments.lexer import RegexLexer
from typing import Any

class FelixLexer(RegexLexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    mimetypes: Any = ...
    preproc: Any = ...
    keywords: Any = ...
    keyword_directives: Any = ...
    keyword_declarations: Any = ...
    keyword_types: Any = ...
    keyword_constants: Any = ...
    operator_words: Any = ...
    name_builtins: Any = ...
    name_pseudo: Any = ...
    decimal_suffixes: str = ...
    tokens: Any = ...
