from pygments.lexer import RegexLexer
from typing import Any

class FoxProLexer(RegexLexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    mimetype: Any = ...
    flags: Any = ...
    tokens: Any = ...
