from pygments.lexer import RegexLexer
from typing import Any

class JLexer(RegexLexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    mimetypes: Any = ...
    validName: str = ...
    tokens: Any = ...
