from pygments.lexer import Lexer, RegexLexer
from typing import Any

class JuliaLexer(RegexLexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    mimetypes: Any = ...
    flags: Any = ...
    tokens: Any = ...
    def analyse_text(text: Any): ...

class JuliaConsoleLexer(Lexer):
    name: str = ...
    aliases: Any = ...
    def get_tokens_unprocessed(self, text: Any) -> None: ...
