from pygments.lexer import RegexLexer
from typing import Any

class ObjectiveCLexer:
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    mimetypes: Any = ...
    priority: float = ...

class ObjectiveCppLexer:
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    mimetypes: Any = ...
    priority: float = ...

class LogosLexer(ObjectiveCppLexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    mimetypes: Any = ...
    priority: float = ...
    tokens: Any = ...
    def analyse_text(text: Any): ...

class SwiftLexer(RegexLexer):
    name: str = ...
    filenames: Any = ...
    aliases: Any = ...
    mimetypes: Any = ...
    tokens: Any = ...
    def get_tokens_unprocessed(self, text: Any) -> None: ...
