from pygments.lexer import ExtendedRegexLexer, Lexer, RegexLexer
from typing import Any

class RubyLexer(ExtendedRegexLexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    mimetypes: Any = ...
    flags: Any = ...
    def heredoc_callback(self, match: Any, ctx: Any) -> None: ...
    def gen_rubystrings_rules(): ...
    tokens: Any = ...
    def analyse_text(text: Any): ...

class RubyConsoleLexer(Lexer):
    name: str = ...
    aliases: Any = ...
    mimetypes: Any = ...
    def get_tokens_unprocessed(self, text: Any) -> None: ...

class FancyLexer(RegexLexer):
    name: str = ...
    filenames: Any = ...
    aliases: Any = ...
    mimetypes: Any = ...
    tokens: Any = ...
