from pygments.lexer import RegexLexer
from typing import Any

class SolidityLexer(RegexLexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    mimetypes: Any = ...
    flags: Any = ...
    datatype: str = ...
    tokens: Any = ...
