from pygments.lexer import RegexLexer
from typing import Any

class TclLexer(RegexLexer):
    keyword_cmds_re: Any = ...
    builtin_cmds_re: Any = ...
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    mimetypes: Any = ...
    tokens: Any = ...
    def analyse_text(text: Any): ...
