from pygments.lexer import Lexer
from typing import Any

class TNTLexer(Lexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    cur: Any = ...
    LOGIC: Any = ...
    OPERATORS: Any = ...
    VARIABLES: Any = ...
    PRIMES: Any = ...
    NEGATORS: Any = ...
    QUANTIFIERS: Any = ...
    NUMBERS: Any = ...
    WHITESPACE: Any = ...
    RULES: Any = ...
    LINENOS: Any = ...
    COMMENT: Any = ...
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...
    def whitespace(self, start: Any, text: Any, required: bool = ...): ...
    def variable(self, start: Any, text: Any): ...
    def term(self, start: Any, text: Any): ...
    def formula(self, start: Any, text: Any): ...
    def rule(self, start: Any, text: Any): ...
    def lineno(self, start: Any, text: Any): ...
    def error_till_line_end(self, start: Any, text: Any): ...
    def get_tokens_unprocessed(self, text: Any): ...
