from pygments.lexer import RegexLexer
from typing import Any

class VCLLexer(RegexLexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    mimetypes: Any = ...
    def analyse_text(text: Any): ...
    tokens: Any = ...

class VCLSnippetLexer(VCLLexer):
    name: str = ...
    aliases: Any = ...
    mimetypes: Any = ...
    filenames: Any = ...
    def analyse_text(text: Any): ...
    tokens: Any = ...
