from pygments.lexer import RegexLexer
from typing import Any

class X10Lexer(RegexLexer):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    mimetypes: Any = ...
    keywords: Any = ...
    types: str = ...
    values: Any = ...
    modifiers: Any = ...
    tokens: Any = ...
