# AUTOGENERATED BY scripts/sync_auth0_python.py
from typing import Any, type_check_only

from .base import _AuthenticationBaseAsync

@type_check_only
class _BackChannelLoginAsync(_AuthenticationBaseAsync):
    async def back_channel_login_async(self, binding_message: str, login_hint: str, scope: str, **kwargs) -> Any: ...
