# AUTOGENERATED BY scripts/sync_auth0_python.py
from typing import Any, type_check_only

from auth0.authentication.base import AuthenticationBase
from auth0.types import RequestData

@type_check_only
class _AuthenticationBaseAsync(AuthenticationBase):
    async def post_async(self, url: str, data: RequestData | None = None, headers: dict[str, str] | None = None) -> Any: ...
    async def authenticated_post_async(self, url: str, data: dict[str, Any], headers: dict[str, str] | None = None) -> Any: ...
    async def get_async(self, url: str, params: dict[str, Any] | None = None, headers: dict[str, str] | None = None) -> Any: ...
