# AUTOGENERATED BY scripts/sync_auth0_python.py
from typing import Any, type_check_only

from .base import _AuthenticationBaseAsync

@type_check_only
class _RevokeTokenAsync(_AuthenticationBaseAsync):
    async def revoke_refresh_token_async(self, token: str) -> Any: ...
