class AtomicCounter:
    value: int
    def __init__(self, initial: int = 0) -> None: ...
    def increment(self, num: int = 1) -> int | None: ...
    def decrement(self, num: int = 1) -> int | None: ...
    def get_current(self) -> int | None: ...
    def reset(self) -> int | None: ...
