# Names in __all__ with no definition:
#   bdist
#   bdist_dumb
#   bdist_rpm
#   bdist_wininst
#   build
#   build_clib
#   build_ext
#   build_py
#   build_scripts
#   check
#   clean
#   install
#   install_data
#   install_headers
#   install_lib
#   install_scripts
#   register
#   sdist
#   upload
