from _typeshed import Incomplete

PLATFORM: Incomplete
IS_CYGWIN: Incomplete

class WorkerTmp:
    def __init__(self, cfg) -> None: ...
    def notify(self) -> None: ...
    def last_update(self): ...
    def fileno(self): ...
    def close(self): ...
