from dataclasses import dataclass
from typing import Any

from django.db import models
from django.db.models import Q
from django.db.models.query import QuerySet

from .models import PolymorphicModel

@dataclass(frozen=True)
class ParentLinkInfo:
    model: type[models.Model]
    link: models.Field[Any, Any]

def reset_polymorphic_ctype(*models: type[PolymorphicModel], **filters: Any) -> None: ...
def sort_by_subclass(*classes: type[models.Model]) -> list[type[models.Model]]: ...
def get_base_polymorphic_model(
    ChildModel: type[PolymorphicModel], allow_abstract: bool = False
) -> type[PolymorphicModel] | None: ...
def route_to_ancestor(model_class: type[models.Model], ancestor_model: type[models.Model]) -> list[ParentLinkInfo]: ...
def is_model_loaded(model: type[models.Model]) -> bool: ...
def concrete_descendants(model_class: type[models.Model], include_proxy: bool = False) -> list[type[models.Model]]: ...
def prepare_for_copy(obj: models.Model) -> None: ...
def lazy_ctype(model: type[models.Model], using: str = ...) -> int | QuerySet[Any]: ...
def _lazy_ctype(model: type[models.Model], using: str = ...) -> int | Q: ...
def _map_queryname_to_class(base_model: type[models.Model], qry_name: str) -> type[models.Model]: ...
def _clear_utility_caches() -> None: ...
