# Stubs for code

from typing import Any, Callable, Mapping, Optional
from types import CodeType

class InteractiveInterpreter:
#    locals = ...  # type: Any
#    compile = ...  # type: Any
    def __init__(self, locals: Optional[Mapping[str, Any]] = ...) -> None: ...
#    def runsource(self, source, filename='', symbol=''): ...
#    def runcode(self, code): ...
#    def showsyntaxerror(self, filename=None): ...
#    def showtraceback(self): ...
#    def write(self, data): ...

class InteractiveConsole(InteractiveInterpreter):
#    filename = ...  # type: Any
    def __init__(self, locals: Optional[Mapping[str, Any]] = ...,
                 filename: str = ...) -> None: ...
#    buffer = ...  # type: Any
#    def resetbuffer(self): ...
#    def interact(self, banner=None): ...
#    def push(self, line): ...
#    def raw_input(self, prompt=''): ...

def interact(banner: Optional[str] = ...,
             readfunc: Optional[Callable[[str], str]] = ...,
             local: Optional[Mapping[str, Any]] = ...) -> None: ...
def compile_command(source: str, filename: str = ...,
                    symbol: str = ...) -> Optional[CodeType]: ...
