import sys
from typing import Any, Dict, List, Optional, Text, Union

_ModuleGlobals = Dict[str, Any]
_FileName = Union[str, Text]

def getline(filename: _FileName, lineno: int, module_globals: Optional[_ModuleGlobals] = ...) -> str: ...
def clearcache() -> None: ...
def getlines(filename: _FileName, module_globals: Optional[_ModuleGlobals] = ...) -> None: ...
def checkcache(filename: Optional[_FileName] = ...) -> None: ...
def updatecache(filename: _FileName, module_globals: Optional[_ModuleGlobals] = ...) -> List[str]: ...
if sys.version_info >= (3, 5):
    def lazycache(filename: _FileName, module_globals: _ModuleGlobals) -> bool: ...
