from _typeshed import Incomplete

from antlr4.Token import Token as Token

INVALID_INTERVAL: Incomplete

class Tree: ...
class SyntaxTree(Tree): ...
class ParseTree(SyntaxTree): ...
class RuleNode(ParseTree): ...
class TerminalNode(ParseTree): ...
class ErrorNode(TerminalNode): ...

class ParseTreeVisitor:
    def visit(self, tree: Incomplete) -> Incomplete: ...
    def visitChildren(self, node: Incomplete) -> Incomplete: ...
    def visitTerminal(self, node: Incomplete) -> Incomplete: ...
    def visitErrorNode(self, node: Incomplete) -> Incomplete: ...
    def defaultResult(self) -> None: ...
    def aggregateResult(self, aggregate: Incomplete, nextResult: Incomplete) -> Incomplete: ...
    def shouldVisitNextChild(self, node: Incomplete, currentResult: Incomplete) -> Incomplete: ...

ParserRuleContext: Incomplete

class ParseTreeListener:
    def visitTerminal(self, node: TerminalNode) -> Incomplete: ...
    def visitErrorNode(self, node: ErrorNode) -> Incomplete: ...
    def enterEveryRule(self, ctx: ParserRuleContext) -> Incomplete: ...
    def exitEveryRule(self, ctx: ParserRuleContext) -> Incomplete: ...

class TerminalNodeImpl(TerminalNode):
    parentCtx: Incomplete
    symbol: Incomplete
    def __init__(self, symbol: Token) -> None: ...
    def __setattr__(self, key: Incomplete, value: Incomplete) -> None: ...
    def getChild(self, i: int) -> Incomplete: ...
    def getSymbol(self) -> Incomplete: ...
    def getParent(self) -> Incomplete: ...
    def getPayload(self) -> Incomplete: ...
    def getSourceInterval(self) -> Incomplete: ...
    def getChildCount(self) -> Incomplete: ...
    def accept(self, visitor: ParseTreeVisitor) -> Incomplete: ...
    def getText(self) -> Incomplete: ...

class ErrorNodeImpl(TerminalNodeImpl, ErrorNode):
    def __init__(self, token: Token) -> None: ...
    def accept(self, visitor: ParseTreeVisitor) -> Incomplete: ...

class ParseTreeWalker:
    DEFAULT: Incomplete
    def walk(self, listener: ParseTreeListener, t: ParseTree) -> Incomplete: ...
    def enterRule(self, listener: ParseTreeListener, r: RuleNode) -> Incomplete: ...
    def exitRule(self, listener: ParseTreeListener, r: RuleNode) -> Incomplete: ...
