from typing import Any

class _PasslibRegistryProxy:
    __name__: str
    __package__: str | None
    def __getattr__(self, attr: str) -> Any: ...
    def __setattr__(self, attr: str, value) -> None: ...
    def __dir__(self) -> list[str]: ...

def register_crypt_handler_path(name: str, path: str) -> None: ...
def register_crypt_handler(handler: Any, force: bool = False, _attr: str | None = None) -> None: ...
def get_crypt_handler(name: str, default: Any = ...) -> Any: ...
def list_crypt_handlers(loaded_only: bool = False) -> list[str]: ...
