from _typeshed import Incomplete

from antlr4.atn.ATNConfigSet import ATNConfigSet as ATNConfigSet
from antlr4.atn.ATNState import DecisionState as DecisionState, StarLoopEntryState as StarLoopEntryState
from antlr4.dfa.DFAState import DFAState as DFAState
from antlr4.error.Errors import IllegalStateException as IllegalStateException

class DFA:
    atnStartState: Incomplete
    decision: Incomplete
    s0: Incomplete
    precedenceDfa: bool
    def __init__(self, atnStartState: DecisionState, decision: int = ...) -> None: ...
    def getPrecedenceStartState(self, precedence: int) -> Incomplete: ...
    def setPrecedenceStartState(self, precedence: int, startState: DFAState) -> Incomplete: ...
    def setPrecedenceDfa(self, precedenceDfa: bool) -> Incomplete: ...
    @property
    def states(self) -> Incomplete: ...
    def sortedStates(self) -> Incomplete: ...
    def toString(self, literalNames: list[str] = ..., symbolicNames: list[str] = ...) -> Incomplete: ...
    def toLexerString(self) -> Incomplete: ...
