from _typeshed import Incomplete

class GarbageCollector:
    debug: Incomplete
    timer: Incomplete
    threshold: Incomplete
    def __init__(self, interval: float = 1.0, debug: bool = False) -> None: ...
    def check(self) -> None: ...
    def debug_cycles(self) -> None: ...
