from typing import Any

def hook_re_module() -> None: ...

class EnabledHooks:
    def __init__(self) -> None: ...
    def add(self, hook: str) -> None: ...
    def __contains__(self, hook: str) -> bool: ...

enabled_hooks: EnabledHooks

def _hook_str(*args: Any, **kwargs: Any) -> bool: ...
