import sys
from datetime import datetime

if sys.version_info >= (3, 12):
    dtfont: tuple[str, int, str]
    current_day: int | None
    def display_date_time() -> None: ...

def jump(distanz: float, winkel: int = 0) -> None: ...
def hand(laenge: float, spitze: float) -> None: ...
def make_hand_shape(name: str, laenge: float, spitze: float) -> None: ...
def clockface(radius: float) -> None: ...
def setup() -> None: ...
def wochentag(t: datetime) -> str: ...
def datum(z: datetime) -> str: ...
def tick() -> None: ...
def main() -> str: ...
