from collections.abc import Generator
from turtle import Turtle

def symRandom(n: int) -> int: ...
def randomize(branchlist: list[tuple[float, float]], angledist: int, sizedist: int) -> list[tuple[float, float]]: ...
def randomfd(t: Turtle, distance: float, parts: int, angledist: int) -> None: ...
def tree(
    tlist: list[Turtle],
    size: float,
    level: int,
    widthfactor: float,
    branchlists: list[list[tuple[float, float]]],
    angledist: int = 10,
    sizedist: int = 5,
) -> Generator[int | None]: ...
def start(t: Turtle, x: float, y: float) -> None: ...
def doit1(level: int, pen: Turtle) -> Generator[int | None]: ...
def doit2(level: int, pen: Turtle) -> Generator[int | None]: ...
def doit3(level: int, pen: Turtle) -> Generator[int | None]: ...
def main() -> str: ...
