from turtle import Turtle, Vec2D

G: int

class GravSys:
    planets: list[Star]
    t: int
    dt: float
    def __init__(self) -> None: ...
    def init(self) -> None: ...
    def start(self) -> None: ...

class Star(Turtle):
    m: int
    v: Vec2D
    gravSys: GravSys
    def __init__(self, m: int, x: Vec2D, v: Vec2D, gravSys: GravSys, shape: str) -> None: ...
    a: Vec2D
    def init(self) -> None: ...
    def acc(self) -> Vec2D: ...
    def step(self) -> None: ...

def main() -> str: ...
