from turtle import Turtle
from typing import SupportsIndex

class Block(Turtle):
    size: int
    def __init__(self, size: int) -> None: ...
    def glow(self) -> None: ...
    def unglow(self) -> None: ...

class Shelf(list[Block]):
    y: int
    x: int
    def __init__(self, y: int) -> None: ...
    def push(self, d: Block) -> None: ...
    def pop(self, key: SupportsIndex) -> Block: ...  # type: ignore[override]
    def insert(self, key: SupportsIndex, b: Block) -> None: ...

def isort(shelf: Shelf) -> None: ...
def ssort(shelf: Shelf) -> None: ...
def partition(shelf: Shelf, left: int, right: int, pivot_index: int): ...
def qsort(shelf: Shelf, left: int, right: int) -> None: ...
def randomize() -> None: ...
def show_text(text: str, line: int = 0) -> None: ...
def start_ssort() -> None: ...
def start_isort() -> None: ...
def start_qsort() -> None: ...
def init_shelf() -> None: ...
def disable_keys() -> None: ...
def enable_keys() -> None: ...
def main() -> str: ...

instructions1: str
instructions2: str
