version = "0.23.*"
requires = ["types-setuptools"]
upstream_repository = "https://github.com/sass/libsass-python"

# When ran directly on our stubs, mypy won't understand that they are partial
# This is not an issue with pyright because it understands per-module py.typed (setuptools/_distutils/py.typed)
[mypy-tests.distutils]
module_name = "setuptools._distutils.*"
values = { "follow_untyped_imports" = true }

[tool.stubtest]
# The runtime package has an undeclared dependency on setuptools
stubtest_requirements = ["setuptools"]
