def symbol(string_or_url): ...
def parse_counter_style_name(tokens, counter_style): ...

class CounterStyle(dict):
    def resolve_counter(self, counter_name, previous_types=None): ...
    def render_value(self, counter_value, counter_name=None, counter=None, previous_types=None): ...
    def render_marker(self, counter_name, counter_value): ...
    def copy(self): ...
