from _typeshed import Incomplete

class Function:
    name: Incomplete
    arguments: Incomplete
    def __init__(self, token) -> None: ...
    def split_space(self): ...
    def split_comma(self, single_tokens: bool = True, trailing: bool = False): ...

def check_attr(token, allowed_type=None): ...
def check_counter(token, allowed_type=None): ...
def check_content(token): ...
def check_string_or_element(string_or_element, token): ...
def check_var(token): ...
def check_math(token): ...
