from _typeshed import Incomplete

from influxdb_client.domain.write_precision import _WritePrecision

EPOCH: Incomplete
DEFAULT_WRITE_PRECISION: _WritePrecision

class Point:
    @staticmethod
    def measurement(measurement): ...
    @staticmethod
    def from_dict(dictionary: dict[Incomplete, Incomplete], write_precision: _WritePrecision = ..., **kwargs): ...
    def __init__(self, measurement_name) -> None: ...
    def time(self, time, write_precision=...): ...
    def tag(self, key, value): ...
    def field(self, field, value): ...
    def to_line_protocol(self, precision: Incomplete | None = ...): ...
    @property
    def write_precision(self): ...
    @classmethod
    def set_str_rep(cls, rep_function) -> None: ...
