from typing import overload, Any, Callable, TypeVar, Union
from typing import Tuple, List, Sequence, MutableSequence

Callback = Union[Callable[..., None], None]
Buffer = TypeVar('Buffer')
Pointer = TypeVar('Pointer')
Template = TypeVar('Template')

import vtkmodules.vtkCommonCore
import vtkmodules.vtkCommonExecutionModel

class vtkMotionFXCFGReader(vtkmodules.vtkCommonExecutionModel.vtkMultiBlockDataSetAlgorithm):
    def GetFileName(self) -> str: ...
    def GetNumberOfGenerationsFromBase(self, type:str) -> int: ...
    @staticmethod
    def GetNumberOfGenerationsFromBaseType(type:str) -> int: ...
    def GetTimeResolution(self) -> int: ...
    def GetTimeResolutionMaxValue(self) -> int: ...
    def GetTimeResolutionMinValue(self) -> int: ...
    def IsA(self, type:str) -> int: ...
    @staticmethod
    def IsTypeOf(type:str) -> int: ...
    def NewInstance(self) -> 'vtkMotionFXCFGReader': ...
    @staticmethod
    def SafeDownCast(o:'vtkObjectBase') -> 'vtkMotionFXCFGReader': ...
    def SetFileName(self, fname:str) -> None: ...
    def SetTimeResolution(self, _arg:int) -> None: ...

