BadAlign: int
BAD_ALIGN: int
BadAlphaChannel: int
BAD_ALPHA_CHANNEL: int
BadCOI: int
BAD_COI: int
BadCallBack: int
BAD_CALL_BACK: int
BadDataPtr: int
BAD_DATA_PTR: int
BadDepth: int
BAD_DEPTH: int
BadImageSize: int
BAD_IMAGE_SIZE: int
BadModelOrChSeq: int
BAD_MODEL_OR_CH_SEQ: int
BadNumChannel1U: int
BAD_NUM_CHANNEL1U: int
BadNumChannels: int
BAD_NUM_CHANNELS: int
BadOffset: int
BAD_OFFSET: int
BadOrder: int
BAD_ORDER: int
BadOrigin: int
BAD_ORIGIN: int
BadROISize: int
BAD_ROISIZE: int
BadStep: int
BAD_STEP: int
BadTileSize: int
BAD_TILE_SIZE: int
GpuApiCallError: int
GPU_API_CALL_ERROR: int
GpuNotSupported: int
GPU_NOT_SUPPORTED: int
HeaderIsNull: int
HEADER_IS_NULL: int
MaskIsTiled: int
MASK_IS_TILED: int
OpenCLApiCallError: int
OPEN_CLAPI_CALL_ERROR: int
OpenCLDoubleNotSupported: int
OPEN_CLDOUBLE_NOT_SUPPORTED: int
OpenCLInitError: int
OPEN_CLINIT_ERROR: int
OpenCLNoAMDBlasFft: int
OPEN_CLNO_AMDBLAS_FFT: int
OpenGlApiCallError: int
OPEN_GL_API_CALL_ERROR: int
OpenGlNotSupported: int
OPEN_GL_NOT_SUPPORTED: int
StsAssert: int
STS_ASSERT: int
StsAutoTrace: int
STS_AUTO_TRACE: int
StsBackTrace: int
STS_BACK_TRACE: int
StsBadArg: int
STS_BAD_ARG: int
StsBadFlag: int
STS_BAD_FLAG: int
StsBadFunc: int
STS_BAD_FUNC: int
StsBadMask: int
STS_BAD_MASK: int
StsBadMemBlock: int
STS_BAD_MEM_BLOCK: int
StsBadPoint: int
STS_BAD_POINT: int
StsBadSize: int
STS_BAD_SIZE: int
StsDivByZero: int
STS_DIV_BY_ZERO: int
StsError: int
STS_ERROR: int
StsFilterOffsetErr: int
STS_FILTER_OFFSET_ERR: int
StsFilterStructContentErr: int
STS_FILTER_STRUCT_CONTENT_ERR: int
StsInplaceNotSupported: int
STS_INPLACE_NOT_SUPPORTED: int
StsInternal: int
STS_INTERNAL: int
StsKernelStructContentErr: int
STS_KERNEL_STRUCT_CONTENT_ERR: int
StsNoConv: int
STS_NO_CONV: int
StsNoMem: int
STS_NO_MEM: int
StsNotImplemented: int
STS_NOT_IMPLEMENTED: int
StsNullPtr: int
STS_NULL_PTR: int
StsObjectNotFound: int
STS_OBJECT_NOT_FOUND: int
StsOk: int
STS_OK: int
StsOutOfRange: int
STS_OUT_OF_RANGE: int
StsParseError: int
STS_PARSE_ERROR: int
StsUnmatchedFormats: int
STS_UNMATCHED_FORMATS: int
StsUnmatchedSizes: int
STS_UNMATCHED_SIZES: int
StsUnsupportedFormat: int
STS_UNSUPPORTED_FORMAT: int
StsVecLengthErr: int
STS_VEC_LENGTH_ERR: int
