BAD_ALIGN: int
BAD_ALPHA_CHANNEL: int
BAD_CALL_BACK: int
BAD_COI: int
BAD_DATA_PTR: int
BAD_DEPTH: int
BAD_IMAGE_SIZE: int
BAD_MODEL_OR_CH_SEQ: int
BAD_NUM_CHANNEL1U: int
BAD_NUM_CHANNELS: int
BAD_OFFSET: int
BAD_ORDER: int
BAD_ORIGIN: int
BAD_ROISIZE: int
BAD_STEP: int
BAD_TILE_SIZE: int
BadAlign: int
BadAlphaChannel: int
BadCOI: int
BadCallBack: int
BadDataPtr: int
BadDepth: int
BadImageSize: int
BadModelOrChSeq: int
BadNumChannel1U: int
BadNumChannels: int
BadOffset: int
BadOrder: int
BadOrigin: int
BadROISize: int
BadStep: int
BadTileSize: int
GPU_API_CALL_ERROR: int
GPU_NOT_SUPPORTED: int
GpuApiCallError: int
GpuNotSupported: int
HEADER_IS_NULL: int
HeaderIsNull: int
MASK_IS_TILED: int
MaskIsTiled: int
OPEN_CLAPI_CALL_ERROR: int
OPEN_CLDOUBLE_NOT_SUPPORTED: int
OPEN_CLINIT_ERROR: int
OPEN_CLNO_AMDBLAS_FFT: int
OPEN_GL_API_CALL_ERROR: int
OPEN_GL_NOT_SUPPORTED: int
OpenCLApiCallError: int
OpenCLDoubleNotSupported: int
OpenCLInitError: int
OpenCLNoAMDBlasFft: int
OpenGlApiCallError: int
OpenGlNotSupported: int
STS_ASSERT: int
STS_AUTO_TRACE: int
STS_BACK_TRACE: int
STS_BAD_ARG: int
STS_BAD_FLAG: int
STS_BAD_FUNC: int
STS_BAD_MASK: int
STS_BAD_MEM_BLOCK: int
STS_BAD_POINT: int
STS_BAD_SIZE: int
STS_DIV_BY_ZERO: int
STS_ERROR: int
STS_FILTER_OFFSET_ERR: int
STS_FILTER_STRUCT_CONTENT_ERR: int
STS_INPLACE_NOT_SUPPORTED: int
STS_INTERNAL: int
STS_KERNEL_STRUCT_CONTENT_ERR: int
STS_NOT_IMPLEMENTED: int
STS_NO_CONV: int
STS_NO_MEM: int
STS_NULL_PTR: int
STS_OBJECT_NOT_FOUND: int
STS_OK: int
STS_OUT_OF_RANGE: int
STS_PARSE_ERROR: int
STS_UNMATCHED_FORMATS: int
STS_UNMATCHED_SIZES: int
STS_UNSUPPORTED_FORMAT: int
STS_VEC_LENGTH_ERR: int
StsAssert: int
StsAutoTrace: int
StsBackTrace: int
StsBadArg: int
StsBadFlag: int
StsBadFunc: int
StsBadMask: int
StsBadMemBlock: int
StsBadPoint: int
StsBadSize: int
StsDivByZero: int
StsError: int
StsFilterOffsetErr: int
StsFilterStructContentErr: int
StsInplaceNotSupported: int
StsInternal: int
StsKernelStructContentErr: int
StsNoConv: int
StsNoMem: int
StsNotImplemented: int
StsNullPtr: int
StsObjectNotFound: int
StsOk: int
StsOutOfRange: int
StsParseError: int
StsUnmatchedFormats: int
StsUnmatchedSizes: int
StsUnsupportedFormat: int
StsVecLengthErr: int
