from cv2.cv2 import _Boolean

def getIppVersion() -> str: ...
def setUseIPP(flag: _Boolean) -> None: ...
def setUseIPP_NotExact(flag: _Boolean) -> None: ...
def useIPP() -> bool: ...
def useIPP_NotExact() -> bool: ...
