from cv2.cv2 import _Boolean

def addSamplesDataSearchPath(path: str | None) -> None: ...
def addSamplesDataSearchSubDirectory(subdir: str | None) -> None: ...
def findFile(relative_path: str, required: _Boolean = ..., silentMode: _Boolean = ...) -> str: ...
def findFileOrKeep(relative_path: str, silentMode: _Boolean = ...) -> str: ...
