from _typeshed import Incomplete
from collections.abc import Generator

from ..tokens import comma_separated_list, single_keyword, single_token

DESCRIPTORS: Incomplete
NOT_PRINT_MEDIA: Incomplete

class NoneFakeToken:
    type: str
    lower_value: str

class NormalFakeToken:
    type: str
    lower_value: str

def preprocess_descriptors(rule, base_url, descriptors) -> Generator[Incomplete]: ...
def descriptor(rule, descriptor_name=None, wants_base_url: bool = False): ...
def expand_font_variant(tokens) -> Generator[Incomplete]: ...
def font_family(tokens, allow_spaces: bool = False): ...
@comma_separated_list
def src(tokens, base_url): ...
@single_keyword
def font_style(keyword): ...
@single_token
def font_weight(token): ...
@single_keyword
def font_stretch(keyword): ...
def font_feature_settings(tokens): ...
def font_variant(tokens): ...
@comma_separated_list
@single_token
def unicode_range(token): ...
def system(tokens): ...
def negative(tokens, base_url): ...
def prefix_suffix(tokens, base_url): ...
@comma_separated_list
def range(tokens): ...
def pad(tokens, base_url): ...
@single_token
def fallback(token): ...
def symbols(tokens, base_url): ...
def additive_symbols(tokens, base_url): ...
@single_token
def color_profile_src(token, base_url): ...
@single_keyword
def rendering_intent(keyword): ...
@comma_separated_list
def components(tokens): ...
