from _typeshed import Incomplete
from collections.abc import Generator

from ..tokens import Pending

EXPANDERS: Incomplete

class PendingExpander(Pending):
    validator: Incomplete
    def __init__(self, tokens, validator) -> None: ...
    def validate(self, tokens, wanted_key): ...

def expander(property_name): ...
def generic_expander(*expanded_names, **kwargs): ...
def expand_four_sides(tokens, name, base_url) -> Generator[Incomplete, Incomplete]: ...
def border_radius(tokens, name, base_url) -> Generator[Incomplete]: ...
def expand_list_style(tokens, name, base_url) -> Generator[Incomplete]: ...
def expand_border(tokens, name, base_url) -> Generator[Incomplete, Incomplete]: ...
def expand_border_side(tokens, name) -> Generator[Incomplete]: ...
def expand_border_image(tokens, name, base_url) -> Generator[Incomplete]: ...
def expand_mask_border(tokens, name, base_url) -> Generator[Incomplete]: ...
def expand_background(tokens, name, base_url) -> Generator[Incomplete, Incomplete, Incomplete]: ...
def expand_text_decoration(tokens, name) -> Generator[Incomplete]: ...
def expand_page_break_before_after(tokens, name) -> Generator[Incomplete]: ...
def expand_page_break_after(tokens, name): ...
def expand_page_break_before(tokens, name): ...
def expand_page_break_inside(tokens, name) -> Generator[Incomplete]: ...
def expand_columns(tokens, name) -> Generator[Incomplete]: ...
def font_variant(tokens, name): ...
def expand_font(tokens, name) -> Generator[Incomplete]: ...
def expand_word_wrap(tokens, name) -> Generator[Incomplete]: ...
def expand_flex(tokens, name) -> Generator[Incomplete]: ...
def expand_flex_flow(tokens, name) -> Generator[Incomplete]: ...
def expand_grid_template(tokens, name) -> Generator[Incomplete, Incomplete]: ...
def expand_grid(tokens, name) -> Generator[Incomplete]: ...
def expand_grid_column_row(tokens, name) -> Generator[Incomplete]: ...
def expand_grid_area(tokens, name) -> Generator[Incomplete]: ...
def expand_gap(tokens, name) -> Generator[Incomplete]: ...
def expand_legacy_column_gap(tokens, name) -> Generator[Incomplete]: ...
def expand_legacy_row_gap(tokens, name) -> Generator[Incomplete]: ...
def expand_place_content(tokens, name) -> None: ...
def expand_place_items(tokens, name) -> None: ...
def expand_place_self(tokens, name) -> None: ...
def expand_line_clamp(tokens, name) -> Generator[Incomplete]: ...
def expand_text_align(tokens, name) -> Generator[Incomplete]: ...
