class _BaseExponentialBackoff:
    def __init__(
        self,
        total_attempts: int = 3,
        initial_wait_seconds: float = 1.0,
        randomization_factor: float = 0.1,
        multiplier: float = 2.0,
    ) -> None: ...
    @property
    def total_attempts(self) -> int: ...
    @property
    def backoff_count(self) -> int: ...

class ExponentialBackoff(_BaseExponentialBackoff):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def __iter__(self) -> ExponentialBackoff: ...
    def __next__(self) -> int: ...

class AsyncExponentialBackoff(_BaseExponentialBackoff):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    def __aiter__(self) -> AsyncExponentialBackoff: ...
    async def __anext__(self) -> int: ...
