class GoogleAuthError(Exception):
    def __init__(self, *args: object, **kwargs: object) -> None: ...
    @property
    def retryable(self) -> bool: ...

class TransportError(GoogleAuthError): ...
class RefreshError(GoogleAuthError): ...
class UserAccessTokenError(GoogleAuthError): ...
class DefaultCredentialsError(GoogleAuthError): ...
class MutualTLSChannelError(GoogleAuthError): ...

class ClientCertError(GoogleAuthError):
    @property
    def retryable(self) -> bool: ...

class OAuthError(GoogleAuthError): ...

class ReauthFailError(RefreshError):
    def __init__(self, message: str | None = None, **kwargs: object) -> None: ...

class ReauthSamlChallengeFailError(ReauthFailError): ...
class MalformedError(DefaultCredentialsError, ValueError): ...
class InvalidResource(DefaultCredentialsError, ValueError): ...
class InvalidOperation(DefaultCredentialsError, ValueError): ...
class InvalidValue(DefaultCredentialsError, ValueError): ...
class InvalidType(DefaultCredentialsError, TypeError): ...
class OSError(DefaultCredentialsError, EnvironmentError): ...
class TimeoutError(GoogleAuthError): ...
class ResponseError(GoogleAuthError): ...
