from collections.abc import Coroutine, Mapping
from typing import Any

from google.auth import credentials as _credentials
from google.auth.crypt import Signer as _Signer

_DEFAULT_TOKEN_LIFETIME_SECS: int
_DEFAULT_MAX_CACHE_SIZE: int
_ALGORITHM_TO_VERIFIER_CLASS: dict[str, type]
_CRYPTOGRAPHY_BASED_ALGORITHMS: frozenset[str]

def encode(
    signer: _Signer, payload: Mapping[str, str], header: Mapping[str, str] | None = None, key_id: str | None = None
) -> bytes: ...
def _decode_jwt_segment(encoded_section: bytes) -> Mapping[str, object]: ...
def _unverified_decode(token: str | bytes) -> tuple[Mapping[str, object], Mapping[str, object], bytes, bytes]: ...
def decode_header(token: str | bytes) -> Mapping[str, object]: ...
def _verify_iat_and_exp(payload: Mapping[str, str], clock_skew_in_seconds: int = 0) -> None: ...
def decode(
    token: str,
    certs: str | bytes | Mapping[str, str | bytes] | None = None,
    verify: bool = True,
    audience: str | list[str] | None = None,
    clock_skew_in_seconds: int = 0,
) -> Mapping[str, str]: ...

class Credentials(_credentials.Signing, _credentials.CredentialsWithQuotaProject):
    expiry: Any

    def __init__(
        self,
        signer: _Signer,
        issuer: str,
        subject: str,
        audience: str,
        additional_claims: Mapping[str, str] | None = None,
        token_lifetime: int = ...,
        quota_project_id: str | None = None,
    ) -> None: ...
    @classmethod
    def _from_signer_and_info(cls, signer: _Signer, info: Mapping[str, str], **kwargs: Any) -> Credentials: ...
    @classmethod
    def from_service_account_info(cls, info: Mapping[str, str], **kwargs: Any) -> Credentials: ...
    @classmethod
    def from_service_account_file(cls, filename: str, **kwargs: Any) -> Credentials: ...
    @classmethod
    def from_signing_credentials(cls, credentials: _credentials.Signing, audience: str, **kwargs: Any) -> Credentials: ...
    def with_claims(
        self,
        issuer: str | None = None,
        subject: str | None = None,
        audience: str | None = None,
        additional_claims: Mapping[str, str] | None = None,
    ) -> Credentials: ...
    def with_quota_project(self, quota_project_id: str | None) -> Credentials: ...
    def refresh(self, request: Any) -> None: ...
    def sign_bytes(self, message: bytes) -> bytes: ...
    @property
    def signer_email(self) -> str: ...
    @property
    def signer(self) -> _Signer: ...
    @property
    def additional_claims(self) -> Mapping[str, str]: ...

class OnDemandCredentials(_credentials.Signing, _credentials.CredentialsWithQuotaProject):
    def __init__(
        self,
        signer: _Signer,
        issuer: str,
        subject: str,
        additional_claims: Mapping[str, str] | None = None,
        token_lifetime: int = ...,
        max_cache_size: int = ...,
        quota_project_id: str | None = None,
    ) -> None: ...
    @classmethod
    def from_service_account_info(cls, info: Mapping[str, str], **kwargs: Any) -> OnDemandCredentials: ...
    @classmethod
    def from_service_account_file(cls, filename: str, **kwargs: Any) -> OnDemandCredentials: ...
    @classmethod
    def from_signing_credentials(cls, credentials: _credentials.Signing, **kwargs: Any) -> OnDemandCredentials: ...
    def with_claims(
        self, issuer: str | None = None, subject: str | None = None, additional_claims: Mapping[str, str] | None = None
    ) -> OnDemandCredentials: ...
    def with_quota_project(self, quota_project_id: str | None) -> OnDemandCredentials: ...
    @property
    def valid(self) -> bool: ...
    def refresh(self, request: Any) -> None: ...
    def before_request(
        self, request: Any, method: str, url: str, headers: Mapping[str, str]
    ) -> None | Coroutine[Any, Any, None]: ...
    def sign_bytes(self, message: bytes) -> bytes: ...
    @property
    def signer_email(self) -> str: ...
    @property
    def signer(self) -> _Signer: ...
