from typing import Any, Optional
from xml.etree.ElementTree import XMLParser

def parse(file: str, parser: Optional[XMLParser] = ..., bufsize: Optional[int] = ...): ...
def parseString(string: str, parser: Optional[XMLParser] = ...): ...
def __getattr__(name: str) -> Any: ...  # incomplete
