from _typeshed import Incomplete

from docutils.utils import Reporter

class Babel:
    language_codes: dict[str, str]
    warn_msg: str
    active_chars: dict[str, str]

    def __init__(self, language_code: str, reporter: Reporter | None = None) -> None: ...
    def __call__(self) -> str: ...
    def language_name(self, language_code: str) -> str: ...
    def get_language(self) -> str: ...

def __getattr__(name: str) -> Incomplete: ...
