from _typeshed import Incomplete
from typing import ClassVar

from webob.request import Request

class wsgify:
    RequestClass: ClassVar[type[Request]]
    func: Incomplete
    args: Incomplete
    kwargs: Incomplete
    middleware_wraps: Incomplete
    def __init__(
        self,
        func: Incomplete | None = ...,
        RequestClass: Incomplete | None = ...,
        args=...,
        kwargs: Incomplete | None = ...,
        middleware_wraps: Incomplete | None = ...,
    ) -> None: ...
    def __get__(self, obj, type: Incomplete | None = ...): ...
    def __call__(self, req, *args, **kw): ...
    def get(self, url, **kw): ...
    def post(self, url, POST: Incomplete | None = ..., **kw): ...
    def request(self, url, **kw): ...
    def call_func(self, req, *args, **kwargs): ...
    def clone(self, func: Incomplete | None = ..., **kw): ...
    @property
    def undecorated(self): ...
    @classmethod
    def middleware(cls, middle_func: Incomplete | None = ..., app: Incomplete | None = ..., **kw): ...

class _UnboundMiddleware:
    wrapper_class: Incomplete
    app: Incomplete
    kw: Incomplete
    def __init__(self, wrapper_class, app, kw) -> None: ...
    def __call__(self, func, app: Incomplete | None = ...): ...

class _MiddlewareFactory:
    wrapper_class: Incomplete
    middleware: Incomplete
    kw: Incomplete
    def __init__(self, wrapper_class, middleware, kw) -> None: ...
    def __call__(self, app: Incomplete | None = ..., **config): ...
