version = "0.8.*"
upstream-repository = "https://github.com/nmslib/hnswlib"
# Requires a version of numpy with a `py.typed` file
dependencies = ["numpy>=1.21"]

[tool.stubtest]
# TODO: stubtest fails without output or discernable reason during the daily
# test. https://github.com/python/typeshed/issues/16100
#skip = true
