from _typeshed import Incomplete

from dateutil.tz import tzfile as _tzfile

class tzfile(_tzfile):
    def __reduce__(self): ...

class ZoneInfoFile:
    zones: Incomplete
    metadata: Incomplete
    def __init__(self, zonefile_stream: Incomplete | None = ...) -> None: ...
    def get(self, name, default: Incomplete | None = ...): ...

def get_zonefile_instance(new_instance: bool = ...): ...
def gettz(name): ...
def gettz_db_metadata(): ...
