"""Stub file for the '_json' module."""
# This is an autogenerated file. It serves as a starting point
# for a more percise manual annotation of this module.
# Feel free to edit the source below, but remove this header when you do.

def encode_basestring_ascii(*args, **kwargs) -> object:
    raise TypeError()

def scanstring(a, b: int, *args, **kwargs) -> tuple:
    raise TypeError()
