"""Stub file for the '_stat' module."""
# This is an autogenerated file. It serves as a starting point
# for a more percise manual annotation of this module.
# Feel free to edit the source below, but remove this header when you do.

def S_IFMT(*args, **kwargs) -> long: pass

def S_IMODE(*args, **kwargs) -> long: pass

def S_ISBLK(*args, **kwargs) -> bool: pass

def S_ISCHR(*args, **kwargs) -> bool: pass

def S_ISDIR(*args, **kwargs) -> bool: pass

def S_ISDOOR(*args, **kwargs) -> bool: pass

def S_ISFIFO(*args, **kwargs) -> bool: pass

def S_ISLNK(*args, **kwargs) -> bool: pass

def S_ISPORT(*args, **kwargs) -> bool: pass

def S_ISREG(*args, **kwargs) -> bool: pass

def S_ISSOCK(*args, **kwargs) -> bool: pass

def S_ISWHT(*args, **kwargs) -> bool: pass

def filemode(*args, **kwargs) -> unicode: pass
