"""Stub file for the '_tracemalloc' module."""
# This is an autogenerated file. It serves as a starting point
# for a more percise manual annotation of this module.
# Feel free to edit the source below, but remove this header when you do.

def _get_object_traceback(*args, **kwargs) -> object: pass

def _get_traces() -> object:
    raise MemoryError()

def clear_traces() -> NoneType: pass

def get_traceback_limit() -> long: pass

def get_traced_memory() -> tuple: pass

def get_tracemalloc_memory() -> object: pass

def is_tracing() -> bool: pass

def start(*args, **kwargs) -> NoneType:
    raise ValueError()

def stop() -> NoneType: pass
