"""Stub file for the 'atexit' module."""
# This is an autogenerated file. It serves as a starting point
# for a more percise manual annotation of this module.
# Feel free to edit the source below, but remove this header when you do.

def _clear() -> NoneType: pass

def _ncallbacks() -> long: pass

def _run_exitfuncs() -> NoneType: pass

def register(*args, **kwargs) -> object:
    raise TypeError()
    raise MemoryError()

def unregister(*args, **kwargs) -> NoneType: pass
