"""Stub file for the 'atexit' module."""
# This is an autogenerated file. It serves as a starting point
# for a more percise manual annotation of this module.
# Feel free to edit the source below, but remove this header when you do.

from typing import List, Tuple, Dict, Undefined, GenericType

def _clear() -> None: pass

def _ncallbacks() -> long: pass

def _run_exitfuncs() -> None: pass

def register(*args, **kwargs) -> object:
    raise MemoryError()
    raise TypeError()

def unregister(*args, **kwargs) -> None: pass
