# Stubs for _random

from typing import Optional, Any

class Random(object):
    def __init__(self, seed: x, object = None) -> None: ...
    def seed(self, x: object = None) -> None: ...
    def getstate(self) -> tuple: ...
    def setstate(self, state: tuple) -> None: ...
    def random(self) -> float: ...
    def getrandbits(self, k: int) -> int: ...
    def jumpahead(self, i: int) -> None: ...
