from datetime import datetime, timedelta, tzinfo
from typing import Any

class TomlTz(tzinfo):
    def __init__(self, toml_offset: str) -> None: ...
    def __deepcopy__(self, memo: Any) -> TomlTz: ...
    def tzname(self, __dt: datetime | None) -> str | None: ...
    def utcoffset(self, __dt: datetime | None) -> timedelta | None: ...
    def dst(self, __dt: datetime | None) -> timedelta | None: ...
