from _typeshed import Incomplete

from ..Qt import QtWidgets

class FormatExportListWidgetItem(QtWidgets.QListWidgetItem):
    expClass: Incomplete
    def __init__(self, expClass, *args, **kwargs) -> None: ...

class ExportDialog(QtWidgets.QWidget):
    shown: bool
    currentExporter: Incomplete
    scene: Incomplete
    selectBox: Incomplete
    ui: Incomplete
    def __init__(self, scene) -> None: ...
    def show(self, item=None) -> None: ...
    def updateItemList(self, select=None) -> None: ...
    def updateItemTree(self, item, treeItem, select=None) -> None: ...
    def exportItemChanged(self, item, prev) -> None: ...
    def updateFormatList(self) -> None: ...
    def exportFormatChanged(self, item, prev) -> None: ...
    def exportClicked(self) -> None: ...
    def copyClicked(self) -> None: ...
    def close(self) -> None: ...
    def closeEvent(self, event) -> None: ...
