import sys
from typing import Any, Iterable, Iterator, List, Optional

from wsgiref.types import WSGIApplication, InputStream, ErrorStream

class WSGIWarning(Warning): ...

def validator(application: WSGIApplication) -> WSGIApplication: ...

if sys.version_info < (3,):
    _Bytes = str
else:
    _Bytes = bytes

class InputWrapper:
    input: InputStream
    def __init__(self, wsgi_input: InputStream) -> None: ...
    if sys.version_info < (3,):
        def read(self, size: int = ...) -> str: ...
        def readline(self) -> str: ...
    else:
        def read(self, size: int) -> bytes: ...
        def readline(self, size: int = ...) -> bytes: ...
    def readlines(self, hint: int = ...) -> _Bytes: ...
    def __iter__(self) -> Iterable[_Bytes]: ...
    def close(self) -> None: ...  # no return

class ErrorWrapper:
    errors: ErrorStream
    def __init__(self, wsgi_errors: ErrorStream) -> None: ...
    def write(self, s: str) -> None: ...
    def flush(self) -> None: ...
    def writelines(self, seq: List[str]) -> None: ...
    def close(self) -> None: ...  # no return

class WriteWrapper:
    writer: Iterable[_Bytes]
    def __init__(self, wsgi_writer: Iterable[_Bytes]) -> None: ...
    def __call__(self, s: _Bytes) -> None: ...

class PartialIteratorWrapper:
    iterator: Iterator[_Bytes]
    def __init__(self, wsgi_iterator: Iterator[_Bytes]) -> None: ...
    def __iter__(self) -> IteratorWrapper: ...

class IteratorWrapper:
    original_iterator: Iterator[_Bytes]
    iterator: Iterator[_Bytes]
    closed: bool
    check_start_response: Optional[bool]
    def __init__(self, wsgi_iterator: Iterator[_Bytes], check_start_response: Optional[bool]) -> None: ...
    def __iter__(self) -> IteratorWrapper: ...
    if sys.version_info < (3,):
        def next(self) -> str: ...
    else:
        def __next__(self) -> bytes: ...
    def close(self) -> None: ...
    def __del__(self) -> None: ...
