from commonmark.node import Node

class Renderer:
    buf: str
    last_out: str
    def render(self, ast: Node) -> str: ...
    def lit(self, s: str) -> None: ...
    def cr(self) -> None: ...
    def out(self, s: str) -> None: ...
