# Stubs for base64

# Based on http://docs.python.org/3.2/library/base64.html

from typing import Union, BinaryIO

def b64encode(s: Union[bytes, bytearray],
              altchars: Union[bytes, bytearray] = ...) -> bytes: ...
def b64decode(s: Union[bytes, bytearray],
              altchars: Union[bytes, bytearray] = ...,
              validate: bool = ...) -> bytes: ...
def standard_b64encode(s: Union[bytes, bytearray]) -> bytes: ...
def standard_b64decode(s: Union[bytes, bytearray]) -> bytes: ...
def urlsafe_b64encode(s: Union[bytes, bytearray]) -> bytes: ...
def urlsafe_b64decode(s: Union[bytes, bytearray]) -> bytes: ...
def b32encode(s: Union[bytes, bytearray]) -> bytes: ...
def b32decode(s: Union[bytes, bytearray], casefold: bool = ...,
              map01: Union[bytes, bytearray] = ...) -> bytes: ...
def b16encode(s: Union[bytes, bytearray]) -> bytes: ...
def b16decode(s: Union[bytes, bytearray], casefold: bool = ...) -> bytes: ...

def decode(input: BinaryIO, output: BinaryIO) -> None: ...
def decodebytes(s: Union[bytes, bytearray]) -> bytes: ...
def decodestring(s: Union[bytes, bytearray]) -> bytes: ...
def encode(input: BinaryIO, output: BinaryIO) -> None: ...
def encodebytes(s: Union[bytes, bytearray]) -> bytes: ...
def encodestring(s: Union[bytes, bytearray]) -> bytes: ...
