# Stubs for unicodedata (Python 3.4)
from typing import Any, TypeVar, Union

ucd_3_2_0 = ...  # type: UCD
ucnhash_CAPI = ...  # type: Any
unidata_version = ...  # type: str

_default = TypeVar('_default')

def bidirectional(__chr: str) -> str: ...
def category(__chr: str) -> str: ...
def combining(__chr: str) -> int: ...
def decimal(__chr: str, __default: _default=...) -> Union[int, _default]: ...
def decomposition(__chr: str) -> str: ...
def digit(__chr: str, __default: _default=...) -> Union[int, _default]: ...
def east_asian_width(__chr: str) -> str: ...
def lookup(__name: Union[str, bytes]) -> str: ...
def mirrored(__chr: str) -> int: ...
def name(__chr: str, __default: _default=...) -> Union[str, _default]: ...
def normalize(__form: str, __unistr: str) -> str: ...
def numeric(__chr: str, __default: _default=...) -> Union[float, _default]: ...

class UCD:
    unidata_version = ...  # type: str
    def bidirectional(self, __chr: str) -> str: ...
    def category(self, __chr: str) -> str: ...
    def combining(self, __chr: str) -> int: ...
    def decimal(self, __chr: str, __default: _default=...) -> Union[int, _default]: ...
    def decomposition(self, __chr: str) -> str: ...
    def digit(self, __chr: str, __default: _default=...) -> Union[int, _default]: ...
    def east_asian_width(self, __chr: str) -> str: ...
    def lookup(self, __name: Union[str, bytes]) -> str: ...
    def mirrored(self, __chr: str) -> int: ...
    def name(self, __chr: str, __default: _default=...) -> Union[str, _default]: ...
    def normalize(self, __form: str, __unistr: str) -> str: ...
    def numeric(self, __chr: str, __default: _default=...) -> Union[float, _default]: ...
