from pygments.style import Style as Style
from pygments.token import Comment as Comment, Error as Error, Keyword as Keyword, Name as Name, Operator as Operator, String as String
from typing import Any

class Algol_NuStyle(Style):
    background_color: str = ...
    default_style: str = ...
    styles: Any = ...
