from pygments.style import Style as Style
from pygments.token import Comment as Comment, Error as Error, Generic as Generic, Keyword as Keyword, Name as Name, Number as Number, Operator as Operator, String as String, Token as Token
from typing import Any

def make_style(colors: Any): ...

DARK_COLORS: Any
LIGHT_COLORS: Any

class SolarizedDarkStyle(Style):
    styles: Any = ...
    background_color: Any = ...
    highlight_color: Any = ...
    line_number_color: Any = ...
    line_number_background_color: Any = ...

class SolarizedLightStyle(SolarizedDarkStyle):
    styles: Any = ...
    background_color: Any = ...
    highlight_color: Any = ...
    line_number_color: Any = ...
    line_number_background_color: Any = ...
