"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing
from collections import abc as _abc

from google.protobuf import descriptor as _descriptor, message as _message
from google.protobuf.internal import containers as _containers
from tensorflow.compiler.xla.tsl.protobuf import error_codes_pb2 as _error_codes_pb2

if sys.version_info >= (3, 11):
    from typing import Never as _Never, TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias
    from typing_extensions import Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class StatusProto(_message.Message):
    """Wire-format for Status.
    Next tag: 4
    """

    DESCRIPTOR: _descriptor.Descriptor

    @_typing.final
    class PayloadEntry(_message.Message):
        DESCRIPTOR: _descriptor.Descriptor

        KEY_FIELD_NUMBER: _builtins.int
        VALUE_FIELD_NUMBER: _builtins.int
        key: _builtins.str
        value: _builtins.bytes
        def __init__(self, *, key: _builtins.str | None = ..., value: _builtins.bytes | None = ...) -> None: ...
        _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
        def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
        _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
        def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
        def WhichOneof(self, oneof_group: _Never) -> None: ...

    CODE_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    PAYLOAD_FIELD_NUMBER: _builtins.int
    code: _error_codes_pb2.Code.ValueType
    """Status code as defined in
    tensorflow/compiler/xla/tsl/protobuf/error_codes.proto.
    """
    message: _builtins.str
    """Detail error message."""
    @_builtins.property
    def payload(self) -> _containers.ScalarMap[_builtins.str, _builtins.bytes]:
        """Unique type URL -> value, like absl::Status payloads."""

    def __init__(
        self,
        *,
        code: _error_codes_pb2.Code.ValueType | None = ...,
        message: _builtins.str | None = ...,
        payload: _abc.Mapping[_builtins.str, _builtins.bytes] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "message", b"message", "payload", b"payload"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StatusProto: _TypeAlias = StatusProto  # noqa: Y015
