from typing import Any

from google.cloud.ndb import exceptions as exceptions

class BlobKey:
    def __init__(self, blob_key: Any) -> None: ...
    def __eq__(self, other: Any) -> Any: ...
    def __lt__(self, other: Any) -> Any: ...
    def __hash__(self) -> Any: ...
