from _typeshed import Incomplete

from .. import dockarea as dockarea
from ..graphicsItems.GraphicsObject import GraphicsObject
from ..Qt import QtWidgets
from .Node import Node

__init__: Incomplete

def strDict(d): ...

class Flowchart(Node):
    sigFileLoaded: Incomplete
    sigFileSaved: Incomplete
    sigChartLoaded: Incomplete
    sigStateChanged: Incomplete
    sigChartChanged: Incomplete
    library: Incomplete
    filePath: Incomplete
    inputWasSet: bool
    nextZVal: int
    processing: bool
    inputNode: Incomplete
    outputNode: Incomplete
    def __init__(self, terminals=None, name=None, filePath=None, library=None) -> None: ...
    def setLibrary(self, lib) -> None: ...
    def setInput(self, **args) -> None: ...
    def outputChanged(self) -> None: ...
    def output(self): ...
    def nodes(self): ...
    def addTerminal(self, name, **opts): ...
    def removeTerminal(self, name) -> None: ...
    def internalTerminalRenamed(self, term, oldName) -> None: ...
    def internalTerminalAdded(self, node, term) -> None: ...
    def internalTerminalRemoved(self, node, term) -> None: ...
    def terminalRenamed(self, term, oldName) -> None: ...
    def createNode(self, nodeType, name=None, pos=None): ...
    def addNode(self, node, name, pos=None) -> None: ...
    def removeNode(self, node) -> None: ...
    def nodeClosed(self, node) -> None: ...
    def nodeRenamed(self, node, oldName) -> None: ...
    def arrangeNodes(self) -> None: ...
    def internalTerminal(self, term): ...
    def connectTerminals(self, term1, term2) -> None: ...
    def process(self, **args): ...
    def processOrder(self): ...
    def nodeOutputChanged(self, startNode) -> None: ...
    def chartGraphicsItem(self): ...
    scene: Incomplete
    viewBox: Incomplete
    def widget(self): ...
    def listConnections(self): ...
    def saveState(self): ...
    def restoreState(self, state, clear: bool = False): ...
    fileDialog: Incomplete
    def loadFile(self, fileName=None, startDir=None) -> None: ...
    def saveFile(self, fileName=None, startDir=None, suggestedFileName: str = "flowchart.fc") -> None: ...
    def clear(self) -> None: ...
    def clearTerminals(self) -> None: ...

class FlowchartGraphicsItem(GraphicsObject):
    chart: Incomplete
    def __init__(self, chart) -> None: ...
    terminals: Incomplete
    def updateTerminals(self) -> None: ...
    def boundingRect(self): ...
    def paint(self, p, *args) -> None: ...

class FlowchartCtrlWidget(QtWidgets.QWidget):
    items: Incomplete
    currentFileName: Incomplete
    chart: Incomplete
    ui: Incomplete
    cwWin: Incomplete
    def __init__(self, chart) -> None: ...
    def chartToggled(self, b) -> None: ...
    def reloadClicked(self) -> None: ...
    def loadClicked(self) -> None: ...
    def fileSaved(self, fileName) -> None: ...
    def saveClicked(self) -> None: ...
    def saveAsClicked(self) -> None: ...
    def setCurrentFile(self, fileName) -> None: ...
    def itemChanged(self, *args) -> None: ...
    def scene(self): ...
    def viewBox(self): ...
    def nodeRenamed(self, node, oldName) -> None: ...
    def addNode(self, node) -> None: ...
    def removeNode(self, node) -> None: ...
    def bypassClicked(self) -> None: ...
    def chartWidget(self): ...
    def outputChanged(self, data) -> None: ...
    def clear(self) -> None: ...
    def select(self, node) -> None: ...
    def clearSelection(self) -> None: ...

class FlowchartWidget(dockarea.DockArea):
    chart: Incomplete
    ctrl: Incomplete
    hoverItem: Incomplete
    view: Incomplete
    viewDock: Incomplete
    hoverText: Incomplete
    hoverDock: Incomplete
    selInfo: Incomplete
    selInfoLayout: Incomplete
    selDescLabel: Incomplete
    selNameLabel: Incomplete
    selectedTree: Incomplete
    selDock: Incomplete
    def __init__(self, chart, ctrl) -> None: ...
    nodeMenu: Incomplete
    subMenus: Incomplete
    def reloadLibrary(self) -> None: ...
    def buildMenu(self, pos=None): ...
    menuPos: Incomplete
    def menuPosChanged(self, pos) -> None: ...
    def showViewMenu(self, ev) -> None: ...
    def scene(self): ...
    def viewBox(self): ...
    def nodeMenuTriggered(self, action) -> None: ...
    def selectionChanged(self) -> None: ...
    def hoverOver(self, items) -> None: ...
    def clear(self) -> None: ...

class FlowchartNode(Node): ...
