from _typeshed import Incomplete

def isNodeClass(cls): ...

class NodeLibrary:
    nodeList: Incomplete
    nodeTree: Incomplete
    def __init__(self) -> None: ...
    def addNodeType(self, nodeClass, paths, override: bool = False) -> None: ...
    def getNodeType(self, name): ...
    def getNodeTree(self): ...
    def copy(self): ...
    @staticmethod
    def treeCopy(tree): ...
    def reload(self) -> None: ...
