version = "2.3.*"
upstream_repository = "https://github.com/google/atheris"
partial_stub = true

[tool.stubtest]
ignore_missing_stub = true
# TODO: unskip once `atheris` can be installed on `ubuntu-24.04`,
# see https://github.com/python/typeshed/pull/13582
skip = true
