version = "1.16.*"
upstream_repository = "https://foss.heptapod.net/pypy/cffi"
requires = ["types-setuptools"]
incomplete = true

[tool.stubtest]
# linux and darwin are mostly equivalent, except for a single `RTLD_DEEPBIND` variable
platforms = ["linux", "win32"]
