from _typeshed import Incomplete

log: Incomplete
PRODUCER_CLIENT_ID_SEQUENCE: Incomplete

class KafkaProducer:
    DEFAULT_CONFIG: Incomplete
    DEPRECATED_CONFIGS: Incomplete
    config: Incomplete
    def __init__(self, **configs) -> None: ...
    def bootstrap_connected(self): ...
    def __del__(self) -> None: ...
    def close(self, timeout=None, null_logger: bool = False): ...
    def partitions_for(self, topic): ...
    @classmethod
    def max_usable_produce_magic(cls, api_version): ...
    def init_transactions(self) -> None: ...
    def begin_transaction(self) -> None: ...
    def send_offsets_to_transaction(self, offsets, consumer_group_id) -> None: ...
    def commit_transaction(self) -> None: ...
    def abort_transaction(self) -> None: ...
    def send(self, topic, value=None, key=None, headers=None, partition=None, timestamp_ms=None): ...
    def flush(self, timeout=None) -> None: ...
    def metrics(self, raw: bool = False): ...
