from typing import Tuple

def getstatus(file: str) -> str: ...
def getoutput(cmd: str) -> str: ...
def getstatusoutput(cmd: str) -> Tuple[int, str]: ...

def mk2arg(head: str, x: str) -> str: ...
def mkarg(x: str) -> str: ...
