from typing import overload, AnyStr, Text, Tuple

def getstatus(file: str) -> str: ...
def getoutput(cmd: str) -> str: ...
def getstatusoutput(cmd: str) -> Tuple[int, str]: ...

@overload
def mk2arg(head: bytes, x: bytes) -> bytes: ...
@overload
def mk2arg(head: AnyStr, x: Text) -> Text: ...
@overload
def mk2arg(head: Text, x: AnyStr) -> Text: ...

def mkarg(x: AnyStr) -> AnyStr: ...
