from typing import List, Iterator, Union

_string = Union[str, unicode]

def glob(pathname: _string) -> List[_string]: ...
def iglob(pathname: _string) -> Iterator[_string]: ...
def glob1(dirname: _string, pattern: _string) -> List[_string]: ...
def glob0(dirname: _string, basename: _string) -> List[_string]: ...
