# Stubs for Python 2.7 md5 stdlib module

from typing import AnyStr

class md5(object):
    name = ...  # type: str
    block_size = ...  # type: int
    digest_size = ...  # type: int
    digestsize = ...  # type: int
    def __init__(self, arg: AnyStr= ...) -> None: ...
    def update(self, arg: AnyStr) -> None: ...
    def digest(self) -> str: ...
    def hexdigest(self) -> str: ...
    def copy(self) -> md5: ...

def new(string: str = ...) -> md5: ...
blocksize = 0
digest_size = 0
