version = "23.2.*"
upstream_repository = "https://github.com/Tinche/aiofiles"

[tool.stubtest]
# linux and darwin are equivalent
platforms = ["linux", "win32"]
# Currently we are in a pickle, because aiofiles.os.__all__ is incorrect at
# runtime when running on win32. (https://github.com/Tinche/aiofiles/pull/174)
# This means that stubtest is either correct on Windows or all other platforms.
skip = true
