from _typeshed import Incomplete
from collections.abc import Generator

def initialize_page_maker(context, root_box) -> None: ...
def layout_fixed_boxes(context, pages, containing_page) -> Generator[Incomplete]: ...
def layout_document(html, root_box, context, max_loops: int = 8) -> Generator[Incomplete]: ...

class FakeList(list):
    def append(self, item) -> None: ...

class LayoutContext:
    style_for: Incomplete
    get_image_from_uri: Incomplete
    font_config: Incomplete
    counter_style: Incomplete
    target_collector: Incomplete
    footnotes: Incomplete
    page_footnotes: Incomplete
    current_page_footnotes: Incomplete
    reported_footnotes: Incomplete
    current_footnote_area: Incomplete
    page_bottom: Incomplete
    string_set: Incomplete
    running_elements: Incomplete
    current_page: Incomplete
    forced_break: bool
    broken_out_of_flow: Incomplete
    in_column: bool
    tables: Incomplete
    dictionaries: Incomplete
    def __init__(self, style_for, get_image_from_uri, font_config, counter_style, target_collector) -> None: ...
    def overflows_page(self, bottom_space, position_y): ...
    @staticmethod
    def overflows(bottom, position_y): ...
    @property
    def excluded_shapes(self): ...
    @excluded_shapes.setter
    def excluded_shapes(self, excluded_shapes) -> None: ...
    def create_block_formatting_context(self, root_box=None, new_list=None) -> None: ...
    def finish_block_formatting_context(self, root_box=None) -> None: ...
    def create_flex_formatting_context(self, root_box) -> None: ...
    def finish_flex_formatting_context(self, root_box) -> None: ...
    def add_broken_out_of_flow(self, new_box, box, containing_block, resume_at) -> None: ...
    def get_string_set_for(self, page, name, keyword: str = "first"): ...
    def get_running_element_for(self, page, name, keyword: str = "first"): ...
    def get_string_or_element_for(self, store, page, name, keyword): ...
    def layout_footnote(self, footnote): ...
    def unlayout_footnote(self, footnote) -> None: ...
    def report_footnote(self, footnote) -> None: ...
