from .min_max import handle_min_max_width

class AbsolutePlaceholder:
    def __init__(self, box) -> None: ...
    def set_laid_out_box(self, new_box) -> None: ...
    def translate(self, dx: int = 0, dy: int = 0, ignore_floats: bool = False) -> None: ...
    def copy(self): ...
    def __getattr__(self, name): ...
    def __setattr__(self, name, value) -> None: ...

@handle_min_max_width
def absolute_width(box, context, cb_x, cb_y, cb_width, cb_height): ...
def absolute_height(box, context, cb_x, cb_y, cb_width, cb_height): ...
def absolute_block(context, box, containing_block, fixed_boxes, bottom_space, skip_stack, cb_x, cb_y, cb_width, cb_height): ...
def absolute_layout(context, placeholder, containing_block, fixed_boxes, bottom_space, skip_stack) -> None: ...
def absolute_box_layout(context, box, containing_block, fixed_boxes, bottom_space, skip_stack): ...
def absolute_replaced(context, box, cb_x, cb_y, cb_width, cb_height): ...
