from _typeshed import Incomplete
from collections.abc import Generator
from typing import NamedTuple

from .min_max import handle_min_max_height, handle_min_max_width

class PageType(NamedTuple):
    side: Incomplete
    blank: Incomplete
    name: Incomplete
    index: Incomplete
    groups: Incomplete

class OrientedBox:
    @property
    def sugar(self): ...
    @property
    def outer(self): ...
    inner: Incomplete
    @outer.setter
    def outer(self, new_outer_width) -> None: ...
    @property
    def outer_min_content_size(self): ...
    @property
    def outer_max_content_size(self): ...

class VerticalBox(OrientedBox):
    context: Incomplete
    box: Incomplete
    inner: Incomplete
    margin_a: Incomplete
    margin_b: Incomplete
    padding_plus_border: Incomplete
    def __init__(self, context, box) -> None: ...
    def restore_box_attributes(self) -> None: ...
    @property
    def min_content_size(self): ...
    @property
    def max_content_size(self): ...

class HorizontalBox(OrientedBox):
    context: Incomplete
    box: Incomplete
    inner: Incomplete
    margin_a: Incomplete
    margin_b: Incomplete
    padding_plus_border: Incomplete
    def __init__(self, context, box) -> None: ...
    def restore_box_attributes(self) -> None: ...
    @property
    def min_content_size(self): ...
    @property
    def max_content_size(self): ...

def compute_fixed_dimension(context, box, outer, vertical, top_or_left) -> None: ...
def compute_variable_dimension(context, side_boxes, vertical, available_size) -> None: ...
def make_margin_boxes(context, page, state) -> Generator[Incomplete, None, Incomplete]: ...
def margin_box_content_layout(context, page, box): ...
def page_width_or_height(box, containing_block_size) -> None: ...
@handle_min_max_width
def page_width(box, context, containing_block_width) -> None: ...
@handle_min_max_height
def page_height(box, context, containing_block_height) -> None: ...
def make_page(context, root_box, page_type, resume_at, page_number, page_state): ...
def set_page_type_computed_styles(page_type, html, style_for) -> None: ...
def remake_page(index, context, root_box, html): ...
def make_all_pages(context, root_box, html, pages) -> Generator[Incomplete]: ...
