def percentage(value, computed, refer_to): ...
def resolve_one_percentage(box, property_name, refer_to) -> None: ...
def resolve_position_percentages(box, containing_block) -> None: ...
def resolve_percentages(box, containing_block) -> None: ...
def resolve_radii_percentages(box) -> None: ...
def adjust_box_sizing(box, axis) -> None: ...
