from .min_max import handle_min_max_height, handle_min_max_width

def default_image_sizing(
    intrinsic_width, intrinsic_height, intrinsic_ratio, specified_width, specified_height, default_width, default_height
): ...
def contain_constraint_image_sizing(constraint_width, constraint_height, intrinsic_ratio): ...
def cover_constraint_image_sizing(constraint_width, constraint_height, intrinsic_ratio): ...
def replacedbox_layout(box): ...
@handle_min_max_width
def replaced_box_width(box, containing_block) -> None: ...
@handle_min_max_height
def replaced_box_height(box) -> None: ...
def inline_replaced_box_layout(box, containing_block) -> None: ...
def inline_replaced_box_width_height(box, containing_block) -> None: ...
def min_max_auto_replaced(box) -> None: ...
def block_replaced_box_layout(context, box, containing_block): ...
@handle_min_max_width
def block_replaced_width(box, containing_block) -> None: ...
