"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins as _builtins
import sys
import typing as _typing
from collections import abc as _abc

from google.protobuf import descriptor as _descriptor, message as _message
from google.protobuf.internal import containers as _containers, enum_type_wrapper as _enum_type_wrapper
from tensorflow.core.framework import summary_pb2 as _summary_pb2

if sys.version_info >= (3, 11):
    from typing import Never as _Never, TypeAlias as _TypeAlias
else:
    from typing import TypeAlias as _TypeAlias
    from typing_extensions import Never as _Never

if sys.version_info >= (3, 13):
    from warnings import deprecated as _deprecated
else:
    from typing_extensions import deprecated as _deprecated

DESCRIPTOR: _descriptor.FileDescriptor

class _WorkerHealth:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _WorkerHealthEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_WorkerHealth.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    OK: _WorkerHealth.ValueType  # 0
    """By default a worker is healthy."""
    RECEIVED_SHUTDOWN_SIGNAL: _WorkerHealth.ValueType  # 1
    INTERNAL_ERROR: _WorkerHealth.ValueType  # 2
    SHUTTING_DOWN: _WorkerHealth.ValueType  # 3
    """Worker has been instructed to shutdown after a timeout."""

class WorkerHealth(_WorkerHealth, metaclass=_WorkerHealthEnumTypeWrapper):
    """Worker heartbeat messages.  Support for these operations is currently
    internal and expected to change.

    Current health status of a worker.
    """

OK: WorkerHealth.ValueType  # 0
"""By default a worker is healthy."""
RECEIVED_SHUTDOWN_SIGNAL: WorkerHealth.ValueType  # 1
INTERNAL_ERROR: WorkerHealth.ValueType  # 2
SHUTTING_DOWN: WorkerHealth.ValueType  # 3
"""Worker has been instructed to shutdown after a timeout."""
Global___WorkerHealth: _TypeAlias = WorkerHealth  # noqa: Y015

class _WorkerShutdownMode:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _WorkerShutdownModeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_WorkerShutdownMode.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    DEFAULT: _WorkerShutdownMode.ValueType  # 0
    NOT_CONFIGURED: _WorkerShutdownMode.ValueType  # 1
    WAIT_FOR_COORDINATOR: _WorkerShutdownMode.ValueType  # 2
    SHUTDOWN_AFTER_TIMEOUT: _WorkerShutdownMode.ValueType  # 3

class WorkerShutdownMode(_WorkerShutdownMode, metaclass=_WorkerShutdownModeEnumTypeWrapper):
    """Indicates the behavior of the worker when an internal error or shutdown
    signal is received.
    """

DEFAULT: WorkerShutdownMode.ValueType  # 0
NOT_CONFIGURED: WorkerShutdownMode.ValueType  # 1
WAIT_FOR_COORDINATOR: WorkerShutdownMode.ValueType  # 2
SHUTDOWN_AFTER_TIMEOUT: WorkerShutdownMode.ValueType  # 3
Global___WorkerShutdownMode: _TypeAlias = WorkerShutdownMode  # noqa: Y015

@_typing.final
class Event(_message.Message):
    """Protocol buffer representing an event that happened during
    the execution of a Brain model.
    """

    DESCRIPTOR: _descriptor.Descriptor

    WALL_TIME_FIELD_NUMBER: _builtins.int
    STEP_FIELD_NUMBER: _builtins.int
    FILE_VERSION_FIELD_NUMBER: _builtins.int
    GRAPH_DEF_FIELD_NUMBER: _builtins.int
    SUMMARY_FIELD_NUMBER: _builtins.int
    LOG_MESSAGE_FIELD_NUMBER: _builtins.int
    SESSION_LOG_FIELD_NUMBER: _builtins.int
    TAGGED_RUN_METADATA_FIELD_NUMBER: _builtins.int
    META_GRAPH_DEF_FIELD_NUMBER: _builtins.int
    SOURCE_METADATA_FIELD_NUMBER: _builtins.int
    wall_time: _builtins.float
    """Timestamp of the event."""
    step: _builtins.int
    """Global step of the event."""
    file_version: _builtins.str
    """An event file was started, with the specified version.
    This is use to identify the contents of the record IO files
    easily.  Current version is "brain.Event:2".  All versions
    start with "brain.Event:".
    """
    graph_def: _builtins.bytes
    """An encoded version of a GraphDef."""
    meta_graph_def: _builtins.bytes
    """An encoded version of a MetaGraphDef."""
    @_builtins.property
    def summary(self) -> _summary_pb2.Summary:
        """A summary was generated."""

    @_builtins.property
    @_deprecated("""This field has been marked as deprecated using proto field options.""")
    def log_message(self) -> Global___LogMessage:
        """The user output a log message. This was theoretically used by the defunct
        tensorboard_logging module, which has since been removed; this field is
        now deprecated and should not be used.
        """

    @_builtins.property
    def session_log(self) -> Global___SessionLog:
        """The state of the session which can be used for restarting after crashes."""

    @_builtins.property
    def tagged_run_metadata(self) -> Global___TaggedRunMetadata:
        """The metadata returned by running a session.run() call."""

    @_builtins.property
    def source_metadata(self) -> Global___SourceMetadata:
        """Information of the source that writes the events, this is only logged in
        the very first event along with the `file_version` field.
        """

    def __init__(
        self,
        *,
        wall_time: _builtins.float | None = ...,
        step: _builtins.int | None = ...,
        file_version: _builtins.str | None = ...,
        graph_def: _builtins.bytes | None = ...,
        summary: _summary_pb2.Summary | None = ...,
        log_message: Global___LogMessage | None = ...,
        session_log: Global___SessionLog | None = ...,
        tagged_run_metadata: Global___TaggedRunMetadata | None = ...,
        meta_graph_def: _builtins.bytes | None = ...,
        source_metadata: Global___SourceMetadata | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal[
        "file_version",
        b"file_version",
        "graph_def",
        b"graph_def",
        "log_message",
        b"log_message",
        "meta_graph_def",
        b"meta_graph_def",
        "session_log",
        b"session_log",
        "source_metadata",
        b"source_metadata",
        "summary",
        b"summary",
        "tagged_run_metadata",
        b"tagged_run_metadata",
        "what",
        b"what",
    ]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "file_version",
        b"file_version",
        "graph_def",
        b"graph_def",
        "log_message",
        b"log_message",
        "meta_graph_def",
        b"meta_graph_def",
        "session_log",
        b"session_log",
        "source_metadata",
        b"source_metadata",
        "step",
        b"step",
        "summary",
        b"summary",
        "tagged_run_metadata",
        b"tagged_run_metadata",
        "wall_time",
        b"wall_time",
        "what",
        b"what",
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_what: _TypeAlias = _typing.Literal[
        "file_version", "graph_def", "summary", "log_message", "session_log", "tagged_run_metadata", "meta_graph_def"
    ]  # noqa: Y015
    _WhichOneofArgType_what: _TypeAlias = _typing.Literal["what", b"what"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_what) -> _WhichOneofReturnType_what | None: ...

Global___Event: _TypeAlias = Event  # noqa: Y015

@_typing.final
class SourceMetadata(_message.Message):
    """Holds the information of the source that writes the events."""

    DESCRIPTOR: _descriptor.Descriptor

    WRITER_FIELD_NUMBER: _builtins.int
    writer: _builtins.str
    """Low level name of the summary writer, such as
    `tensorflow.core.util.events_writer`.
    """
    def __init__(self, *, writer: _builtins.str | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["writer", b"writer"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SourceMetadata: _TypeAlias = SourceMetadata  # noqa: Y015

@_deprecated("""This message has been marked as deprecated using proto message options.""")
@_typing.final
class LogMessage(_message.Message):
    """Protocol buffer used for logging messages to the events file.

    This was theoretically used by the defunct tensorboard_logging module, which
    has been removed; this message is now deprecated and should not be used.
    """

    DESCRIPTOR: _descriptor.Descriptor

    class _Level:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _LevelEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[LogMessage._Level.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        UNKNOWN: LogMessage._Level.ValueType  # 0
        DEBUGGING: LogMessage._Level.ValueType  # 10
        """Note: The logging level 10 cannot be named DEBUG. Some software
        projects compile their C/C++ code with -DDEBUG in debug builds. So the
        C++ code generated from this file should not have an identifier named
        DEBUG.
        """
        INFO: LogMessage._Level.ValueType  # 20
        WARN: LogMessage._Level.ValueType  # 30
        ERROR: LogMessage._Level.ValueType  # 40
        FATAL: LogMessage._Level.ValueType  # 50

    @_deprecated("""This enum has been marked as deprecated using proto enum options.""")
    class Level(_Level, metaclass=_LevelEnumTypeWrapper): ...

    UNKNOWN: LogMessage.Level.ValueType  # 0
    DEBUGGING: LogMessage.Level.ValueType  # 10
    """Note: The logging level 10 cannot be named DEBUG. Some software
    projects compile their C/C++ code with -DDEBUG in debug builds. So the
    C++ code generated from this file should not have an identifier named
    DEBUG.
    """
    INFO: LogMessage.Level.ValueType  # 20
    WARN: LogMessage.Level.ValueType  # 30
    ERROR: LogMessage.Level.ValueType  # 40
    FATAL: LogMessage.Level.ValueType  # 50

    LEVEL_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    level: Global___LogMessage.Level.ValueType
    message: _builtins.str
    def __init__(
        self, *, level: Global___LogMessage.Level.ValueType | None = ..., message: _builtins.str | None = ...
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["level", b"level", "message", b"message"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___LogMessage: _TypeAlias = LogMessage  # noqa: Y015

@_typing.final
class SessionLog(_message.Message):
    """Protocol buffer used for logging session state."""

    DESCRIPTOR: _descriptor.Descriptor

    class _SessionStatus:
        ValueType = _typing.NewType("ValueType", _builtins.int)
        V: _TypeAlias = ValueType  # noqa: Y015

    class _SessionStatusEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[SessionLog._SessionStatus.ValueType], _builtins.type):
        DESCRIPTOR: _descriptor.EnumDescriptor
        STATUS_UNSPECIFIED: SessionLog._SessionStatus.ValueType  # 0
        START: SessionLog._SessionStatus.ValueType  # 1
        STOP: SessionLog._SessionStatus.ValueType  # 2
        CHECKPOINT: SessionLog._SessionStatus.ValueType  # 3

    class SessionStatus(_SessionStatus, metaclass=_SessionStatusEnumTypeWrapper): ...
    STATUS_UNSPECIFIED: SessionLog.SessionStatus.ValueType  # 0
    START: SessionLog.SessionStatus.ValueType  # 1
    STOP: SessionLog.SessionStatus.ValueType  # 2
    CHECKPOINT: SessionLog.SessionStatus.ValueType  # 3

    STATUS_FIELD_NUMBER: _builtins.int
    CHECKPOINT_PATH_FIELD_NUMBER: _builtins.int
    MSG_FIELD_NUMBER: _builtins.int
    status: Global___SessionLog.SessionStatus.ValueType
    checkpoint_path: _builtins.str
    """This checkpoint_path contains both the path and filename."""
    msg: _builtins.str
    def __init__(
        self,
        *,
        status: Global___SessionLog.SessionStatus.ValueType | None = ...,
        checkpoint_path: _builtins.str | None = ...,
        msg: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "checkpoint_path", b"checkpoint_path", "msg", b"msg", "status", b"status"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SessionLog: _TypeAlias = SessionLog  # noqa: Y015

@_typing.final
class TaggedRunMetadata(_message.Message):
    """For logging the metadata output for a single session.run() call."""

    DESCRIPTOR: _descriptor.Descriptor

    TAG_FIELD_NUMBER: _builtins.int
    RUN_METADATA_FIELD_NUMBER: _builtins.int
    tag: _builtins.str
    """Tag name associated with this metadata."""
    run_metadata: _builtins.bytes
    """Byte-encoded version of the `RunMetadata` proto in order to allow lazy
    deserialization.
    """
    def __init__(self, *, tag: _builtins.str | None = ..., run_metadata: _builtins.bytes | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["run_metadata", b"run_metadata", "tag", b"tag"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TaggedRunMetadata: _TypeAlias = TaggedRunMetadata  # noqa: Y015

@_typing.final
class WatchdogConfig(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TIMEOUT_MS_FIELD_NUMBER: _builtins.int
    timeout_ms: _builtins.int
    def __init__(self, *, timeout_ms: _builtins.int | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["timeout_ms", b"timeout_ms"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WatchdogConfig: _TypeAlias = WatchdogConfig  # noqa: Y015

@_typing.final
class RequestedExitCode(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    EXIT_CODE_FIELD_NUMBER: _builtins.int
    exit_code: _builtins.int
    def __init__(self, *, exit_code: _builtins.int | None = ...) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["exit_code", b"exit_code"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RequestedExitCode: _TypeAlias = RequestedExitCode  # noqa: Y015

@_typing.final
class WorkerHeartbeatRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SHUTDOWN_MODE_FIELD_NUMBER: _builtins.int
    WATCHDOG_CONFIG_FIELD_NUMBER: _builtins.int
    EXIT_CODE_FIELD_NUMBER: _builtins.int
    shutdown_mode: Global___WorkerShutdownMode.ValueType
    @_builtins.property
    def watchdog_config(self) -> Global___WatchdogConfig: ...
    @_builtins.property
    def exit_code(self) -> Global___RequestedExitCode: ...
    def __init__(
        self,
        *,
        shutdown_mode: Global___WorkerShutdownMode.ValueType | None = ...,
        watchdog_config: Global___WatchdogConfig | None = ...,
        exit_code: Global___RequestedExitCode | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["exit_code", b"exit_code", "watchdog_config", b"watchdog_config"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "exit_code", b"exit_code", "shutdown_mode", b"shutdown_mode", "watchdog_config", b"watchdog_config"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WorkerHeartbeatRequest: _TypeAlias = WorkerHeartbeatRequest  # noqa: Y015

@_typing.final
class WorkerHeartbeatResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    HEALTH_STATUS_FIELD_NUMBER: _builtins.int
    WORKER_LOG_FIELD_NUMBER: _builtins.int
    HOSTNAME_FIELD_NUMBER: _builtins.int
    health_status: Global___WorkerHealth.ValueType
    hostname: _builtins.str
    @_builtins.property
    def worker_log(self) -> _containers.RepeatedCompositeFieldContainer[Global___Event]: ...
    def __init__(
        self,
        *,
        health_status: Global___WorkerHealth.ValueType | None = ...,
        worker_log: _abc.Iterable[Global___Event] | None = ...,
        hostname: _builtins.str | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal[
        "health_status", b"health_status", "hostname", b"hostname", "worker_log", b"worker_log"
    ]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WorkerHeartbeatResponse: _TypeAlias = WorkerHeartbeatResponse  # noqa: Y015
