from typing import Generic

from networkx.classes.graph import Graph, _Node
from networkx.classes.multidigraph import MultiDiGraph

class MultiGraph(Graph[_Node], Generic[_Node]):
    def new_edge_key(self, u: _Node, v: _Node) -> int: ...
    def copy(self, as_view: bool = False) -> MultiGraph[_Node]: ...
    def to_directed(self, as_view: bool = False) -> MultiDiGraph[_Node]: ...
    def to_undirected(self, as_view: bool = False) -> MultiGraph[_Node]: ...
    def number_of_edges(self, u: _Node | None = None, v: _Node | None = None) -> int: ...
