version = "4.69.*"
upstream-repository = "https://github.com/tqdm/tqdm"
optional-dependencies = ["types-requests"]

[tool.stubtest]
extras = ["slack", "telegram"]
stubtest-dependencies = ["dask", "pandas", "rich", "tensorflow"]
