version = "4.66.*"
upstream_repository = "https://github.com/tqdm/tqdm"
incomplete = true

[tool.stubtest]
extras = ["slack", "telegram"]
stubtest_requirements = ["dask", "pandas", "rich", "tensorflow"]
