from _typeshed import Incomplete
from typing import Any

UNICODE_ASCII_CHARACTER_SET: str
CLIENT_ID_CHARACTER_SET: str
SANITIZE_PATTERN: Any
INVALID_HEX_PATTERN: Any
always_safe: str
log: Any

def quote(s, safe: bytes = b"/"): ...
def unquote(s): ...
def urlencode(params): ...
def encode_params_utf8(params): ...
def decode_params_utf8(params): ...

urlencoded: Any

def urldecode(query): ...
def extract_params(raw): ...
def generate_nonce(): ...
def generate_timestamp(): ...
def generate_token(length: int = 30, chars=...): ...
def generate_signed_token(private_pem, request): ...
def verify_signed_token(public_pem, token): ...
def generate_client_id(length: int = 30, chars=...): ...
def add_params_to_qs(query, params): ...
def add_params_to_uri(uri, params, fragment: bool = False): ...
def safe_string_equals(a, b): ...
def to_unicode(data, encoding: str = "UTF-8"): ...

class CaseInsensitiveDict(dict[Any, Any]):
    proxy: Any
    def __init__(self, data) -> None: ...
    def __contains__(self, k): ...
    def __delitem__(self, k) -> None: ...
    def __getitem__(self, k): ...
    def get(self, k, default: Incomplete | None = None): ...
    def __setitem__(self, k, v) -> None: ...
    def update(self, *args, **kwargs) -> None: ...

class Request:
    uri: str | None
    http_method: str | None
    headers: CaseInsensitiveDict | None
    body: str | None
    decoded_body: list | None
    oauth_params: Union[dict, list] | None
    validator_log: dict
    _params: dict
    def __init__(
        self,
        uri,
        http_method: str = "GET",
        body: Incomplete | None = None,
        headers: Incomplete | None = None,
        encoding: str = "utf-8",
    ): ...
    def __getattr__(self, name: str): ...
    @property
    def uri_query(self) -> str: ...
    @property
    def uri_query_params(self) -> list: ...
    @property
    def duplicate_params(self) -> list: ...

    #   These properties are Read-Only
    #   Some are managed within self._params
    #   Others are assigned or expected by functions and subclasses
    @property
    def access_token(self) -> str | None: ...
    @property
    def acr_values(self) -> Any: ...
    @property
    def callback(self) -> str | None: ...
    @property
    def claims(self) -> Any: ...
    @property
    def client(self) -> Any: ...
    @property
    def client_id(self) -> str | None: ...
    @property
    def client_key(self) -> str | None: ...
    @property
    def client_secret(self) -> str | None: ...
    @property
    def code(self) -> str | None: ...
    @property
    def code_challenge(self) -> str | None: ...
    @property
    def code_challenge_method(self) -> str | None: ...
    @property
    def code_verifier(self) -> str | None: ...
    @property
    def display(self) -> str | None: ...
    @property
    def expires_in(self) -> int | None: ...
    @property
    def extra_credentials(self) -> dict | None: ...
    @property
    def grant_type(self) -> str | None: ...
    @property
    def id_token_hint(self) -> str | None: ...
    @property
    def login_hint(self) -> Any: ...
    @property
    def max_age(self) -> Any: ...
    @property
    def nonce(self) -> str | None: ...
    @property
    def params(self) -> list | None: ...
    @property
    def password(self) -> str | None: ...
    @property
    def prompt(self) -> Any: ...
    @property
    def realm(self) -> str | None: ...
    @property
    def realms(self) -> list[str] | None: ...
    @property
    def redirect_uri(self) -> str | None: ...
    @property
    def refresh_token(self) -> str | None: ...
    @property
    def request_token(self) -> str | None: ...
    @property
    def resource_owner_key(self) -> str | None: ...
    @property
    def response_mode(self) -> str | None: ...
    @property
    def response_type(self) -> str | None: ...
    @property
    def scope(self) -> Any: ...
    @property
    def scopes(self) -> list[str] | None: ...
    @property
    def signature(self) -> str | None: ...
    @property
    def signature_method(self) -> str | None: ...
    @property
    def state(self) -> str | None: ...
    @property
    def timestamp(self) -> str | None: ...
    @property
    def token(self) -> str | None: ...
    @property
    def token_type_hint(self) -> str | None: ...
    @property
    def ui_locales(self) -> str | None: ...
    @property
    def user(self) -> Any: ...
    @property
    def username(self) -> str | None: ...
    @property
    def using_default_redirect_uri(self) -> bool: ...
    @property
    def verifier(self) -> str | None: ...
