from _typeshed import Incomplete

class Unreader:
    buf: Incomplete
    def __init__(self) -> None: ...
    def chunk(self) -> None: ...
    def read(self, size=None): ...
    def unread(self, data) -> None: ...

class SocketUnreader(Unreader):
    sock: Incomplete
    mxchunk: Incomplete
    def __init__(self, sock, max_chunk: int = 8192) -> None: ...
    def chunk(self): ...

class IterUnreader(Unreader):
    iter: Incomplete
    def __init__(self, iterable) -> None: ...
    def chunk(self): ...
