from _typeshed import Incomplete

from gunicorn.app.base import Application

class WSGIApplication(Application):
    app_uri: Incomplete
    def init(self, parser, opts, args) -> None: ...
    def load_config(self) -> None: ...
    def load_wsgiapp(self): ...
    def load_pasteapp(self): ...
    def load(self): ...

def run(prog=None) -> None: ...
