from vobject import base as base, icalendar as icalendar

def change_tz(cal, new_timezone, default, utc_only: bool = ..., utc_tz=...) -> None: ...
def main() -> None: ...

version: str

def get_options(): ...
