from .base import Component as Component, getBehavior as getBehavior, newFromBehavior as newFromBehavior, readOne as readOne

def getSortKey(component): ...
def sortByUID(components): ...
def deleteExtraneous(component, ignore_dtstamp: bool = ...) -> None: ...
def diff(left, right): ...
def prettyDiff(leftObj, rightObj) -> None: ...
def main() -> None: ...

version: str

def getOptions(): ...
