class YAJLImportError(ImportError): ...

def require_version(version, required) -> None: ...
def get_yajl_version(yajl): ...
def find_yajl_ctypes(required): ...
def find_yajl_cffi(ffi, required): ...
