from _typeshed import Incomplete

from ..Qt import QtWidgets

class ExceptionHandlerWidget(QtWidgets.QGroupBox):
    sigStackItemClicked: Incomplete
    sigStackItemDblClicked: Incomplete
    filterString: str
    def __init__(self, parent=None) -> None: ...
    def setStack(self, frame=None) -> None: ...
    def setException(self, exc=None, lastFrame=None) -> None: ...
    def selectedFrame(self): ...
    def catchAllExceptions(self, catch: bool = True) -> None: ...
    def catchNextException(self, catch: bool = True) -> None: ...
    def enableExceptionHandling(self) -> None: ...
    def disableExceptionHandling(self) -> None: ...
    def clearExceptionClicked(self) -> None: ...
    def updateSysTrace(self) -> None: ...
    def exceptionHandler(self, excInfo, lastFrame=None) -> None: ...
    inSystrace: bool
    def systrace(self, frame, event, arg): ...
    def checkException(self, excType, exc, tb): ...
    def stackItemClicked(self, item) -> None: ...
    def stackItemDblClicked(self, item) -> None: ...
