from pygments.formatter import Formatter
from typing import Any

class NullFormatter(Formatter):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    def format(self, tokensource: Any, outfile: Any) -> None: ...

class RawTokenFormatter(Formatter):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    unicodeoutput: bool = ...
    encoding: str = ...
    compress: Any = ...
    error_color: Any = ...
    def __init__(self, **options: Any) -> None: ...
    def format(self, tokensource: Any, outfile: Any) -> None: ...

class TestcaseFormatter(Formatter):
    name: str = ...
    aliases: Any = ...
    def __init__(self, **options: Any) -> None: ...
    def format(self, tokensource: Any, outfile: Any) -> None: ...
