from pygments.formatter import Formatter
from typing import Any, Optional

class EscapeSequence:
    fg: Any = ...
    bg: Any = ...
    bold: Any = ...
    underline: Any = ...
    italic: Any = ...
    def __init__(self, fg: Optional[Any] = ..., bg: Optional[Any] = ..., bold: bool = ..., underline: bool = ..., italic: bool = ...) -> None: ...
    def escape(self, attrs: Any): ...
    def color_string(self): ...
    def true_color_string(self): ...
    def reset_string(self): ...

class Terminal256Formatter(Formatter):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
    xterm_colors: Any = ...
    best_match: Any = ...
    style_string: Any = ...
    usebold: Any = ...
    useunderline: Any = ...
    useitalic: Any = ...
    linenos: Any = ...
    def __init__(self, **options: Any) -> None: ...
    def format(self, tokensource: Any, outfile: Any): ...
    def format_unencoded(self, tokensource: Any, outfile: Any) -> None: ...

class TerminalTrueColorFormatter(Terminal256Formatter):
    name: str = ...
    aliases: Any = ...
    filenames: Any = ...
