version = "4.6.0"
upstream_repository = "https://github.com/redis/redis-py"
# Requires a version of cryptography with a `py.typed` file
requires = ["cryptography>=35.0.0", "types-pyOpenSSL"]
partial_stub = true
# While upstream added a py.typed file, the upstream annotations are rather
# incomplete. By using "obsolete_since" we recommend deinstalling this
# package, which isn't the best idea at the moment.
# obsolete_since = "5.0.0" # Released on 2023-08-15

[tool.stubtest]
ignore_missing_stub = true
extras = ["ocsp"]
