version = "4.5.5"
# Requires a version of cryptography with a `py.typed` file
requires = ["cryptography>=35.0.0", "types-pyOpenSSL"]
partial_stub = true

[tool.stubtest]
ignore_missing_stub = true
extras = ["ocsp"]
