import datetime
from _typeshed import Incomplete, StrPath
from typing import IO

from openpyxl import _Decodable
from openpyxl.chartsheet.chartsheet import Chartsheet
from openpyxl.styles.named_styles import NamedStyle
from openpyxl.workbook.child import _WorkbookChild
from openpyxl.workbook.defined_name import DefinedName
from openpyxl.worksheet._read_only import ReadOnlyWorksheet
from openpyxl.worksheet._write_only import WriteOnlyWorksheet
from openpyxl.worksheet.worksheet import Worksheet

INTEGER_TYPES: tuple[type[int]]

class Workbook:
    template: bool
    path: str
    defined_names: Incomplete
    properties: Incomplete
    security: Incomplete
    shared_strings: Incomplete
    loaded_theme: Incomplete
    vba_archive: Incomplete
    is_template: bool
    code_name: Incomplete
    encoding: str
    iso_dates: Incomplete
    rels: Incomplete
    calculation: Incomplete
    views: Incomplete
    def __init__(self, write_only: bool = ..., iso_dates: bool = ...) -> None: ...
    @property
    def epoch(self) -> datetime.datetime: ...
    @epoch.setter
    def epoch(self, value: datetime.datetime) -> None: ...
    @property
    def read_only(self) -> bool: ...
    @property
    def data_only(self) -> bool: ...
    @property
    def write_only(self) -> bool: ...
    @property
    def excel_base_date(self) -> datetime.datetime: ...
    @property
    def active(self) -> Worksheet: ...
    @active.setter
    def active(self, value: Worksheet) -> None: ...
    def create_sheet(self, title: str | _Decodable | None = ..., index: int | None = ...) -> WriteOnlyWorksheet | Worksheet: ...
    def move_sheet(self, sheet: str | Worksheet, offset: int = ...) -> None: ...
    def remove(self, worksheet: Worksheet | WriteOnlyWorksheet | Chartsheet) -> None: ...
    def remove_sheet(self, worksheet) -> None: ...
    def create_chartsheet(self, title: str | _Decodable | None = ..., index: int | None = ...): ...
    def get_sheet_by_name(self, name): ...
    def __contains__(self, key: str): ...
    def index(self, worksheet: Worksheet | ReadOnlyWorksheet | WriteOnlyWorksheet) -> int: ...
    def get_index(self, worksheet): ...
    def __getitem__(self, key: str): ...
    def __delitem__(self, key: str) -> None: ...
    def __iter__(self): ...
    def get_sheet_names(self): ...
    @property
    def worksheets(self) -> list[Worksheet | ReadOnlyWorksheet | WriteOnlyWorksheet]: ...
    @property
    def chartsheets(self) -> list[Chartsheet]: ...
    @property
    def sheetnames(self) -> list[str]: ...
    def create_named_range(
        self,
        name: str | None,
        worksheet: _WorkbookChild | ReadOnlyWorksheet | None = ...,
        value: str | None = ...,
        scope: int | None = ...,
    ) -> None: ...
    def add_named_style(self, style: NamedStyle) -> None: ...
    @property
    def named_styles(self) -> list[str]: ...
    def get_named_ranges(self) -> list[DefinedName]: ...
    def add_named_range(self, named_range: DefinedName) -> None: ...
    def get_named_range(self, name): ...
    def remove_named_range(self, named_range) -> None: ...
    @property
    def mime_type(self) -> str: ...
    def save(self, filename: StrPath | IO[bytes]) -> None: ...
    @property
    def style_names(self): ...
    def copy_worksheet(self, from_worksheet: Worksheet) -> WriteOnlyWorksheet | Worksheet: ...
    def close(self) -> None: ...
