from _typeshed import Incomplete

from docutils import writers

__docformat__: str

class Writer(writers._html_base.Writer):
    supported: Incomplete
    default_stylesheets: Incomplete
    default_stylesheet_dirs: Incomplete
    default_template: Incomplete
    settings_spec: Incomplete
    config_section: str
    parts: Incomplete
    translator_class: Incomplete
    def __init__(self) -> None: ...

class HTMLTranslator(writers._html_base.HTMLTranslator):
    doctype: str
    content_type: str
    content_type_mathml: str
    special_characters: Incomplete
    attribution_formats: Incomplete
    def set_first_last(self, node) -> None: ...
    def visit_address(self, node) -> None: ...
    def depart_address(self, node) -> None: ...
    def visit_admonition(self, node) -> None: ...
    def depart_admonition(self, node: Incomplete | None = None) -> None: ...
    def visit_author(self, node) -> None: ...
    author_in_authors: bool
    def depart_author(self, node) -> None: ...
    def visit_authors(self, node) -> None: ...
    def depart_authors(self, node) -> None: ...
    def visit_colspec(self, node) -> None: ...
    def depart_colspec(self, node) -> None: ...
    def is_compactable(self, node): ...
    def visit_citation(self, node) -> None: ...
    def depart_citation(self, node) -> None: ...
    def visit_citation_reference(self, node) -> None: ...
    def depart_citation_reference(self, node) -> None: ...
    def visit_classifier(self, node) -> None: ...
    def depart_classifier(self, node) -> None: ...
    def visit_compound(self, node) -> None: ...
    def depart_compound(self, node) -> None: ...
    def visit_definition(self, node) -> None: ...
    def depart_definition(self, node) -> None: ...
    def visit_definition_list(self, node) -> None: ...
    def depart_definition_list(self, node) -> None: ...
    def visit_definition_list_item(self, node) -> None: ...
    def depart_definition_list_item(self, node) -> None: ...
    def visit_description(self, node) -> None: ...
    def depart_description(self, node) -> None: ...
    in_docinfo: bool
    def visit_docinfo(self, node) -> None: ...
    docinfo: Incomplete
    body: Incomplete
    def depart_docinfo(self, node) -> None: ...
    def visit_docinfo_item(self, node, name, meta: bool = True) -> None: ...
    def depart_docinfo_item(self) -> None: ...
    def visit_doctest_block(self, node) -> None: ...
    def depart_doctest_block(self, node) -> None: ...
    def visit_entry(self, node) -> None: ...
    def depart_entry(self, node) -> None: ...
    compact_p: Incomplete
    compact_simple: Incomplete
    def visit_enumerated_list(self, node) -> None: ...
    def depart_enumerated_list(self, node) -> None: ...
    def visit_field(self, node) -> None: ...
    def depart_field(self, node) -> None: ...
    def visit_field_body(self, node) -> None: ...
    def depart_field_body(self, node) -> None: ...
    compact_field_list: bool
    def visit_field_list(self, node) -> None: ...
    def depart_field_list(self, node) -> None: ...
    def visit_field_name(self, node) -> None: ...
    def depart_field_name(self, node) -> None: ...
    def visit_footnote(self, node) -> None: ...
    def footnote_backrefs(self, node) -> None: ...
    def depart_footnote(self, node) -> None: ...
    def visit_footnote_reference(self, node) -> None: ...
    def depart_footnote_reference(self, node) -> None: ...
    def visit_generated(self, node) -> None: ...
    object_image_types: Incomplete
    def visit_image(self, node) -> None: ...
    def depart_image(self, node) -> None: ...
    def visit_label(self, node) -> None: ...
    def depart_label(self, node) -> None: ...
    def visit_list_item(self, node) -> None: ...
    def depart_list_item(self, node) -> None: ...
    def visit_literal(self, node) -> None: ...
    def depart_literal(self, node) -> None: ...
    def visit_literal_block(self, node) -> None: ...
    def depart_literal_block(self, node) -> None: ...
    def visit_option_group(self, node) -> None: ...
    def depart_option_group(self, node) -> None: ...
    def visit_option_list(self, node) -> None: ...
    def depart_option_list(self, node) -> None: ...
    def visit_option_list_item(self, node) -> None: ...
    def depart_option_list_item(self, node) -> None: ...
    def should_be_compact_paragraph(self, node): ...
    def visit_paragraph(self, node) -> None: ...
    def depart_paragraph(self, node) -> None: ...
    in_sidebar: bool
    def visit_sidebar(self, node) -> None: ...
    def depart_sidebar(self, node) -> None: ...
    def visit_subscript(self, node) -> None: ...
    def depart_subscript(self, node) -> None: ...
    in_document_title: Incomplete
    def visit_subtitle(self, node) -> None: ...
    subtitle: Incomplete
    def depart_subtitle(self, node) -> None: ...
    def visit_superscript(self, node) -> None: ...
    def depart_superscript(self, node) -> None: ...
    def visit_system_message(self, node) -> None: ...
    def depart_system_message(self, node) -> None: ...
    def visit_table(self, node) -> None: ...
    def depart_table(self, node) -> None: ...
    def visit_tbody(self, node) -> None: ...
    def depart_tbody(self, node) -> None: ...
    def visit_term(self, node) -> None: ...
    def depart_term(self, node) -> None: ...
    def visit_thead(self, node) -> None: ...
    def depart_thead(self, node) -> None: ...
    def section_title_tags(self, node): ...

class SimpleListChecker(writers._html_base.SimpleListChecker):
    def visit_list_item(self, node) -> None: ...
    def visit_paragraph(self, node) -> None: ...
    def visit_definition_list(self, node) -> None: ...
    def visit_docinfo(self, node) -> None: ...
