class CronExpressionGenerator:
    @staticmethod
    def hourly(): ...
    @staticmethod
    def daily(hour: int = 0): ...
    @staticmethod
    def daily_every_x_hours(hour_interval, starting_hour: int = 0): ...
