from typing import Any

XXHASH_VERSION: str

class xxh32:
    block_size: Any
    digest_size: Any
    digestsize: Any
    name: Any
    seed: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def copy(self) -> xxh32object: ...
    def digest(self) -> string: ...
    def hexdigest(self) -> string: ...
    def intdigest(self) -> int: ...
    def reset(self) -> Any: ...
    def update(self, input) -> Any: ...

class xxh3_128:
    block_size: Any
    digest_size: Any
    digestsize: Any
    name: Any
    seed: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def copy(self) -> xxh3_128object: ...
    def digest(self) -> string: ...
    def hexdigest(self) -> string: ...
    def intdigest(self) -> int: ...
    def reset(self) -> Any: ...
    def update(self, input) -> Any: ...

class xxh3_64:
    block_size: Any
    digest_size: Any
    digestsize: Any
    name: Any
    seed: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def copy(self) -> xxh64object: ...
    def digest(self) -> string: ...
    def hexdigest(self) -> string: ...
    def intdigest(self) -> int: ...
    def reset(self) -> Any: ...
    def update(self, input) -> Any: ...

class xxh64:
    block_size: Any
    digest_size: Any
    digestsize: Any
    name: Any
    seed: Any
    def __init__(self, *args, **kwargs) -> None: ...
    def copy(self) -> xxh64object: ...
    def digest(self) -> string: ...
    def hexdigest(self) -> string: ...
    def intdigest(self) -> int: ...
    def reset(self) -> Any: ...
    def update(self, input) -> Any: ...

def xxh32_digest(*args, **kwargs) -> Any: ...
def xxh32_hexdigest(*args, **kwargs) -> Any: ...
def xxh32_intdigest(*args, **kwargs) -> Any: ...
def xxh3_128_digest(*args, **kwargs) -> Any: ...
def xxh3_128_hexdigest(*args, **kwargs) -> Any: ...
def xxh3_128_intdigest(*args, **kwargs) -> Any: ...
def xxh3_64_digest(*args, **kwargs) -> Any: ...
def xxh3_64_hexdigest(*args, **kwargs) -> Any: ...
def xxh3_64_intdigest(*args, **kwargs) -> Any: ...
def xxh64_digest(*args, **kwargs) -> Any: ...
def xxh64_hexdigest(*args, **kwargs) -> Any: ...
def xxh64_intdigest(*args, **kwargs) -> Any: ...
