from _typeshed import Incomplete

from ...exceptions.exceptions import InvalidSamplingManifestError as InvalidSamplingManifestError
from .sampling_rule import SamplingRule as SamplingRule

local_sampling_rule: Incomplete
SUPPORTED_RULE_VERSION: tuple[int, int]

class LocalSampler:
    def __init__(self, rules=...) -> None: ...
    def should_trace(self, sampling_req: Incomplete | None = None) -> bool: ...
    def load_local_rules(self, rules) -> None: ...
    def _should_trace(self, sampling_rule: SamplingRule) -> bool: ...
