from _typeshed import Incomplete
from collections.abc import Iterable

def rmtree(path: str) -> None: ...
def isdir(path: str) -> bool: ...
def listdir(path: str) -> list[str]: ...
def exists(path: str) -> bool: ...
def copy(src: str, dst: str, overwrite: bool = False) -> None: ...
def makedirs(path: str) -> None: ...
def glob(pattern: str | Iterable[str]) -> list[str]: ...
def __getattr__(name: str) -> Incomplete: ...
