from _typeshed import Incomplete

from .constants import *

def set_global_machine_arch(machine_arch) -> None: ...
def describe_attr_value(attr, die, section_offset): ...
def describe_CFI_instructions(entry): ...
def describe_CFI_register_rule(rule): ...
def describe_CFI_CFA_rule(rule): ...
def describe_DWARF_expr(expr, structs, cu_offset: Incomplete | None = None): ...
def describe_reg_name(regnum, machine_arch: Incomplete | None = None, default: bool = True): ...
def describe_form_class(form): ...

class ExprDumper:
    structs: Incomplete
    expr_parser: Incomplete
    def __init__(self, structs) -> None: ...
    def dump_expr(self, expr, cu_offset: Incomplete | None = None): ...
