from _typeshed import Incomplete
from typing import Any

from ruamel.yaml.error import MarkedYAMLError
from ruamel.yaml.events import *
from ruamel.yaml.tag import Tag
from ruamel.yaml.tokens import *

__all__ = ["Parser", "RoundTripParser", "ParserError"]

class ParserError(MarkedYAMLError): ...

class Parser:
    DEFAULT_TAGS: Incomplete
    loader: Incomplete
    def __init__(self, loader: Any) -> None: ...
    current_event: Incomplete
    tag_handles: Incomplete
    states: Incomplete
    marks: Incomplete
    state: Incomplete
    def reset_parser(self) -> None: ...
    def dispose(self) -> None: ...
    @property
    def scanner(self) -> Any: ...
    @property
    def resolver(self) -> Any: ...
    def check_event(self, *choices: Any) -> bool: ...
    def peek_event(self) -> Any: ...
    last_event: Incomplete
    def get_event(self) -> Any: ...
    def parse_stream_start(self) -> Any: ...
    def parse_implicit_document_start(self) -> Any: ...
    def parse_document_start(self) -> Any: ...
    def parse_document_end(self) -> Any: ...
    def parse_document_content(self) -> Any: ...
    def process_directives(self) -> Any: ...
    def parse_block_node(self) -> Any: ...
    def parse_flow_node(self) -> Any: ...
    def parse_block_node_or_indentless_sequence(self) -> Any: ...
    def select_tag_transform(self, tag: Tag) -> None: ...
    def parse_node(self, block: bool = False, indentless_sequence: bool = False) -> Any: ...
    def parse_block_sequence_first_entry(self) -> Any: ...
    def parse_block_sequence_entry(self) -> Any: ...
    def parse_indentless_sequence_entry(self) -> Any: ...
    def parse_block_mapping_first_key(self) -> Any: ...
    def parse_block_mapping_key(self) -> Any: ...
    def parse_block_mapping_value(self) -> Any: ...
    def parse_flow_sequence_first_entry(self) -> Any: ...
    def parse_flow_sequence_entry(self, first: bool = False) -> Any: ...
    def parse_flow_sequence_entry_mapping_key(self) -> Any: ...
    def parse_flow_sequence_entry_mapping_value(self) -> Any: ...
    def parse_flow_sequence_entry_mapping_end(self) -> Any: ...
    def parse_flow_mapping_first_key(self) -> Any: ...
    def parse_flow_mapping_key(self, first: Any = False) -> Any: ...
    def parse_flow_mapping_value(self) -> Any: ...
    def parse_flow_mapping_empty_value(self) -> Any: ...
    def process_empty_scalar(self, mark: Any, comment: Any = None) -> Any: ...
    def move_token_comment(self, token: Any, nt: Any | None = None, empty: bool | None = False) -> Any: ...

class RoundTripParser(Parser):
    def select_tag_transform(self, tag: Tag) -> None: ...
    def move_token_comment(self, token: Any, nt: Any | None = None, empty: bool | None = False) -> Any: ...

class RoundTripParserSC(RoundTripParser):
    def move_token_comment(self, token: Any, nt: Any = None, empty: bool | None = False) -> None: ...
    def distribute_comment(self, comment: Any, line: Any) -> Any: ...
