from _typeshed import Incomplete

tag_attrib: str

class Tag:
    attrib = tag_attrib
    handle: Incomplete
    suffix: Incomplete
    handles: Incomplete
    def __init__(
        self, handle: Incomplete | None = None, suffix: Incomplete | None = None, handles: Incomplete | None = None
    ) -> None: ...
    def __hash__(self) -> int: ...
    def __eq__(self, other) -> bool: ...
    def startswith(self, x: str) -> bool: ...
    @property
    def trval(self) -> str | None: ...
    value = trval
    @property
    def uri_decoded_suffix(self) -> str | None: ...
    def select_transform(self, val: bool) -> None: ...
    def check_handle(self) -> bool: ...
