from datadog.api.resources import CreateableAPIResource, DeletableAPIResource, GetableAPIResource, UpdatableAPIResource

class GcpIntegration(GetableAPIResource, CreateableAPIResource, DeletableAPIResource, UpdatableAPIResource):
    @classmethod
    def list(cls, **params): ...
    @classmethod
    def delete(cls, **body): ...
    @classmethod
    def create(cls, **params): ...
    @classmethod
    def update(cls, **body): ...
