version = "4.*"
upstream_repository = "https://github.com/django/channels"
requires = ["django-stubs>=4.2,<5.3", "asgiref"]

[tool.stubtest]
skip = true  # TODO: enable stubtest once Django mypy plugin config is supported
stubtest_requirements = ["daphne"]
