version = "4.*"
upstream_repository = "https://github.com/django/channels"
requires = ["django-stubs", "asgiref"]

[tool.stubtest]
skip = true  # due to the need of django mypy plugin config, it should be skipped.
stubtest_requirements = ["daphne"]
