from _typeshed import Incomplete

TAGS: Incomplete
NOT_INHERITED_ATTRIBUTES: Incomplete
COLOR_ATTRIBUTES: Incomplete
DEF_TYPES: Incomplete

class Node:
    attrib: Incomplete
    vertices: Incomplete
    bounding_box: Incomplete
    def __init__(self, wrapper, style) -> None: ...
    def copy(self): ...
    def get(self, key, default=None): ...
    @property
    def tag(self): ...
    @property
    def text(self): ...
    @property
    def tail(self): ...
    @property
    def display(self): ...
    @property
    def visible(self): ...
    def cascade(self, child) -> None: ...
    def __iter__(self): ...
    def get_viewbox(self): ...
    def get_href(self, base_url): ...
    def del_href(self) -> None: ...
    @staticmethod
    def process_whitespace(string, preserve): ...
    def get_child(self, id_): ...
    def text_children(self, element, trailing_space, text_root: bool = False): ...
    def flatten(self): ...
    def pop_rotation(self, original_rotate, rotate) -> None: ...
    __class__: Incomplete
    def override_iter(self, iterator): ...
    def set_svg_size(self, svg, concrete_width, concrete_height) -> None: ...

class LazyDefs:
    def __init__(self, name, svg) -> None: ...
    def __getitem__(self, name): ...
    def get(self, name): ...
    def __contains__(self, name) -> bool: ...

class SVG:
    tree: Incomplete
    font_config: Incomplete
    url_fetcher: Incomplete
    url: Incomplete
    filters: Incomplete
    gradients: Incomplete
    images: Incomplete
    markers: Incomplete
    masks: Incomplete
    patterns: Incomplete
    paths: Incomplete
    symbols: Incomplete
    use_cache: Incomplete
    cursor_position: Incomplete
    cursor_d_position: Incomplete
    text_path_width: int
    def __init__(self, tree, url, font_config, url_fetcher=None) -> None: ...
    def get_intrinsic_size(self, font_size): ...
    def get_viewbox(self): ...
    def point(self, x, y, font_size): ...
    def length(self, length, font_size): ...
    stream: Incomplete
    base_url: Incomplete
    context: Incomplete
    def draw(self, stream, concrete_width, concrete_height, base_url, context) -> None: ...
    def draw_node(self, node, font_size, fill_stroke: bool = True) -> None: ...
    def draw_markers(self, node, font_size, fill_stroke) -> None: ...
    @staticmethod
    def get_paint(value): ...
    def set_graphical_state(self, node, font_size, text: bool = False) -> None: ...
    def fill_stroke(self, node, font_size, text: bool = False) -> None: ...
    def transform(self, node, font_size) -> None: ...
    def inherit_element(self, element, defs) -> None: ...
    def calculate_bounding_box(self, node, font_size, stroke: bool = True): ...

class Pattern(SVG):
    svg: Incomplete
    tree: Incomplete
    def __init__(self, tree, svg) -> None: ...
    def draw_node(self, node, font_size, fill_stroke: bool = True) -> None: ...
