from _typeshed import Incomplete

EMPTY_BOUNDING_BOX: Incomplete

def bounding_box(svg, node, font_size, stroke): ...
def bounding_box_rect(svg, node, font_size): ...
def bounding_box_circle(svg, node, font_size): ...
def bounding_box_ellipse(svg, node, font_size): ...
def bounding_box_line(svg, node, font_size): ...
def bounding_box_polyline(svg, node, font_size): ...
def bounding_box_path(svg, node, font_size): ...
def bounding_box_text(svg, node, font_size): ...
def bounding_box_g(svg, node, font_size): ...
def bounding_box_use(svg, node, font_size): ...
def extend_bounding_box(bounding_box, points): ...
def is_valid_bounding_box(bounding_box): ...

BOUNDING_BOX_METHODS: Incomplete
