class PointError(Exception): ...

def normalize(string): ...
def size(string, font_size=None, percentage_reference=None): ...
def alpha_value(value): ...
def point(svg, string, font_size): ...
def preserve_ratio(svg, node, font_size, width, height, viewbox=None): ...
def parse_url(url): ...
def color(string): ...
def transform(transform_string, transform_origin, font_size, normalized_diagonal): ...
