from typing import Any

from .upload import upload as upload

class upload_docs(upload):
    DEFAULT_REPOSITORY: str
    description: str
    user_options: Any
    boolean_options: Any
    def has_sphinx(self): ...
    sub_commands: Any
    upload_dir: Any
    target_dir: Any
    def initialize_options(self) -> None: ...
    def finalize_options(self) -> None: ...
    def create_zipfile(self, filename) -> None: ...
    def run(self) -> None: ...
    def upload_file(self, filename) -> None: ...
