import tkinter as tk
from typing import Any

from ._widget import ThemedWidget as ThemedWidget

class ThemedTk(tk.Tk, ThemedWidget):
    def __init__(self, *args, **kwargs) -> None: ...
    def set_theme(self, theme_name, toplevel: Any | None = ..., themebg: Any | None = ...) -> None: ...
    def config(self, kw: Any | None = ..., **kwargs): ...
    def cget(self, k): ...
    def configure(self, kw: Any | None = ..., **kwargs): ...
    def __getitem__(self, k): ...
    def __setitem__(self, k, v): ...
