from _typeshed import Incomplete
from collections.abc import Iterator

log: Incomplete

class KafkaConsumer(Iterator[Incomplete]):
    DEFAULT_CONFIG: Incomplete
    DEFAULT_SESSION_TIMEOUT_MS_0_9: int
    config: Incomplete
    def __init__(self, *topics, **configs) -> None: ...
    def bootstrap_connected(self): ...
    def assign(self, partitions) -> None: ...
    def assignment(self): ...
    def close(self, autocommit: bool = True, timeout_ms=None) -> None: ...
    def commit_async(self, offsets=None, callback=None): ...
    def commit(self, offsets=None, timeout_ms=None) -> None: ...
    def committed(self, partition, metadata: bool = False, timeout_ms=None): ...
    def topics(self): ...
    def partitions_for_topic(self, topic): ...
    def poll(self, timeout_ms: int = 0, max_records=None, update_offsets: bool = True): ...
    def position(self, partition, timeout_ms=None): ...
    def highwater(self, partition): ...
    def pause(self, *partitions) -> None: ...
    def paused(self): ...
    def resume(self, *partitions) -> None: ...
    def seek(self, partition, offset) -> None: ...
    def seek_to_beginning(self, *partitions) -> None: ...
    def seek_to_end(self, *partitions) -> None: ...
    def subscribe(self, topics=(), pattern=None, listener=None) -> None: ...
    def subscription(self): ...
    def unsubscribe(self) -> None: ...
    def metrics(self, raw: bool = False): ...
    def offsets_for_times(self, timestamps): ...
    def beginning_offsets(self, partitions): ...
    def end_offsets(self, partitions): ...
    def __iter__(self): ...
    def __next__(self): ...
