from _typeshed import Incomplete

from hvac.api.vault_api_base import VaultApiBase

DEFAULT_MOUNT_POINT: str

class Okta(VaultApiBase):
    def configure(
        self,
        org_name,
        api_token: Incomplete | None = ...,
        base_url: Incomplete | None = ...,
        ttl: Incomplete | None = ...,
        max_ttl: Incomplete | None = ...,
        bypass_okta_mfa: Incomplete | None = ...,
        mount_point=...,
    ): ...
    def read_config(self, mount_point=...): ...
    def list_users(self, mount_point=...): ...
    def register_user(self, username, groups: Incomplete | None = ..., policies: Incomplete | None = ..., mount_point=...): ...
    def read_user(self, username, mount_point=...): ...
    def delete_user(self, username, mount_point=...): ...
    def list_groups(self, mount_point=...): ...
    def register_group(self, name, policies: Incomplete | None = ..., mount_point=...): ...
    def read_group(self, name, mount_point=...): ...
    def delete_group(self, name, mount_point=...): ...
    def login(self, username, password, use_token: bool = ..., mount_point=...): ...
