def rectangle_aabb(matrix, pos_x, pos_y, width, height): ...
def gather_anchors(box, anchors, links, bookmarks, forms, parent_matrix=None, parent_form=None) -> None: ...
def make_page_bookmark_tree(page, skipped_levels, last_by_depth, previous_level, page_number, matrix): ...
