from _typeshed import Incomplete

class Page:
    width: Incomplete
    height: Incomplete
    bleed: Incomplete
    bookmarks: Incomplete
    links: Incomplete
    anchors: Incomplete
    forms: Incomplete
    def __init__(self, page_box) -> None: ...
    def paint(self, stream, scale: int = 1) -> None: ...

class DiskCache:
    def __init__(self, folder) -> None: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, value) -> None: ...
    def __contains__(self, key) -> bool: ...
    def __del__(self) -> None: ...

class Document:
    pages: Incomplete
    metadata: Incomplete
    url_fetcher: Incomplete
    fonts: Incomplete
    font_config: Incomplete
    color_profiles: Incomplete
    def __init__(self, pages, metadata, url_fetcher, font_config, color_profiles) -> None: ...
    def copy(self, pages: str = "all"): ...
    def make_bookmark_tree(self, scale: int = 1, transform_pages: bool = False): ...
    def write_pdf(self, target=None, zoom: int = 1, finisher=None, **options): ...
