from _typeshed import Incomplete

HTML5_UA_COUNTER_STYLE: Incomplete
HTML5_UA: Incomplete
HTML5_UA_FORM: Incomplete
HTML5_PH: Incomplete
HTML5_UA_STYLESHEET: Incomplete
HTML5_UA_FORM_STYLESHEET: Incomplete
HTML5_PH_STYLESHEET: Incomplete
HTML_WHITESPACE: str
HTML_SPACE_SEPARATED_TOKENS_RE: Incomplete

def ascii_lower(string): ...
def element_has_link_type(element, link_type): ...

HTML_HANDLERS: Incomplete

def handle_element(element, box, get_image_from_uri, base_url): ...
def handler(tag): ...
def make_replaced_box(element, box, image): ...
def handle_img(element, box, get_image_from_uri, base_url): ...
def handle_embed(element, box, get_image_from_uri, base_url): ...
def handle_object(element, box, get_image_from_uri, base_url): ...
def handle_colgroup(element, box, _get_image_from_uri, _base_url): ...
def handle_col(element, box, _get_image_from_uri, _base_url): ...
def handle_svg(element, box, get_image_from_uri, base_url): ...
def get_html_metadata(html): ...
def strip_whitespace(string): ...

W3C_DATE_RE: Incomplete

def parse_w3c_date(meta_name, string): ...
