from typing import Any, Literal

TrendDirection = Literal["up", "down", "stable"]

class TrendTracker:
    CHANGE_THRESHOLD: float
    def __init__(self, colors: dict[str, int], enabled: bool = True) -> None: ...
    @property
    def enabled(self) -> bool: ...
    def toggle(self) -> bool: ...
    def set_enabled(self, enabled: bool) -> None: ...
    def update(self, key: Any, metric: str, value: float) -> TrendDirection: ...
    def get_trend(self, key: Any, metric: str) -> TrendDirection: ...
    def get_color(self, trend: TrendDirection) -> int: ...
    def update_metrics(self, key: Any, metrics: dict[str, float]) -> dict[str, TrendDirection]: ...
    def clear(self) -> None: ...
