from typing import Any, Optional

from dateparser.calendars import non_gregorian_parser

class hijri:
    @classmethod
    def to_gregorian(cls, year: Optional[Any] = ..., month: Optional[Any] = ..., day: Optional[Any] = ...): ...
    @classmethod
    def from_gregorian(cls, year: Optional[Any] = ..., month: Optional[Any] = ..., day: Optional[Any] = ...): ...
    @classmethod
    def month_length(cls, year: Any, month: Any): ...

class HijriDate:
    year: Any = ...
    month: Any = ...
    day: Any = ...
    def __init__(self, year: Any, month: Any, day: Any) -> None: ...
    def weekday(self): ...

class hijri_parser(non_gregorian_parser):
    calendar_converter: Any = ...
    default_year: int = ...
    default_month: int = ...
    default_day: int = ...
    non_gregorian_date_cls: Any = ...
