name: Daily test

on:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

# Please keep the permissions minimal, as stubtest runs arbitrary code from pypi.
permissions:
  contents: read

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1

jobs:
  stubtest-third-party:
    name: Check third party stubs with stubtest
    if: ${{ github.repository == 'python/typeshed' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        shard-index: [0, 1, 2, 3]
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: pip install $(grep tomli== requirements-tests.txt) termcolor
      - name: Install apt packages
        run: |
          sudo apt update
          sudo apt install -y $(python tests/get_apt_packages.py)
      - name: Run stubtest
        run: xvfb-run python tests/stubtest_third_party.py --num-shards 4 --shard-index ${{ matrix.shard-index }}
