name: Run mypy_primer

on:
  # Only run on PR, since we diff against master
  pull_request:
    # Since modular typeshed, mypy primer doesn't check third party stubs. Till that is changed,
    # only run it on stdlib changes to avoid false confidence and wasted CI minutes.
    paths:
    - 'stdlib/**'

permissions:
  contents: read

jobs:
  mypy_primer:
    name: Run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shard-index: [0, 1]
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          path: typeshed_to_test
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install git+https://github.com/hauntsaninja/mypy_primer.git
      - name: Run mypy_primer
        shell: bash
        run: |
          cd typeshed_to_test
          echo "new commit"
          git rev-list --format=%s --max-count=1 $GITHUB_SHA
          git checkout -b upstream_master origin/master
          echo "base commit"
          git rev-list --format=%s --max-count=1 upstream_master
          echo ''
          cd ..
          # fail action if exit code isn't zero or one
          (
            mypy_primer \
            --new 551eea3697 --old 551eea3697 \
            --custom-typeshed-repo typeshed_to_test \
            --new-typeshed $GITHUB_SHA --old-typeshed upstream_master \
            --num-shards 2 --shard-index ${{ matrix.shard-index }} \
            --debug \
            --output concise \
            | tee diff_${{ matrix.shard-index }}.txt
          ) || [ $? -eq 1 ]
      - name: Upload mypy_primer diff
        uses: actions/upload-artifact@v2
        with:
          name: mypy_primer_diffs
          path: diff_${{ matrix.shard-index }}.txt

  comment:
    name: Comment
    runs-on: ubuntu-latest
    needs: mypy_primer
    permissions:
      pull-requests: write
    steps:
      - name: Download diffs
        uses: actions/download-artifact@v2
        with:
          name: mypy_primer_diffs

      - name: Post comment
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const fs = require('fs')
            const data = (
              ['diff_0.txt', 'diff_1.txt']
              .map(fileName => fs.readFileSync(fileName, { encoding: 'utf8' }))
              .join('')
              .substr(0, 30000)  // About 300 lines
            )

            console.log("Diff from mypy_primer:")
            console.log(data)

            let body
            if (data.trim()) {
              body = 'Diff from [mypy_primer](https://github.com/hauntsaninja/mypy_primer), showing the effect of this PR on open source code:\n```diff\n' + data + '```'
            } else {
              body = 'According to [mypy_primer](https://github.com/hauntsaninja/mypy_primer), this change has no effect on the checked open source code. 🤖🎉'
            }

            await github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            })

      - uses: kanga333/comment-hider@9141763feccc8da773595675adc567d6616b6e6f
        name: Hide old comments
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          leave_visible: 1
