name: Run mypy_primer

on:
  # Only run on PR, since we diff against master
  pull_request:

jobs:
  mypy_primer:
    name: Run mypy_primer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: typeshed_to_test
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install git+https://github.com/hauntsaninja/mypy_primer.git
      - name: Run mypy_primer
        run: |
          cd typeshed_to_test
          echo "new commit"
          git rev-list --format=%s --max-count=1 $GITHUB_SHA
          git checkout -b upstream_master origin/master
          echo "base commit"
          git rev-list --format=%s --max-count=1 upstream_master
          cd ..
          echo "ATTENTION: failures here shouldn't be treated as blocking; use your judgement"
          echo "(Unfortunately, Github doesn't seem to have an \"allowed_failures\" equivalent)"
          mypy_primer --new v0.790 --old v0.790 --custom-typeshed-repo typeshed_to_test --new-typeshed $GITHUB_SHA --old-typeshed upstream_master -o concise
