name: Check stubs with stubtest

on:
  push:
  pull_request:

jobs:
  stubtest:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: [3.5, 3.6, 3.7, 3.8]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U mypy==0.780
      - name: Run stubtest
        run: ./tests/stubtest_test.py --ignore-unused-whitelist
