name: Find unused stubtest whitelist entries

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  find:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: [3.5, 3.6, 3.7, 3.8]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U git+git://github.com/python/mypy@b3d43984
      - name: Run stubtest
        run: ./tests/stubtest_unused.py
