name: Find unused stubtest whitelist entries

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  stubtest:
    if: github.repository == 'python/typeshed'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
        python-version: [3.5, 3.6, 3.7, 3.8]
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install -U mypy==0.780
      - name: Run stubtest
        shell: bash
        run: ./tests/stubtest_unused.py | tee stubtest-output-${{ matrix.os }}-${{ matrix.python-version }} || true
      - name: Store output
        uses: actions/upload-artifact@v2
        with:
          name: stubtest-output
          path: stubtest-output-${{ matrix.os }}-${{ matrix.python-version }}

  collate:
    if: github.repository == 'python/typeshed'
    runs-on: ubuntu-latest
    needs: stubtest
    steps:
      - name: Get stubtest outputs
        uses: actions/download-artifact@v2
        with:
          name: stubtest-output
      - name: Remove duplicates
        run: |
          cat stubtest-output-* | sort -u | tee stubtest-output
          test "$(wc -l stubtest-output | cut -d ' ' -f 1)" = 0
