from typing import Any

DesignatedWrapPolicy = Any  # from win32com.server.policy import DesignatedWrapPolicy

class FileOperationProgressSink(DesignatedWrapPolicy):
    newItem: Any
    def __init__(self) -> None: ...
    def PreDeleteItem(self, flags, item): ...
    def PostDeleteItem(self, flags, item, hrDelete, newlyCreated) -> None: ...
    def StartOperations(self) -> None: ...
    def FinishOperations(self, Result) -> None: ...
    def PreRenameItem(self, Flags, Item, NewName) -> None: ...
    def PostRenameItem(self, Flags, Item, NewName, hrRename, NewlyCreated) -> None: ...
    def PreMoveItem(self, Flags, Item, DestinationFolder, NewName) -> None: ...
    def PostMoveItem(self, Flags, Item, DestinationFolder, NewName, hrMove, NewlyCreated) -> None: ...
    def PreCopyItem(self, Flags, Item, DestinationFolder, NewName) -> None: ...
    def PostCopyItem(self, Flags, Item, DestinationFolder, NewName, hrCopy, NewlyCreated) -> None: ...
    def PreNewItem(self, Flags, DestinationFolder, NewName) -> None: ...
    def PostNewItem(self, Flags, DestinationFolder, NewName, TemplateName, FileAttributes, hrNew, NewItem) -> None: ...
    def UpdateProgress(self, WorkTotal, WorkSoFar) -> None: ...
    def ResetTimer(self) -> None: ...
    def PauseTimer(self) -> None: ...
    def ResumeTimer(self) -> None: ...

def CreateSink(): ...
