import os
from typing import Any

from .compat import environb as environb, text_type as text_type
from .exceptions import TrashPermissionError as TrashPermissionError
from .util import preprocess_paths as preprocess_paths

fsencode = os.fsencode
fsdecode = os.fsdecode
FILES_DIR: bytes
INFO_DIR: bytes
INFO_SUFFIX: bytes
XDG_DATA_HOME: Any
HOMETRASH_B: Any
HOMETRASH: Any
uid: Any
TOPDIR_TRASH: bytes
TOPDIR_FALLBACK: Any

def is_parent(parent, path): ...
def format_date(date): ...
def info_for(src, topdir): ...
def check_create(dir) -> None: ...
def trash_move(src, dst, topdir: Any | None = ...) -> None: ...
def find_mount_point(path): ...
def find_ext_volume_global_trash(volume_root): ...
def find_ext_volume_fallback_trash(volume_root): ...
def find_ext_volume_trash(volume_root): ...
def get_dev(path): ...
def send2trash(paths): ...
