# tornado ships with types as of version 6, but
# we keep these stubs around for the benefit of
# Python 2 users (see #4412). Therefore, these
# stubs target version 5.1, the last to support
# Python 2.
version = "5.1"
python2 = true
